open62541/open62541

CMakeLists.txt, examples/networklayer_tcp.c, examples/networklayer_udp.c, examples/networklayer_udp.h, examples/opcuaClient.c, examples/opcuaServer.c, examples/statelessClient.c, src/server/ua_server_binary.c, src/server/ua_server_worker.c
I'd like to merge it in as long as it is not too far apart from master, relates #153
=> Udp transport

examples/server.c, examples/server_simple.c, include/ua_server.h, include/ua_types.h, src/server/ua_server.c, src/server/ua_server_binary.c, src/server/ua_server_internal.h, src/server/ua_services_session.c, src/ua_types.c, tests/check_server_interaction_fileinput.c, tools/generate_datatypes.py
=> Server config

tools/amalgamate.py
Without this update there is no pointer to our project if it is used in other projects.
=> add link to http://open62541.org/ to amalgamated files

tools/amalgamate.py
This makes debugging with the amalgamated files much easier.
=> add a hint which file is appended

include/ua_server.h, src/server/ua_server_internal.h, src/server/ua_server_worker.c
Hey guys,
I have separated UA_Server_run into three parts s.t. we can run the server without an endless loop as proposed by @LEvertz.
Is it okay for everyone? I'd also merge it into v0.1 since the interface is only extended and not changed.
Best Regards
Sten
=> splitting server_run s.t. the server can run in one thread with other applications

src/client/ua_client.c, src/ua_util.h
- Mex compilation check flag 
- Matlab Memory macros
- Memory presistence
=> Matlab Mex Macros and Memory Presistence

CMakeLists.txt
this could fix #263 with python 3 and python 2.x
=> using ${PYTHON_EXECUTABLE} and a better check for lxml.

tools/amalgamate.py, tools/generate_datatypes.py
The output seems to be the same with python 3.
=> python 3 fixes for generate_datatypes.py and amalgamate.py

src/server/ua_server.c
added a function to delete external namespaces to the server --> fixes a memleak when using external namespaces
=> fixed a memleak when using external namespaces

CMakeLists.txt, examples/server.c, src/ua_util.h
It could be compiled in the cygwin environment.
closes #297
=> support cygwin envirnment

examples/client.c, include/ua_client.h, src/client/ua_client.c
@tpiat confirms it working in #350 #348, so i reintegrate it into master
=> initial lifecycle change for the client - review/test needed #350 #348

src/client/ua_client.c
=> Do not make a client request if renewSecureChannel failed

src/client/ua_client.c
With this change a client could call `UA_Client_renewSecureChannel` for keeping the session open. 
He can not check the expiry himself!
=> move SecureChannel expire check into internal function

.travis.yml
=> adding clang to travis builds

CMakeLists.txt, include/ua_config.h.in, tools/pyUANamespace/ua_namespace.py
getting nodeset example to work in msvs, based on 824f7b8eb0240290329b7a929fd33041fc3645e4 by @joerg555 and 7328cd72c1fb05e3b8fa9ed3646f0f7d56697aee by @jpfr
=> fixing #308

include/ua_types.h, src/server/ua_server_worker.c, src/server/ua_session_manager.c, src/server/ua_session_manager.h, src/server/ua_subscription.c, src/ua_session.h, src/ua_types.c, src/ua_types_encoding_binary.c
- correct def of UA_Variant_decodeBinary() missing *UA_RESTRICT
- no more Bug in void processJobs() jobsSize may be -1
- Timeout calculation in processRepeatedJobs() must be 32 Bit (if 16 bit overflow at 65 s)
- some comments for UA_DateTime variables to check code
- no "#ifdef _MSC_VER" in Subscription_registerUpdateJob thats stuff
=> Correct declarations (missing const, ...) and 2 small bugs in ua_server_worker()

examples/networklayer_tcp.c
remove multiple calls to WSAGetLastError()
=> remove multiple calls to WSAGetLastError()

include/ua_types.h, src/server/ua_server.c, src/server/ua_services_session.c, src/server/ua_session_manager.c
Fixing compiler warning C4244 about data type conversions
=> Fixing compiler warning C4244 about data type conversions

src/ua_types.c
replace sprintf with its safer version in windows platform (squash previous commits)
=> replace sprintf with its safer version in windows platform

src/client/ua_client.c, tools/amalgamate.py
* adding tamestamp to requests
* adding handleId counts to requests and client
=> making client more conformant, fixes #420

include/ua_server.h, src/server/ua_server_binary.c, src/server/ua_server_internal.h
Now i have reset my fork to acplt/master.
This are the minimum changes i need to be in sync with acplt/master and my MFC VC2015 Examples.
With this changes i can include "ua_server_internal.h" to my project.
It's verry nice, that its possible to attach all your work with C++ classes and my MFC-Server starts working now.
``` c++
class UaNetLayer : public UA_ServerNetworkLayer
{
public:
/* config */
UA_Logger m_Ua_logger;
UA_UInt32 m_uListenport;
UA_ConnectionConfig m_UaConf; 
UA_ByteString m_SenBuf; // message buffer that is reused
public:
UaNetLayer();
UaNetLayer(UA_ConnectionConfig ConConfig, UA_UInt32 uListenPort)
{
Init(ConConfig, uListenPort);
}
~UaNetLayer();
/* */
};
```
=> Small changes to go with C++

include/ua_client.h, src/client/ua_client.c
=> adding UA_Client_NamespaceGetIndex

src/server/ua_securechannel_manager.c, src/server/ua_securechannel_manager.h
Added tracking of secure channels #446 by simply adding a counter to the secureChannel structure. Each time a secureChannel is opened the counter is increased, analogous for closing.
=> Channel counting

src/server/ua_subscription.c
@jpfr @ichrispa should i merge it in as a temporary fix?
=> workaround for #496

doc/tutorial_client_firstSteps.rst, doc/tutorial_server_firstSteps.rst
The old version caused various compiler errors and wasn't up to date.
=> Fixed tutorial to match current source. Fixed some typos.

doc/tutorial_server_variables.rst
Some more fixes for the tutorial pages
=> Fixed tutorials

include/ua_client_highlevel.h, src/client/ua_client_highlevel_subscriptions.c
Hello,
If I modify the client (in example directory) with something like that : 
```
while(1)
{
UA_Client_Subscriptions_manuallySendPublishRequest(client);
sleep(1);
}
```
I don't have possibility to know if the client are connected to the server.
You can find a PR to correct this problem.
=> modify UA_Client_Subscriptions_manuallySendPublishRequest to return status

src_extra/networklayer_tcp.c
Workaround for https://cygwin.com/ml/cygwin/2013-07/msg00107.html
=> recv don't support timeout under cygwin

examples/client.c, include/ua_client_highlevel.h, src/client/ua_client_highlevel_subscriptions.c
see UA_Client_MonitoredItem def
```
typedef struct UA_Client_MonitoredItem_s {
UA_UInt32  MonitoredItemId;
UA_UInt32  MonitoringMode;
UA_NodeId  monitoredNodeId;
UA_UInt32  AttributeID;
UA_UInt32  ClientHandle;
UA_Double  SamplingInterval;
UA_UInt32  QueueSize;
UA_Boolean DiscardOldest;
void       (*handler)(UA_UInt32 handle, UA_DataValue *value, void *context);
void       *handlerContext;
LIST_ENTRY(UA_Client_MonitoredItem_s)  listEntry;
} UA_Client_MonitoredItem;
```
=> correct client handlingFunction

src_extra/networklayer_udp.c
=> fixing a memleak

src/server/ua_server.c, src/server/ua_services_nodemanagement.c
Added external namespaces urls to intern namespaces array of server in order to view external namespaces after UA_Server_addExternalNamespace(...).
=> List external namespaces in server->namespaces

tests/CMakeLists.txt
File "check_server_binary_messages.c" needs "logger_stdout.h"
=> Fix include order

CMakeLists.txt, tools/pyUANamespace/open62541_MacroHelper.py
Minor fix in CMakelists.
Add a rudimentary replacement function to avoid issue #578. The resulting identifiers are not guaranteed to be unique.
Please review!
=> Generate nodemacros

CMakeLists.txt, README.md, examples/client.c, examples/client_firstSteps.c, examples/server.c, examples/server.cpp, examples/server_datasource.c, examples/server_firstSteps.c, examples/server_mainloop.c, examples/server_method.c, examples/server_nodeset.c, examples/server_readspeed.c, examples/server_repeated_job.c, examples/server_variable.c, include/ua_client.h, include/ua_client_highlevel.h, include/ua_server.h, plugins/networklayer_tcp.h, plugins/ua_config_standard.c, plugins/ua_config_standard.h, src/client/ua_client.c, src/client/ua_client_internal.h, src/server/ua_server.c, tests/check_server_binary_messages.c, tests/check_services_attributes.c, tests/check_services_nodemanagement.c
and move the standard config definition into a plugin
=> move logger and connection-function into the client config

.travis.yml, tools/travis/travis_linux_before_install.sh
This removes all the "pass by reference" warnings
=> Use cppcheck 1.73

src/server/ua_server_binary.c
See issue description for further details.
Related to https://github.com/open62541/open62541/pull/591
=> Fix #590: Possible nullpointer in decode if invalid message

tools/travis/travis_linux_script.sh
Add additional check with `scan-build` and amalgamation
=> Add static analysis with amalgamation enabled

include/ua_client_highlevel.h
UA_Client_processPublishResponse call : 
mon->handler(mon->MonitoredItemId, &mitemNot->value, mon->handlerContext);
=> fix UA_MonitoredItemHandlingFunction definition

include/ua_config.h.in, src/ua_types_encoding_binary.c
This is what I needed to be able to compile with -Werror on centos6 with gcc 4.4 (see issue #622).
=> Gcc44 centos6

include/ua_log.h, src/server/ua_services_session.c, src/server/ua_session_manager.c, src/server/ua_session_manager.h, src/server/ua_subscription.c, src/ua_session.h
this fixes some tests, since session id do not collide with nodes in NS0
=> changing session id to random GUID, updated logging of session ids

examples/server_method.c, src/server/ua_services_call.c
-it is now possible to pass enumerations as argument of a call
-method nodes can be interconnected with any subtype of hasComponent reference
=> fixes for call service

doc/tutorial_client_firstSteps.rst
Eddited client tutorial, basic client exmpale did not compile
- Changed dir sturcture to be sorted correctly
- Added include to basic client example
- Removed Logger_Stdout parameter from UA_Client_new
- Removed UA_ClientCOnnectionTCP from UA_Client_connect
=> Fix Tutorial_client_firstSteps

doc/tutorial_client_firstSteps.rst, doc/tutorial_server_firstSteps.rst
* Added 2 headers
* Commented out 1 header
* Changed 2 parameters in client creation
* Unified space usage
=> Fix "First steps with open62541-client" tutorial

include/ua_connection.h, plugins/ua_network_tcp.c, src/client/ua_client.c, src/client/ua_client_internal.h, src/server/ua_server_binary.c, src/ua_connection.c, src/ua_securechannel.c, src/ua_securechannel.h
The client in the moment has a struct of connection and securechannel. For future extensions it is easier to have just a pointer. 
Moreover I added the checking of the sequenceNumber in the client.
=> Changes Client

appveyor.yml
This is only a refactoring. The compilation tests are still the same as before.
It should also fix random timeouts when downloading cygwin
=> Refactor appveyor.yml

appveyor.yml
In PR #682 the cache path was wrong
=> Fix appveyor cache path

tests/CMakeLists.txt, tests/check_discovery.c
Unit tests for discovery service.
Not yet ready for merge, waiting until CI and Coveralls tests run through.
=> Unit tests for discovery service

doc/CMakeLists.txt
=> add latex pdf generation in cmake

appveyor.yml
exes are back in appveyor's artifacts
=> Artifacts appveyor

doc/tutorial_client_firstSteps.rst, doc/tutorial_server_firstSteps.rst, doc/tutorial_server_method.rst, doc/tutorial_server_variables.rst, examples/client_firstSteps.c, examples/server_firstSteps.c, examples/server_method.c, examples/server_variable.c
Including code from example for first tutorial. I omitted all the non-amalgamtion stuff.
It can be used to help fixing #509 
If this is okay for you I would do the same for the rest of the tutorials.
Was there a reason for the whitespace between *#* and *include*?
=> Include code from server_firstSteps.c in documentation

CMakeLists.txt, doc/building.rst
align CMAKE options and build documentation
relates #509
=> Improve build documentation

appveyor.yml, tools/amalgamate.py
=> Mingw32 amalgamation

CMakeLists.txt, src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_server_worker.c, src/server/ua_services_discovery.c, tests/check_discovery.c
Some hotfixes for the PR #730 / #732
=> Hotfixes for mdns implementation

.travis.yml, CMakeLists.txt, src/server/ua_services_discovery.c, tests/check_discovery.c, tools/travis/travis_linux_script.sh
Limit mDNS label to max 63 chars according to DNS RFC
=> Limit mDNS label length

.travis.yml, appveyor.yml, tools/travis/travis_linux_before_install.sh, tools/travis/travis_linux_script.sh
Fix TODO `Merge Travis/Appveyor improvements into master beforehand to lighten the PR` in PR #732 
Please rebase the branch `feature_mdns` after merging this PR and `0.2` into master (yes, you can force push).
=> Extract Travis/Appveyor changes from PR #732 into separate PR

src/server/ua_server_worker.c
UA_UInt32 for interval in nsec means maximum interval of 429 seconds -> too small
Especially RegisterServer needs an interval of 600 seconds.
=> Use UA_UInt64 for repeated job interval

src/server/ua_server_worker.c
Cast to UInt64 needed, otherwise it will be calculated as UInt32
=> Fix conversion to UInt64

include/ua_types.h, src/server/ua_services_attribute.c, src/ua_types.c
=> allow deep numeric ranges to reach into scalars containing an array

.gitignore, CMakeLists.txt
To make it easier to integrate open62541 within external toolchains.
=> Add install section for CMake

examples/CMakeLists.txt, examples/server_inheritance.c
Following @ichrispa comments from #802, I would like to add  tests, documentation and an example for instantiation and inheritence in open62541
=> WIP: Add Test, Documentation and Example for instantiation and inheritence

FEATURES.md, README.md
First draft for the features table. See https://github.com/open62541/open62541/issues/810
I took the supported services from `services.h`
For the lower table please check it carefully, since I just C&P it from node-opcua.
=> Features Table

CMakeLists.txt, examples/CMakeLists.txt, examples/server_udp.c, plugins/ua_network_udp.c, plugins/ua_network_udp.h, src/server/ua_services_attribute.c
As mentioned in #818 the udp network layer code was not update for recent code changes
=> Fix compilation errors in UDP network plugin

tools/travis/travis_linux_after_success.sh
My previous commit had some errors. Needs to be merged so I can test it
=> Fix travis after_success script

doc/tutorial_server_firstSteps.rst
Thanks @deyspandan (https://github.com/open62541/open62541-www/pull/6)
=> Include closing bracket

plugins/ua_network_tcp.c
For developers/users it's hard to find out what the problem is if there is no detailed error message.
=> Add error message to "Connection failed" error

deps/libc_time.c, plugins/ua_network_tcp.c, src/client/ua_client.c, src/client/ua_client_highlevel.c, src/client/ua_client_highlevel_subscriptions.c, src/server/ua_nodestore.c, src/server/ua_nodestore_concurrent.c, src/server/ua_server.c, src/server/ua_server_utils.c, src/server/ua_server_worker.c, src/server/ua_services_attribute.c, src/server/ua_services_call.c, src/server/ua_services_discovery.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_session.c, src/server/ua_services_subscription.c, src/server/ua_services_view.c, src/server/ua_subscription.c, src/ua_connection.c, src/ua_securechannel.c, src/ua_types.c, src/ua_types_encoding_binary.c, tools/generate_statuscode_descriptions.py, tools/pyUANamespace/open62541_MacroHelper.py
There were some places where the post(in|de)crement could not be changed, e.g. myArray[i++]. I hope I spotted all cases.
=> Be afraid of premature pessimization, use pre(in|de)crement  ;D

tools/amalgamate.py
This fixes a warning with some compilers.
I am not too sure about the desired output, but this should match.
=> Added newline to amalgameted file

tools/travis/travis_linux_before_install.sh, tools/travis/travis_linux_script.sh
Add specific echo commands in travis script to fold long output of travis log.
See https://travis-ci.org/Pro/open62541/jobs/201509063 for an example.
=> Travis fold log

tools/amalgamate.py
Trying to fix the random Travis/Appveyor build fails, as described in #970
=> Fix random build fails on travis/appveyor

examples/client.c
ref->nodeId.nodeId.namespaceIndex is the interesting one, if one wants to work with the node found.
=> Small Fix in client.c

Dockerfile, TinyDockerfile
=> Fix docker build error - " No CMAKE_CXX_COMPILER could be found."

plugins/ua_network_tcp.c
This PR fixes an #1012 with an issue with networking on windows.
On Unix, we receive an error on the socket and can filter out closed sockets without synchronizing threads.
On Windows, we need to filter out closed sockets before "select".
=> remove closed sockets before select

include/ua_client.h, tests/CMakeLists.txt, tests/check_client_highlevel.c
Additionally fixes a small bug in ua_client.h
Not yet ready to merge since there are still some bugs.
=> Add unit tests for client highlevel functions

examples/server_readspeed.c, src/server/ua_services_attribute.c, src/server/ua_services_subscription.c, tests/check_services_subscriptions.c
Adds additional basic unit tests for subscription.
Additionally fixes bug for Service_Read which used wrong Browse name for Encoding `Default Binary`
=> Unit tests for subscription and small bug fix

appveyor.yml
Hopefully this fixes random fails on AppVeyor. Let's see what the result of this PR shows...
=> Try to fix random appveyor build fails

plugins/ua_network_tcp.c, src/server/ua_server_ns0.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_view.c, src/ua_timer.c
Fixes latest errors on VS2008 from 0.2 merge
=> Fix build on VS2008 and support C++ compilation

tests/CMakeLists.txt, tests/check_discovery.c
@jpfr does this fix #1035 for you?
=> Only enable multicast unit tests if multicast is enabled

src/server/ua_nodes.c, src/server/ua_nodes.h, src/server/ua_server_internal.h, src/server/ua_server_utils.c, src/server/ua_services_call.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_view.c, src/ua_session.c, src/ua_session.h, tests/check_client_highlevel.c, tests/check_services_view.c
Internal Nomenclature: ReferenceKind = (ReferenceType + direction)
This PR speeds up searching in the references, as we can skip all targets of the same reference type + direction.
Adding many nodes goes down from minutes to seconds.
=> WIP: structure node reference by reference "kind"

src/server/ua_server_worker.c
Two edge cases were missed for removing of repeated jobs.
First, the job in tmp_rj could be removed and accessed in the
LIST_FOREACH_SAFE macro. Second, the job "lastNow" could be
removed and accessed during the search for the next insertion
point.
The master branch was not exposed to the bug, as the code was
already cleaned up in the push to make repeated jobs available
in the client.
=> fix removing repeated jobs by a repeated job

CMakeLists.txt, include/ua_config.h.in, plugins/ua_debug_dump_pkgs.c, src/server/ua_server_binary.c, src/ua_connection.c, src/ua_util.h, tests/fuzz/binary.dict, tests/fuzz/fuzz_binary_message.cc, tests/testing_networklayers.c
Ref: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2690
@jpfr can you please review.
This should fix at least the first symptoms of the current fuzzing bug.
=> Fix fuzzing issue 2690

src/ua_types_encoding_binary.c
Reference: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2883
Credit to OSS-Fuzz
=> Fix memory leak on last array element

src/ua_types_encoding_binary.c
Credit to OSS-Fuzz
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2888
=> Fix memory leak

src/client/ua_client_highlevel_subscriptions.c
One of the comments even spelled out how this block of code should be named -- findSubscription.
=> Refactor duplicate code into a named function.

examples/server_nodeset.c
I suspect that this is a fallout from
commit a8012d3040f903ffd127d06c70c73cbc87379602
Author: Infinity95 <mark.giraud@student.kit.edu>
Date:   Thu Aug 10 19:00:32 2017 +0200
endpoints in the server config; new/delete functions for the server config
=> Unbreak the build

src/client/ua_client_highlevel.c
Before it did return UA_BADINTERNALERROR.
Also fix #1190
=> Fix reading of nodeClass attribute

tools/gdb-prettyprint.py, tools/hex2bin.py, tools/pyUANamespace/generate_open62541CCode.py, tools/pyUANamespace/open62541_MacroHelper.py, tools/pyUANamespace/open62541_XMLPreprocessor.py, tools/pyUANamespace/ua_builtin_types.py, tools/pyUANamespace/ua_constants.py, tools/pyUANamespace/ua_namespace.py, tools/pyUANamespace/ua_node_types.py
This changes fixes the interpreter locations for a set of Python files.
=> Fix interpreter locations

examples/CMakeLists.txt, examples/custom_datatype/client_types_custom.c, examples/custom_datatype/custom_datatype.h, examples/custom_datatype/server_types_custom.c
Includes examples for client and server. The data type used is 3D point example.
Thanks to @Muddasir-Shakil
=> Create examples for custom datatypes

CMakeLists.txt
=> Fix #1198 version commit id was not set

tests/fuzz/fuzz_binary_decode.cc, tools/generate_datatypes.py, tools/generate_statuscode_descriptions.py, tools/travis/travis_linux_script.sh
Also adds check on Linux for CI, to explicitly test python2 and python3
=> Fix scripts to support python 3

CMakeLists.txt, include/ua_config.h.in, tools/generate_datatypes.py
We can use this PR to collect all the commits and changes which should be backported to the maintenance release 0.2.1
=> Backporting to 0.2.1

CMakeLists.txt, src/server/ua_securechannel_manager.c, src/server/ua_server_binary.c, src/ua_securechannel.c, src/ua_types.c
Includes integer overflow, mem leaks and access after return.
=> Bugfixes detected by oss-fuzz

examples/nodeset/server_nodeset.c, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py
This PR is a collection of small bugfixes for the new nodeset compiler implementation
=> Small bugfixes for nodeset compiler

CMakeLists.txt, include/ua_config.h.in, plugins/ua_network_tcp.c, plugins/ua_network_udp.c, src/ua_types_encoding_binary.c
Add vxworks option to CMakelists.txt, include the right files
for select in networking, and solve uncompatible code
=> Add VxWorks Support

plugins/ua_securitypolicy_none.c, src/client/ua_client.c, src/server/ua_server_binary.c, src/server/ua_services_securechannel.c, src/server/ua_services_session.c, src/ua_securechannel.c
This PR fixes a few issues that are only present when using actual encryption.
=> Fix bugs preventing encryption from working correctly

src/server/ua_services_attribute.c
When reading the description of the Bad_NotWritable status code
it says: "The access level does not allow writing to the Node" while
the description of the Bad_UserAccessDenied says:
"User does not have permission to perform the requested operation.".
Different status codes are used to explicitly tell if the node
doesn't accept the request or if the user is not allowed to
execute the request.
=> AccessLevel attribute check for reading/writing variable nodes

src/server/ua_services_discovery.c
Fix oss-fuzz issue 3736
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=3736
=> Check for duplicate entry in filter list

src/ua_util.h
checking for compiler extensions
=> use thread-local for C++11, check for standard compliance before

src/client/ua_client_connect.c
fix https://github.com/open62541/open62541/issues/1289
=> fix client securechannel

examples/nodeset/server_nodeset.xml, tools/nodeset_compiler/backend_open62541_nodes.py
For Variable and Object nodes the Nodeset Compiler added the hasTypeDefinition reference two times.
=>  Fix #1302 duplicate hasTypeDef 

examples/server_certificate.c, src/ua_securechannel.c, src/ua_types_encoding_binary.c
Fixes build error https://github.com/google/oss-fuzz/issues/953
and memory leak:  https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4020
=> Various fuzzer fixes

plugins/ua_network_tcp.c
fix https://github.com/open62541/open62541/issues/1316
=> fix connection problem with siemens OPC UA .NET Client

src/client/ua_client_highlevel_subscriptions.c
forcing UA_Client_Subscriptions_manuallySendPublishRequest to end after timeout
see https://github.com/open62541/open62541/pull/1311 https://github.com/open62541/open62541/issues/1308
=> in some cases of "stress" UA_Client_Subscriptions_manuallySendPublishRequest never end

src/server/ua_subscription.c, src/server/ua_subscription.h
fix https://github.com/open62541/open62541/issues/1308
=> save the position of the last monitored item sent

tests/fuzz/fuzz_binary_decode.cc
Add testing of UA_encodeBinary to fuzzer
=> Add fuzzer test for UA_encodeBinary

include/ua_plugin_nodestore.h, plugins/ua_nodestore_default.c, src/server/ua_nodes.c, src/server/ua_server.c, tests/server/check_server_userspace.c
=> Fix copy of references. 

src/ua_types.c
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4178
=> Fix dereference of NULL

tools/nodeset_compiler/backend_graphviz.py, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/nodeset.py, tools/nodeset_compiler/nodeset_testing.py
=> Fix #1346 force encoding to utf-8

src/server/ua_services_nodemanagement.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4183
=> Check type matching corresponding nodeclass when adding node

examples/client.c, include/ua_client_highlevel.h, src/client/ua_client_highlevel_subscriptions.c, tests/client/check_client_subscriptions.c
If you agree, I can modify examples/includes/tests files.
=> adding samplingInterval to UA_Client_Subscriptions_addMonitoredItem

.gitignore, tools/travis/travis_linux_script.sh
=> Ignore test and examples directory for coveralls

src/server/ua_services_subscription.c, src/ua_session.c, src/ua_session.h
=> save last seen immediate subscription

examples/server.c, include/ua_plugin_network.h, include/ua_server_config.h, plugins/ua_config_default.c, plugins/ua_config_default.h, plugins/ua_network_tcp.c, src/server/ua_server_worker.c, tests/server/check_server_userspace.c
replace https://github.com/open62541/open62541/pull/1380
=> add custom hostname

src/server/ua_nodes.c, src/server/ua_services_nodemanagement.c, tests/CMakeLists.txt, tests/server/check_node_inheritance.c
See #1363 for a more detailed description
=> Inherit node value and modelling rule of intermediate types

src/server/ua_services_securechannel.c, src/ua_securechannel.c
=> possible fix for #1224

src/ua_types_encoding_binary.c, tests/fuzz/fuzz_binary_message.cc
Fix heap buffer overflow if exchangeBuffer did not help
see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4496
=> Fix heap buffer overflow

tests/client/check_client_subscriptions.c
=> add test for #968

src/client/ua_client_connect.c
fix https://travis-ci.org/StalderT/open62541/jobs/314763869#L1511
=> fix travis warning

doc/CMakeLists.txt
https://travis-ci.org/open62541/open62541/jobs/315263985#L1341
=> remove PDFLATEX_COMPILER --quiet option

examples/client_connect_loop.c, examples/tutorial_client_firststeps.c, include/ua_types.h, plugins/ua_clock.c, plugins/ua_log_stdout.c, plugins/ua_network_tcp.c, src/client/ua_client.c, src/client/ua_client_connect.c, src/client/ua_client_highlevel_subscriptions.c, src/server/ua_securechannel_manager.c, src/server/ua_server_worker.c, src/server/ua_services_discovery.c, src/server/ua_services_discovery_multicast.c, src/ua_connection.c, src/ua_session.c, src/ua_timer.c, src/ua_types.c, tests/check_types_builtin.c, tests/testing-plugins/testing_clock.c, tools/nodeset_compiler/backend_open62541_datatypes.py
fix https://github.com/open62541/open62541/issues/1439
=> fix #1439 (UTC / LocalTime)

src/client/ua_client_connect.c, src/client/ua_client_discovery.c, src/server/ua_server_discovery.c
Initializations are performed in the __UA_Client_Service function
https://github.com/open62541/open62541/blob/983f956003269732b023e24a68a32bedbedb8f18/src/client/ua_client.c#L306
=> Removes unneeded initializations

examples/server.c, examples/server_certificate.c
[server_certificate.c:31]: (error) Resource leak: fp
[server.c:34]: (error) Resource leak: fp
=> fix cppcheck error

include/ua_client_highlevel.h, src/client/ua_client_highlevel_subscriptions.c, tests/client/check_client_subscriptions.c
=> fix UA_Client_Subscriptions_addMonitored(Items/Events) definition

include/ua_constants.h, src/server/ua_subscription_datachange.c
fix https://github.com/open62541/open62541/issues/1505
=> add InfoBits Overflow

AUTHORS
in addition to https://github.com/open62541/open62541/pull/1514
=> add me in AUTHORS

src/server/ua_nodes.c, src/server/ua_server_binary.c, src/server/ua_services_session.c
See the corresponding commit messages
=> Various fuzzer bug fixes

.travis.yml, src/server/ua_services_nodemanagement.c, tests/check_types_builtin.c, tests/server/check_discovery.c, tests/server/check_server_userspace.c, tools/travis/travis_linux_before_install.sh, tools/travis/travis_linux_script.sh
This PR adds unit tests and support for TinyCC (tcc) compiler
Fixes #1217
=> Add support for TinyCC

tests/client/check_client.c
https://ci.appveyor.com/project/open62541/open62541/build/5191/job/e8w6y07yp3rnfwsr#L8968
=> fix Client_Reconnect test. Sometimes failed with appveyor.

src/server/ua_services_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, tests/server/check_services_subscriptions.c
fix https://groups.google.com/forum/#!msg/open62541/5LylGYaew_Y/xaPxHtn8AQAJ
see https://github.com/open62541/open62541/pull/1506
=> add shrinkMonitoredItemQueue and a test

CMakeLists.txt, include/ua_config.h.in, plugins/ua_clock.c, plugins/ua_network_tcp.c, plugins/ua_network_udp.c, src/client/ua_client_internal.h, src/server/ua_securechannel_manager.h, src/server/ua_session.h, src/server/ua_session_manager.h, src/ua_securechannel.h, src/ua_util.h
An adaptation of the code to freeRTOS OS using LwIP stack. It was tested with LwIP 2.0.3 and worked partially (the opcua server became unstable after many nodes were added, but the problem was on the heap management, and wans't solved yet). 
Related to pull request #1160 and issue #1149
=> First Changes for freeRTOS

examples/client_subscription_loop.c, examples/server_instantiation.c, examples/tutorial_datatypes.c, examples/tutorial_server_datasource.c, examples/tutorial_server_object.c, include/ua_server.h, include/ua_server_config.h, plugins/ua_accesscontrol_default.c, plugins/ua_config_default.h, plugins/ua_network_tcp.c, plugins/ua_securitypolicy_basic128rsa15.c, src/client/ua_client_connect.c, src/client/ua_client_highlevel_subscriptions.c, src/server/ua_mdns.c, src/server/ua_server_binary.c, src/server/ua_server_ns0.c, src/server/ua_server_worker.c, src/server/ua_services.h, src/server/ua_services_attribute.c, src/server/ua_services_call.c, src/server/ua_services_discovery_multicast.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_subscription.c, src/server/ua_services_view.c, src/ua_types.c, src/ua_types_encoding_binary.c, tools/generate_datatypes.py
found with cpplint ```Line ends in whitespace``` https://github.com/open62541/open62541/pull/1538
=> remove unneeded whitespaces

plugins/ua_config_default.c, plugins/ua_nodestore_default.c
=> Trivial corrections

include/ua_server.h, src/server/ua_server_internal.h, src/server/ua_services_nodemanagement.c, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/nodeset_compiler.py
Fixes #1547 wrong inheritane of child nodes
=> Use _begin and _finish methods in Nodeset Compiler

src/ua_types_encoding_binary.c
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5835
=> Check recursion limit for DiagnosticInfo containing DiagnosticInfo

tests/client/check_client.c
To verify #775 this adds a unit test.
The issue was probably fixed in https://github.com/open62541/open62541/commit/e15cdfacbee3692a6a1a05a9c073e43efcd7f0b2
=> Add unit test for empty GetEndpoints call

src/server/ua_server_binary.c
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=6026
=> Fix memleak only happening on fuzzer

tests/client/check_client_subscriptions.c
https://travis-ci.org/open62541/open62541/jobs/343010556#L8030 seems to happen in some cases
=> try fixing client subscription test

include/ua_types.h, src/ua_types.c
=> Add UA_ExpandedNodeId_equal and UA_QualifiedName_equal

plugins/ua_pki_certificate.c
@jpfr This should fix the issue you mentioned
=> Fix allow all when no cert list provided

CMakeLists.txt, tools/nodeset_compiler/backend_open62541_datatypes.py
Allows overriding the NS0 file if someone wants to use his own minimized custom NS0 xml
=> Allow overriding of NS0 file

examples/server_inheritance.c, examples/server_instantiation.c, examples/tutorial_server_datasource.c, examples/tutorial_server_object.c, examples/tutorial_server_variable.c, examples/tutorial_server_variabletype.c, include/ua_server.h, src/server/ua_nodes.c, src/server/ua_server_internal.h, src/server/ua_server_ns0.c, src/server/ua_services_nodemanagement.c, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_nodes.py
=> Set variable types in examples and add example for _begin and _finish

examples/client_subscription_loop.c
Adapted `client_subscription_loop.c` to equal `client_connect_loop.c`, `ua_services_discovery_multicast.c`, `ua_clock.c` and `ua_network_tcp.c`.
=> Adapted POSIX feature defines to be equal to other places

tools/appveyor/install.ps1
https://ci.appveyor.com/project/open62541/open62541/build/job/virfudyb72lbpig9#L54
=> fix appveyor

src/server/ua_server_internal.h, tools/appveyor/build.ps1, tools/appveyor/install.ps1
=> UPDATE: remove const qualifier from edit node

CMakeLists.txt, doc/CMakeLists.txt, doc/conf.py, doc/nodeset_compiler.rst, doc/protocol.rst, include/ua_client.h, include/ua_client_config.h, include/ua_server.h, plugins/ua_config_default.c, src/server/ua_server_discovery.c, tools/generate_datatypes.py, tools/travis/travis_linux_after_success.sh, tools/travis/travis_push_coverity.sh, tools/travis/travis_push_doc.sh
After this is merged we can simply add bugfixes to 0.3 and new features to master, and then merge 0.3 into master from time to time
=> Merge 0.3 into master

include/ua_client_config.h, plugins/ua_config_default.c, tools/nodeset_compiler/backend_open62541.py
fix compilation error #1698 
replace #1699
=> fix for #1698

plugins/ua_network_tcp.c, plugins/ua_securitypolicy_basic256sha256.c
This PR is a collection of PRs for backporting commits in master into 0.3
We can leave it open for a bit to collect more commits
=> WIP: Backport master commits to 0.3

examples/encryption/client_basic128rsa15.c, examples/encryption/server_basic128rsa15.c, examples/encryption/server_basic256sha256.c
https://github.com/open62541/open62541/pull/1705
=> unify : include "common.h"

CMakeLists.txt, examples/tutorial_datatypes.c, include/ua_client.h, include/ua_server.h, src/client/ua_client_discovery.c, src/server/ua_services.h, src/server/ua_services_discovery.c, tests/check_types_memory.c, tests/client/check_client_highlevel.c, tests/client/check_client_subscriptions.c, tools/generate_datatypes.py, tools/schema/datatypes_discovery.txt, tools/schema/datatypes_method.txt, tools/schema/datatypes_minimal.txt
This PR adds a file datatypes_method.c.
We can use the mechanism for all optional features to reduce the binary footprint.
=> Generate datatypes only when the feature is used

src/server/ua_services_discovery_multicast.c, src/ua_util.h
=> replace MIN/MAX by UA_MIN/UA_MAX

src/ua_types.c, src/ua_types_encoding_binary.c, tools/generate_datatypes.py
Some small changes to enable a future effort...
=> [WIP] Some changes to enable a JSON encoding implementation

src/client/ua_client_subscriptions.c
=> CLIENT : remove BadSessionClosed when disconnect

src/pubsub/ua_pubsub.c
The fix was part of PR #1774. It was pulled out of the commit to ensure
a timely merge ahead of additional refactoring work done in the PR.
=> Memfix PubSub publish delta message

include/ua_types.h, src/server/ua_services_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, src/ua_types.c
This also fixes bugs and do not change the API.
This is already on master.
This is the merge for 0.3.
=> Merge to 0.3: Already on master. Add filter support for numeric absolute filters for monitored items

CMakeLists.txt, src/pubsub/ua_pubsub.c, src/pubsub/ua_pubsub.h, src/pubsub/ua_pubsub_manager.c, src/pubsub/ua_pubsub_networkmessage.c, tests/pubsub/check_pubsub_connection_udp.c, tests/pubsub/check_pubsub_publish.c
1. Enable Amalgamation + PubSub results currently in a compile-error. (conditional compilation)
2. Extended PubSub publish test (generate delta messages)
=> Fix PubSub compile Error PubSub + Amalgamation

doc/CMakeLists.txt, examples/CMakeLists.txt, examples/tutorial_server_datasource.c, examples/tutorial_server_monitoreditems.c, include/ua_server.h, src/client/ua_client.c, src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_services_subscription.c, src/server/ua_session.c, src/server/ua_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, tests/server/check_services_subscriptions.c
With this, the server can have local MonitoredItems with a callback method and context pointer each.
=> Add local MonitoredItems for the server

src/server/ua_subscription.c, src/server/ua_subscription_datachange.c, src/server/ua_subscription_events.c
A collection of small improvements for MonitoredItems / Events.
@Pro Can you ignore the "cosmetic" commits and greenlight the other changes?
=> Polish events

include/ua_server.h, src/server/ua_services_subscription.c, src/server/ua_services_view.c, src/server/ua_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, src/server/ua_subscription_events.c, tests/server/check_services_view.c
@Pro
@aDogCalledSpot 
Can you review?
We still need to look into the handling of the event fields.
The severity field should be transmitted with every EventNotification.
But it isn't.
=> Event improvements

src/server/ua_subscription_events.c
This was causing the build to fail.
=> remove findAllSubtypeNodeIderatorCallback

include/ua_server.h, src/server/ua_server.c
Request namespace index by namespace uri from server.
=> Add server helper function "getNamespaceByName"

examples/CMakeLists.txt, tools/certs/create_self-signed.py, tools/certs/localhost.cnf
At the moment the "UA_BUILD_SELFSIGNED_CERTIFICATE" option is not creating a self-signed certificate. Therefore there are trusting issues with some tools like UAExpert.
=> Create self-signed ApplicationInstanceCertificate

src/server/ua_mdns.c, src/server/ua_services_nodemanagement.c, src/ua_types.c, src/ua_types_encoding_binary.c, tests/testing-plugins/testing_policy.h
=> Consistantly use UA_Boolean instead of bool

tools/schema/Opc.Ua.NodeSet2.Minimal.xml
Fixed misordered items, introduced in #1862
=> Fixed item order of Opc.Ua.NodeSet2.Minimal.xml

CONTRIBUTING.md
This PR proposes a first set of contribution guidelines.
So we can point new contributors to our "way of doing things".
Okay @open62541/open62541-core ?
Okay everybody else?
=> Proposed Contribution Guidelines

examples/server_ctt.c
Before the server would just exist.  This fixes #1853.
=> server_ctt starts without defined certificate

examples/server_ctt.c, include/ua_plugin_pki.h, plugins/ua_pki_certificate.c, src/server/ua_securechannel_manager.c, src/server/ua_securechannel_manager.h, src/server/ua_server_binary.c, src/server/ua_server_ns0.c, src/server/ua_services_session.c, src/server/ua_services_subscription.c
Merge somes master commit to 0.3.
What do you think? Would there be others to add?
=> Merge master to 03

src/server/ua_services_view.c
Add MaxNodesPerBrowse handling
=> Fix max nodes per browse handling (ServerCapabilities)

include/ua_server_config.h, src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_server_ns0.c, src/server/ua_services_attribute.c, src/server/ua_services_call.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_subscription.c, src/server/ua_services_view.c, src/server/ua_session.c, src/server/ua_session.h, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, tests/server/check_server_readspeed.c, tests/server/check_services_subscriptions.c, tests/server/check_subscription_events.c, tools/travis/travis_osx_before_install.sh, tools/travis/travis_osx_script.sh
=> Added callback to register MonitoredItems in userland

src/client/ua_client.c, src/client/ua_client_connect.c, src/client/ua_client_connect_async.c, src/server/ua_securechannel_manager.c, src/server/ua_server_binary.c, src/ua_securechannel.c, src/ua_securechannel.h, tests/check_securechannel.c, tests/fuzz/ua_debug_dump_pkgs_file.c, tests/server/check_server_readspeed.c
Before, the client could perform a RenewSecureChannel between two
chunks.
Still WIP. To be merged after #1940.
=> [WIP] Always process chunks in-order

src/server/ua_subscription.c
CTT subscription Basic script passed for me.
=> Store retransmission message in right order

plugins/ua_securitypolicy_basic256sha256.c
=> [0.3] cherry-pick Update URIs in SecurityPolicy #2021

src/server/ua_services_session.c
https://github.com/open62541/open62541/pull/2018
=> [master] cherry-pick fix Service_CreateSession after #2013

ISSUE_TEMPLATE.md
Github does not see the issue template in the tools folder
=> Move template back

CMakeLists.txt
Replaces #1975 and is also included in #2000
=> Add additional check for valid git commit id. Fixes #1969

arch/CMakeLists.txt, arch/ua_architecture_definitions.h, arch/wec7/CMakeLists.txt, arch/wec7/ua_architecture.h, arch/wec7/ua_architecture_functions.c, arch/wec7/ua_clock.c, plugins/ua_log_stdout.c, src/server/ua_services_discovery.c, tools/travis/travis_linux_before_install.sh
=> Add Windows Embedded Compact 7 (WEC7) Architecture

src/server/ua_services_view.c, src/ua_types_encoding_binary.c
See https://github.com/open62541/open62541/pull/1949#issuecomment-422366740
=> Backport cherry-picked commits to 0.3

examples/client_subscription_loop.c, src/client/ua_client.c, src/client/ua_client_connect_async.c, src/client/ua_client_worker.c, src/server/ua_server_binary.c, src/ua_securechannel.c, src/ua_securechannel.h, tests/client/check_client.c, tests/fuzz/ua_debug_dump_pkgs_file.c
=> WIP: Fix #1930

src/server/ua_services_session.c
The server certificate included in the Create session response have
been retrieved from the secure channel that the session is created 
on. This works if the security policy of the secure channel != security
policy none.
If the secure channel is not secured (security policy none) but the
security policy of the UserIdentityToken != security policy none 
(e.g. encrypted password when using UserIdentityToken Username_1),
the certificate of the endpoint must be present in the Create session 
response. In this case it is not possible to retrieve it from the channel,
as the channel is not secured and has no reference to the certificate of 
the device.
A common solution that works in both cases is to retrieve the
certificate from the endpoint of the server that the client has
connected to.
=> Get server certificate of create session rsp from endpoint

include/ua_plugin_pubsub.h, plugins/ua_config_default.c, src/pubsub/ua_pubsub_manager.c, tests/CMakeLists.txt, tests/pubsub/check_pubsub_multiple_layer.c
- Added helper function to reallocate memory.
- Added unit test
Signed-off-by: Heiko Thiery <heiko.thiery@kontron.com>
=> fix issue with freeing transport layer memory

arch/ua_network_tcp.c
=> fix crash for client connect async / fix #1912

src/server/ua_services_subscription.c, src/server/ua_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_monitoreditem.c, src/ua_securechannel.c
This pulls all the counting logic into ua_subscription_monitoreditem.c.
@aDogCalledSpot Can you have a short look?
=> [Review] Refactor OverflowEvent counting 

src/server/ua_subscription_monitoreditem.c
Fix unused variable compilation error
=> Remove unused variable

include/ua_server_config.h, tests/server/check_services_subscriptions.c
=> add comments about the duration

src/server/ua_services_nodemanagement.c, tools/generate_datatypes.py
Related to #2119 where datatypes node ids can also be string values with quotations within the string
=> [Review] Correctly handle datatypes with string NodeIds

tools/generate_datatypes.py
Reduces the line length of the generated datatype code by adding newlines. Fixes #2104
=> Reduce line length of generated datatype code. Fixes #2104

src/client/ua_client_connect.c, src/client/ua_client_connect_async.c
=> client : reset requestId and sendSequenceNumber at connect fix #2139

src/client/ua_client_connect.c
client : reset requestId at connect fix #2139
=> client : reset requestId and sendSequenceNumber at connect fix #2139 (0.3)

README.md
@basyskom-jvoe can you please approve? Please also check the contact address and the details.
Also, we agreed that every commercial partner should have a landing page on his webpage which describes the services he offers in connection with open62541. Could you also create a similar page on your domain as Kalycito already has (https://www.kalycito.com/landing/open62541-commercial-partner). We can than link this readme and the webpage correspondingly.
I just saw, that you are listed on our webpage, but not in the readme.
=> Add basysKom as commercial partner

plugins/ua_network_pubsub_ethernet.c
The issue and the solution were reported by Andrew Crosland.
=> PubSub: Fix GCC issue for structure initialization #2134

src/client/ua_client.c
=> [master] Fix Missing null checks for callback functions (#2168)

src/client/ua_client.c
=> [0.3] Fix Missing null checks for callback functions (#2168)

tools/nodeset_compiler/nodes.py, tools/nodeset_compiler/nodeset.py
=> [0.3 Backport] NodesetCompiler: Correctly handle namespace mapping for encoded objects

src/server/ua_session.h, src/server/ua_subscription.c, src/server/ua_subscription.h
=> Subscriptions: Track number of retransmission messages for session

tools/travis/travis_linux_script.sh
=> CI: Include shared libs in release

src/client/ua_client.c, src/server/ua_server_binary.c, src/ua_securechannel.c, src/ua_securechannel.h, tests/fuzz/ua_debug_dump_pkgs_file.c
fix #1930 #1844 based on the work of @Infinity95
=> [0.3] add previousSecurityToken

tools/travis/travis_linux_script.sh, tools/travis/travis_push_release.sh
This is a followup fix of #2182
=> CI: Pack lib binaries into zip and tar release

include/ua_types.h, src/server/ua_subscription_datachange.c, src/ua_types.c
=> [0.3] Add Boolean to the numeric data types author: @jpfr

tools/travis/travis_linux_script.sh, tools/travis/travis_push_release.sh
Cherry-picked from 0.3.
Can be merged as soon as the release test is successful. I'll update here.
=> [WIP] Hotfix/release binaries master

include/ua_client_config.h, include/ua_plugin_network.h, src/client/ua_client.c, src/ua_connection.c
prevent reentrant renew secure channel
fix #2199 #1844
=> prevent reentrant renew securechannel

tools/c2rst.py, tools/certs/create_self-signed.py, tools/generate_datatypes.py, tools/generate_nodeid_header.py, tools/generate_statuscode_descriptions.py, tools/nodeset_compiler/backend_graphviz.py, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py, tools/nodeset_compiler/nodeset.py, tools/nodeset_compiler/nodeset_compiler.py, tools/update_copyright_header.py
See also https://lgtm.com/projects/g/open62541/open62541/alerts
=> CodeQuality: Fix issues found by lgtm.com

CMakeLists.txt
=> Removes `merge-all-constants` flag

plugins/ua_accesscontrol_default.c, plugins/ua_accesscontrol_default.h, plugins/ua_config_default.c, src/server/ua_nodes.c, src/ua_types.c, tests/fuzz/fuzz_binary_message.cc
Fixes various issues found by OSS-fuzz.
@jpfr please review.
I needed to change the method signature from 
```
UA_AccessControl
UA_AccessControl_default(UA_Boolean allowAnonymous, size_t usernamePasswordLoginSize,
```
to
```
UA_StatusCode
UA_AccessControl_default(UA_AccessControl *ac,
UA_Boolean allowAnonymous, size_t usernamePasswordLoginSize,
const UA_UsernamePasswordLogin *usernamePasswordLogin)
```
to be able to handle malloc failure correctly.
=> [Review] Fix various OOM checks

CMakeLists.txt, plugins/ua_securitypolicy_basic128rsa15.c, plugins/ua_securitypolicy_basic128rsa15.h, plugins/ua_securitypolicy_basic256sha256.c, plugins/ua_securitypolicy_basic256sha256.h
=>  [Review][0.3] include basic128rsa15 and basic256sha256 in amalgamation

CMakeLists.txt
Same as #2260 but for master
Fixes #1415 
Fixes #1480 
Fixes #2044
=> Install without amalgamation

tools/generate_datatypes.py
=> generate_datatypes.py cleanup

CMakeLists.txt
Fix for Issue #2290 and another outstanding issue which i noted while fixing the first one
=> [CMake] build environment fixes

tests/server/check_historical_data.c
This fixes the test for historical data server.
It calls the server with UA_TIMESTAMPSTORETURN_BOTH.
This is useful to test if the server has set the source and server timestamps.
This extends the test for bugfix: 8934388fc52308486304958ba41de33626f27f88
=> historical_server: Fix server test.

tools/travis/travis_linux_script.sh
Fixes #2264 and mainly reverts 61aa8b7f4dcba68afb893425be39266f20c02a92
=> 0.3: Do not build shared libs for release

tools/generate_datatypes.py, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/nodes.py
Backports nodeset compiler fixes.
Fixes #2317
=> Backport nodeset compiler fixes

include/ua_plugin_historydatabase.h, plugins/historydata/ua_plugin_history_data_gathering.h
The typedef below is sufficient.
=> No need to fwd declare these structs

plugins/historydata/ua_historydatabackend_memory.c
false as implicitly converted to NULL
=> Fix the type of the return

src/client/ua_client_connect_async.c
=> [WIP] Client: Cleanup async connection HEL handshake; Fix #2295 memleak

include/ua_client_config.h, plugins/ua_config_default.c, src/client/ua_client_connect.c, src/client/ua_client_connect_async.c
This is my first Pull Request.
Implemented #2291.
=> add requestedSessionTimeout to UA_ClientConfig (#2291)

examples/nodeset/testnodeset.csv, examples/nodeset/testnodeset.xml
adds DataTypeDictionary to the nodeset.
Fixes https://github.com/open62541/open62541/issues/1420
=> Provide information for ExtensionObject decoding

tools/nodeset_compiler/backend_open62541_nodes.py
Hi, this PR should fix issue https://github.com/open62541/open62541/issues/2300
=> [REVIEW] Nodeset-Compiler: fix return value

tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py, tools/nodeset_compiler/nodeset.py
=> NodesetCompiler: fix python shebang lines

include/ua_plugin_access_control.h, include/ua_plugin_historydatabase.h, include/ua_server.h, plugins/historydata/ua_historydatabackend_memory.c, plugins/historydata/ua_historydatabase_default.c, plugins/historydata/ua_plugin_history_data_backend.h, plugins/ua_accesscontrol_default.c, src/server/ua_server.c, src/server/ua_server_binary.c, src/server/ua_services.h, src/server/ua_services_attribute.c, tests/server/check_server_historical_data.c, tests/server/historical_read_test_data.h, tools/schema/datatypes_historizing.txt
This is the server side of the history update functionality.
See the https://github.com/open62541/open62541/pull/2362 pull request for tests.
=> server_historical_update: Add api to alter raw data.

tools/generate_datatypes.py
=> DatatypeGenerator: Also build types which have 'Test' in Name

examples/nodeset/CMakeLists.txt, examples/nodeset/Opc.Ua.POWERLINK.NodeSet2.bsd, examples/nodeset/server_nodeset_powerlink.c, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py
Fixes #2300 
Also adds example for PowerLink Nodeset.
=> NodesetCompiler: Add support for OptionSet

examples/discovery/server_lds.c, examples/discovery/server_register.c, examples/nodeset/CMakeLists.txt, examples/nodeset/server_nodeset_plcopen.c, examples/nodeset/server_nodeset_powerlink.c, examples/nodeset/server_testnodeset.c
=> Janitor stuff

include/ua_client.h, include/ua_client_highlevel.h, src/client/ua_client_highlevel.c, tests/client/check_client_historical_data.c, tests/client/historical_read_test_data.h
This adds client and server historical update.
=> Client history update

tools/generate_datatypes.py
A collection of cosmetic changes for the datatype generator
=> Cleanup datatype generator

examples/access_control/client_access_control.c, examples/tutorial_server_datasource.c, examples/tutorial_server_firststeps.c
Working on improving the examples a bit.
=> Examples: small improvements

src/ua_securechannel.c
I am not really sure if this option is supported or not, but I enabled all the possible options to test some changes, and I experienced this problem that was easy to fix.
=> Fix compilation with UA_ENABLE_UNIT_TEST_FAILURE_HOOKS CMake option enabled

examples/access_control/client_access_control.c, examples/access_control/server_access_control.c, plugins/ua_config_default.c
Janitor stuff + improvements to the AC example
=> Beifang accesscontrol

src/server/ua_services_attribute.c
=> Review: Fix invalid cast in case of writing object attribute EventNotifier

include/ua_server.h
=> Fix UA_Server_writeArrayDimensions

examples/nodeset/testnodeset.csv, examples/nodeset/testnodeset.xml, examples/nodeset/testtypes.bsd, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py
This PR should enable the code generation for arrays nested within an extension object. Example is provided via examples/testnodeset.xml.
Please consider that this PR has WIP status.
=> [REVIEW] NodesetCompiler: enhancement for extension objects

tools/cmake/macros_public.cmake
=> Create output directory for ua_generate_ macros

src/ua_types_encoding_json.c
* Introduce macros for checking types and null values.
* Return decoding error for Guid and DateTime null values.
* Do not set the destination variable for null values, since the calling
function is responsible for initalizing it before calling.
* Allways CHECK_TOKEN_BOUNDS before GET_TOKEN.
=> JSON: cleanup and avoid code duplication in decoding functions

plugins/ua_config_default.c
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11646
=> Stack: Check for out-of-memory while creating server config

doc/installing.rst
=> Doc: Adapt install doc to 0.4

tests/client/check_client_subscriptions.c
=> Completely cover UA_Client_Subscriptions_modify

appveyor.yml, doc/building.rst, tools/appveyor/install.ps1
=> Doc: Adapt install doc to 0.3

src/client/ua_client_connect.c, src/ua_securechannel.c
It helped me for debugging the connection process
=> Added connection logs

include/ua_plugin_nodestore.h, src/server/ua_nodes.c, src/server/ua_server_ns0.c, src/server/ua_services_nodemanagement.c, tests/server/check_node_inheritance.c
First create all child nodes and references, then call the constructors recursively.
=> Delayed constructors

src/ua_types_encoding_binary.c
=> Fix QualifiedName encoding/decoding

README.md
Add success stories to readme.
This should list some interesting projects which use open62541.
=> Success stories

examples/tutorial_datatypes.c
=> Tutorial: renaming ua_types.h to types.h (Issue #2669)

include/open62541/server_config.h, src/server/ua_services.h
I tried squashing my two commits into one, to keep the commit log cleaner. (Should've read the wiki before).
Let me know if I have done it correctly.
=> small readability improvements in doc-comments

CMakeLists.txt, tools/schema/Opc.Ua.NodeSet2.EventsMinimal.xml, tools/schema/Opc.Ua.NodeSet2.HistorizingMinimal.xml, tools/schema/Opc.Ua.NodeSet2.Minimal.xml, tools/schema/datatypes_events.txt
=> Set minimal nodesets for Historizing and Events

arch/network_tcp.c, src/server/ua_services_discovery_multicast.c
Fixes #2634
Same as #2690 for master
=> Stack: Correct cast of SOCKET to int on Windows

src/ua_types_encoding_binary.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12889
=> Stack: Correctly pass pointer to encoding for DiagnosticInfo

plugins/ua_accesscontrol_default.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14567
=> Stack: Avoid double free/heap use after free

plugins/ua_nodestore_default.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14425
=> Stack: Avoid NULL-dereference

src/server/ua_server.c, tests/fuzz/custom_memory_manager.c
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12349
=> Stack: Check for memory allocation success 

src/server/ua_discovery_manager.c, src/server/ua_services_discovery_multicast.c, tests/server/check_discovery.c
=> Stack: Only shut down mDNS if it was initialized before.

.gitmodules, tests/check_types_memory.c, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py
=> Update nodeset to current v1.04

src/server/ua_server_ns0.c
=> Server: Take BuildInfo from the server config at runtime

src/client/ua_client_subscriptions.c, src/server/ua_services_subscription.c, src/server/ua_subscription_monitoreditem.c, tests/server/check_subscription_events.c
=> Fix server crash if no event filter defined. Correctly check client handle in notification.

src/server/ua_services_nodemanagement.c, src/server/ua_subscription_events.c, tests/server/check_node_inheritance.c, tests/server/check_services_nodemanagement.c
See OPC UA Amendment 7
@jpfr please review and merge
=> [REVIEW] Stack: Add support for DefaultInstanceBrowseName (see Amendment 7)

src/server/ua_server_internal.h, src/server/ua_server_utils.c, src/server/ua_services_nodemanagement.c, tests/server/check_node_inheritance.c, tools/schema/Opc.Ua.NodeSet2.Minimal.xml
=> [REVIEW] Stack: Add support for HasInterface reference (Amendment 7)

src/server/ua_server_discovery.c, src/server/ua_server_ns0.c, src/server/ua_services_subscription.c, src/server/ua_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, src/server/ua_subscription_events.c, src/server/ua_subscription_monitoreditem.c, tools/schema/Opc.Ua.NodeSet2.EventsMinimal.xml
The SimpleOverflowEvent type could not be added without the full sn0 activated.
Some more fixes and simplifications in the other commits.
=>  Fix #2758

examples/pubsub/tutorial_pubsub_subscribe.c, include/open62541/server_pubsub.h, src/pubsub/ua_pubsub.c, src/pubsub/ua_pubsub.h, src/pubsub/ua_pubsub_ns0.c, src/pubsub/ua_pubsub_ns0.h, tests/CMakeLists.txt, tests/pubsub/check_pubsub_subscribe.c, tools/schema/datatypes_minimal.txt, tools/schema/datatypes_pubsub.txt
- Add ReaderGroup, DataSetReader, TargetVariables functionality
- The data filtered from the DataSetReader gets updated in the target variable available in the information model
- Multiple ReaderGroup and DataSetReader are not verified
=> [FEATURE] Subscriber implementation

examples/server_ctt.c, src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_server_ns0.c
- Update the ServerArray with same value as NamespaceArray
- Add support for reading multiple CRL files to server_ctt
=> Fixes for CTT

examples/discovery/server_multicast.c, include/open62541/server_config.h, plugins/ua_config_default.c, src/server/ua_discovery_manager.c, src/server/ua_server_config.c
I made a most-easy way of setting the outbound inerface by entering exact IP. In case user wants some more sugar like selecting interface from string, e.g. "eth0", she will need to do it in user-space.
#2774
=> [Review] First attempt of mDNS interface selection (relates to #2774)

CMakeLists.txt, debian/open62541-dev.install, debian/open62541.install
This ports the changes from #2833 and #2841 to master branch. Superset of #2851.
=> Port CMake fixes from 0.3 branch

examples/encryption/server_encryption.c, examples/server_ctt.c, plugins/include/open62541/plugin/pki_default.h, plugins/include/open62541/server_config_default.h, plugins/ua_config_default.c, plugins/ua_pki_default.c, tests/encryption/check_encryption_basic128rsa15.c, tests/encryption/check_encryption_basic256sha256.c
- Usability related bug fix for server_ctt
- Pass issuer list separately
- Add functionality to:
- Check if a not trusted certificate has a CRL file
- Check if a trusted certificate has a CRL file
=> CTT: Security Certificate Validation fixes

tools/travis/travis_linux_before_install.sh
This should fix the latest CI errors
=> CI: Pin docutils to 0.14

tools/travis/travis_linux_before_install.sh
=> [0.3] CI: Pin docutils to 0.14

tools/travis/travis_linux_before_install.sh
=> [master] CI: Pin docutils to 0.14

src/client/ua_client_subscriptions.c
=> Client: Add timeout check for publish response

src/client/ua_client_subscriptions.c, src/server/ua_services_nodemanagement.c, tests/server/check_subscription_events.c
=> Allow abstract events

CMakeLists.txt, src/server/ua_server_ns0.c
This reverts commit 0df12186316f4213cbaa216ff9cfca256e4aa023.
=> Revert "[CTT] Remove unsupported nodes from server namespace"

src/server/ua_services_attribute.c, src/server/ua_services_nodemanagement.c, tests/CMakeLists.txt, tests/server/check_server_callbacks.c
I discovered some issues while working with immutable nodes (UA_ENABLE_IMMUTABLE_NODES)
I was able to break it down into two test cases:
- Value callbacks are not working with immutable nodes.
- While reading multiple attributes of one variable, this variable can be deleted. This is causing an invalid read warning message when analysed by valgrind.
Actually, the second test case has nothing to do with immutable nodes.
I have added corresponding test cases with suggested solutions.
=> Immutable nodes

examples/server_ctt.c, src/server/ua_server_ns0.c, src/ua_securechannel.c
- Disable timestamp check in FindServerRequest
- Change warning log
- Remove subtypes from ServerRedundancy
=> [CTT] Fixes for Micro Embedded Device Server Profile

include/open62541/server.h, include/open62541/types.h, src/server/ua_server_internal.h, src/server/ua_server_utils.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_view.c, src/server/ua_subscription_events.c, src/ua_types.c, tests/server/check_services_nodemanagement.c
=> Refactor browse to fix #2866

examples/server_ctt.c, include/open62541/server_config.h, plugins/ua_config_default.c, src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_server_ns0.c
Both required for certification.
=> Add Namingrules, Add delayed server shutdown

.travis.yml, debian/open62541-dev.install, debian/open62541.install, examples/pubsub/tutorial_pubsub_subscribe.c, examples/server_ctt.c, open62541.pc.in, src/client/ua_client_subscriptions.c, src/server/ua_services_nodemanagement.c, src/ua_types.c, tests/check_utils.c, tests/server/check_subscription_events.c
1.0 branch can be merged into master with:
```
git checkout master
git merge 1.0
```
=> merge: 1.0 into master

src/server/ua_nodes.c, tests/server/check_services_nodemanagement.c
=> NodeManagement: Allow AddNodes with an undecoded ExtensionObject value

examples/server_ctt.c, plugins/include/open62541/plugin/pki_default.h, plugins/ua_pki_default.c
=> Reload certs at runtime

.travis.yml, CMakeLists.txt, appveyor.yml, debian/update_changelog.py, examples/server_ctt.c, include/open62541/server.h, plugins/include/open62541/plugin/pki_default.h, plugins/ua_config_default.c, plugins/ua_pki_default.c, src/server/ua_nodes.c, src/server/ua_server_ns0.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_view.c, tests/server/check_services_nodemanagement.c, tests/server/check_services_view.c, tools/cmake/SetGitBasedVersion.cmake, tools/travis/travis_linux_script.sh
```bash
git checkout master
git merge 1.0
```
=> Merge 1.0 into master

src/server/ua_services_discovery.c
- Remove the redundant listing of DiscoveryUrls in
FindServer service
=> server: CTT - Remove redundant listing of DiscoveryURL in FindServers

src/client/ua_client.c
=> Return error when sending async request on unconnected servers

README.md
Fixes #3049
Will be merged into master with the next merge batch from 1.0 to master
=> Add badge for azure pipeline

.travis.yml, README.md, tools/travis/travis_linux_script.sh
This also updates the readme with some general howto for installing the stack.
=> Correctly update `pack/` branches for release tags

doc/installing.rst
=> fix(docs): Add info about pack branches

arch/network_tcp.c, plugins/ua_config_default.c, src/server/ua_server.c, tests/server/check_server_userspace.c
=> fix(server): Correctly initialize application description discovery urls for custom hostname

tests/fuzz/ua_debug_dump_pkgs_file.c
This PR fixes some of the issues reported by codacy (Error Prone category)
=> Fix codacy issues

src/server/ua_services_nodemanagement.c
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16141
=> fix(server): Do not allow node having itself as parent. Fixes stack-overflow

src/client/ua_client_connect.c
client is disconnected by server on second renew SecureChannel since clientNonce is reused
OPC Unified Architecture, Part 4 (Table 7 defines the parameters for the Service)
clientNonce:
A random number that shall not be used in any other request. A new clientNonce shall be generated for each time a SecureChannel is renewed.
=> create clientNonce on each SecureChannel renew

src/client/ua_client_connect.c
client is disconnected by server on second renew SecureChannel #3024
OPC Unified Architecture, Part 4 (Table 7 defines the parameters for the Service)
clientNonce:
A random number that shall not be used in any other request. A new clientNonce shall be generated for each time a SecureChannel is renewed.
=> create clientNonce on each SecureChannel renew (#3084)

include/open62541/client.h, include/open62541/server.h, plugins/include/open62541/client_config_default.h, plugins/include/open62541/server_config_default.h, plugins/ua_config_default.c, src/client/ua_client.c, src/server/ua_server.c
So we can select logging already during startup.
=> Put Server_new and Client_new into plugin

src/server/ua_server_ns0.c
See OPC UA Spec. Part 5, 1.04, Table 100.
=> (Bug) Fix NonHierarchicalReferences shall be symetric

src/server/ua_server_ns0.c
See OPC UA Spec. Part 5, 1.04, Table 102.
=> (Bug) Fix ReferenceType Aggregates shall be abstract

src/pubsub/ua_pubsub_reader.c
- Get the required Datasetreader even if multiple datasetreader has same Publisher ID
- Modified the return value from Datasetreader to status values
=> fix(pubsub): Multiple datasetreader with same Publisher ID

deps/itoa.c, include/open62541/types.h, src/server/ua_subscription_events.c, src/ua_types_encoding_json.c
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=17099
=> Fix various oss-fuzz issues

.gitmodules, tools/appveyor/install.ps1
See also https://stackoverflow.com/a/38895397/869402
=> ci: Use shallow submodules

src/ua_types_encoding_json.c
=> fix: minor memory issues in json and mdnsd

src/server/ua_nodes.c
Use ziptree macros in UA_Node_copy
=> [Review] Refactor UA_Node_copy function

README.md
Client Example is needed more header to build
=> Add open62541/client_highleve.h header in Example

src/server/ua_services_monitoreditem.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, tests/server/check_monitoreditem_filter.c
This unifies and simplifies the code path for the "hot" sample callback.
=> Cache absolute deadband percentage deadband filter

src/pubsub/ua_pubsub_writer.c
Adding checks to avoid calling UA_calloc with param num == 0.
Because the return value of UA_calloc is in this case implementation defined.
Fixes #3145
=> fix(pubsub): add size checks before UA_calloc calls

tools/nodeset_compiler/type_parser.py
=> fix: Remove datatype_generator debug output

src/server/ua_server_internal.h
UA_Nodestore* now available from server config.
=> [REVIEW] remove nsCtx from UA_Server struct

CMakeLists.txt, doc/building.rst, tools/schema/Opc.Ua.NodeSet2.Part8_Subset.xml, tools/schema/datatypes_dataaccess.txt
This cherry-picks some of the improvements from #2821.
Authorship is retained in the commits.
=> More DataAccess support

README.md, docker/Dockerfile, docker/README.md, tools/travis/travis_linux_script.sh
Currently the builds on Docker Cloud fail. This fixes it.
=> fix(docker): Move Docker files into separate directory and fix Docker Cloud build

deps/base64.c
=> fix(core): Backport various base64 encoding/decoding issues

examples/server_ctt.c, include/open62541/client_config.h, include/open62541/server_config.h, plugins/ua_config_default.c, tools/certs/create_self-signed.py, tools/certs/localhost.cnf
=> Always instantiate a nodestore if not set in the default config

arch/freertosLWIP/ua_architecture.h, include/open62541/config.h.in, include/open62541/server_config.h, plugins/ua_config_default.c, src/server/ua_server_config.c, src/server/ua_server_discovery_mdns.c
This is the case e.g. on an ESP32 chip
=> feat(core): Allow setting custom ip address list if platform does not support getifaddr

examples/nodeset/CMakeLists.txt, tools/cmake/macros_public.cmake, tools/generate_datatypes.py
See also #3315 for master branch
=> fix(datatype-generator): Clarify error message and add IMPORT_BSD option

src/server/ua_subscription_monitoreditem.c, tests/server/check_subscription_events.c
=> Limit overflow events

src/server/ua_subscription_alarms_conditions.c
Refresh start and end events will be created only once when the first condition is created. Refresh events will be reused to save the time used to create those two events each time refresh methods get called.
=> Optimize Condition Refresh Methods

CMakeLists.txt, arch/network_tcp.c, doc/CMakeLists.txt, doc/toc.rst, include/open62541/common.h, include/open62541/plugin/network.h, include/open62541/server.h, include/open62541/types.h, src/pubsub/ua_pubsub_writer.c, src/server/ua_securechannel_manager.c, src/server/ua_securechannel_manager.h, src/server/ua_server.c, src/server/ua_server_binary.c, src/server/ua_server_internal.h, src/server/ua_services_securechannel.c, src/server/ua_services_session.c
Rebase of #3341 for discussion.
=> Server statistics

arch/network_tcp.c, include/open62541/architecture_definitions.h, src/client/ua_client.c, src/client/ua_client_highlevel.c, src/client/ua_client_subscriptions.c, src/pubsub/ua_pubsub_reader.c, src/pubsub/ua_pubsub_writer.c, src/server/ua_server.c, src/server/ua_server_async.c, src/server/ua_server_binary.c, src/server/ua_services_attribute.c, src/server/ua_services_monitoreditem.c, src/server/ua_services_subscription.c, src/server/ua_subscription.c, src/server/ua_subscription_datachange.c, src/ua_securechannel.h, src/ua_securechannel_crypto.c
Now using portable format specifiers for UA_LOG macros
=> Using portable format specifiers

tools/certs/create_self-signed.py
- Add "-c" option for certificate naming
=> refactor(sec): option to provide certificate name

arch/network_ws.c
1. Pad send buffer with LWS_PRE on allocation
2. Minor memory issue fixed
3. Fixed high cpu usage which was due to timeout being ignored
4. Added some notes
=> [REVIEW] Some fixes and improvements of ws layer

arch/network_tcp.c
Hi,
I'm proposing a fix for:
https://github.com/open62541/open62541/issues/2509
I tested this fix trying to start two open62541-based OPC-UA servers on the same port and now the error:
[2020-02-24 11:01:04.254 (UTC+0100)] warn/network	Error binding a server socket: Address already in use
correctly propagates into the return code.
(Previously any error like that would be ignored by the stack).
=> Fix for #2509: Network Layer start-up result ignored (errors get unnoticed...)

arch/CMakeLists.txt
when open is added as cmake subdirectory to other project
=> fixes compile error of network_tcp.c 

plugins/ua_config_default.c
This allows a SecurityPolicy to return "BadNotSupported" and the
endpoint will not be created.
=> fix(plugin): Don't abort server/client config when a SecurityPolicy cannot init

doc/CMakeLists.txt, include/open62541/common.h, include/open62541/plugin/nodestore.h, include/open62541/types.h, include/open62541/util.h, src/server/ua_session.h, src/ua_types_lex.c, src/ua_types_lex.re, src/ua_util.c, src/ua_util_internal.h, tests/check_types_parse.c
According to the format defined in Part 4, A2.
=> Parse human-readable RelativePath

plugins/ua_pubsub_udp.c
Only create a warning.  Fixes #3530.
=> fix(pubsub): Allow publishing on a unicast address

src/server/ua_subscription.c
Free resources in relation to retransmission queue is available or not.
=> [Review] (Bug) Fix memory leak if enableRetransmissionQueue is disabled

plugins/ua_pubsub_udp.c
As mentioned in [#3530](https://github.com/open62541/open62541/issues/3530) pubsub didn't work for unicast because it tries to join a multicast group even when it is a unicast address.
=> fix for unicast

src/client/ua_client_subscriptions.c, src/server/ua_server_async.c, src/server/ua_server_binary.c, src/server/ua_server_internal.h, src/server/ua_services.h, src/ua_securechannel_crypto.c, src/ua_types.c, src/ua_types_lex.c, src/ua_types_lex.re
Generate local variables for re2c instead of global definitions.
=> refactor(core): Make ua_types_lex.re thread-safe without locks

arch/eCos/ua_architecture.h, arch/posix/ua_architecture.h, arch/vxworks/ua_architecture.h, arch/wec7/ua_architecture.h, arch/win32/ua_architecture.h, include/open62541/architecture_functions.h, src/server/ua_services_discovery_multicast.c, src/ua_types.c, src/ua_util_internal.h, tests/check_utils.c, tests/server/check_discovery.c
=> fix(discovery): Correctly filter ServerOnNetwork (ignore case, match multiple)

deps/mqtt-c/mqtt.c, deps/mqtt-c/mqtt.h, examples/pubsub/tutorial_pubsub_mqtt_publish.c
This PR updates the project contained MQTT-C library to Tag Version 1.1.0 (https://github.com/LiamBindle/MQTT-C/tree/v1.1.0). This was e.g. needed to solve problems together with the ESP32 and eCos platform (see. https://esp32.com/viewtopic.php?t=13000).
Currently there is a lot of adjustments needed on the MQTT-C files to pass our WALL cmake setup. In a long term it would be better to use the git submodule mechanism for the MQTT library. For sure, this needs adjustments on the library itself but results in an much easier update process.
=> feat(pubsub) Updated and adjusted MQTT-C dependency

examples/CMakeLists.txt, examples/server_settimestamp.c
Signed-off-by: Kjeld Flarup <kfa@deif.com>
=> Add example of how to manipulate timestamp on a write operation

src/server/ua_services_method.c
See issue #2193 for further details.
Should this part be switchable in cmake?
[Update] In release mode with gcc 4.5.2 the difference is 0,4kB.
=> [Review] Add capability to call/reference a method from a FunctionalGroup

plugins/ua_pubsub_ethernet.c
check the return value of UA_malloc in the function UA_PubSubChannelEthernet_send.
=> merge PR#3656 to 1.1

include/open62541/server.h, src/server/ua_subscription_alarms_conditions.c, tests/CMakeLists.txt, tests/server/check_server_alarmsconditions.c
This PR adds UA_Server_deleteCondition to delete a condition with it's internals from the address space.
=> Add UA_Server_deleteCondition 

src/client/ua_client_connect.c, src/client/ua_client_internal.h, src/server/ua_server_binary.c, src/server/ua_server_internal.h, src/server/ua_services_securechannel.c, src/ua_securechannel.c, src/ua_securechannel.h, src/ua_securechannel_crypto.c, tests/check_securechannel.c, tools/schema/Custom.Opc.Ua.Transport.bsd, tools/schema/datatypes_transport.txt
=> [REVIEW] Feature: decrypt in securechannel

examples/client_async.c, include/open62541/client_highlevel_async.h, src/client/ua_client_highlevel.c
The API of this function is broken and has to be redone.
=> fix(client): Deprecate UA_Cient_translateBrowsePathsToNodeIds_async

include/open62541/plugin/nodestore.h, plugins/ua_nodestore_hashmap.c, plugins/ua_nodestore_ziptree.c, src/server/ua_nodes.c, src/server/ua_server.c, src/server/ua_server_async.c, src/server/ua_server_internal.h, src/server/ua_server_utils.c, src/server/ua_services_attribute.c, src/server/ua_services_method.c, src/server/ua_services_monitoreditem.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_view.c, src/server/ua_subscription_alarms_conditions.c, src/server/ua_subscription_events.c, tests/server/check_nodestore.c, tests/server/check_services_attributes.c
=> refactor(server): Use a union to avoid casting of node classes

src/server/ua_services_monitoreditem.c
- According to 'Table 42 – EventNotifierType Definition' in
Part 3 Address Space Model specification, the
'SubscribeToEvents' bit of EventNotifier attribute should be set
to 1, to subscribe to Events within an object
- If the condition is true, monitored item can be created, else it
returns UA_STATUSCODE_BADNOTSUPPORTED status code to the client
Change-Id: Ib6acfed9c1b1c0d84e8061d8f7feb2028d77d7ba
=> fix(server): Add check for EventNotifier attribute value

arch/network_tcp.c
In a Docker container the local address is usually not the gobal
address in DNS.  So binding to the published address will fail.  As
a fallback bind to any address but with the given port.
=> feat(server): bind fallback to unspecified address

CMakeLists.txt, arch/network_ws.c
I get "error C2084: function already has a body" for this functions:
connection_getsendbuffer, connection_releasesendbuffer, connection_releaserecvbuffer.
They are defined in files:
open62541\arch\network_tcp.c
open62541\arch\network_ws.c
These functions are static, so the problem occurs only with enabled amalgamation.
I also added libwebsockets include dir in cmake.
=> Fix building websocket with amalgamation

examples/discovery/server_register.c
Fix to issue "Could not remove mDNS record #3789"
=> Fix (discovery example): server_register.c

include/open62541/server_pubsub.h
- Add comments for Subscriber in server_pubsub.h for
- DataSetReader
- ReaderGroup
- SubscribedDataSet
- TargetVariables
=> docs(pubsub): add comments for Subscriber

src/pubsub/ua_pubsub_writer.c
Accessing the stack array outside of the called function `generateNetworkMessage` caused reading from corrupt memory.
=> fix(pubsub) allocate array on the heap

src/server/ua_subscription.c
Trying to fix the compile error.
I am not sure if the log message with the notifications variable is needed.
=> Fix compiler errors in UA_Subscription_publish()

arch/network_tcp.c
=> Suppress possible memory leak in network_tcp.c

arch/network_tcp.c
- More details on UA_socket errors
=> Use UA_LOG_SOCKET_ERRNO_WRAP on UA_socket error

arch/common/ua_lwip.h, arch/freertosLWIP/ua_architecture.h, arch/network_tcp.c, src/server/ua_discovery_manager.c, src/server/ua_server.c, src/server/ua_server_binary.c, src/server/ua_server_config.c, src/server/ua_server_discovery_mdns.c, src/server/ua_server_utils.c, src/server/ua_services_nodemanagement.c
This fixes some small issues which cause compile failure on embedded devices, e.g., freeRTOS
=> Fix various smaller issues related to embedded builds, e.g. FreeRTOS

plugins/ua_config_default.c
=> [Review] fix(leak): Fix memory leaks from config_default

include/open62541/server.h, plugins/ua_config_default.c, src/server/ua_server.c
=> Fix leak in UA_Server_newWithConfig

plugins/ua_nodestore_hashmap.c, src/server/ua_services_nodemanagement.c
Fix memory leaks detected by #3841
=> fix(server, hashmap): Memory leaks fixed where needed

examples/pubsub/server_pubsub_subscriber_rt_level.c, examples/pubsub/tutorial_pubsub_subscribe.c, examples/pubsub_realtime/pubsub_TSN_loopback.c, examples/pubsub_realtime/pubsub_TSN_publisher.c, include/open62541/server_pubsub.h, src/pubsub/ua_pubsub.h, src/pubsub/ua_pubsub_reader.c, tests/pubsub/check_pubsub_multiple_subscribe_rt_levels.c, tests/pubsub/check_pubsub_subscribe.c, tests/pubsub/check_pubsub_subscribe_config_freeze.c, tests/pubsub/check_pubsub_subscribe_rt_levels.c
This PR adds feature on top of #3739 i.e., it extends the support of external data source variable (RT configuration) in subscriber.
=> [REVIEW] feat(pubsub) Extended support in subscriber on external Data Source and Information model RT variables

src/pubsub/ua_pubsub_ns0.c, src/pubsub/ua_pubsub_ns0.h, src/pubsub/ua_pubsub_reader.c, tests/pubsub/check_pubsub_informationmodel.c, tools/schema/Opc.Ua.NodeSet2.PubSubMinimal.xml
Subscriber Information model restructuring as per specification
- Restructuring done until dataSetReader
- TODO: Place susbcribedDataSet under DataSetReader
=> [Review] Subscriber information model

src/server/ua_subscription_events.c
Currently we check, if the event source is inside the objects folder using the Organizes and hasComponent references. This PR extends this check and includes subtypes of these references.
Some background information’s are figured out there: https://github.com/open62541/open62541/issues/2949#issuecomment-517150253
=> fix(server) Follow reference subtyes during the event source check 

src/pubsub/ua_pubsub_config.c, tests/CMakeLists.txt, tools/schema/datatypes_pubsub.txt
=> fix(pubsub config): updated ua_pubsub_config.c to use new subscriber api

examples/pubsub_realtime/pubsub_TSN_loopback.c, examples/pubsub_realtime/pubsub_TSN_publisher.c
Modified to stop the application when maximum logging reached
=> fix(pubsub): Segmentation fault while enabling csv logs in realtime TSN samples

include/open62541/plugin/nodestore.h, src/server/ua_nodes.c, src/server/ua_server_internal.h, src/server/ua_services_attribute.c, src/server/ua_services_nodemanagement.c, src/server/ua_session.c, src/server/ua_session.h, tests/client/check_client_subscriptions.c, tests/server/check_services_attributes.c
Some behaviour is now deemed "non-compliant" and is fixed by this PR.
Has to be "frontported" to later releases once ready.
=> Fix certification issues for 1.0

CMakeLists.txt
=> Check install directory for deps with full path (#4032)

examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_publisher.c, examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_subscriber.c, plugins/ua_pubsub_ethernet_etf.c, plugins/ua_pubsub_ethernet_xdp.c
Fix warnings/errors reported by GCC-10. Also fix the RT publisher/subscriber example
=> Bugfix for gcc-10 and ETF examples

arch/vxworks/ua_architecture.h, arch/vxworks/ua_architecture_functions.c, examples/pubsub_realtime/pubsub_interrupt_publish.c, examples/pubsub_realtime/vxworks/pubsub_interrupt_publish_tsn.c, plugins/ua_pubsub_ethernet.c
port the changes of https://github.com/open62541/open62541/pull/4098 from "master" branch to "1.2" branch.
=> [Review] fix(ex): align VxWorks TSN publisher example with v1.2

doc/CMakeLists.txt, doc/tutorials.rst, examples/pubsub/tutorial_pubsub_subscribe.c, examples/pubsub_realtime/README_pubsub_TSN.txt, examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_publisher.c, examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_subscriber.c, examples/pubsub_realtime/pubsub_TSN_loopback.c, examples/pubsub_realtime/pubsub_TSN_publisher.c, src/pubsub/ua_pubsub_reader.c
Added command-line arguments support to real-time pubsub examples.
Documentation for pubsub tutorial subscriber example, pubsub real-time examples.
=> [Review] Simplify realtime pubsub examples to support command line arguments

.github/workflows/build_linux.yml
Temporary fix for open62541/open62541#4148
=> [Review] fix(ci): set ubuntu to 18.04

.github/workflows/codeql.yml
As per discussion with @andreasebner:
Initial setup of codeScanning with CodeQL
=> [Review] Setup CodeScanning with CodeQL

src/server/ua_server_internal.h, src/server/ua_services_view.c
In preparation for a further upcoming fix.
=> Expose RefTree API internally

src/client/ua_client_connect.c
I saw some functions whose return values are not handled and added some temporary solution. I'm not sure if this the right way of doing it. 
I see the relationship between the session and connection state of the client is not always consistent.
Some of the functions involved in the code change the state of the connection inside of it and some don't.
=> [REVIEW] Handle errors on client session commands

.github/dependabot.yml
Following my and other recent updates to the OPC UA NodeSets. #4213 #4144 #3967 
I propose an semi-automatic update of the corresponding gitsubmodules.
=> [REVIEW] feat(ci): automatic gitsubmodule updates

examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_publisher.c, examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_subscriber.c, examples/pubsub_realtime/pubsub_TSN_loopback.c, examples/pubsub_realtime/pubsub_TSN_publisher.c, examples/pubsub_realtime/pubsub_interrupt_publish.c, include/open62541/server_pubsub.h, include/open62541/util.h, src/client/ua_client.c, src/pubsub/ua_pubsub_manager.c, src/pubsub/ua_pubsub_manager.h, src/pubsub/ua_pubsub_reader.c, src/pubsub/ua_pubsub_writer.c, src/server/ua_server.c, src/ua_timer.c, src/ua_timer.h, tests/check_timer.c, tests/pubsub/check_pubsub_publish_rt_levels.c
- baseTime and handleCycleMissWithBaseTime variables are added in timer process
=> [Review] feat(pubsub): Support baseTime to timer callbacks

src/server/ua_services_monitoreditem.c
Some external sources can report a StatusCode. Allow the generation of
MonitoredItems for most StatusCodes != Good.
The issue was reported by Grant Edwards in #4258.
=> fix(server): Allow MonitoredItems with an initial StatusCode != Good

src/server/ua_server.c
…oduce a false positive assert.
=> Remove Assert in serverExecuteRepeatedCallback

src/pubsub/ua_pubsub_ns0.c
- While calling the addPublishedItems method from the client the last argument (UA_PublishedVariableDataType) gets corrupted
- Fixed by changing the last argument (UA_PublishedVariableDataType) from variant type to extension object
=> [REVIEW] fix(pubsub): AddPublishedItems method call throws segmentation fault #4223

plugins/ua_pubsub_udp.c
- use the given interface from the application when subscribing to a multicast addr
=> fix(pubsub) interface selection for multicast

src/server/ua_subscription_datachange.c, tests/server/check_monitoreditem_filter.c
=> fix(server): Correct MonitoredItem filter for empty values

src/server/ua_nodes.c
Reapply the fix from @juangburgos that was lost in translation.
=> fix(server): Fix comparing reference kinds

src/pubsub/ua_pubsub_writer.c, tests/pubsub/check_pubsub_publish_rt_levels.c, tests/pubsub/check_pubsub_publish_uadp.c
- Remove WriterGroup regist function for MQTT publish fix
=> fix(pubsub): Fix MQTT publish

examples/pubsub_realtime/README_pubsub_TSN.txt
- Update hardware information in README_pubsub_TSN.txt
=> (doc) PubSub: Update README_pubsub_TSN.txt

plugins/ua_pubsub_ethernet.c, plugins/ua_pubsub_ethernet_etf.c, plugins/ua_pubsub_ethernet_xdp.c, src/pubsub/ua_pubsub_reader.c
- Changed ethertype from LLC to ETHERTYPE_UADP(0xb62c)
according to pubsub specification
- Handled the padding bytes in the src file
=> fix(pubsub): Send ethernet packets of ethertype 0xb62c

tools/nodeset_compiler/backend_open62541.py
When building open62541, set UA_NAMESPACE_ZERO to FULL.
A more than 6000 lines statement is generated in the function namespace0_generated in namespace0_generated.c, It looks the same as:
```
bool dummy = (
!(retVal = function_namespace0_generated_0_begin(server, ns))
&& !(retVal = function_namespace0_generated_0_finish(server, ns))
&& !(retVal = function_namespace0_generated_1_begin(server, ns))  
...
&& !(retVal = function_namespace0_generated_10_finish(server, ns))
&& !(retVal = function_namespace0_generated_9_finish(server, ns))
&& !(retVal = function_namespace0_generated_8_finish(server, ns))
); (void)(dummy);
return retVal;
```
This too long statement will generate a lot of temporary variables when it is running, causing the task to run it to allocate a large
stack.
This fix is to …
=> [REVIEW]fix: the generated statement is too long in namespace0_generated in namespace0_generated.c

arch/network_tcp.c
This pull request is solution for this comment: https://github.com/open62541/open62541/pull/3460#issuecomment-684856177
=> fix(server): Fix starting server on IPv4-only systems

src/pubsub/ua_pubsub_networkmessage.c, src/pubsub/ua_pubsub_networkmessage.h
Decoding and encoding is separated into different functions
concerened about header, payload, footer decoding/encoding
=> [REVIEW] refactor(pubsub): separate decoding and encoding

src/pubsub/ua_pubsub_writer.c
The position and portion to be encrypted is now handled
by the caller. Encoding methods decoupled from encryption info.
=> refactor(pubsub): encryption decoupled from encode

CMakeLists.txt, plugins/crypto/mbedtls/securitypolicy_pubsub_aes256ctr.c, tests/CMakeLists.txt, tests/pubsub/check_pubsub_encryption_aes256.c
Adds a plugin and test for aes256 pubsub encryption.
=> feature(plugin): aes256 encryption

tests/pubsub/check_pubsub_subscribe_msgrcvtimeout.c
The "Test_many_components" is failing under specific circumstances,
disable it until it is fixed (correctly set the publisher-ids,
writergroup-ids, datasetwriter-ids).
=> test(pubsub): disable false-negative test

CONTRIBUTING.md
Merge the codestyle information from the wiki into contributing.
=> [REVIEW] refactor: pull codestyle from wiki to contributing

plugins/ua_pubsub_ethernet.c
Hi,
the PubSub code with XDP enabled, does not compile. Tested with gcc 10 and libbpf-0.3. Fix it.
Thanks, Kurt
=> fix(pubsub): Fix conversion error

src/pubsub/ua_pubsub_networkmessage.c, tests/pubsub/check_pubsub_connection_xdp.c
Hi,
I've came across two more compilation issues. Fix them. 
Tested with gcc-11 and PubSub XDP enabled.
Thanks, Kurt
=> fix(pubsub): Fix compile issues

src/pubsub/ua_pubsub.h, src/pubsub/ua_pubsub_reader.c, tests/pubsub/check_pubsub_subscribe_msgrcvtimeout.c
=> Subscriber message receive timeout implementation for fast-path

CMakeLists.txt, arch/network_tcp.c, arch/posix/ua_architecture.h, deps/open62541_queue.h, examples/client.c, examples/client_historical.c, examples/discovery/client_find_servers.c, examples/server_ctt.c, include/open62541/architecture_definitions.h, plugins/crypto/mbedtls/ua_pki_mbedtls.c, plugins/ua_nodestore_ziptree.c, src/client/ua_client_connect.c, src/client/ua_client_subscriptions.c, src/pubsub/ua_pubsub_networkmessage.c, src/pubsub/ua_pubsub_networkmessage_json.c, src/pubsub/ua_pubsub_reader.c, src/pubsub/ua_pubsub_security.c, src/pubsub/ua_pubsub_writer.c, src/server/ua_server_binary.c, src/server/ua_server_discovery_mdns.c, src/server/ua_server_utils.c, src/server/ua_services_attribute.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_view.c, src/ua_types_encoding_json.c, src/ua_types_encoding_json.h, src/ua_util_internal.h, tests/server/check_server_historical_data.c
This PR fixes a memory leak and refactors the code to comply with static analysis tools.
=> Fix and refactor

include/open62541/server_pubsub.h, src/pubsub/ua_pubsub_reader.c
Signed-off-by: Keerthivasan Alagarsamy Senthilkumaran <keerthivasan.as@kalycito.com>
Change-Id: I483210216dee5623441efa0016f66834dab6cb60
Replaces #4487
=> refactor(pubsub): Add groupProperties parameter for UA_ReaderGroupConfig

src/pubsub/ua_pubsub_reader.c, tests/pubsub/check_pubsub_subscribe_msgrcvtimeout.c
Hi all!
Enable PubSub message receive timeout tests, which have been disabled by this commit.
b0fbe61
I have closed this pull request: https://github.com/open62541/open62541/pull/4449
Because I had so many merge conflicts.
And opened this one instead.
=> PubSub: tests - Enable failing msgrcvtimeout tests

CMakeLists.txt, tools/ua-tool/CMakeLists.txt, tools/ua-tool/ua.c
Only the getendpoints and read service are implemented at this time.
=> feat(tools): Add "ua" shell tool for interacting with OPC UA servers

.github/workflows/build_linux.yml, CMakeLists.txt, examples/encryption/server_encryption.c, plugins/crypto/openssl/ua_openssl_create_certificate.c, plugins/include/open62541/plugin/create_certificate.h, tests/CMakeLists.txt, tests/encryption/check_cert_generation.c, tools/ci.sh
Create a self-signed encryption certificate in C (only implemented with OpenSSL/LibreSSL).
For demonstration purpose, `UA_CreateCertificate` is implemented as a fallback in `server_encryption.c`, if no files are passed using the command line.
Resolves: #2816
=> [Review] feat(sec): Create certificate in C using OpenSSL/LibreSSL

plugins/ua_pubsub_ethernet.c
Open62541 doesn’t compile when BPF headers are available on the system.
The root cause is this “message” variable which no longer exists:
https://github.com/open62541/open62541/blob/master/plugins/ua_pubsub_ethernet.c#L1155
The commit which broke it:
https://github.com/open62541/open62541/commit/5d7b509d26939065b6e8768c647a53366904b5f9#diff-b3a77898cbe9ab570871aaa4393ddeeb80891c56035e2b8c0a45d6f5dfed136aL1115 
This fix needs to be tested and compiled against a system with BPF headers available.
=> [REVIEW] Hofix: when BPF defined error for undefined variable

examples/CMakeLists.txt, examples/events/client_eventfilter.c, examples/events/server_random_events.c, src/server/ua_services_monitoreditem.c, src/server/ua_subscription.h, src/server/ua_subscription_events.c
This PR is the first batch of the event filter server logic. 
This Batch currently contains:
- New pair of examples for the event-filter mechanism
- Static select clause  validation
The PR is based on the work in #4225.
=> feat(server) Event-Filter Batch 1 (Examples, Static-Filter-Validation)

plugins/mqtt/ua_mqtt_adapter.c
change the error messages to reflect the correct meaning.
=> refactor(pubsub): improve error messages

debian/control-template
same as #4669 but for 1.1 branch
=> fix(debian): add libmbedtls-dev dependency to open62541-dev

.github/workflows/build_linux.yml, CMakeLists.txt, doc/building.rst, examples/CMakeLists.txt, examples/encryption/README_client_server_tpm_keystore.txt, examples/encryption/client_encryption_tpm_keystore.c, examples/encryption/server_encryption_tpm_keystore.c, tools/ci.sh, tools/tpm_keystore/CMakeLists.txt, tools/tpm_keystore/cert_encrypt_tpm.c
- Encrypt the private key using the key stored in TPM and remove the unencrypted private key from the filesystem
- Used the encrypted key intermittently for software-based encryption/decryption
=> [REVIEW] Client Server Encryption using key stored in TPM

doc/building.rst
=> fix project name error

src/server/ua_services_nodemanagement.c, src/server/ua_services_view.c, src/ua_types.c
=> A NodeId with an empty string is also considered "Null"

examples/pubsub_realtime/pubsub_TSN_loopback.c, examples/pubsub_realtime/pubsub_TSN_publisher.c
Refer: https://github.com/open62541/open62541/pull/4613
=> fix(PubSub): Fix signing key length for Aes128-CTR

examples/CMakeLists.txt, examples/tutorial_server_historicaldata_circular.c, plugins/historydata/ua_history_data_backend_memory.c, plugins/historydata/ua_history_data_gathering_default.c, plugins/include/open62541/plugin/historydata/history_data_backend_memory.h, plugins/include/open62541/plugin/historydata/history_data_gathering_default.h, tests/CMakeLists.txt, tests/server/check_server_historical_data_circular.c
The idea behind the circular buffer historydata implementation is to have a fixed number of nodes to historize, that means it is mandatory to choose a maximum number of nodes (and that number will never be exceeded) and for each of that nodes a circular array of values will be saved and, each time a client performs a UA_HistoryReadRequest on a certain node, the current circular buffer (full of values) will be sent by the server.
To do so I started from the original history functions and I did some modifications to obtain the desired result. This was the faster solution for me but it means that most of the code it is very similar to the original implementation. Sorry for that but I did not find a faster way to implement the algorithms.
The following images describe the differences between …
=> [REVIEW] Circular buffer implementation for historydata plugin

src/server/ua_subscription_datachange.c, tests/server/check_local_monitored_item.c
The following test cases of Monitored Item Services fails:
* Monitor Basic - Err-014-0.js
* Monitor Basic - Err-041.js
* Monitor Value Change - 016.js
* Monitor Value Change - 031.js
* Monitor Value Change - Err-001.js
=> fix(server): Monitoring out of bounds index range fails on CTT

arch/eventloop_posix.c, tests/fuzz/CMakeLists.txt
Also reduce log spam and format code in eventloop.
=> fix: Fuzzing didn't compile because of missing sources.

examples/events/client_eventfilter.c, src/server/ua_subscription_events_filter.c
This PR contains missing init instructions within our client-event filter example.
=> fix(ex) Fix event filter client example

CMakeLists.txt, src/server/ua_services_nodemanagement.c, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/backend_open62541_typedefinitions.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodeset_compiler.py
This PR moves the latest master nodeset-compiler updates into 1.3.
=> Nodeset-Compiler updates to 1.3

tools/cmake/CMakeFindFrameworks.cmake, tools/cmake/FindPackageHandleStandardArgs.cmake, tools/cmake/FindPackageMessage.cmake, tools/cmake/FindPython/Support.cmake, tools/cmake/FindPython3.cmake
(cherry picked from commit d401f3198a2b3675d602bfc2739c170efb78bee1)
=> Backport 1.3. fix(server) add cmake find file for python3 (#4815)

deps/mqtt-c/mqtt.c
correct typo error : useTSL change to useTLS
=> (fix)PubSub: Update mqtt.c

tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_typedefinitions.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py
This pull reguest fixes the issues https://github.com/open62541/open62541/issues/3964 and https://github.com/open62541/open62541/issues/4901
=> Fix Nodeset-Compiler code generation OptionsSets, Enums and Unions

examples/nodeset/CMakeLists.txt, tests/nodeset-compiler/CMakeLists.txt
=> [Review] chore(deps): Updates ua-nodeset to `f71b3f4`

examples/events/client_eventfilter.c, src/server/ua_services_view.c, src/server/ua_subscription_events_filter.c, tests/server/check_subscription_event_filter.c
The PR introduces some additional checks for the select clause, defined in Part 4 Table 144.
=> Extended Event-Filter select clause validation

tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c, tests/nodeset-compiler/testnodeset.xml, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py
=> (nc) Fixed generation of nested strctures values. Added support for generating Guid values

src/pubsub/ua_pubsub_writergroup.c, src/ua_util_internal.h, tests/check_utils.c
Update some code in the pubsub publish callback for better comprehension.
=> [REVIEW] refactor(pubsub): clean up logic in publish-callback

.gitmodules, tests/server/check_services_nodemanagement.c
* The `latest `branch is a merge between v1.05 base spec and all CS
Base UA Spec is v1.05 now.
=> [Review] build(deps): Switches branch for `deps/ua-nodeset` -> UA v1.05

src/client/ua_client_internal.h, src/client/ua_client_subscriptions.c
=> fix(client): Big complexity in the "processDataChangeNotification" function

plugins/ua_pubsub_udp.c, tests/check_utils.c
Clean up the pubsub udp channel open logic.
=> [REVIEW] refactor(pubsub): cleanup pubsub-udp channel-open logic

deps/mqtt-c/mqtt.c
Revert the inversion of the flag values.
=> fix(deps): Revert changes from 58e8125

src/pubsub/ua_pubsub.h, src/pubsub/ua_pubsub_networkmessage.c, src/pubsub/ua_pubsub_reader.c, src/pubsub/ua_pubsub_writer.c, src/pubsub/ua_pubsub_writergroup.c
This PR is an extension and overhaul of #5056 
The added heartbeat functionality is defined OPC UA Part 14 1.05.
The base implementation was provided by @MurzynJ.
=> feat(pubsub): Implement a heartbeat message

src/server/ua_services_method.c, tests/server/check_services_call.c
Allow situation, where the objectType's method is invoked on its instance (or instance of its subtype) - the object's objectType (or it's supertype) is the source of HasComponent reference.
=> feat(server): Allow invoking ObjectType's method on its instance

src/client/ua_client_connect.c, tests/CMakeLists.txt, tests/client/check_client_encryption.c
Reported with a proposed fix by @nokem61.
=> Merge 1.2 to 1.3

include/open62541/server_pubsub.h, src/pubsub/ua_pubsub_manager.c
clean up and simplify pubsub-manager add-connection.
also add documentation for add-connection call
=> [REVIEW] refactor(pubsub): cleanup add-connection call

arch/eventloop_posix_udp.c, tests/check_eventloop_udp.c
- Improve udp eventloop testing structure
- Improve udp eventloop core code
=> [REVIEW] Feature: eventloop udp cleanup

tools/schema/Opc.Ua.Types.bsd
Update the types.bsd to the newest version ([UA-1.05.01-2022-02-24 Release](https://github.com/OPCFoundation/UA-Nodeset/commit/d69b75a4b90ed21fbf57a330181f29c75fa2b072))
=> feat: update types.bsd to v1.05

plugins/ua_config_default.c, tests/check_securechannel.c
Based on a reported DoS vulnerability reported by Team82 (Claroty
Research).
=> fix(plugin): Add default limits for chunks and message size

src/pubsub/ua_pubsub.h, src/pubsub/ua_pubsub_manager.c, src/pubsub/ua_pubsub_reader.c, src/pubsub/ua_pubsub_readergroup.c, src/pubsub/ua_pubsub_writer.c, src/pubsub/ua_pubsub_writergroup.c, tests/pubsub/check_pubsub_subscribe_msgrcvtimeout.c
Call state change callbacks whenever a state changes
Proposal: Add parameter for error cause
Functions *_setPubSubState are extended with parameter for error cause.
-> proposal accepted (see comment below by jpfr)
=> feat(pubsub): Call statechange callback

src/ua_types.c
=> fix(server): subscription of UnionDataTypes

CMakeLists.txt
fix https://github.com/open62541/open62541/issues/5191
=> fix(cmake): check if CMAKE_CXX_COMPILER_VERSION is defined

CMakeLists.txt
Added an option `UA_ENABLE_SANITIZER` that allows to disable address sanitizers if needed. By default it is still on.
=> build(pack): add option UA_ENABLE_SANITIZER

arch/eventloop_posix_udp.c, include/open62541/plugin/eventloop.h, plugins/ua_pubsub_ethernet.c, plugins/ua_pubsub_udp.c, tools/azure-devops/win/build.ps1
Integrate parameters for opening udp connections via the udp-connectionmanager.
- retrieve address information
- create socket
- setup common options from parameters
- if multicast
- setup ipv4 and ipv6 multicast options from parameters
- bind...
=> [REVIEW] feat(el): udp connection-manager parameters for openConnection

src/client/ua_client.c
Commit de9d691906547c9fc99e0a77198a80fe5bba54b1 fixed a use after
free in UA_Client_AsyncService_cancel().  The same bug is present
in asyncServiceTimeoutCheck(), so use the same fix.  After timeout,
remove the async service calls from the global list and store them
in a local one.  Call UA_Client_AsyncService_cancel() and with it
the UA_free() while traversing this local list.  Otherwise the
callback could free a global list element that asyncServiceTimeoutCheck()
is referencing.
=> fix(client): use after free in asyncServiceTimeoutCheck

src/pubsub/ua_pubsub_ns0.c, tests/pubsub/check_pubsub_informationmodel.c
There is a memleak when reading the value of PDS->PublishedData/DataSetMetaData/ConfigurationVersion.
Adjusted the unit test for the PDS to also read the value of the children to verify the memleak is fixed.
=> Fix(pubsub/infomodel) memleak when reading PDS/SDS children

arch/network_tcp.c
There seem to be an error with the connection timeout counter.
Should be increased incase of timeout.
=> updates connection timeout counter

src/server/ua_services_attribute.c
Checking method input arguments was failing with BadInvalidArgument in valid use cases:
1) Input argument is an empty array of structures (ExtensionObjects).
2) Input argument is a structure of a non-NS0 datatype, or an abstract data type.
=> fix(core): fix issues with checking method input arguments.

.idea/vcs.xml, arch/eventloop_posix_tcp.c, arch/eventloop_posix_udp.c, include/open62541/plugin/eventloop.h
Cache address of UDP connection for using sendto instead of connect + send
=> [REVIEW] Feature/eventloop cached address udp

include/open62541/client.h
Signed-off-by: Joakim Roubert <joakimr@axis.com>
=> client.h: Documentation updates

include/open62541/types.h, plugins/ua_config_default.c, plugins/ua_pubsub_udp.c, src/client/ua_client_highlevel.c, src/pubsub/ua_pubsub_manager.c, src/server/ua_subscription.c, tests/check_utils.c, tools/generate_statuscode_descriptions.py
Fixes https://github.com/open62541/open62541/issues/5376
=> fix(core): DataValue statuscodes checks ignore additional information bits

src/pubsub/ua_pubsub_manager.c
=> Overhaul of the reserveId function.

examples/pubsub/tutorial_pubsub_publish_raw.c, include/open62541/server_pubsub.h, src/pubsub/ua_pubsub_networkmessage.c, src/pubsub/ua_pubsub_networkmessage.h, src/pubsub/ua_pubsub_reader.c, src/pubsub/ua_pubsub_writer.c, src/pubsub/ua_pubsub_writergroup.c
This PR targets the support of maxStringLength in the PubSub path. This es e.g. needed for the fixedLengthFrames.
=> feat(pubsub) check the maxStringLength in the pubsub path

src/pubsub/ua_pubsub_reader.c
Fix for a reader not receiving messages without a writer group header.
=> [REVIEW] fix(pubsub): receive messages without groupheader

plugins/ua_config_default.c, src/server/ua_server.c
- only start if its not started yet (external el)
- start in the configuration state (ready to be used)
=> [REVIEW] refactor(el): make sure eventloop starts correctly

src/pubsub/ua_pubsub_manager.c, src/pubsub/ua_pubsub_ns0.c
mutexLock is already taken in this code path --> change methodcall to deleteNode
=> fix deadlock on removeSDS

plugins/ua_config_default.c, src/client/ua_client.c, src/client/ua_client_connect.c, src/client/ua_client_internal.h
Make a number of related changes intended to improve the handling of UA_ClientConfig and its use with setting up a UA_Client.  Related to #5435.
=> [Review] Update handling of ClientConfig

src/client/ua_client_subscriptions.c
Changes for https://github.com/open62541/open62541/issues/5447
=> Fix response on Publish status: BAD_NOSUBSCRIPTION

src/server/ua_server.c, tests/server/check_server.c
=> fix(server): Range check in getNamespaceByIndex (#5527)

plugins/crypto/openssl/ua_openssl_create_certificate.c
In the function UA_CreateCertificate the buffers were allocated by OpenSSL, but cleared with UA_ByteString_clear. Allocate buffer with UA_ByteString_alloc to get correct UA_ByteString.
Fixes issue #5510
=> fix(plugin): Memory exception clearing OpenSSL buffer with UA_ByteString

src/pubsub/ua_pubsub_dataset.c
Before this change, removeDataSetField was called in a loop for all DataSet fields. Inside removeDataSetField the DataSetMetadata is regenerated again and again and that's not necessary when you want to remove the whole DataSet anyway.
=> refactor(pubsub): optimize removal of a PublishedDataSet

include/open62541/server.h
=> feat(server): Add a void-ptr-context to the server config

src/server/ua_services_view.c
fix for https://github.com/open62541/open62541/issues/5655
=> [server] fix #5655

tests/nodeset-loader/add_node_integration_test/run_test.sh
Fix for integration issues in #5658.
=> fix(test): remove CNC companion specification

tests/pubsub/check_pubsub_publish.c
This test should cover [ua_pubsub_writer.c](https://app.codecov.io/gh/open62541/open62541/blob/master/src/pubsub/ua_pubsub_writer.c) but the coverage is just about 50%. 
After investigating, I found that the test used the optional `UA_NS0ID_SERVER_LOCALTIME` which resulted in a fieldSize of 0 in the dataSet. I changed this to the mandatory `UA_NS0ID_SERVER_SERVERSTATUS_CURRENTTIME`. 
Furthermore, I rearranged the order of the setup functions and added another field in the `PublishDataSetFieldAsDeltaFrame` Test because you need at least 2 fields in order to publish as DeltaFrame. ("if a PDS contains only one fields no delta messages
should be generated because they need more memory than a keyframe with 1 field")
The codecoverage should now cover at least every function in …
=> fix(pubsub) Fixed PubSub Pubslish test

plugins/crypto/mbedtls/ua_securitypolicy_basic128rsa15.c
The issue was reported in #5631.
=> fix(plugin): Forward rng when calling mbedtls_pk_decrypt

arch/eventloop_posix_tcp.c, arch/eventloop_posix_udp.c
Fixes https://github.com/open62541/open62541/issues/5709, please see the issue for a detailed description of the problem and proposed change
=> [Review] Allow binding a listening socket before the network interface is configured

.github/workflows/build_linux.yml, tools/ci.sh
Enable mqtt examples for valgrind
=> fix(CI): Enable mqtt examples

src/client/ua_client_highlevel.c, src/client/ua_client_subscriptions.c
Initializing variables with NULL if the initialization gets omitted by a GOTO label
see: https://bugreports.qt.io/browse/QTBUG-113504
=> Fix(client): Error C2362 on Windows

arch/eventloop_posix_udp.c, plugins/mqtt/ua_mqtt-c_adapter.c, src/ua_util.c
fix(core): fix string length error with mqtt in UA_parseEndpointUrl
refactor(arch): Don't listen for events on UDP send-connections
=> feat(core): Allow parsing of opc.eth:// in UA_parseEndpointUrl

include/open62541/client.h, plugins/include/open62541/client_config_default.h, plugins/include/open62541/plugin/accesscontrol_default.h, plugins/ua_accesscontrol_default.c, plugins/ua_config_default.c, src/client/ua_client.c, src/client/ua_client_connect.c, src/client/ua_client_internal.h, src/pubsub/ua_pubsub_keystorage.c, src/pubsub/ua_pubsub_ns0.c, src/pubsub/ua_pubsub_securitygroup.c, tests/CMakeLists.txt, tests/client/check_activateSession.c, tests/client/check_activateSessionAsync.c, tests/client/check_client_async_connect.c, tests/client/check_subscriptionWithactivateSession.c, tests/pubsub/check_pubsub_sks_client.c, tests/pubsub/check_pubsub_sks_pull.c, tools/schema/datatypes_pubsub.txt
=> Add activate session API for client

tests/nodeset-loader/add_node_integration_test/run_test.sh, tools/nodeset_injector/CMakeLists.txt
* Updates ua-nodeset
* Fixes Scales test, as new CS requirements where added with v1.01
Replace #5826
=> [Review] fix(nodesetinjector): Extend test for Scales v1.01 specification

include/open62541/architecture_definitions.h
This is a draft pull request since I would first like to get some guidance from you and I'm not sure if these are the absolutely correct fixes.
For some reason that I cannot fully explain I don't seem to be able to compile the code without these changes. With these changes the code compiles fine.
We were initially not sure how to upstream the changes, but I noticed now that this has already been addressed in the `master` branch. The only issue is that we would like to use a stable branch, and would thus ideally like to see a fix in `1.3`. I'm not sure if the changes from `master` could easily be cherry-picked since there were multiple non-trivial commits involved, the last one being 76bb7dc11f0302c1dddc52ddf72d20d5a5bf52bb by @jpfr.
These functions were mostly removed by …
=> Replace intrinsics to fix the build with multithreading support for MSVC

src/pubsub/ua_pubsub_eventloop.c, src/server/ua_server_binary.c, src/server/ua_server_ns0_diagnostics.c, src/server/ua_session.c, src/server/ua_subscription_alarms_conditions.c
Call unlock at all return cases after lock.
=> fix(server): Fix symmetry of serviceMutex 

arch/eventloop_posix.c, arch/eventloop_posix_select.c
Call unlock at all return cases after lock.
=> fix (arch): Fix issues with eventloop mutex

src/pubsub/ua_pubsub_eventloop.c, src/server/ua_server.c, src/server/ua_server_ns0.c, src/server/ua_services_attribute.c, src/server/ua_services_method.c, src/server/ua_services_nodemanagement.c, src/server/ua_subscription_datachange.c, src/server/ua_subscription_monitoreditem.c
Call UA_LOCK_ASSERT in all functions where unlock is done.
=> feat (server): add asserts for serviceMutex

src/server/ua_services_subscription.c, src/server/ua_services_view.c
=> fix(server): unlock serviceMutex before calling accessControl callbacks

arch/eventloop_posix_eth.c
Amalagamated source incompatible with UA_ARCHITECTURE_WIN32 https://github.com/open62541/open62541/pull/5886
=> Update eventloop_posix_eth.c for UA_ARCHITECTURE_WIN32

arch/eventloop_posix_interrupt.c, arch/eventloop_posix_tcp.c, arch/eventloop_posix_udp.c, src/ua_types_encoding_json.c
=> Cosmetic fixes in arch and core

src/pubsub/ua_pubsub_connection.c, src/pubsub/ua_pubsub_networkmessage.c, src/pubsub/ua_pubsub_networkmessage.h, src/pubsub/ua_pubsub_reader.c, tests/pubsub/check_pubsub_subscribe_rt_levels.c
Fix decoding of rawdata message with rtLevel UA_PUBSUB_RT_FIXED_SIZE.
Resolves issue #5975
=> fix(PubSub): Fix decoding of rawdata message

plugins/crypto/openssl/ua_openssl_basic256sha256.c, plugins/crypto/openssl/ua_pki_openssl.c
Two small secutity fixes. I found one with Visual Studio "Code analysis" and a small projekt with single file distro open62541.c/h
=> 1.2 security fixes

src/pubsub/ua_pubsub_bufmalloc.c
Fixes commit 928931ec36d4441fc12d27b11470ea96f7dc9b9b
=> fix(core): Include stdlib.h for usage of malloc, free etc.

include/open62541/client_highlevel.h, include/open62541/client_highlevel_async.h, src/client/ua_client_highlevel.c
Implemented client functionality to read and write the AccessLevelEx attribute of a variable.
=> [REVIEW]feat(client): Added support for reading the AccessLevelEx attribute.

tools/nodeset_compiler/backend_open62541_nodes.py
The generated code for the "node.eventNotifier" attribute is not correct. Changed the code part from logical OR to bitwise OR.
=> fix(nc): Resolving of the event notifier attributes not correct

examples/server_ctt.c, plugins/ua_accesscontrol_default.c, plugins/ua_config_default.c, src/server/ua_services_discovery.c, src/server/ua_services_session.c
AccessControl extended with the ability to add multiple userTokenPolicies.
=> [REVIEW]: feat(server): AccessControl extended with the ability to add multiple userTokenPolicies.

doc/nodeset_compiler.rst, tools/nodeset_injector/CMakeLists.txt
* The Nodeset Compiler documentation has been updated with information on which companion specifications are currently not buildable and why.
* Added more Companion Specifications to the Nodesetinjector.
=> [REVIEW] Added more Companion Specifications supported by the nodesetinjector autoload feature.

src/server/ua_discovery.c, src/server/ua_discovery.h
In compliance to the standard we need to call the Register2 and afterwards (if not successful) the Register service
=> WIP fix(server) adjust discovery register service order

src/server/ua_services_securechannel.c
The fix was provided by Phuong Nguyen of Hilscher in #6083.
=> fix(server): Use only the leaf certificate from the asymmetric security header

src/client/ua_client_connect.c
Pick endpoint based on highest security level rather than using first
Closes #6167
=> fix(client): honor endpoint security policies

src/client/ua_client_connect.c, src/server/ua_server_binary.c, src/ua_util.c, src/ua_util_internal.h, tests/check_utils.c
Client does not switch from discovery to full-feature endpoint if security policy does not change
Closes #6165
=> fix(client): failure to switch from discovery url

src/ua_securechannel.c
This was missed when the client reuses its SecureChannel structure. Some servers want the client to start the sequence number close to zero.
Reported by Mike Granby in #6177.
=> fix(core): Reset sequence numbers in UA_SecureChannel_close

plugins/crypto/openssl/ua_pki_openssl.c
If the data buffer created by i2d_PrivateKey() is returned directly, freeing the ByteString causes a heap corruption on Windows.
=> Fix heap corruption on Windows when loading a PEM encoded private key

.gitignore
We need the debian folder in the pack branch.
=> fix(ci) Update .gitignore

.gitignore, src/pubsub/ua_pubsub_ns0.c
* adapt pubsub to UA 1.05.3
Co-authored-by: dependabot[bot] <support@github.com>
=> [REVIEW] build(deps): bump deps/ua-nodeset from `d1bb6a2` to `9cd8699`

.github/dependabot.yml, .github/workflows/build_linux.yml, .github/workflows/cifuzz.yml, .github/workflows/codeql.yml, .github/workflows/coverage.yml, .github/workflows/debian_packing.yml, .github/workflows/doc_upload.yml, .github/workflows/rebase.yml
* automate the update of GitHub actions with dependabot.
=> [Review] fix(ci): update all GitHub actions to the latest version

include/open62541/client_subscriptions.h, src/client/ua_client_subscriptions.c
=> fix: `UA_Client_MonitoredItems_modify_async` implementation

tools/cmake/macros_public.cmake, tools/generate_bsd.py, tools/nodeset_compiler/nodeset.py, tools/nodeset_compiler/type_parser.py
Follow-up to #6214
ping @NoelGraf
=> [Review] fix(tools): remove deprecated NAMESPACE_MAP from cmake macros

include/open62541/architecture_definitions.h
=> adding floating point number representation for ESP platform (v1.3)

src/pubsub/ua_pubsub_reader.c
Set the state of a readergroup with UA_PUBSUB_RT_FIXED_SIZE to UA_PUBSUBSTATE_OPERATIONAL also after several disable and endable calls. The buffered network message is not reset when disabling a readergroup.
=> fix(pubsub): Set readergroup state to operational after restart

tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/datatypes.py
Refers open62541/open62541-nodeset-loader#253
This adds support for GUID Node IDs in nodeset compiler.
=> Nodeset compiler with guid nodeids

src/pubsub/ua_pubsub_networkmessage_json.c
(cherry picked from commit 0a2b8fbfbb65c0a0821d271ecf9661514ad54efe)
=> Backport fix for a potential memleak on very large PubSub JSON messages.

CMakeLists.txt, tools/cmake/open62541Config.cmake.in, tools/packaging/debian/control-template, tools/packaging/debian/libopen62541-tools.install-template, tools/prepare_packaging.py
Nodeset compiler has been removed with commit 9e0b766fbba73be8d703b6ccbfdeec5bfd200b48
=> fix(build): Provide libopen62541-tools package again

CMakeLists.txt, include/open62541/plugin/certificategroup.h, include/open62541/util.h, plugins/crypto/mbedtls/ua_certificategroup_memorystore_mbedtls.c, plugins/crypto/openssl/ua_certificategroup_memorystore_openssl.c, plugins/crypto/ua_certificategroup_none.c, plugins/include/open62541/plugin/certificategroup_default.h, plugins/ua_config_default.c, src/util/ua_util.c, tools/schema/Opc.Ua.NodeSet2.Reduced.xml, tools/schema/datatypes_minimal.txt
This PR adds the memorystore backend for the certificate groups.
=> [WIP] Implement memorystore backend for certificate groups

plugins/crypto/mbedtls/ua_securitypolicy_aes128sha256rsaoaep.c, plugins/crypto/mbedtls/ua_securitypolicy_aes256sha256rsapss.c, plugins/crypto/mbedtls/ua_securitypolicy_basic256sha256.c, plugins/crypto/openssl/ua_openssl_aes128sha256rsaoaep.c, plugins/crypto/openssl/ua_openssl_aes256sha256rsapss.c, plugins/crypto/openssl/ua_openssl_basic256sha256.c
This refines the changes done in PR #6170.
=> fix(server): Fix security level values for the security policies

src/client/ua_client_connect.c
=> fix(client): added missing channel state "UA_SECURECHANNELSTATE_OPN_SENT"

.gitignore
If anyone want to update tools/cmake files , we can allow to update and push it.
=> delete .cmake flag from .gitignore.

tools/schema/Opc.Ua.NodeSet2.EventsMinimal.xml
Add ModelChangeEventType and ConditionType to support subscriptions with reduced namespace
=> [REVIEW] Add ModelChangeEventType and ConditionType to reduced namespace

arch/eventloop_posix_udp.c
=> fix(arch): Fix build error with undefined UA_IPV6

src/client/ua_client_connect.c
The correct user identity token is required to execute GetEndpoints().
=> [REVIEW] Return all endpoints without requiring user identity token configuration

deps/base64.c
The code from stackoverflow was (by default) under CC-BY-SA license. This has raised some unclear points concerning copyleft.
=> refactor(deps): Use only base64 routines under the BSD license

src/server/ua_services_session.c
If there is a userTokenPolicy use that one to verify the userTokenSignature
=> fix(server): Select the right sp to check userTokenSignature

.github/workflows/build_linux.yml, .github/workflows/cifuzz.yml, .github/workflows/codeql.yml, .github/workflows/coverage.yml, .github/workflows/debian_packing.yml, .github/workflows/doc_upload.yml, .github/workflows/rebase.yml, CMakeLists.txt
fix(ci): update all GH actions
(cherry picked from 1581b063137cc23e256eed4634831a8169b28132)
fix(ci): Add bcrypt library for windows
=> Fix CI build on 1.4

plugins/crypto/mbedtls/certificategroup.c
This PR removes two allocations while creating the certificate thumbprint and instead does the binary to hexstring conversion in place.
=> fix(plugin): remove overhead for thumbprint creation (MbedTLS)

src/pubsub/ua_pubsub_reader.c
Has already been resolved on the master branch with commit c4686f6351ec192f75dadb5ac570b07b3fbda5d3.
=> fix(pubsub): Only check message timeout if message is valid

examples/pubsub/tutorial_pubsub_mqtt_publish.c, src/pubsub/ua_pubsub_config.c, src/pubsub/ua_pubsub_ns0.c, tests/pubsub/check_pubsub_publisherid.c
Fixes #6814
This is the 1.4 version of the PR #6815 which can probably be deleted if this one is accepted.
At the moment Test_multiple_connections from check_pubsub_publisherid falls into endless loop on some targets. So, work in progress.
=> [Review] fix(pubsub): fix WriterGroup message & transport settings

.gitignore
add visual studio temp folder to .gitignore
=> refactor: add visual studio temp folder to .gitignore

examples/pubsub/tutorial_pubsub_mqtt_publish.c, examples/pubsub/tutorial_pubsub_mqtt_subscribe.c, src/pubsub/ua_pubsub_readergroup.c, tests/pubsub/check_pubsub_mqtt.c
Fixes #6808
This is the 1.4 version of the #6821 PR which can probably be deleted if this one is accepted.
- fix` UA_ReaderGroupConfig` copy & clear functions
- extend unit test
- use correct data type in example
=> [Review] fix(pubsub): fix MQTT subscribe (#6808)

.gitignore
add .vs folder and CMakeSettings.json (Visual Studio temp settings for cmake)
=> refactor: add visual studio temp files to .gitignore

tools/nodeset_injector/CMakeLists.txt
To be able to include the nodeset of LADS, I added it.
=> LADS were missing

CMakeLists.txt, examples/encryption/server_encryption.c, plugins/crypto/mbedtls/ua_mbedtls_create_certificate.c, tests/CMakeLists.txt
(cherry picked from commit 1f19a8e484f5e6ff3ec77793c67f433b6318810c)
Back porting #6145 from main.
=> [Review] feat(plugins): Support certificate generation with mbedTLS [backporting]

include/open62541/plugin/eventloop.h, plugins/ua_config_default.c, src/pubsub/ua_pubsub_keystorage.c, tools/ua2json/ua2json.c
Microsoft C does not have a unistd.h header for the ssize_t data type
=> fix(tools): fix compilation for Microsoft C

src/ua_securechannel.c
=> Prevent duplicate clear in sendSymmetricChunk

tools/generate_bsd.py, tools/nodeset_compiler/nodeset.py
Missed these instances of the same escapement errors in the patch from yesterday.
=> fix(tools): Fix regular expression replacement parameter escapement

deps/cj5.c
=> fix(deps): Add missing switch-case for \n in cj5.c

src/ua_types_encoding_binary.c
Requested by the contributor himself :grinning:
=> [Review] Fix typo in contributor name of Grigory Fridman

arch/README.md, arch/posix/eventloop_posix.c, arch/posix/eventloop_posix.h, include/open62541/config.h.in
Added support for building for qnx
=> Qnx support

.github/workflows/build_macos.yml, CMakeLists.txt, arch/posix/eventloop_posix.h, examples/CMakeLists.txt, plugins/crypto/ua_certificategroup_filestore.c, plugins/crypto/ua_filestore_common.c, plugins/crypto/ua_filestore_common.h, plugins/include/open62541/plugin/certificategroup_default.h, src/util/ua_util.c
After some commits on the master branch compilation for macos was not working. This PR restores macos
to a building state and adds workflows to assist
in maintaining that compatibility.
=> Fix compilation on macos, workflow added

arch/Readme.md, arch/eventloop_posix.h, arch/eventloop_posix_udp.c, include/open62541/config.h.in
Added qnx build support
- Added _QNX_SOURCE define
- Checking for existence of ip_mreqn (inspired by commit 39ef16f)
- Not including deps/open62541_queue.h for qnx
=> Added qnx build support

doc/building.rst, include/open62541/plugin/eventloop.h
This should fix the warnings from #7156
=> fix(docs): fix warnings

.github/workflows/build_linux.yml, .github/workflows/build_ubuntu2204.yml, CMakeLists.txt, tests/check_eventloop_mqtt.c, tests/pubsub/check_pubsub_connection_mqtt.c, tests/pubsub/check_pubsub_mqtt.c, tools/nodeset_injector/CMakeLists.txt
=> Merge 1.3 to 1.4

.github/workflows/build_linux.yml
Some small cleanup I had lying around that should have been part of https://github.com/open62541/open62541/pull/7033
=> refactor(ci): remove unnecessary syntax in conditionals in build_linux

src/server/ua_discovery_mdns.c
Adjust mDNS comments to actual usage in the source code.
=> refactor(server): adjust mDNS comments to actual usage in the source

tools/nodeset_compiler/datatypes.py
Changed parsing opaque NodeIds from "o=" to "b="
=> Fix:Corrected issue with opaque NodeIds (fixes #7269)

src/server/ua_services_monitoreditem.c, tests/server/check_subscription_event_filter.c
Currently, the event filter is not validated again for ModifyMonitoredItem requests.
This PR introduces the following changes:
- Also check the event filter for ModifyMonitoredItem
- Always return BadEventFilterInvalid for create/modify if the check fails
=> Improve event filter validation

src/server/ua_server_ns0_gds.c
Replace malloc with UA_malloc in ua_server_ns0_gds.c
=> fix(server): use UA_malloc instead of malloc
