include/ua_server.h, src/server/ua_services_view.c
Up to now the service translateBrowsePathToNodeId was always called on the internal nodeStore. When only external nodeStores were present this resulted in a NULL-Pointer deref (the ns-Pointer in the server-strucutre is not set as there is no internal nodeStore).
If the starting point for a path translation lies within an external namespace, it makes sense to call this namespace's translate function. Therefore, I added the translateBrowsePathToNodeId function to the external nodeStore function pointer table and implemented the check for external namespaces for the path starting points, calling the external function when necessarry. The looping and checks are analog to the other services.
=> Enabling External NodeStores for path translation

CMakeLists.txt
Python-lxml can be detected by Cmake now.
=> Fix for issue #263

include/ua_types.h, src/ua_types.c, src/ua_types_encoding_binary.c
the cleanup needs to trace the position of the last allocation + calloc in array decoding
no valgrind varnings or memleaks, tests do pass
however, I am still not sure... @jpfr review needed
=> removing init from the decodeBinary -> brings up to 10% of performance

examples/networklayer_tcp.c, include/ua_server.h, src/server/ua_server_worker.c
sockets are only closed in the main loop. if a worker wants to close a connection, the socket is only shutdown, not closed.
this is then picked up by the select-call in the next main loop iteration.
when a connection is closed, two jobs are returned. one to immediately detach the securechannel and a delayed job that eventually frees the connection memory.
=> simplfy closing connections in the network layer

examples/networklayer_tcp.c, src/server/ua_server_addressspace.c, src/server/ua_subscription.c
ServerNetworkLayerTCP_getJobs function allocate js variable (UA_Job type) but sometime, for some reasons return 0.
In this case UA_Server_run_mainloop function don't free js variable allocated by ServerNetworkLayerTCP_getJobs.
Best regards,
Thomas
fixes #326
=> Memory leak in ServerNetworkLayerTCP_getJobs function

src/client/ua_client.c
Remove 
==32297== Invalid read of size 4
==32297==    at 0x40579B1: UA_Client_removeSubscription (open62541.c:11824)
==32297==    by 0x8049515: main (client.c:131)
==32297==  Address 0x42fa1c8 is 56 bytes inside a block of size 64 free'd
==32297==    at 0x402C3D8: free (in /usr/lib/valgrind/vgpreload_memcheck-x86-linux.so)
==32297==    by 0x4057F04: UA_Client_unMonitorItemChanges (open62541.c:11951)
==32297==    by 0x40579AA: UA_Client_removeSubscription (open62541.c:11825)
==32297==    by 0x8049515: main (client.c:131)
==32297== 
see : https://github.com/acplt/open62541/issues/323
=> Update ua_client.c, fixes #323

src/server/ua_server_addressspace.c
Fix for AppleClang error: comparison of constant 'UA_NODECLASS_OBJECTTYPE' (8) with boolean expression is always false (`if (!typeDefNode->nodeClass == UA_NODECLASS_OBJECTTYPE) {`).
=> Fix for AppleClang error

src/server/ua_server.c, tests/check_services_attributes.c, tests/check_session.c
Updated unit tests to use `ck_assert_ptr_eq` rather than `ck_assert_int_eq` where appropriate to avoid "incompatible pointer to integer conversion" compiler errors.
=> Unit test updates

CMakeLists.txt
With this change the files are executable without installing the c runtime enviroment
=> include C runtime into the exe for MSVC

bindings/CMakeLists.txt, bindings/open62541.i, include/ua_server.h, include/ua_types.h
Please review as I am a little uncertain about the changes to UA_StatusCode_new and UA_StatusCode_copy.
The following changes were made:
* Updated CMakeList.txt to reference updated output name
* Updated CMakeList.txt for Python and Lua library dependency
* Updated `bindings/open62541.i` to fix init warnings
* Cast `UA_INT64_(MAX/MIN)` and `UA_UINT64_(MAX/MIN)` to export with correct precision
* Changed `UA_NodeIdType` to be external enum for exporting
* Updated UA_StatusCode type handling functions
=> Updates to compile Python and Lua bindings

include/ua_statuscodes.h, include/ua_types.h, src/server/ua_nodes.h, src/ua_types.c, src/ua_types_encoding_binary.c
- don't macro-generate function definition in ua_type.h
- use static inline functions on integer types (saves 4kb)
- use only (unsigned) int and boolean bitfields (costs 4kb). nonstandard extensions bork various ffi interfaces
=> Static inline type handling functions and standard bitfields

examples/server.c, examples/server_datasource.c, include/ua_server.h, src/server/ua_server.c, src/server/ua_server_addressspace.c, src/server/ua_services_attribute.c, src/server/ua_subscription.c
This will allow to handle multiple nodes with one callback
AFAIK, the nodeid is thread-safe, since the node is not released during execution of the callback
we will also need another set of callback functions, but I will open an issue for it
=> Pass nodeids to datasource callbacks

examples/networklayer_tcp.c
every call to this function tests the return value, so this is probably a good place for the check.
=> prevent a segfault in ClientNetworkLayerGetBuffer

CMakeLists.txt, examples/networklayer_tcp.c, examples/networklayer_tcp.h, examples/networklayer_udp.c, examples/networklayer_udp.h, examples/server_udp.c, include/ua_client.h, include/ua_connection.h, include/ua_job.h, include/ua_server.h, src/client/ua_client.c, src/server/ua_server.c, src/server/ua_server_binary.c, src/server/ua_server_internal.h, src/server/ua_server_worker.c, src/ua_connection.c, src/ua_securechannel.c, src/ua_types.c
Up for discussion, not immediate merging...
This basically enhances the connection struct to enable future implementations of ringbuffers for receiving and sending. Note the different `releaseSendBuffer` and `releaseRecvBuffer`.
```c
struct UA_Connection {
UA_ConnectionState state;
UA_ConnectionConfig localConf;
UA_ConnectionConfig remoteConf;
UA_SecureChannel *channel;
UA_Int32 sockfd;
void *handle;
UA_ByteString incompleteMessage;
UA_StatusCode (*getSendBuffer)(UA_Connection *connection, UA_ByteString *buf);
void (*releaseSendBuffer)(UA_Connection *connection, UA_ByteString *buf);
UA_StatusCode (*send)(UA_Connection *connection, UA_ByteString *buf, size_t buflen);
UA_StatusCode (*recv)(UA_Connection *connection, UA_ByteString *response, UA_UInt32 timeout);
void …
```
=> Network ringbuffer

include/ua_types.h
To use the UA_EXPANDEDNODEID_NUMERIC macro with g++ 4.9, I had to match the order the members were defined in the UA_ExpandedNodeId struct.
I've tested the server-example after changing the macro, it compiles and works fine after the change.
=> match member order definition in UA_ExpandedNodeId struct

src/server/ua_subscription.c, src/server/ua_subscription.h
Commits from pull request #436 squashed. Comment from previous pull request: Using UA Expert, I noticed the source timestamp gets the server timestamp for monitored items. This patch fix this by changing the value field of MonitoredItem_queuedValue to UA_DataValue.
=> use UA_DataValue instead of UA_Variant for MonitoredItem_queuedValue (commits squashed)

include/ua_types.h
reference: https://www.securecoding.cert.org/confluence/x/HAs
=> negative defines should be in parentheses

examples/networklayer_tcp.c
refer to https://www.securecoding.cert.org/confluence/x/qoAyAQ
=> using strtoul instead of atoi in networklayer_tcp

doc/tutorial_server_firstSteps.rst
There is a typo error in the documentation.
=> fix typos in documentation

src/server/ua_subscription.c
I'm using open62541 built with address sanitizer, which reports a memory leak in `MonitoredItem_CopyMonitoredValueToVariant`.
The solution is to not touch the returned data, and let `UA_DataValue_deleteMembers` do all the cleanup (equivalent to how this is done in `getVariableNodeDataType` and `getVariableNodeArrayDimensions` in ua_services_attribute.c).
=> Memory leak in MonitoredItem_CopyMonitoredValueToVariant

src/ua_types_encoding_binary.c
* calcSizeBinaryJumpTable was missing an entry for boolean types
* type was not updated before calling into calcSizeBinaryJumpTable, which meant that the calculated value was wrong (I have several types for my monitored items when this was discovered)
=> calcSizeBinary fixes

src/ua_types.c
When compiling under cygwin we have this error :
```
Scanning dependencies of target open62541-object
[ 10%] Building C object CMakeFiles/open62541-object.dir/src/ua_types.c.o
/home/btc/open62541-master/src/ua_types.c: In function ‘UA_DateTime_nowMonotonic’:
/home/btc/open62541-master/src/ua_types.c:91:19: erreur: ‘CLOCK_MONOTONIC_RAW’ undeclared (first use in this function)
clock_gettime(CLOCK_MONOTONIC_RAW, &ts);
^
/home/btc/open62541-master/src/ua_types.c:91:19: note: each undeclared identifier is reported only once for each function it appears in
CMakeFiles/open62541-object.dir/build.make:90 : la recette pour la cible « CMakeFiles/open62541-object.dir/src/ua_types.c.o » a échouée
make[2]: *** [CMakeFiles/open62541-object.dir/src/ua_types.c.o] Erreur 1
CMakeFiles/Makefile2:104 : la …
```
=> CYGWIN compilation error

src/server/ua_subscription.c
Hello,
I don't have test case and I don't know if it is needed but MonitoredItem_QueuePushDataValue always call UA_DataValue_deleteMembers(&newvalue->value) before UA_free(newvalue). "We cannot remove the oldest value and theres no queue space left. We're done here." is peraps for that?
It is just a question/suggestion. If no simply close the PR.
=> fix possible memory leak

src/server/ua_services_nodemanagement.c
The nodeClass "UA_NODECLASS_VARIABLETYPE" shall have the type "UA_TYPES_VARIABLETYPEATTRIBUTES", not "UA_TYPES_OBJECTTYPEATTRIBUTES". So we can't add them yet.
=> Fixed c&p bug (?) while adding a VariableTypeNode

src/server/ua_subscription.h, src/ua_session.h
In the type defintion of UA_Subscription the "typedef" was missing
=> Compile fix for gcc 4.8.3

src/ua_types_encoding_binary.c
cppcheck revealed the following errors/warnings:
src/ua_types_encoding_binary.c(49): error (arrayIndexOutOfBounds): Array 'buf[4]' index 4 out of bounds
src/ua_types_encoding_binary.c(49): error (arrayIndexOutOfBounds): Array 'buf[4]' index 5 out of bounds
src/ua_types_encoding_binary.c(50): error (arrayIndexOutOfBounds): Array 'buf[4]' index 6 out of bounds
src/ua_types_encoding_binary.c(50): error (arrayIndexOutOfBounds): Array 'buf[4]' index 7 out of bounds
=> Fix: Array index out of bounds warning

Dockerfile, TinyDockerfile
This uses alpine linux and attempts to create a minimal install with tools to develop using open62541
Copies the amalgamated header file into /usr/include and the dynamic and static libraries into /usr/lib
This should allow default gcc to pick them up easy enough
EDIT: also my C/CMake is a little rusty. I wanted to add the files in standard OS locations so people didn't need to mess with installs. If a cmake install target is added it would probably be better to run that instead of the manual CP steps I've done for the docker image.
=> Adds dockerfile

CMakeLists.txt, examples/client.c, examples/server.c, include/ua_server.h, plugins/ua_config_standard.c, src/client/ua_client_highlevel_subscriptions.c, src/server/ua_server_binary.c, src/server/ua_server_worker.c, src/server/ua_services.h, src/server/ua_services_attribute.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_subscription.c, src/server/ua_subscription.c, src/server/ua_subscription.h, src/ua_session.c, src/ua_session.h, tools/schema/datatypes_minimal.txt
This change separates the subscriptions callbacks into two sepate repeated jobs:
- sampling values (job per monitoreditem)
- sending out notifications (job per subscription)
The network traffic is greatly reduced since we use asynchronous responses.
Subsriptions are working fine as per UAExpert.
But some edge cases are not finished. For example Republish is incomplete.
Needs approval from @ichrispa before merging.
Feedback is highly appreciated.
=> Separate Publish Job for Subscriptions

plugins/networklayer_tcp.c
fixed socket-overflow on some devices
This is made regarding an embedded device with proprietary
networklayer-functions. It is geared to socket-functions from the
Unix-man page of select(), which says that it only counts the events
which are watched. If no error-event is watched it won't be counted,
which leads to open sockets even if they should be closed because they
were shutdown'd before, because the select isn't triggered because it
doesn't watch for errors, when the parameter for the error-set is NULL.
It now works fine and closes the specific sockets as it should. Sureley
this isn't a noticable problem on big desktop-machines with a lot of
sockets but if you are on an embedded device reduced to 30 or something
you will experience a run out of free sockets very fast after some …
=> fixing networklayer_tcp select()

.travis.yml, plugins/networklayer_tcp.c, plugins/networklayer_udp.c, src/server/ua_server_worker.c, src/server/ua_services_attribute.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_view.c, src/server/ua_subscription.c, src/ua_types.c, src/ua_types_encoding_binary.c, tools/travis/travis_linux_before_install.sh
Fixes the following issues:
plugins/networklayer_udp.c(174): style (unsignedLessThanZero): Checking if unsigned variable 'length' is less than zero.
plugins/networklayer_tcp.c(291): style (unreadVariable): Variable 'layer' is assigned a value that is never used.
src/server/ua_services_attribute.c(13): style (variableScope): The scope of the variable 'c' can be reduced.
src/server/ua_server_worker.c(552): style (unreadVariable): Variable 'mlw' is assigned a value that is never used.
src/server/ua_services_view.c(262): style (unsignedLessThanZero): Checking if unsigned variable 'referencesSize' is less than zero.
src/server/ua_services_view.c(273): style (unsignedLessThanZero): Checking if unsigned variable 'referencesSize' is less than zero.
src/ua_types.c(544): error (memleak): Memory …
=> Fix all the cppcheck warnings and enable travis fail on cppcheck error

src/server/ua_services_nodemanagement.c
Scanning dependencies of target open62541-object
[ 37%] Building C object CMakeFiles/open62541-object.dir/open62541.c.o
/data/linux/open62541/src/build/open62541.c: In function 'addOneWayReference':
/data/linux/open62541/src/build/open62541.c:17596:5: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
else
^~~~
/data/linux/open62541/src/build/open62541.c:17598:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
return retval;
^~~~~~
cc1: all warnings being treated as errors
CMakeFiles/open62541-object.dir/build.make:186: recipe for target 'CMakeFiles/open62541-object.dir/open62541.c.o' failed
make[2]: *** [CMakeFiles/open62541-object.dir/open62541.c.o] Error 1
CMakeFiles/Makefile2:178: recipe for target …
=> fix gcc 6.1.0 compilation

plugins/networklayer_tcp.c
compiling with mingw32 gcc version 4.5.2 there was an unused variable warning and hence a compile error. A loglevel ifdef fixed it.
=> fixed an unused variable error for loglevels greater 300

include/ua_server_external_ns.h, plugins/networklayer_tcp.c, src/server/ua_services_nodemanagement.c
Ran into a Problem when trying to bridge from NS0 to an external NS with a Reference. The referenced node in the external NS is obviously not found by findNode (called from editNode, called from addReferences_Single).
The standard says, it is ok for references to external nodes when only the source of the reference is edited in the local server. As my problem occurred on an external NS, not on real external nodes, this does not fully apply, but at least it is close. The fix I included in this pull request does its job quite well in first tests, but I'm happy to learn a better alternative.
=> One way reference ofr external namespaces

src/ua_types_encoding_binary.c
When building on my machine, i got the following error: ua_types_encoding_binary.c:265: error: declaration of 'exp' shadows a global declaration
powerpc-linux-gnu/libc/usr/include/bits/mathcalls.h:101: error: shadowed declaration is here
Fix this by renaming the variable.
=> Fixed warning, by renaming variable

src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_services_call.c, src/server/ua_services_nodemanagement.c
I needed some hacks here
* a thread-local variable for a session-context of a method call
* I found an API-flaw of UA_Server_addMethodNode -- we cannot force nodeids of InputArgumetns and OutputArguments properties. Added a workaround in order not to break the 0.2 API.
=> implementation of GetMonitoredItems for CTT

examples/CMakeLists.txt, examples/discovery/server_discovery.c, examples/discovery/server_register.c, include/ua_server.h, plugins/ua_config_standard.c, src/server/ua_services_discovery.c, tests/CMakeLists.txt, tests/check_discovery.c, tests/check_server_userspace.c, tests/check_services_attributes.c, tests/check_services_nodemanagement.c
Added field in config to modify default timeout for de-registering a server.
`config.discoveryCleanupTimeout` in seconds
=> LDS customizable timeout for automatic de-register

tools/pyUANamespace/ua_node_types.py
Allow empty-element tags for base attributes in node XMLs.
Some tools create node XML with empty elements like *<Description/>*.
open62541 should be able to handle this cause they are valid XML documents
example:
```
<UAReferenceType NodeId="ns=1;i=4001" BrowseName="1:providesInputTo">
<DisplayName>providesInputTo</DisplayName>
<Description/>
<References>
<Reference ReferenceType="HasSubtype" IsForward="false">i=33</Reference>
</References>
<InverseName/>
</UAReferenceType>
```
=> Allow empty-element tag for base attributes

CMakeLists.txt, appveyor.yml, examples/CMakeLists.txt, examples/server.c, examples/server_certificate.c, tools/certs/localhost.cnf, tools/travis/travis_linux_script.sh
Apparently some clients (for example teslaSCADA) require a non-zero certificate. Together with #707 it is needed to get the two working together.
=> reviving server's certificates in an example

tools/pyUANamespace/open62541_MacroHelper.py
Should it be also set for `VariableType`?
=> Add accessLevel and userAccessLevel for variables in namespace compiler

CMakeLists.txt, include/ua_server_external_ns.h, src/server/ua_server.c
Changed return types of ExternalNodeStore functions from UA_Int32 to UA_StatusCode for clarity (and to fix Uint conversion).
Only include ua_server_external_ns if necessary.
=> Easy fix for broken external Namespace.

include/ua_constants.h, include/ua_types.h, src/client/ua_client.c, src/server/ua_server_binary.c, src/ua_securechannel.c, src/ua_types_encoding_binary.c, tools/generate_datatypes.py, tools/generate_nodeids.py
See #769 for additional description of the problem.
This is my proposed solution for the problem.
Each DataType struct stores the correct NodeID for binary/XML encoded.
Open for feedback or direct merge
=> Fix #769: Wrong NodeIDs offset for BinaryEncoding

src/client/ua_client.c
OPC UA Part4 says (page 24):
```
endpointUrl:
The network address that the Client used to access the Session Endpoint.
The HostName portion of the URL should be one of the HostNames for the
application that are specified in the Server’s ApplicationInstanceCertificate (see 7.2).
The Server shall raise an AuditUrlMismatchEventType event if the URL does not
match the Server’s HostNames. AuditUrlMismatchEventType event type is defined in
Part 5.
The Server uses this information for diagnostics and to determine the set of
EndpointDescriptions to return in the response.
```
Eclipse Milo requires EndpointUrl to be not null in the CreateSession request.
=> Add EndpointUrl to CreateSessionRequest

src/server/ua_services_call.c
Input/Output Arguments may have arrayDimensions set to 0 which means variable length.
See OPC Specification Part 3, page 61
So it should be fixed like this?
=> Array dimension 0 means variable length

src/server/ua_services_nodemanagement.c
calling
`UA_Server_deleteNode(UA_Server *server, const UA_NodeId nodeId,UA_Boolean deleteReferences);` with `deleteReferences==true`
didnt delete references,
because 
`deleteOneWayReference(UA_Server *server, UA_Session *session, UA_Node *node,
const UA_DeleteReferencesItem *item);`
got null `item->referenceTypeId`
=> Setted referenceTypeId in UA_DeleteReferencesItem (related to #794)

src/client/ua_client_highlevel.c
To handle array read requests in UA_Client_readAttribute, it is necessary to change the if-statement and delete the "UA_Variant_isScalar" condition.
After that, it works very well for me with scalar and array's.
=> Read array attribute in client api

doc/building.rst, doc/tutorial_noderelations.rst, plugins/ua_network_tcp.c, plugins/ua_network_udp.c
I had to introduce the modifications in commits ceb27d6 and 0932f47 to be able to compile on OpenBSD 5.8 without warnings. 
Peculiarities of the build process on OpenBSD are described in building.rst commited in 529bb14 and 
7a2071b.
Furthermore fixed a typo in doc/tutorial_noderelations.rst (a343e49) and modified some flag names also in there (6fff64c) that seem to have changed (?) - not entirely sure the latter is complete.
=> Compile on OpenBSD

plugins/ua_network_tcp.c, plugins/ua_network_udp.c
Added a generic [BSD detection](http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system#BSD)
This should support DragonFly BSD, FreeBSD, OpenBSD, NetBSD and Apple OSX/iOS. 
Hopefully no further changes are needed for them. 
superseeds #798
=> Generic BSD detection for tcp/udp plugin

.travis.yml, tools/travis/travis_linux_after_success.sh, tools/travis/travis_push_coverity.sh, tools/travis/travis_push_doc.sh, tools/travis/travis_push_release.sh
There was a race condition for the after success scripts which were also executed if `ANALYZE=true` and thus created invalid doc.
Could not yet fully test, since it needs to be in the main repo. Please merge and then I'll fix if there are build errors.
=> Fix after_success scripts

src/client/ua_client.c
UA_FooResponse_deleteMembers(&response) does not delete
response.responseHeader.serviceResult but it will initialize it. Thus
the return value is always UA_STATUSCODE_GOOD even if an error occurred.
Regression of 1cc01277d05e8caf0052534a505a7d6d95dd0740
=> Fix return value

src/server/ua_server.c
`servernode->nodeId` can't be reused because it may be deleted in addNodeInternalWithType if the node could not be added. Thus it may lead to an invalid memory access
=> Fix: Safe access to NodeId

tests/CMakeLists.txt, tests/check_server_userspace.c
Valgrind is already used in master branch for the unit tests. This should also be enabled in the 0.2 branch.
=> Add valgrind to unit tests (ported from master)

src/server/ua_server_binary.c
In function UA_Server_processSecureChannelMessage in ua_server_binary.c there was a problem with the UA_LOG_TRACE_CHANNEL. I fixed it in this commit!
=> fix LOG problem

tools/generate_datatypes.py
Therefore the members variable has to be defined as NULL instead of empty array
=> DataTypes may have empty members (e.g. DiscoveryConfiguration)

CMakeLists.txt
Instruct CMake to create a properly versioned library.
Cross-compile environments like OpenEmbedded/Yocto are picky about adhering to these standards, this fixes QA errors resulting from building open62541 as a shared library for embedded targets.
Signed-off-by: Mike Looijmans <mike.looijmans@topic.nl>
=> Generate properly versioned shared library links on Linux

src/client/ua_client_highlevel.c, src/server/ua_server.c, src/server/ua_services_nodemanagement.c, tests/check_services_view.c
This simplifies `register_server_with_discovery_server` a bit.
Notably, members of the request are not copied but point into the server config.
Otherwise, we have to check the statuscode of every array allocation and every UA_copy.
Also, I'm under the impression that `request.server.discoveryUrlsSize` was always zero in the realloc.
@Pro Can you review the changes?
=> Don't copy elements for RegisterServer call

src/server/ua_services_call.c
If a method with Enumerations is called the typeCheckValue-Function overwrites the Variant. At the moment every time the first value was overwritten. Now the correct value will be overwritten.
=> Fixed problem with enumeration decoding.

src/ua_connection_internal.h
This mismatch in declaration and definition was causing a build error in Visual Studio 2015 with errors as warnings.
=> Fixed mismatching function declaration and the resulting build error

src/client/ua_client.c, src/server/ua_server_binary.c, src/ua_connection.c, src/ua_securechannel.c, tools/schema/Custom.Opc.Ua.Transport.bsd, tools/schema/datatypes_transport.txt
The OPC Foundation LDS-ME Server may answer with an 'ERR' TCP message.
The error message is defined in OPC UA Part 6, Section 7.1, Table 34 and 37 
Are there any other places where we should check for that message type?
=> Add parsing of TCP Error Message 'ERR'

.travis.yml, tools/travis/travis_osx_script.sh
This enables OSX builds on travis.
Currently 0.2 builds just fine there.
One drawback is that it may take up to a few hours until the OSX build starts because the OSX machines on travis are overloaded.
=> Enable travis OS X build

CMakeLists.txt, include/open62541.pc.in
This way, people linking against installed open62541 on their systems
will be able to query its CFLAGS/LDFLAGS via pkg-config tool.
I also made the amalgamated header be installed only if the build flag
is set. The files that should be installed as headers otherwise are not
known to me. Anyway, all the examples point to the amalgamated header
nowadays.
=> Have a .pc.in file to install a pkg-config header

src/client/ua_client_highlevel.c
In UA_Client_NamespaceGetIndex the init of ReadDataId was missing, which caused an non-recoverable error on my system.
=> Bugfix UA_Client_NamespaceGetIndex not working

deps/queue.h
If the files are amalgameted there is a redefinition of SLIST_ENTRY. This was avoid earlier in the same way, but then moved to ua_util.h and finally deleted.
=> Fix redefinition of SLIST_ENTRY on mingw winnt.h

include/ua_client_highlevel.h, src/client/ua_client_highlevel.c, src/server/ua_services_attribute.c, tests/check_client_highlevel.c, tests/check_services_attributes.c
This PR adds additional unit tests for client highlevel functions.
I had to change the type for ArrayDimensions from Int32 to UInt32, which is also the correct value in the specification part 3.
@open62541/open62541-core Since this introduces a small api break (https://github.com/open62541/open62541/pull/1024/commits/efafe2567d7797675d7706a535d5550669b29249#diff-fc6ee50978a5f2bda32297608b5360d6R209)
should I still merge it?
=> Client_highlevel unittests

appveyor.yml, examples/CMakeLists.txt, tools/travis/travis_linux_script.sh
Now AppVeyor creates two artifacts:
- open62541-vs2013-static.zip
- open62541-vs2013-dynamic.zip
In travis an additional build is run with `BUILD_SHARED_LIBS=ON`
=> enable shared libs build on travis and appveyor

appveyor.yml, doc/CMakeLists.txt, tools/travis/travis_linux_script.sh, tools/travis/travis_osx_script.sh
The appveyor artifacts now only contain the final output files and not the full build folder.
This also adds latex building on the Appveyor Builds to create the .pdf file
=> Clean up appveyor artifacts and .dll builds

src/server/ua_services_nodemanagement.c
Since somit 645e4ef5 node management services fail to add VariableTypeNodes because it is tried to set _accessLevel_ attribute of _VariableTypeNode_ which has effectively no such attribute and further checks will fail properly with _UA_STATUSCODE_BADNODECLASSINVALID_.
=> VariableTypeNode has no attribute accessLevel

src/server/ua_server_ns0.c
In server NS0 setup the accessLevel attribute was not set for data source variable nodes and induced warnings in log. Changed to new addDataSourceVariableNode(...) function, prevented usage of .._begin() and .._finish() procedures and removed existing ToDos.
=> Missing accessLevel->read for dataSourceVariables in NS0 setup

include/ua_constants.h, tools/schema/Opc.Ua.StatusCodes.csv
Added 3 missing status codes according to underlying schema of OPC foundation git repository (3146d80, Errata-1.03.3) (status code descriptions of already existing status codes were updated before only)
Sorry for the inconvenience!
=> Added missing status codes according to v1.03.3

CMakeLists.txt
When compiling as a shared lib, link against the dynamic c-runtime
version.
Additionally, clean up the compile flags to append /MT to /MD and rather
replace it. This fixes warnings from the compiler.
=> Combine c runtime linkage with build type

src/ua_util.h
The `THREAD_LOCAL` is only necessary for multithreading. If multithreading is disabled, these variables don't need to be thread safe.
=> Fix #1136: THREAD_LOCAL define only necessary for multithreading

tests/check_client_async.c
Turning "running" into an automatic variable simplifies the code.
=> Do not allocate "running" on the heap

src/client/ua_client_highlevel_subscriptions.c
I am not 100% sure, but returning success on an out of memory path looks fishy.
=> Fix returned status code.

CMakeLists.txt
Otherwise, using a shared build, the dll will be left out during install
step on Windows.
=> Add runtime to install target

examples/CMakeLists.txt, examples/tutorial_client_events.c, include/ua_client_highlevel.h, src/client/ua_client_highlevel_subscriptions.c, src/client/ua_client_internal.h, tests/check_types_memory.c, tools/schema/datatypes_minimal.txt
This patchset add support for Events on the client side. This means on open62541-based client will be able to receive events from an non-open62541 OPC-UA server.
So far testing has been done exclusively against a public OPC-UA server provided by prosys.
The patchset provides an example on how to use the API.
Where-clauses should work, but haven't been tested.
=> client side event support

examples/CMakeLists.txt, examples/client_connect_loop.c, plugins/ua_network_tcp.c, src/client/ua_client.c, tests/check_client.c
When the server side is closed while the client is connected,
the client should be set to error state, which causes a reconnect on the
next connect call.
Additionally the `UA_sleep_ms` macro is added.
=> Set client to error state if disconnected. Add example for reconnect

src/server/ua_services_nodemanagement.c
Hi,
Methods could not be called by UAExpert (caused from 733dcad11630fba5f4861f9e9668ab4c5b4d91d8 to 9c4faf8551ace93d54776cc69b03000e7f424356), because arguments are not readable.
ccvca
=> Fix: Set accesslevel to read for arguments of methods

src/client/ua_client_highlevel.c, src/server/ua_services_attribute.c, tests/check_client_highlevel.c
Fix compatibility checks to allow setting the variable type after node creation.
Fix reading of nodeClass attribute
Add additional client highlevel unit tests
=> Fixes for compatibility checks and unit test for client highlevel

README.md, doc/namespace_compiler.rst, examples/client.c, examples/discovery/server_multicast.c, examples/discovery/server_register.c, examples/server.c, examples/server.cpp, examples/server_inheritance.c, examples/server_instantiation.c, examples/server_udp.c, examples/tutorial_server_datasource.c, examples/tutorial_server_method.c, examples/tutorial_server_object.c, examples/tutorial_server_variable.c, examples/tutorial_server_variabletype.c, src/server/ua_server_ns0.c, src/server/ua_services_nodemanagement.c, tests/check_client.c, tests/check_discovery.c, tests/check_server_readspeed.c, tests/check_services_attributes.c, tests/check_services_nodemanagement.c, tools/pyUANamespace/open62541_MacroHelper.py, tools/pyUANamespace/ua_builtin_types.py, tools/pyUANamespace/ua_node_types.py
The LocaleIds was formatted with an underscore as separator between the language and region. According to the OPC UA specification the language and the region shall be separated by a hyphen.
Also removed LocaleId in those cases where a specific language is not addressed, i.e. when presenting a type name.
Changes based on discussion of issue #1173
=> Corrected format of LocaleId in LocalizedText attributes

include/ua_config.h.in, tools/generate_datatypes.py
If that's not the case, the error during compile time will be similar to
`error: named bit-field 'static_assertion_failed_enum_must_be_32bit' has zero width`
=> Fix #1180 ensure enums are 32bit integers

examples/CMakeLists.txt, examples/access_control/client_access_control.c, examples/access_control/server_access_control.c, src/server/ua_services_nodemanagement.c
Fix Issue #1177
The extra functions (restricted*) prevent checking access rights when adding nodes/references by the server.
=> Respect accessControl in nodemanagement service, Fix #1177

src/ua_types_encoding_binary.c
Due to a missing else in front of an if branch in `Float_decodeBinary`
and `Double_decodeBinary`, special cases (like zero values) where not
handled correctly. Instead, `unpack754` was always used unless the value
was NaN.
This patch fixes this problem by adding the missing `else`.
=> Fix decoding of zero float and double values.

tools/generate_datatypes.py
As discussed in the mailling list the first patch removes the no longer necessary ua_util.h include and the second one is an attempt to improve a help text.
=> Small improvements for generate_datatypes.py 

src/server/ua_services_subscription.c
According to UA Specification Part 4, chapter 5.12.2.1, the add
operation for the item shall succeed for the following statues:
* Denied read access (Bad_NotReadable)
* No access rights (Bad_UserAccessDenied)
* The index range does not deliver any data for the current value
(Bad_IndexRangeNoData)
=> Added more allowed status codes in Operation_CreateMonitoredItem

src/client/ua_client.c
Hi,
I just fix two bugs:
- UA_Client_runAsync return UA_GOOD even when connection->send failed
- __UA_Client_AsyncService close the connection when a timeout occure (in UA_Connection_receiveChunksBlocking)
ccvca
=> Fix: Ignore good timeout

examples/server_certificate.c
fix : 
```
/data/open62541-master/examples/server_certificate.c: In function 'loadCertificate':
/data/open62541-master/examples/server_certificate.c:29:22: error: request for implicit conversion from 'void *' to 'UA_Byte * {aka unsigned char *}' not permitted in C++ [-Werror=c++-compat]
certificate.data = UA_malloc(certificate.length*sizeof(UA_Byte));
^
/data/open62541-master/examples/server_certificate.c: At top level:
cc1: error: unrecognized command line option '-Wno-static-in-inline' [-Werror]
cc1: all warnings being treated as errors
```
=> fix a compilation problem

src/ua_timer.c
The server crashes with a segmentation fault when all jobs are removed. This was not noticed before as the user usually does not remove the internal server jobs. 
@jpfr please have a look
=> Bugfixing: Fixed segmentation fault when removing all callback-jobs from job list

src/server/ua_services_subscription.c
See #1331
Immediately send UA_Subscription_answerPublishRequestsNoSubscription
before the session is deleted
=> Fix #1331 heap use after free

CMakeLists.txt
Linux uses by default 8MB
Now we also set it for MSVC if UA_ENABLE_FULL_NS0 is enabled
See #1326
=> Fix #1326 set reserved stack size for full NS0 on MSVC to 8MB

tests/client/check_client_highlevel.c
When UA_ENABLE_NODEMANAGEMENT is disabled, the tests fail with : 
```
24: /root/open62541-master/tests/client/check_client_highlevel.c:101:F:Client Highlevel Node Management:Node_Add:0: Assertion 'retval == 0x00' failed: retval == 2148204544, 0x00 == 0
24: /root/open62541-master/tests/client/check_client_highlevel.c:373:F:Client Highlevel Read/Write:Node_AddReadWriteNodes:0: Assertion 'retval == 0x00' failed: retval == 2148204544, 0x00 == 0
24: /root/open62541-master/tests/client/check_client_highlevel.c:518:F:Client Highlevel Read/Write:Node_ReadWrite_Id:0: Assertion 'retval == 0x00' failed: retval == 2150891520, 0x00 == 0
24: /root/open62541-master/tests/client/check_client_highlevel.c:532:F:Client Highlevel Read/Write:Node_ReadWrite_Class:0: Assertion 'retval == 0x00' failed: retval == …
```
=> fix tests when UA_ENABLE_NODEMANAGEMENT is disabled

CMakeLists.txt, appveyor.yml, tests/CMakeLists.txt, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/travis/travis_linux_script.sh, tools/travis/travis_osx_script.sh
This PR adds DrMemory leak checks for windows unit tests.
The second commit fixes memory leaks on windows since it uses a max_string_length for the nodeset compiler. Due to wrong parameter ordering in python it used UA_LOCALIZEDTEXT_ALLOC instead of the non alloc version. The memory was not freed.
=> Add DrMemory on appveyor and fix memleak on windows

include/ua_server_config.h, src/server/ua_server_ns0.c, src/server/ua_services_attribute.c, src/server/ua_services_call.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_subscription.c, src/server/ua_services_view.c, tools/schema/Opc.Ua.NodeSet2.Minimal.xml
Added support for OperationLimits object, corresponding additions to server config and responding with BadTooManyOperations for relevant services.
Also added support for setting MaxBrowseContinuationPoints and MinSupportedSampleRate of the ServerCapabilities object.
Also added support for limiting the number of references per nodes in the BrowseRequest response.
=> Added support for OperationLimits

include/ua_server_config.h, src/server/ua_services_subscription.c, src/server/ua_subscription.c, src/server/ua_subscription.h, src/ua_session.c, src/ua_session.h
Added support for:
Max number of subscriptions per seession
Max number of publish request per session
Max number of monitered Items per subscription
0 means limited by heap (old behaviour)
=> Added resource limitations for subscriptions and monitored items

src/server/ua_server_binary.c
Check if `connection->localConf.sendBufferSize` is smaller than required size `ackHeader.messageSize` to avoid heap buffer overflow
=> Fix heap overflow

examples/client_connect_loop.c, include/ua_config.h.in, plugins/ua_clock.c, plugins/ua_network_tcp.c, src/server/ua_mdns.c, src/server/ua_services_discovery_multicast.c, src/ua_util.h, tests/server/check_discovery.c, tests/testing-plugins/testing_clock.c, tools/amalgamate.py
Architecture dependant code that changed in the last few months are fixed to compile in vxworks
=> Fix missing code for VxWorks

examples/client_connect_loop.c
```
==18584== 
==18584== HEAP SUMMARY:
==18584==     in use at exit: 16 bytes in 2 blocks
==18584==   total heap usage: 114 allocs, 112 frees, 1,219,690 bytes allocated
==18584== 
==18584== 16 bytes in 2 blocks are definitely lost in loss record 1 of 1
==18584==    at 0x4C2DBC5: calloc (vg_replace_malloc.c:711)
==18584==    by 0x1146F3: UA_new (ua_types.c:823)
==18584==    by 0x11ED01: Variant_decodeBinary (ua_types_encoding_binary.c:1160)
==18584==    by 0x11EFD9: DataValue_decodeBinary (ua_types_encoding_binary.c:1233)
==18584==    by 0x11D81E: Array_decodeBinary (ua_types_encoding_binary.c:569)
==18584==    by 0x11FA55: UA_decodeBinaryInternal (ua_types_encoding_binary.c:1511)
==18584==    by 0x11FBA7: UA_decodeBinary (ua_types_encoding_binary.c:1540)
==18584==    by 0x115A31: …
```
=> fix mem leak in client_connect_loop

examples/client_connect_loop.c, include/ua_client.h, plugins/ua_network_tcp.c, src/client/ua_client.c, src/client/ua_client_connect.c, src/ua_securechannel.c, tests/client/check_client.c
When something goes wrong in the client, it closes the connection. But he tries to close a "bad" connection. The purpose of this PR is to set up a solution to close the connection in case of problems. This PR, corrects here : https://github.com/open62541/open62541/blob/0c55867ebbb9bfdbf49a7d0b2482a9dbb8de183f/src/client/ua_client.c#L294 a problem because in this case the client-> channel members are not released.
=> add UA_Client_close and the ability to reactivate a session

plugins/ua_config_default.c
#1462 
Always use the maximum notification per publish.
This increases speed on slow devices like PLC's, because PLC's can add more notifications in a publish response.
=> use maximum notification per publish

include/ua_server.h, src/server/ua_server_binary.c, src/server/ua_server_internal.h, src/server/ua_services.h, src/server/ua_services_attribute.c, src/ua_securechannel.c, src/ua_securechannel.h, tests/check_securechannel.c, tests/fuzz/fuzz_binary_message.cc, tests/server/check_server_readspeed.c, tests/testing-plugins/testing_networklayers.c, tests/testing-plugins/testing_networklayers.h
This PR is split in two commits:
- build up infrastructure for zero-copy services where we encode (and send) between operations of the same service
- use that for a zero-copy implementation of the read service. If possible, we can encode the value directly to the network buffer
=> Zero-copy read service

CMakeLists.txt
This fixes the cmake error when including open62541 with `find_package(open62541 REQUIRED)`
```cmake
Imported target "open62541" includes non-existent path
"/open62541"
```
=> Fix install includes destination

examples/CMakeLists.txt, examples/client_connect_loop.c, examples/client_subscription_loop.c, include/ua_client.h, plugins/ua_config_default.c, src/client/ua_client.c, src/client/ua_client_connect.c, src/client/ua_client_highlevel_subscriptions.c, src/client/ua_client_internal.h
The client must know when a new session has been created in order to recreate the subscriptions. The current implementation does not allow to do it. The PR adds a callback that is called when the client changes state. An example has been added. In addition, when a new session is created, open62541 automatically releases the subscriptpion and the monitereditems.
=> client subscriptions improvement

plugins/ua_network_tcp.c
For example, pressing ctrl+c in client_subscription_loop cause "select" returning -1. After, the client infinity wait in the next recv. We must check when select return -1.
=> ua_network_tcp select check error

CMakeLists.txt, src/server/ua_server_binary.c, src/server/ua_services_session.c, src/server/ua_services_subscription.c, src/server/ua_session.c, src/server/ua_session.h, src/server/ua_session_manager.c, src/server/ua_subscription.c, src/ua_securechannel.c, src/ua_securechannel.h, tests/check_securechannel.c, tests/server/check_session.c
This removes details of the server's Session implementation from the
SecureChannel code. This was unwanted as the SecureChannel is also used
by the client.
=> move session definition into server

include/ua_constants.h
The OPC Foundation provides an invalid (non escaped) CSV for status codes. This destroyed some generated status code descriptions.
=> Fixed description of some status codes

src/client/ua_client_highlevel_subscriptions.c
solves problem when last client handle will be logged for all monitored items when there is more than 1 monitored item.
=> fix client handle logging

src/ua_securechannel.c
Currently the server  indicates
```
[2018-01-24 13:15:52.061 (UTC+0100)] info/channel	Connection 5 | SecureChannel 1 | Unknown request with type identifier 452
```
when open62541 client tries to close the secure channel, because the message is of type MSG instead of CLO.
=> fix UA_SecureChannel_sendSymmetricMessage

src/ua_securechannel.c
This PR fixes incorrect padding calculation while decrypting.
The paddingSize byte wasn't removed resulting in decoding errors, when dealing with more than one chunk.
=> Fix incorrect padding calculation

src/ua_types_encoding_binary.c
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=5595
=> Also check recursion limit when decoding Variant/DataValue

src/ua_types_encoding_binary.c
Currently overlayable types like Enumerations are encoded as ExtensionObjects which is errorneous.
You can see an example in the attached screenshot from UAExpert. There the node class attribute of each node (which is an as Int32 overlayable enum type indeed) is marked as faulty.
This pull request changes the encoded type ID to Int32 for all overlayable types. After that UAExpert does not complain any more.
=> fixed encoding of overlayable types likes enums (these are int32!)

plugins/ua_network_tcp.c
When the endpoint is invalid, ```UA_ClientConnectionTCP``` return with ```connection.state = UA_CONNECTION_OPENING```. Then the client try to write to a invalid socket.
https://github.com/open62541/open62541/blob/daaa58a92fa5583e6367759d9258c0c0403d65d6/plugins/ua_network_tcp.c#L782-L789
Same if DNS lookup failed : 
https://github.com/open62541/open62541/blob/daaa58a92fa5583e6367759d9258c0c0403d65d6/plugins/ua_network_tcp.c#L813-L825
Or if the socket can't be created : 
https://github.com/open62541/open62541/blob/daaa58a92fa5583e6367759d9258c0c0403d65d6/plugins/ua_network_tcp.c#L839-L851
Setting ```connection.state = UA_CONNECTION_OPENING``` only when we have a valid socket fix the issue.
=> only set UA_CONNECTION_OPENING when we have a valid socket

include/ua_plugin_network.h, tests/client/check_client.c
Calling ```UA_Client_delete``` without calling ```UA_Client_connect``` cause a crash
```
UA_ClientConfig config = UA_ClientConfig_default;
UA_Client *client = UA_Client_new(config);
UA_Client_delete(client);
```
```
==77752== Memcheck, a memory error detector
==77752== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==77752== Using Valgrind-3.12.0.SVN and LibVEX; rerun with -h for copyright info
==77752== Command: bin/examples/client_subscription_loop
==77752== 
==77752== Jump to the invalid address stated on the next line
==77752==    at 0x0: ???
==77752==    by 0x112779: UA_Client_deleteMembers (ua_client.c:54)
==77752==    by 0x11291E: UA_Client_delete (ua_client.c:88)
==77752==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==77752== 
==77752== 
==77752== …
```
=> fix UA_Client_disconnect/close crash

CMakeLists.txt, include/ua_plugin_network.h, plugins/ua_config_default.c, plugins/ua_network_tcp.c, plugins/ua_network_tcp.h, src/client/ua_client_connect.c
Network layer uses configured server logger now.
In case that there is no logger configured it uses `UA_Log_Stdout` as fallback.
=> Network layer uses server's configured logger

src/server/ua_server_internal.h, src/server/ua_services_attribute.c, src/server/ua_services_nodemanagement.c
The compatibility checks in `compatibleDataType` for data types of "nodes against nodes" are different from those of "values/variants against nodes"
=>  compatibleDataType needs to be different for values/variants

src/server/ua_services_attribute.c
Needed to cast compared constant value explicitly so same type like variable operand (signed UA_Int32) since produced positive falses before.
=> Invalid signed comparision for value ranks

CHANGELOG, examples/client.c, examples/client_subscription_loop.c, examples/tutorial_client_events.c, include/ua_client_highlevel.h, src/client/ua_client_highlevel_subscriptions.c, tests/client/check_client_subscriptions.c, tests/fuzz/corpus_generator.c
Sometimes we need to have the client context in the monitored item handling function. Eg: to get the ```clientContext``` (https://github.com/open62541/open62541/pull/1532). But ```client``` is not present. We can't use ```context``` because it can be used to identify the monitoredItem.
That change the API but it is really needed !
=> add client to dataChangeHandler (API change !!!!)

src/server/ua_services_subscription.c
IndexRange must be copied to the monitored item before the first call to UA_MonitoredItem_SampleCallback().
Not doing so produces a data change notification containing the entire array.
=> Fix server side indexRange support for monitored items

.travis.yml, CMakeLists.txt, appveyor.yml, tests/CMakeLists.txt, tests/fuzz/CMakeLists.txt, tests/fuzz/generate_corpus.sh, tools/appveyor/build.ps1, tools/appveyor/install.ps1, tools/cmake/FindCheck.cmake, tools/travis/travis_linux_before_install.sh, tools/travis/travis_linux_script.sh, tools/travis/travis_osx_before_install.sh, tools/travis/travis_osx_script.sh
Set `UA_ENABLE_ENCRYPTION=ON` for continuous integration
Enable temporarily disabled CI checks
=> Enable CI encryption, temporarily disabled OSX and appveyor latex builds

CMakeLists.txt, include/ua_config.h.in, src/server/ua_server_worker.c
The PR adds support for enabling valgrind to dump leak checks every iteration of the server loop.
This makes it possible to do interactive checking and using the valgrind dumps to monitor the server while fuzzing for example.
=> Add flag for interactive valgind dumps

include/ua_config.h.in, src/ua_types_encoding_binary.c
The build failed with the following errors:
- __FLOAT_WORD_ORDER' is not defined, evaluates to 0 [-Werror,-Wundef]
- error: #warning is a language extension [-Werror,-Wpedantic]
=> Fix android build with ndk r16b

tools/cmake/FindMbedTLS.cmake
oss-fuzz does not support dynamic linking of dependencies
=> Use static linking for oss-fuzz

src/ua_types.c, src/ua_types_encoding_binary.c
This pull request adds support for built-in data types (UA_TYPES) with a namespace index that is different from ns==0.
The lookup algorithms of `UA_findDataType` and `UA_findDataTypeByBinaryInternal` are adapted.
`UA_findDataType` has still a ToDo since the custom data types are not known in `ua_types.c` yet.
=> support data types that are different from (nsIndex==0)

include/ua_server.h, src/server/ua_nodes.c, src/server/ua_server_internal.h, src/server/ua_server_ns0.c, src/server/ua_services_nodemanagement.c, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_nodes.py
This is a replacement of #1565
It changes the behavior of _begin to also add the parent and hasTypeDef reference. The _finish method then only adds the remaining children.
See the corresponding discussion in #1565
=> forbid duplicate references and change _begin to also add parent references

src/server/ua_services_subscription.c
fix #1520  issue.
This commit is related with service specification (Part4)
```
7.18 Monitoring Mode
DISABLED_0
The item being monitored is not sampled or evaluated, and Notifications are not generated or queued. Notification reporting is disabled.
REPORTING_2
The item being monitored is sampled and evaluated, and Notifications are generated and queued. Notification reporting is enabled.
```
=> Additional logic of setting monitoring mode

src/server/ua_services_nodemanagement.c
This addresses the comment here:
https://github.com/open62541/open62541/pull/1603#issuecomment-368455022
Additionally, @janitza-thbe requested an additional method which allows to get the parent of a specific node.
@jpfr Should we add it as a public API?
```c
static UA_StatusCode
UA_Server_getNodeParent(UA_Server *server, const UA_Node *node, UA_NodeId **parentNodeId, UA_NodeId **parentReferenceId) {
for (size_t i=0; i< node->referencesSize; i++) {
if (node->references[i].isInverse == UA_TRUE) {
for (uint8_t r =0; r<UA_PARENT_REFERENCES_COUNT; r++) {
// TODO handle subtypes of parent reference types
if (UA_NodeId_equal(&node->references[i].referenceTypeId, &parentReferences[r])) {
*parentNodeId = &node->references[i].targetIds[0].nodeId;
*parentReferenceId = &parentReferences[r];
return …
```
=> Use node ID to make sure refcount is updated

plugins/ua_pki_certificate.c
Stumbled across this while implementing valgrind monitoring for fuzzing.
=> Fix memoryleak in certificateVerification_verify

CMakeLists.txt
This typo introduced the following bug:
When building open62541 against mbedtls, the compiler options
for the C Runtime-Libraries mbedtls is built with do not match
the ones for open62541 anymore resulting in linker errors.
This bug is MSVC-related only.
=> Typo in cmake option: Trailing S missing in BUILD_SHARED_LIBS.

src/server/ua_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c
=> only send monitored items sampled before last triggered publish

open62541.spec
This change does add the additional build time dependency on
python-six and also corrects the directory name of the cmake
files.
=> Fix spec file of RPM build

doc/building.rst
Fix type for UA_BUILD_SELFIGNED_CERTIFICATE
to UA_BUILD_SELFSIGNED_CERTIFICATE for cmake
parameters in build instructions.
Signed-off-by: Andreas Fuchs <andreas.fuchs@sit.fraunhofer.de>
=> Doc: Fix typo in cmake parameter

tools/generate_datatypes.py, tools/nodeset_compiler/backend_open62541.py
I added some namespaces and followed #823 until some point to generate my namespaces files. I wanted to compile these files in my own project in C++ wich uses the open62541 static library. I added then in this PR what's needed for C++ and the big change is that I want to include only the folder where open62541.h file is, so the only thing missing was the ua_types_encoding_binary.h which is not exported so it is only present in the open62541.c file. I added the declarations of it for the namespaces and included a ["hack"](https://github.com/open62541/open62541/compare/master...cabralfortiss:master#diff-36dccac8f1a25167289a84f42ba74460R199) to avoid compiling errors for namespace0 in amalgamation
=> Add missing ifdef for compiling namespace externally

CMakeLists.txt
#1639 
Provide users an option to disable the automatic override of /MD compiler switch with /MT.
Only relevant for MSVC.
=> Add cmake option UA_MSVC_FORCE_STATIC_CRT

CMakeLists.txt, plugins/ua_config_default.c, plugins/ua_config_default.h, plugins/ua_securitypolicy_basic256sha256.c, plugins/ua_securitypolicy_basic256sha256.h, tests/CMakeLists.txt, tests/fuzz/CMakeLists.txt
I hope this pull request meets @Infinity95 expectations on a rebase on master to get rid of the redundant commits and being compliant with the new security policy interface that was merged into master just shortly before. This pull request summarizes the effort we made to make Basic256Sha256 encryption usable and working in open62541. The decisive changes we made by @Infinity95. 
@Infinity95 @jpfr please make a quick check that you are able to connect your client with a server that has Basic256Sha256 enabled as well before doing the merge. I'm using the plugin for several days and faced no problems with anonymous logins whereas username/password logins do not work as i reported at the very end of #1587.
=> Introduced Basic256Sha256 security policy based on Basic128Rsa15

CMakeLists.txt, plugins/ua_securitypolicy_basic128rsa15.c, plugins/ua_securitypolicy_basic256sha256.c, plugins/ua_securitypolicy_common.c, plugins/ua_securitypolicy_common.h, tests/CMakeLists.txt, tests/fuzz/CMakeLists.txt
Adds two additional files in the plugins directory: ua_securitypolicy_common.h/.c
Pulls out sha1 function into these common files and renames other conflicting functions.
These new files could also be used in the future to reduce code duplication between security policy basic128rsa15 and basic256sha256.
#1643
=> fix security policy amalgamation odr violations

tools/schema/datatypes_minimal.txt
There is a working API for event monitoring with event filters, so the operator types for the where clause should be available by default.
=> Enable auto generation for types required by EventFilter

include/ua_config.h.in
A "dirty" fix to allow GCC 4.2.2 compilation by aliasing `__COUNTER__` with `__LINE__`.
=> Fixed __COUNTER__ macro for PowerPC compilation

doc/index.rst
The `easy hacks` label does not exist, while the `good first issue` label seems to be used.
=> Fix broken link in index.rst

CMakeLists.txt
LIB_INSTALL_DIR is already initialized with the relative path `lib`, that works fine when used with the [CMake's `install` command](https://cmake.org/cmake/help/v3.0/command/install.html).
=> Avoid duplicated initialization of LIB_INSTALL_DIR

CMakeLists.txt, doc/CMakeLists.txt, include/ua_client.h, include/ua_client_config.h, include/ua_server.h, plugins/ua_config_default.c, src/server/ua_server_discovery.c
The server implementation needs to initialize a client when it
shall register itself to a discovery server. To avoid including a
private header file of the plugin, a callback function has been
declared in the server header file to be implemented by the plugin
implementation. This callback function are called by the server
when it shall initialize a client.
=> Added callback function to get client config from config plugin

plugins/ua_network_tcp.c
since https://github.com/open62541/open62541/pull/1417/files the connection is closed in ```UA_SecureChannel_deleteMembersCleanup```.
Then
https://github.com/open62541/open62541/blob/fc2200ad685d9249955c9dc98064fa166732bca7/plugins/ua_network_tcp.c#L667-L675
is now wrong and it can cause interpretation problems as in https://github.com/open62541/open62541/issues/1678
=> fix connection closed server log

.travis.yml, README.md, sonar-project.properties, tools/travis/travis_linux_after_success.sh, tools/travis/travis_linux_before_install.sh, tools/travis/travis_linux_script.sh
This PR adds additional static code analysis provided by sonar cloud. It especially shows duplicated code measurements.
All open62541 Github admins should have access to the analytics here:
https://sonarcloud.io/organizations/open62541/projects
=> Add Sonar static code analysis

CMakeLists.txt, examples/discovery/server_multicast.c, examples/discovery/server_register.c, include/ua_client.h, include/ua_client_config.h, include/ua_server.h, plugins/ua_config_default.c, plugins/ua_network_tcp.c, plugins/ua_securitypolicy_basic128rsa15.c, src/client/ua_client_connect.c, src/server/ua_server_discovery.c, src/server/ua_services_discovery.c, tests/CMakeLists.txt, tests/server/check_discovery.c, tests/testing-plugins/testing_clock.c, tests/testing-plugins/testing_clock.h
Since client encryption landed into master, this was an open TODO for
a long time. The multicast server example was updated to use the encryption
client when necessary.
Fixes #938
This introduces the following API changes:
* NEW `UA_Client_connect_noSession`: create a client connection without a session. The OPC Foundation LDS server requires a secure channel, but no session, to call the RegisterServer services.
* CHANGE: `UA_Server_register_discovery`, `UA_Server_unregister_discovery`, `UA_Server_addPeriodicServerRegisterCallback` to use a client instead of a discovery url. This is required so that the user can initialize a client with the required client encryption certificates
=> Support OPC Foundation LDS server

src/ua_types_encoding_binary.c
If variant contains array of overlayable elements, then we don't need to iterate over all elements. The same optimisation is used in array encoding (Array_calcSizeBinary).
=> Variant binary encoding size optimization

examples/CMakeLists.txt, examples/common.h, examples/encryption/client_basic256sha256.c
This adds the common.h file to the cmake project which is necessary for some IDEs to recognize it for analysis.
=> Add common.h to cmake project

examples/encryption/client_basic128rsa15.c, examples/encryption/client_basic256sha256.c, src/client/ua_client.c, tools/certs/create_self-signed.py
- Update UA_ByteString_allocBuffer() to UA_STACKARRAY() in the files
examples/encryption/client_basic128rsa15.c and examples/encryption/
client_basic256sha256.c.
- Handle return value for remote certificate verification in
ua_client.c file.
- Update create_self-signed.py to generate CA certificate in .der
format.
Known issue:
1. Code coverage is not checked using "coveralls".
=> [FIX] Trust list verification for secure client application

src/client/ua_client_subscriptions.c
One of the commercial SDKs (not naming names) is sending wrong subscription sequence numbers from time to time.
See the attached Wireshark dump.
This PR demotes the problem to a warning. So the connection is no longer immediately closed.
Everybody okay with that?
[publish_sequencenumber.zip](https://github.com/open62541/open62541/files/1921915/publish_sequencenumber.zip)
=> Workaround a commercial SDK messing up the subscription sequence numbers

include/ua_types.h, src/server/ua_services_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, src/ua_types.c
The following changes are made for server support:
* Creating an DEADBANDTYPE_ABSOLUTE filter for non numeric data type from client fail with BADFILTERNOTALLOWED
* Creating a DEADBANDTYPE_PERCENT filter will fail with BADNOTIMPLEMENTED (impementing it is not possible as long we do not have the EURange)
* Updates to clients will be filtered for DEADBANDTYPE_ABSOLUTE filters for numeric scalar and array types
If this is also code which should go into 0.3 release, I can also do a pull request for 0.3 branch. In my opinion the first 2 bullet points fixes bugs, because we do always report GOOD when applying filters by clients, but do not handle them right.
=> Add filter support for numeric absolute filters

src/client/ua_client.c, src/client/ua_client_connect.c
The client currently sets the new security token as soon as it receives a OpenSecureChannelResponse. If a publish response with the old tokenId is received after the OpenSecureChannelResponse, the client closes the connection.
This patch saves the new security token to the nextSecurityToken member of UA_SecureChannel. If a message with the new tokenId arrives, the old security token is replaced with the new security token.
If the client is the first to send a message, the token is also replaced.
OPC UA part 4, 5.5.2.1 states that a client should request a new security token after 75% of the old token's  lifetime has elapsed. It also states that a client should accept messages secured with an expired security token for up to 25% of the token lifetime. This is not covered by this patch, so …
=> Fix connection close after secure channel renew with background publish

src/client/ua_client_subscriptions.c
More than one consecutive keepalive message and the first notification message after a keepalive message share the same sequence number.
Don't print a warning for these cases.
This is related to https://github.com/open62541/open62541/commit/792cade2c6d9b05c2d1c69af7ad61a9131ab26c7
=> Fix the missing message detection in the client subscription

plugins/ua_nodestore_default.c
The current implementation generates numeric node ids that collide with node ids specified in NodeIds.csv.
=> Fix generation of numeric node ids

tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/nodes.py
This patch enables the nodeset compiler to create c code for VariableNode instances with arrayDimensions.
The code has been tested with UA_ENABLE_FULL_NS0 and a custom xml file that contains an Object node connected to a VariableNode with a three-dimensional array value (specifying arrayDimensions as attribute works too) :
```xml
<?xml version='1.0' encoding='utf-8'?>
<UANodeSet xmlns="http://opcfoundation.org/UA/2011/03/UANodeSet.xsd" xmlns:uax="http://opcfoundation.org/UA/2008/02/Types.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<NamespaceUris>
<Uri>ValueTest</Uri>
</NamespaceUris>
<Aliases>
<Alias Alias="Double">i=11</Alias>
<Alias Alias="Organizes">i=35</Alias>
<Alias Alias="HasTypeDefinition">i=40</Alias>
<Alias …
```
=> Add multi-dimensional array support for VariableNode code generation

examples/tutorial_server_variable.c
This fixes a typo (`UA_VariableAttrbitues` -> `UA_VariableAttributes`) in the tutorial section 'Adding Variables to a Server'.
=> Fix typo in tutorial documentation

doc/nodeset_compiler.rst
This fixes a typo (`git submodule --init --update` -> `git submodule update --init`) in the section 'XML Nodeset Compiler' of the documentation.
=> Fix typo in XML Nodeset Compiler documentation

src/server/ua_subscription_datachange.c
Thanks to Tino Bischoff for finding the root-cause
Co-authored-by: Tino Bischoff <tino.bischoff@iosb.fraunhofer.de>
=> Events: Fix registering of monitoreditem callbacks

include/ua_server.h
This improves the documentation (doc-string) of the `typedef UA_DataSource`. The old documentation of `UA_DataSource` is incorrect: Some arguments were missing or have different names in the recent versions.
Please review the documentation, in particular the `const UA_NumericRange *range` argument.
=> Improve documentation of UA_DataSource

tools/certs/localhost.cnf
The standard specifies in part 6, p. 41 and part 4, p. 115 that the key usage extension for an Application Instance Certificate shall include
- digitalSignature
- nonRepudiation
- keyEncipherment
- dataEncipherment
=> Adds dataEncipherment to key usage extension for initial certificate

src/server/ua_services_subscription.c
During the creation of a new subscription the number of active
subscriptions are compared to the maximum number of subscriptions
allowed to be created. However, this check validated against
number of received publish requests instead of number of
active subscriptions.
=> Bad max check when creating a new subscription

CMakeLists.txt, include/ua_config.h.in, include/ua_server_config.h, plugins/ua_config_default.c, src/server/ua_server_ns0.c, tools/schema/Opc.Ua.NodeSet2.Minimal.xml
OPC Spec Part 11 - 5.4.2: 
> The ServerCapabilitiesType Objects for any OPC UA Server supporting Historical Access shall contain a Reference to a HistoryServerCapabilitiesType Object.
I made the capabilities configurable via the server config file. This could also help the regarding implementation, as we could quickly check, if the implementation supports the requested feature.
It only gets applied, if `UA_ENABLE_HISTORIZING` is enabled.
The problem: The `HistoryServerCapabilities` are added to `ServerCapabilities` regardless if `UA_ENABLE_HISTORIZING` is set. I don't know how one would get the node compiler to do this dynamically, without creating a new NodeSet containing Minimal and Part 11.
Also adding `HistoricalRawData` Profile, if `UA_ENABLE_HISTORIZING` is enabled.
This could get a …
=> Added HistoryServerCapabilities to ServerCapabilities

plugins/ua_debug_dump_pkgs.c
=> Fix gcc compiler warning: no previous prototype for 'UA_dump_hex_pkg'

src/ua_securechannel.c, src/ua_securechannel.h, src/ua_types.c, src/ua_util.h
@jpfr do you see a better way to handle `static pcg32_random_t UA_rng = PCG32_INITIALIZER;` not being threadsafe?
Fixes #1769
=> Remove all usages of UA_THREAD_LOCAL

include/ua_client_highlevel_async.h
This fixes  `undefined reference to` when using async functions from C++.
=> Add '#ifdef __cplusplus extern "C" {...' in ua_client_highlevel_async.h

src/ua_timer.c, src/ua_timer.h
If there are a set of timer callbacks in the timer list that are
executed in the same timer process cycle the order of them were
inversed every time after they had been executed, except the first
callback. Also, if a set of timer callbacks with same timer interval
are added within 1 second of each other, they are synchronized to
expire at the same time and added in front of each other, except the
first one which will keep the first position. If four timer callbacks
with the same time interval are added after each other they are put
in the timer list in the following order: #1, #4, #3, #2.
This change fixes so callback timers that will be executed with
the same time interval and that are put together in a "block" in the
timer list are not inversed within this block after each execution of …
=> Update timer implementation to not change order of callbacks

include/ua_config.h.in, src/ua_types_encoding_binary.c
Fix the default encoding (no overlays) for longer bool definitions.
This fixes #1840. Thanks to @HamidMapna for uncovering the root cause
for issues on QNX.
=> Types: Ensure booleans are 1 byte long for overlayed encoding

include/ua_plugin_access_control.h, plugins/ua_accesscontrol_default.c, src/server/ua_services_session.c, tools/schema/datatypes_minimal.txt
The PR is a reaction to https://groups.google.com/forum/#!topic/open62541/8qujwG8fTC4
The authentication plugin needs to know some information about the SecureChannel.
For example to allow additional access only over an encrypted channel.
With this change we forward the endpoint information and the remote certificate used for the SecureChannel to the AccessControl plugin.
=> Breaking API: Forward endpoint information and the remote certificate to AccessControl

src/server/ua_subscription_datachange.c, tests/CMakeLists.txt, tests/server/check_local_monitored_item.c
If you run the test without the fix and enabled memory sanitizer, you will see the memory leak in output.
With the fix it is gone.
Note: Enable the sanitizer with the following lines in the CmakeList.txt file.
```
set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fno-omit-frame-pointer -fsanitize=address")
set (CMAKE_C_LINKER_FLAGS "${CMAKE_C_LINKER_FLAGS} -fno-omit-frame-pointer -fsanitize=address")
```
=> Bugfix memory leak in local monitored item

include/ua_plugin_pki.h, plugins/ua_pki_certificate.c, src/server/ua_services_session.c
See #1902.
This is not yet functional since mbedTLS lacks parsing of the URI in the Alternative Subject Names.
See the open PR for mbedTLS: https://github.com/ARMmbed/mbedtls/pull/731
=> [WIP] Compare the ApplicationURI in the certificate

CMakeLists.txt, arch/eCos/CMakeLists.txt, arch/eCos/ua_architecture.h, arch/posix/ua_architecture.h, arch/vxworks/ua_architecture.h
This fixes the local queue.h being in the amalgamated h file. Also it removes some compiler specifics flags for the eCos OS and uses the general variables for adding/removing flags for the specific architecture
=> Fix wrong local include in amalgamated file

arch/ua_network_tcp.c
After the ua_network_tcp.c has been moved to the arch/ directory, there are a few small modifications needed in the ifdef _OS9000 part. Before, it was errno__ which is not longer existing here and therefore errno again. And a remove of WIN32_INT as a casting. That's all to get the project compiling for OS-9 again.
Signed-off-by: Kei-Thomsen <thomsen@microsys.de>
=> Changes in the OS-9 part of ua_network_tcp.c after the move to arch/

arch/ua_network_tcp.c
open62541 applications built with clang with ASAN enabled fail with
>==25154==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffd3812dac0 at pc 0x0000004ddc8d bp 0x7ffd3812d380 sp 0x7ffd3812cb30
This patch fixes the issue. For more details, see https://github.com/google/sanitizers/wiki/AddressSanitizerUseAfterScope
=> Fix stack-use-after-scope in ua_network_tcp.c

examples/discovery/server_multicast.c, src/client/ua_client_connect.c, src/server/ua_mdns.c, src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_services_discovery_multicast.c
The mDNS SRV announce target was currently just taken for the discovery url.
The specification Part 12 explicitly states:
> The hostname maps onto the SRV record target field.
> If the hostname is an IPAddress then it must be converted to a domain name.
> If this cannot be done then LDS shall report an error
This is solved by using the mDNS 'A' record announces, which map host names to IP addresses.
=> Correctly resolve mDNS SRV announce target

CMakeLists.txt
The installed version does not have UA_ARCHITECTURE_* set as compiler definition. This sets the definition as compiled.
If not set, this error is shown (and many more):
>error: ‘UA_SOCKET’ does not name a type; did you mean ‘UA_FORMAT’?
=> Fix propagation of UA_ARCHITECTURE_* to install

doc/building.rst
The example called server_variable.c was removed in https://github.com/open62541/open62541/commit/68402c5ff6e6cfcd1f58b5922dc1df7d865ac697#diff-beb1222a9c51e2083f45b086a9275aa3 .
=> Fix name of tutorial_server_variable.c

CMakeLists.txt
Without this fix if one installed open62541 in the default [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/v3.5/variable/CMAKE_INSTALL_PREFIX.html), or in a custom prefix that was added to pCMAKE_PREFIX_PATH](https://cmake.org/cmake/help/v3.5/variable/CMAKE_PREFIX_PATH.html), `find_package(open62541 REQUIRED)` would still fail. 
This is because the CMake config file was not installed in one of the many directory check by the find_package CMake command: 
https://cmake.org/cmake/help/v3.8/command/find_package.html . 
Before this fix, the only way of actually finding the open62541 CMake package was to directly point `open62541_DIR` or `CMAKE_PREFIX_PATH` to `<prefix>/lib/cmake/open62541` .
See https://cmake.org/cmake/help/v3.10/manual/cmake-packages.7.html#package-configuration-file for …
=> Fix installation directory of CMake config files

src/server/ua_subscription_datachange.c
UA_encodeBinary() no longer returns the UA_STATUSCODE_BADENCODINGLIMITSEXCEEDED status code.
The detectValueChangeWithFilter() function expects this status code as condition to attempt encoding the value on the heap. As a result, values with an encoded size of > 512 bytes could not be encoded.
=> Fix value encoding for data change notifications

src/server/ua_subscription.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, tests/server/check_subscription_events.c
Since the specification only states that the MonitoredItems' queue sizes are unaffected by EventQueueOverflowEvents, an additional counter has been added to MonitoredItems to keep track of the "actual" amount of items in the queue, even if the queueSize only reflects events which aren't overflows.
The subscription queues do not handle OverflowEvents in a special way.
@jpfr Please review.
=> Add support for EventQueueOverflowEvents

CMakeLists.txt, doc/nodeset_compiler.rst, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/nodeset_compiler.py
Due to issue #1254 : The huge strings are changed as arrays of ASCII values of each element inside for ByteArrays. And also some implementations are done due to task.
Fixes #1254
=> NodesetCompiler use Byte array instead of string

src/server/ua_services_attribute.c
The writeValueAttribute function in ua_services_attribute.c uses UA_VariableNode as a common type for access to Variable and VariableType nodes.
UA_VariableTypeNode doesn't have the historizing member, so trying to read it may access unallocated memory if the node is in reality a UA_VariableTypeNode.
=> Fix unaddressable access when writing the value of a VariableType node

tools/nodeset_compiler/backend_open62541_nodes.py
Hello,
I found an issue in NodesetCompiler when instantiating a user defined structure.
Basically the generated code looks like:
```c
UA_ExtensionObject *variablenode_ns_1_i_6008_variant_DataContents = *variablenode_ns_1_i_6008_TestStruct_0_0;
```
while should be
```c
UA_ExtensionObject *variablenode_ns_1_i_6008_variant_DataContents = variablenode_ns_1_i_6008_TestStruct_0_0;
```
See attached nodeset files.
[test.zip](https://github.com/open62541/open62541/files/2281243/test.zip)
=> NodesetCompiler: Fixed instantiation of user defined structures

tools/generate_datatypes.py
Trying to run the script generate_datatypes.py on data type definition (*.bsd) like the following:
```xml
<opc:StructuredType BaseType="ua:ExtensionObject" Name="ExtendedKeyValuePair">
<opc:Field TypeName="opc:CharArray" Name="key"/>
<opc:Field TypeName="ua:Variant" Name="value"/>
<opc:Field TypeName="ua:LocalizedText" Name="description"/>
</opc:StructuredType>
```
the script enters an infinite loop, basically because the type `opc:CharArray ` is not recognized as builtin type String. The patch ensures that `opc:CharArray ` is recognized and transformed to String.
Btw, the standard says:
```xml
<opc:StructuredType Name="String">
<opc:Documentation>A UTF-8 null terminated string value.</opc:Documentation>
<opc:Field Name="Value" TypeName="Char" Terminator="00" />
</opc:StructuredType> …
```
=> NodesetGenerator: CharArray is now considered as String

tools/nodeset_compiler/backend_open62541_nodes.py
I noticed a problem with an enumeration loaded from a generated nodeset. Belowe the EnumStrings property:
```xml
<UAVariable DataType="LocalizedText" ParentNodeId="ns=1;i=3002" ValueRank="1" NodeId="ns=1;i=6020" ArrayDimensions="3" BrowseName="EnumStrings">
<DisplayName>EnumStrings</DisplayName>
<References>
<Reference ReferenceType="HasProperty" IsForward="false">ns=1;i=3002</Reference>
<Reference ReferenceType="HasModellingRule">i=78</Reference>
<Reference ReferenceType="HasTypeDefinition">i=68</Reference>
</References>
<Value>
<uax:ListOfLocalizedText>
<uax:LocalizedText>
<uax:Text>ConnectedNotRunning</uax:Text>
</uax:LocalizedText>
<uax:LocalizedText>
<uax:Text>ConnectedRunning</uax:Text>
</uax:LocalizedText>
<uax:LocalizedText>
<uax:Text>Disconnected</uax:Text>
</uax:LocalizedText> …
```
=> Avoid encoding dimensions in simple array variants

src/server/ua_server.c, src/server/ua_server_worker.c
Some systems (for instance embedded systems) could get there IP-configuration late. This time could be used to create the namespace as well as spend some time to parsing files (e.g. XML for address space).
Other case is that the OPC UA Server is part of a whole system will be started first on request (e.g. after 3 hours runtime), but the address space creation should be done each time at system Startup phase.
All code changes do not change any already available behaviour and do not break any API, since the variable lateEndpointCreate in struct UA_ServerConfig will be initialiazed with 0==false.
=> Move number of endpoints check to UA_Server_run_startup

examples/tutorial_server_events.c
I extended the example to add the rest mandatory EventFields 'Time' and 'SourceName'.
UaExpert Client needs the EventField 'Time' to show the events on Event View.
That fixes #1995 and maybe relevant to issue #1839.
@Pro and @aDogCalledSpot please check it:)
=> add EventFields 'Time' and 'SourceName' in server events tutorial

src/server/ua_subscription.c, src/server/ua_subscription.h
- rename subscription variable sequence number to nextSequenceNumber
- adjust logic
=>  Fix CTT errors for subscription sequence number handling

CMakeLists.txt, include/ua_plugin_historydatabase.h, include/ua_server_config.h, plugins/historydata/ua_historydatabackend_memory.c, plugins/historydata/ua_historydatabackend_memory.h, plugins/historydata/ua_historydatabase_default.c, plugins/historydata/ua_historydatabase_default.h, plugins/historydata/ua_historydatagathering_default.c, plugins/historydata/ua_historydatagathering_default.h, plugins/historydata/ua_plugin_history_data_backend.h, plugins/historydata/ua_plugin_history_data_gathering.h, plugins/ua_config_default.c, src/server/ua_services_attribute.c, tests/CMakeLists.txt, tests/server/check_historical_data.c, tests/server/historical_read_test_data.h
This PR builds on #1852 in the two following ways.
- The plugin struct, UA_HistoricalDataService, is renamed to UA_HistoricalDatabase.
A service has a specific meaning in OPC UA. And the plugin provides several of these services.
- The new public API from #1852 is moved to /plugins/historydata.
We don't need this as public API at the moment. And this gives us the opportunity to performance-test and get experience before we freeze the additional API.
The actual functionality of #1852 is 100% left unchanged.
=> Historical data plugin

src/server/ua_services_session.c
Fixes CTT error for "Session Minimum 2 Parallel/002.js": CreateSession.Response.ServerEndpoints are not needed when a ServiceFault is returned. Expected <0> but got <1>.
=> Move CreateSession in front of the EndpointDescription creation

plugins/ua_securitypolicy_basic128rsa15.c, src/client/ua_client_connect_async.c, src/server/ua_securechannel_manager.c, src/server/ua_server_binary.c, src/server/ua_services_discovery.c
By OR'ing statuscodes we lose information in some cases and in those cases where they don't overlap it complicates getting the actual statuscodes.
Also in some cases we only check at the end of a function if we encountered an error. If the error happens at the beginning of the function the rest is still executed which might lead to other problems.
=> [WIP] Remove OR'ing statuscodes

examples/server_ctt.c
Makes figuring out what the problem is easier when trying to start the CTT server with incorrect file paths.
=> Check if server_ctt certificate and private key are found

tests/client/check_client_subscriptions.c, tests/client/check_client_subscriptions_deprecated.c
When compiling open62541 with ```UA_ENABLE_METHODCALLS``` disabled, I have the following errors:
```
CMakeFiles/check_client_subscriptions.dir/client/check_client_subscriptions.c.o : Dans la fonction « Client_methodcall » :
/data/open62541/tests/client/check_client_subscriptions.c:496 : référence indéfinie vers « UA_Client_call »
/data/open62541/tests/client/check_client_subscriptions.c:513 : référence indéfinie vers « UA_Client_call »
collect2: error: ld returned 1 exit status
tests/CMakeFiles/check_client_subscriptions.dir/build.make:192 : la recette pour la cible « bin/tests/check_client_subscriptions » a échouée
make[2]: *** [bin/tests/check_client_subscriptions] Erreur 1
CMakeFiles/Makefile2:1479 : la recette pour la cible « tests/CMakeFiles/check_client_subscriptions.dir/all » a …
```
=> fix tests when UA_ENABLE_METHODCALLS is disabled

src/server/ua_services_session.c
Hello,
With #2013, ```UA_SessionManager_createSession``` was moved up.
In some cases of errors the session is not removed. This PR fix this problem.
In some other places the value of ```response->responseHeader.serviceResult``` is overwritten. This PR fix this problem.
@pro @jpfr  can you review the code?
@mlang-de can you test this PR with CTT?
=> fix Service_CreateSession after #2013

examples/tutorial_server_events.c, include/ua_server.h
Change a few lines in documentation and example to point out the necessity of the Time field if events should be monitored using UAExpert.
=> Elaborate on "mandatory" event fields

plugins/ua_securitypolicy_basic256sha256.c
The URIs for the "SecurityPolicy [B] - Basic256Sha256" are not set correctly.
Regarding [1] the RSA signtaure algorithm has the URI "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
[1] https://opcfoundation-onlineapplications.org/profilereporting/index.htm?ModifyProfile.aspx?ProfileID=57c0f86d-400a-4146-a919-cb65679aea97
=> Update URIs in SecurityPolicy

src/server/ua_subscription_events.c, tests/server/check_subscription_events.c
An invalid free was causing the server to crash when either creating multiple monitored items on a single node or shutting down the client before closing the subscription.
=> Remove invalid free in ua_subscription_events

plugins/historydata/ua_historydatabackend_memory.h, plugins/historydata/ua_historydatabase_default.h, plugins/historydata/ua_historydatagathering_default.h, plugins/historydata/ua_plugin_history_data_backend.h, plugins/historydata/ua_plugin_history_data_gathering.h, plugins/ua_config_default.h, src/client/ua_client_internal.h, src/pubsub/ua_pubsub.h, src/pubsub/ua_pubsub_manager.h, src/pubsub/ua_pubsub_networkmessage.h, src/pubsub/ua_pubsub_ns0.h, src/server/ua_mdns_internal.h, src/server/ua_securechannel_manager.h, src/server/ua_server_internal.h, src/server/ua_services.h, src/server/ua_session.h, src/server/ua_session_manager.h, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, src/ua_connection_internal.h, src/ua_securechannel.h, src/ua_timer.h, src/ua_types_encoding_binary.h, src/ua_util_internal.h
Fixes the speed regression reported in #2034.
=> Don't prepare NodeIds for logging when the loglevel is too high

tools/nodeset_compiler/nodeset.py
The regexp in nodeset.py that is used to remove references to the 'uax:' namespace from the XML did not match all cases, causing it to corrupt the XML that is fed to the parser. This lead to Expat 'mismatched tag' errors.
Examples which did not match:
`<uax:Description />`
(because of the space)
`<uax:test property="/test">`
(the space and the special characters). Note that I didn't find actual usage of attributes in my XML, so the second example may not really be an issue in practice..
The modified regexp should match anything up to the first `/>` or `>`, which would convert the above examples into:
`<Description />
<test property="/test">`
The non-greedy match is applied to prevent consuming multiple XML elements, when they occur on the same line (for example: …
=> [Review] Fix removal of 'uax:' namespaces from elements

src/server/ua_server_binary.c, src/ua_util.c, tests/check_types_custom.c, tests/server/check_discovery.c, tests/server/check_server_userspace.c, tests/server/check_services_attributes.c, tools/appveyor/install.ps1, tools/travis/travis_linux_before_install.sh
Locks sphinx to an older version, otherwise it fails on travis
Now MinGW also uses gcc8, thus this PR also includes major parts of 0fec88807a3277b178a8b2482101064de72deb8d
=> Fix gcc8 and travis

tools/generate_datatypes.py, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py
Apparently, OPC-UA identifiers may contain a wide range of special characters, including quotation marks, dots and spaces.
For example, this is a fragment from an UANodeSet XML exported from Siemens TIA Portal V15:
```
<UAVariable NodeId="ns=3;s=&quot;dbCounters_748&quot;.&quot;AllData&quot;.&quot;Element&quot;[11].&quot;CountData&quot;.&quot;Product&quot;[0]" BrowseName="3:0" ParentNodeId="ns=3;s=&quot;dbCounters_748&quot;.&quot;AllData&quot;.&quot;Element&quot;[11].&quot;CountData&quot;.&quot;Product&quot;" DataType="ns=3;s=DT_&quot;udtCounter_627&quot;" AccessLevel="3">
<DisplayName>0</DisplayName>
<References>
<Reference ReferenceType="HasTypeDefinition">ns=3;s=VT_"udtCounter_627"</Reference>
<Reference ReferenceType="HasComponent" …
```
=> [Review] Fix/cleanup unsafe c names

src/server/ua_server_binary.c
To support network layers that only provides 1 send buffer only one
message context can be initialized at once. Some services, e.g.
Delete Subscriptions, also initializes message contexts when they
are processed. To only have 1 message context active concurrently,
the normal services are now processed before the message context are
initialized.
=> Process normal services before initalizing the message context

plugins/ua_securitypolicy_basic128rsa15.c
The function asym_decrypt_sp_basic128rsa15() did not set any rsa
padding. If some other function of the security policy
was executed, setting a different padding, it made the decrypt
function to not work anymore.
The RSA padding is now set to PKCS-1 v.1.5 with hash ID 0. It equals
the padding the encrypt function of the security policy sets.
=> Asymetric decrypt func of Basic128Rsa15 did not set rsa padding

src/server/ua_subscription_events.c
Make sure the EventType is not a Subtype of CondtionType (Part 9 not supported yet).
1) The check should ignore the "ConditionId" Clause set by UaExpert and ignore all Events which are Conditions. (However, if a Condition Event was created and UaExpert is used, then all the Fields of that Event except the "ConditionId" will be presenet in the Event View) -> The User should not use Events which are Conditions in that case!
2) The second check is to make sure the Event has a TypeDefinition of an BaseEventType SubType.
Fixes #2027 and fixes #2038 
Cherry-picked from @sqadasi
=> Correct Event validity check

src/ua_securechannel.c
Before encoding the response into the send buffer space was reserved
for the header, the signature (if applicable) and 2 bytes for the
padding (if applicable). When reserving space for the header, the
end of the buffer was moved out of bounds of the send buffer instead
of reducing the size available for encoded data. 2 bytes padding is
also not enough for worst-case padding scenarios.
With this fix the end buffer position is calculated correctly when
reserving space for the message header and enough space is reserved
for the padding (if the chunk shall be encrypted).
=> Reduce the size of the msg chunks to fit header and footer

src/server/ua_subscription.c, src/server/ua_subscription_monitoreditem.c, tests/server/check_subscription_events.c
Fixes https://github.com/open62541/open62541/issues/2072.
The problem wasn't an overflow, but an underflow. This was causing the notification queue size to be reduced below 0. Usages of eventOverflows should be correctly found now.
Also, there are generally less overflows being generated since the generation was moved outside of the while loop in UA_MonitoredItem_ensureQueueSpace. The wording in the specification isn't entirely clear here. In Part 4 5.12.1.5 it says that when "events are discarded" (plural), an overflow is generated but it only discards the first event "without discarding any other events". I  believe having only overflowEvent indicate the removal of numerous events sounds more reasonable than generating one for each them - opinions?
=> Fix OverflowEvent counting

appveyor.yml, tools/appveyor/build.ps1, tools/appveyor/install.ps1
This regularly breaks.
And we use the pdfs from appveyor only for releases.
And we have to manually edit the release zips anyway.
=> Disable PDF generation on Appveyor

src/ua_types.c
CTT scripts "View TranslateBrowsePath/011 + Err-020" requires the check for all NodeId types against being NULL.
=> Extend function UA_NodeId_isNull

examples/custom_datatype/client_types_custom.c, examples/custom_datatype/server_types_custom.c, include/ua_client_config.h, include/ua_server_config.h, include/ua_types.h, plugins/ua_config_default.c, src/client/ua_client.c, src/server/ua_nodes.c, src/server/ua_server_binary.c, src/ua_types.c, src/ua_types_encoding_binary.c, src/ua_types_encoding_binary.h, tests/check_types_custom.c, tests/check_types_memory.c, tests/fuzz/fuzz_binary_decode.cc, tests/server/check_server_readspeed.c, tools/generate_datatypes.py
This PR makes the array of custom types a *linked list of arrays of custom types*.
So we have a bit more flexibility. For example for adding types that come from the nodeset compiler.
See #2061.
This is a breaking change of the config API.
Please review @open62541/open62541-core @Pro @ichrispa .
=> Custom types at runtime

src/ua_securechannel.c
GCC version 4.9.x complains about variable finalLength (compiler setting -Wmaybe-uninitialized)
=> Fix-gcc-V4.9.x-warning -maybe-uninitialized

plugins/ua_securitypolicy_basic128rsa15.c, plugins/ua_securitypolicy_basic256sha256.c, src/server/ua_services_session.c
A client are allowed to include a partitial or a complete certificate
chain both in the OpenSecureChannelRequest and in the
CreateSessionRequest. When comparing the certificates while
processing the CreateSessionRequest this must be considered.
The comparition has been updated to use the compareCertificate
function of the channelModule of the SecurityPolicy plugin API.
=> Compare end certificates of channel and CreateSessionRequest

src/server/ua_server.c, src/server/ua_subscription_datachange.c
PC-lint complains about the naming:
Declaration of symbol 'index' hides symbol 'index(const char *, int)' (file ..\arm-none-eabi-gcc\4.5.2\arm-none-eabi\include\string.h)
=> Fix PC-lint warning: Declaration of symbol 'index' hides symbol 'index(...)'

tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py
The valueRank for data types is currently not used in the nodeset compiler
and thus we can hide the warning. The rest of the code still works.
This valueRank attribute should then later on be used when creating
data type definitions on the fly with fixed array size instead of malloc
arrays.
See also #2137
=> NodesetCompiler: Hide valueRank not supported warning

tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py
The valueRank for data types is currently not used in the nodeset compiler
and thus we can hide the warning. The rest of the code still works.
This valueRank attribute should then later on be used when creating
data type definitions on the fly with fixed array size instead of malloc
arrays.
See also #2137
=> [0.3 Backport] NodesetCompiler: Hide valueRank not supported warning

tools/nodeset_compiler/nodes.py, tools/nodeset_compiler/nodeset.py
=> NodesetCompiler: Correctly handle namespace mapping for encoded objects.

plugins/ua_nodestore_default.c
The newEntry variable in UA_NodeMap_insertNode is named the same as a function which produces shadow errors in some compilers. Now, the name is similar to UA_NodeMap_replaceNode.
This is for issue #2216
=> Rename newEntry that produces shadow errors in some compilers

src/client/ua_client_subscriptions.c
if requestHeader timeoutHint is '0' the corresponding server should treat it as no timeout, but some server misbehave and really treat it as zero timeout, which is of course a fault in the server.
To make the client more tolerant a large timeoutHint, i.e. 60000, would help.
=> some server have problems with RequestHeader timeoutHint=0

tests/server/check_subscription_events.c, tests/testing-plugins/thread_wrapper.h
If the tests run a server in a separate thread, server calls made in the main thread should use a mutex. (Not using one could lead to bugs when, for example, an event is triggered while the events are being moved).
=> Mutex wrapper for unit testing

CMakeLists.txt, arch/posix/ua_architecture.h, arch/ua_architecture_base.h, arch/vxworks/ua_architecture.h, arch/wec7/ua_architecture.h, arch/win32/ua_architecture.h, tests/testing-plugins/testing_clock.c
With this change someone can override malloc/free/realloc/calloc with his own implementation by using preprocessor defines.
An example usage is found in: #2188
=> [Review] Architecture: Allow overriding memory allocation functions

include/ua_types.h, src/ua_types.c, tools/generate_datatypes.py
_deleteMembers is so common that we cannot deprecate it. Possibly after
the 0.4 release cycle.
=> Stack: Add _clear as a shorter alternative to _deleteMembers

.travis.yml, tools/appveyor/install.ps1, tools/travis/travis_linux_before_install.sh
Appveyor (and windows builds) showed warnings for missing .pdb files in libcheck.
This uses the new release which also includes the .pdb
Also, this includes another fix for travis to try to flush stdout before exiting on error
=> CI: Use debug symbols for check to avoid missing .pdb warnings

.travis.yml, tools/appveyor/install.ps1
Appveyor (and windows builds) showed warnings for missing .pdb files in libcheck.
This uses the new release which also includes the .pdb
Also, this includes another fix for travis to try to flush stdout before exiting on error
Backport of #2196
=> [0.3] CI: Use debug symbols for check to avoid missing .pdb warnings

tools/generate_datatypes.py
Only the inserted dataTypes in list whitelistFuncAttrWarnUnusedResult will be generated with the define UA_INTERNAL_FUNC_ATTR_WARN_UNUSED_RESULT in front of the function declaration.
In file ua_types_generated_handling.h, for example:
```C
UA_INTERNAL_FUNC_ATTR_WARN_UNUSED_RESULT static UA_INLINE UA_StatusCode
UA_ByteString_copy(const UA_ByteString *src, UA_ByteString *dst) {
return UA_copy(src, dst, &UA_TYPES[UA_TYPES_BYTESTRING]);
}
```
=> Prepare python script for usage of define UA_INTERNAL_FUNC_ATTR_WARN_UNUSED_RESULT

CMakeLists.txt
Compiling the `open62541  v0.4` with `UA_ENABLE_MULTITHREADING=ON`  gives errors like
`open62541.c:4965:5: error: unknown type name 'UA_DelayedCallback'
UA_DelayedCallback delayedCleanup;` 
With both options UA_ENABLE_DISCOVERY=ON and UA_ENABLE_MULTITHREADING=ON the open62541 library doesn't compile anymore because the `ua_discovery_manager.h` file will be inserted at position `5` into internal_headers and that is to early.
inserting `ua_discovery_manager.h` at position `13` works, but I don't know if this has other unwanted side effects?!
=> fix missing types during compilation with UA_ENABLE_MULTITHREADING

appveyor.yml, tools/appveyor/build.ps1
=> CI: Remove VS2015 from Appveyor builds to save build time

src/server/ua_services_attribute.c
Timestamps from DataValues will never be set on arrival and will be set to now when read.
This is wrong behaviour.
DataValues server timestamps should be set when the values arrive in the server.
While a client read data, the timestamps should not be altered.
=> Bugfix: Fix server timestamps

src/server/ua_services_attribute.c
Timestamps from DataValues will never be set and will be set to now when read.
This is wrong behaviour.
DataValues server timestamps should be set when the values arrive in the server.
While a client read data, the timestamps should not be set to now.
=> [0.3] Bugfix: Fix server timestamps

src/server/ua_services_discovery_multicast.c
This fixes the case, that servername + hostname have a length of 61 or 62.
outServiceDomain is a buffer of length 63 + 24
so maxLen is 63
When Servername + hostname in total are 61 or 62 UA_snprintf will cut off the last (two) letter(s).
f.e.
servername:
123456789_123456789_123456789_123456789_123456789_123456789
hostname:
abc
will result in 
123456789_123456789_123456789_123456789_123456789_123456789-a\0
and the next UA_snprintf will insert after the \0
=> Fix: mdns record when strlen(hostname) + strlen(servername) is 61 or 62

CMakeLists.txt
Backport of #2292 and documentation on how to install open62541.
This emphasizes that we recommend installing without amalgamation, as discussed here https://github.com/open62541/open62541/pull/2292#discussion_r241106424
=> [0.3] Backport and further CMake install improvements

src/server/ua_services_attribute.c
The number of array dimensions must be set to 1 only if the value is not scalar and if the array dimensions size is 0. Omitting the second check breaks the compatibility check for arrays with more than one dimension.
=> Fix value rank compatibility check

CMakeLists.txt
=> CMake: Add missing ua_architecture headers

tests/check_securechannel.c
The SecureChannel tests manually set the encryption mode to EncryptAndSign.
This broke the test when ecnryption is disabled.
=> Repaire SecureChannel tests

plugins/ua_nodestore_default.c, tests/server/check_nodestore.c
- The nodestore is a lot cleaner now.
- Using the same datastructure in several places reduces cognitive overhead
- Small speed improvements on by box
=> Nodestore: Use zip tree instead of hashmap for the nodestore

CMakeLists.txt, tests/pubsub/check_pubsub_connection_udp.c, tests/server/check_historical_data.c
Fixes #2330
See https://github.com/open62541/open62541/issues/2330#issuecomment-451135876 for a detailed error description
=> Fix Historical Data Unit Test random failure

.clang-format, src/server/ua_discovery_manager.c, src/server/ua_discovery_manager.h, src/server/ua_server_discovery_mdns.c, src/server/ua_services_discovery_multicast.c
The spec says that mDNS should announce the hostname, and this hostname should be used for the discovery URL.
An IP address for the SRV.hostname is not allowed.
Up to now we took the announced IP address and tried to resolve it to a hostname, which may lead to various issues (e.g. #2322, #2212). This procedure was done for every received mDNS record.
=> mDNS: Use hostname instead of resolving IP address

tests/client/check_client.c, tests/client/check_client_securechannel.c, tests/client/check_client_subscriptions.c, tests/encryption/check_encryption_basic128rsa15.c, tests/encryption/check_encryption_basic256sha256.c, tests/fuzz/corpus_generator.c, tests/server/check_accesscontrol.c
This PR is also an RFC.  :-)
Is there a good reason to allocate the bool on the heap? I saw it being done like this in a few places. I would tend to convert them all but want to collect feedback first.
=> Do not dynamically allocate a simple bool

src/server/ua_server_discovery_mdns.c
Handle path== NULL when parsing a mdns message (which was not sent by open62541).
=> Fix: Segfault when path == NULL

CMakeLists.txt, tools/travis/travis_linux_script.sh
Remove hardcoded optimization level for NS0 file. Fixes #2315 
This is for now a test to see how fast everything compiles.
=> CI: Remove NS0 hardcoded optimization

CMakeLists.txt
Follow up of #2320
We need to disable NS0 optimization on appveyor, otherwise these builds take too long (almost an hour).
=> CI: Disable NS0 optimization on appveyor

examples/nodeset/CMakeLists.txt, examples/nodeset/server_testnodeset.c, examples/nodeset/testnodeset.csv, examples/nodeset/testnodeset.xml, examples/nodeset/testtypes.bsd, src/ua_types_encoding_binary.h, tests/nodeset-compiler/CMakeLists.txt, tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c, tests/nodeset-compiler/testnodeset.csv, tests/nodeset-compiler/testnodeset.xml, tests/nodeset-compiler/testtypes.bsd, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/schema/datatypes_minimal.txt
This pr shold remove the necessity of calling ua_encodebinary during namespace generation with the nodeset compiler.
I have added a testnodeset in examples/nodeset. I will move this to tests folder and write some tests.
=> [REVIEW] #1914 - remove binary encoding from namespace generation

include/ua_plugin_securitypolicy.h, include/ua_server_config.h, plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c, plugins/securityPolicies/ua_securitypolicy_basic256sha256.c, plugins/ua_config_default.c, src/server/ua_server.c, src/server/ua_server_binary.c, src/server/ua_services_discovery.c, src/server/ua_services_session.c
Currently the SecurityPolicies supported by the server are strongly
tied together with the endpoints. To be able to reuse the
SecurityPolicy instances of the server also in the Access Control
plugin to handle encrypted passwords the SecurityPolicies are moved
to the server config struct.
=> WIP: Separate SecurityPolicies from Endpoints in the server

include/ua_plugin_access_control.h
Every header should stand for itself. 
Otherwise include order in other locations mater.
=> access_control: Add missing ua_server.h include.

examples/encryption/client_basic128rsa15.c, examples/encryption/client_basic256sha256.c
UA_ByteStrings aren't refcounted. The call to UA_ByteString_delete()
surely frees the memory. It does not derefence a string.
=> Remove comments - I felt to be misleading

src/client/ua_client_subscriptions.c
If the OPC-UA server has closed the session without the client knowing, the
subscription should be deleted.
We observed this behavior with open62541 UA Client against a Beckhoff twincat OPC-UA server when the connection was lost (briefly). The bugfix simply checks if the subscription is already removed on the open62541 client side (and some outstanding publish background checks are coming in) or if the subscription is still active on the client but closed on the server.
=> Bugfix: delete subscriptions that are closed by the server

src/pubsub/ua_pubsub_networkmessage_json.c, src/ua_types_encoding_json.c, src/ua_types_encoding_json.h
- For nested structured types the correct _UA_DataType_ is now forwarded in _decodeEntry_.
- The correct size is now set for decoded arrays.
=> JSON: fix decoding of structured types

arch/win32/ua_architecture.h
Fix https://github.com/open62541/open62541/issues/2406
=> Correctly cast third argument of recv in win32

CMakeLists.txt
This is a follow-up fix for #2400 
It should fix current build errors on master:
https://travis-ci.org/open62541/open62541/jobs/487317314#L7549
=> CI: Only use sanitize leak if valgrind disabled

examples/CMakeLists.txt, examples/discovery/server_register.c
Registering server complains that the port 4840 is already in use (as the LDS is
running there).
./discovery_server_register
[...]
[2019-02-04 22:45:20.070 (UTC+0100)] info/userland      Node read the.answer
[2019-02-04 22:45:20.070 (UTC+0100)] info/userland      read value 42
[2019-02-04 22:45:20.070 (UTC+0100)] warn/network       Error binding a server socket: Address already in use
[2019-02-04 22:45:20.070 (UTC+0100)] warn/network       Error binding a server socket: Address already in use
[2019-02-04 22:45:20.070 (UTC+0100)] info/network       TCP network layer listening on opc.tcp://prokyon:4840/
=> Resolve port conflict

.travis.yml, tools/travis/travis_linux_before_install.sh, tools/travis/travis_linux_script.sh
A bunch of small changes to the Travis build, trying to make things more obvious without changing the actual builds too much:
- fix some misleading output in the build script
- make the static code analysis build a special build like the others
- group the pre-installs in .travis.yml by the feature they are needed for and remove unnecessary ones
- use Travis variables for setting compilers (reduce number of specific env variables for jobs)
- only set env variables for jobs that are needed (i.e. differ from default)
Things that still could be done (considered too disruptive for this PR):
- rename MINGW to CROSS (as it also activates cross builds for linux and raspi)
- create documentation only in the build(s) that actually use it (reduces pre-installs)
Note: The lower part of the diff …
=> Travis clean up

arch/vxworks/ua_architecture.h
In both the POSIX ( http://pubs.opengroup.org/onlinepubs/009695299/basedefs/time.h.html ) and C11 ( https://en.cppreference.com/w/c/chrono/timespec ) standards, the struct timespec structure and the nanosleep function are defined in the time.h header. 
Depending on the specific VxWorks version, the time.h header could be already transitively included by one of the other headers,  but explicitly adding the time.h include makes sure the `UA_sleep_ms` macro will work correctly on all possible versions.
=> Include time.h when struct timespec is used

tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py
This fixes the nodeset compiler for some very special case:
If there's a variable with an ExtensionObject Value, the namespace of the DataType ID was not correctly mapped.
E.g. 
```xml
<UAVariable NodeId="ns=1;i=15399" BrowseName="InputArguments" ParentNodeId="ns=1;i=15398" DataType="i=296" ValueRank="1">
<DisplayName>InputArguments</DisplayName>
<References>
<Reference ReferenceType="HasTypeDefinition">i=68</Reference>
<Reference ReferenceType="HasProperty" IsForward="false">ns=1;i=15398</Reference>
</References>
<Value>
<ListOfExtensionObject xmlns="http://opcfoundation.org/UA/2008/02/Types.xsd">
<ExtensionObject>
<TypeId>
<Identifier>i=297</Identifier>
</TypeId>
<Body>
<Argument>
<Name>Name</Name>
<DataType>
<Identifier>i=12</Identifier>
</DataType>
<ValueRank>-1</ValueRank> …
```
=> NodesetCompiler: Correctly map namespace for extension object type id

arch/ua_architecture_definitions.h, arch/wec7/ua_architecture.h, arch/win32/ua_architecture.h
=> Fix wrong MSVC version check and avoid redefinition of _CRT_SECURE_NO_WARNINGS

CMakeLists.txt
Lintian throws an error when trying to Installi bytecompiled python files.
If the `.pyc` files really needed one should create them at package installation time in a postins script.
=> don't install bytecompiled python files

src/server/ua_services_session.c
- Test case Err-009.js in Session services/Session base in CTT fails
due to matching of userToken types against configured endpoints
- The error status code to be returned is BadIdentityTokenInvalid
(0x80200000) but obtained BadIdentityTokenRejected (0x80210000)
- This fix will resolve the test and returns the expected status code
(BadIdentityTokenInvalid - 0x80200000)
Signed-off-by: Jayanth Velusamy <jayanth.v@kalycito.com>
This pull request resolves #2418
=> [FIX] Return proper status code for unsupported UserToken types

CMakeLists.txt, doc/installing.rst, tools/travis/travis_linux_script.sh
Fix https://github.com/open62541/open62541/issues/2415 . 
I also added a `add_library(open62541::open62541 ALIAS open62541)` command to make sure that `open62541::open62541` is also available in the open62541's build itself. This is useful when `open62541` is part of a bigger project by being vendored (or fetched via [CMake's FetchContent module](https://cmake.org/cmake/help/v3.11/module/FetchContent.html)) and included with `add_subdirectory`. See https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#using-a-library-defined-in-the-same-cmake-tree-should-look-the-same-as-using-an-external-library for more details.
=> Add NAMESPACE open62541:: to exported CMake targets

tools/generate_datatypes.py
I faced the problem, that types derived from the builtin types like UInt32 where translated to a C representation of ByteString.
The `generate_datatypes.py` script uses `nodeset_compiler/opaque_type_mapping.py` to lookup how to handle such types, that have a direct representation in C. 
It would have been necessary to add custom types to this list, however modifying this file directly is not a good idea. Therefore I added a switch `--opaque-map` to `generate_datatypes.py` which loads the mapping from a JSON file which must have contents like this:
```javascript
{
// Note: In the actual JSON, comments are not allowed
// Custom type name "Duration10ms"
"Duration10ms": {
// Mapped to builtin type: Int32 (Node-ID: ns=0;i=6)
"ns": 0,
"id": 6,
"name": "Int32"
},
"Duration32": {
"ns": 0,
"id": …
```
=> Review: Added custom opaque type mappings

include/ua_types.h
Shrink the size from 96 bytes to 80 bytes by reordering members to avoid padding
(64bit linux).
=> Decrease the size of UA_DataValue

examples/custom_datatype/server_types_custom.c
Makes this example run valgrind clean.
==7424== HEAP SUMMARY:
==7424==     in use at exit: 0 bytes in 0 blocks
==7424==   total heap usage: 96,908 allocs, 96,908 frees, 190,708,768 bytes allocated
vs.
==5408== HEAP SUMMARY:
==5408==     in use at exit: 96 bytes in 2 blocks
==5408==   total heap usage: 96,908 allocs, 96,906 frees, 190,708,768 bytes allocated
==5408==
==5408== 96 (48 direct, 48 indirect) bytes in 1 blocks are definitely lost in loss record 2 of 2
==5408==    at 0x4C2DBF6: malloc (vg_replace_malloc.c:299)
==5408==    by 0x40312A: main (server_types_custom.c:68)
==5408==
==5408== LEAK SUMMARY:
==5408==    definitely lost: 48 bytes in 1 blocks
==5408==    indirectly lost: 48 bytes in 1 blocks
before
=> Free all allocations before exiting

src/client/ua_client.c
The UA_Client did not use custom data types stored in UA_ClientConfig.customDataTypes to decode the stream.
=> Fix: UA_client always uses custom datatypes when decoding objects

tools/nodeset_compiler/backend_open62541.py
Fix #2487 
When sorting, a set was used which produced a on stable sort. I changed this to use a list.
=> Stabilize the order of node generation code produced by the Nodeset Compiler

plugins/ua_config_default.c
The default configuration of a connection is hardcoded to 65535. In some devices with low memory this is a problem. 
This PR adds the possibility to set the default values as preprocessor variables, and if not provided, use the old ones.
Also, the client connection uses the default connection variable instead of setting it field by field
=> Make default connection configurable

CMakeLists.txt, examples/CMakeLists.txt, tests/CMakeLists.txt, tests/fuzz/CMakeLists.txt
Since CMake ~3.0, the `target_include_directories` can be used to specify the include directories that a are part of the CMake target [`INTERFACE_INCLUDE_DIRECTORIES`](https://cmake.org/cmake/help/v3.0/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html), i.e. the include directories that must be used in compilation if another target links to it. See https://cmake.org/cmake/help/v3.10/manual/cmake-buildsystem.7.html#build-specification-and-usage-requirements for more details. 
For the `open62541` target exported in installation tree, setting `INTERFACE_INCLUDE_DIRECTORIES` was handled by [INCLUDE DESTINATION](https://github.com/open62541/open62541/blob/ab04d497b1f2b6edb846926aaf4773033bd8e247/CMakeLists.txt#L1084) option of the `install(TARGETS ..)` command. However, it is also useful to properly …
=> Properly use target_include_directories to propagate include directories

CMakeLists.txt, examples/nodeset/CMakeLists.txt, tools/cmake/macros_public.cmake, tools/generate_datatypes.py
If there's a type definition in the .bsd file, but there is no corresponding
entry in the .csv, then the old code silently set the type id to NODEID_NULL.
This will then cause the server to fail on a later stage. To avoid this,
the datatype generator should check this immediately and inform the user.
=> DatatypeGenerator: Check for valid node id in csv

CMakeLists.txt, examples/CMakeLists.txt, examples/nodeset/CMakeLists.txt, tools/travis/travis_linux_script.sh
In this PR the examples are defined as subproject to open62541. One can build the examples  standalone or, as before, during the build of the whole open62541 project.
It's assumed that open62541 lib, examples and tools are already installed at a standard place.
The following workflow builds the examples standalone
```
```
@Pro @ralphlange 
I've decided to make a new PR instead modifying #2451 
Please review and/or comment ...
=> [REVIEW] build examples as subproject

.travis.yml, CMakeLists.txt, Dockerfile, debian/control, doc/building.rst, open62541.spec, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodeset.py
Python3 is now very common. We can expect it for the dev environments
where code is generated. Remove workarounds and the python-six dependency.
=> Remove dependency on python-six

include/ua_util.h, plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c, plugins/securityPolicies/ua_securitypolicy_basic256sha256.c
I just found this security issue while skimming the code. Maybe there are similar issues in other parts of the code too.
=> Use constant time memcmp to verify signatures to mitigate timing attacks

src/ua_types_encoding_json.c, tests/check_types_builtin_json.c
The OPC UA specification 1.04 part 6 does not allow boolean values
encoded as "null". Boolean fields with null values in structs must
be omitted in the resulting JSON object, which is different to an
encoded null value.
=> JSON: raise error when decoding Boolean null values

src/ua_types_encoding_json.c, tests/check_types_builtin_json.c
According to the OPC UA specification 1.04 part 6 paragraph 5.4.2.3:
"Int64 and UInt64 values shall be formatted as a decimal number encoded
as a JSON string."
=> JSON: encode UInt64 and Int64 as string

src/ua_types_encoding_json.c, tests/check_types_builtin_json.c, tests/pubsub/check_pubsub_encoding_json.c
The OPC UA specification 1.04 part 6 at paragraph 5.4.2.6 does not
define any restrictions of the fraction part of ISO 8601. To support
the whole precison of DateTime we need to support at least 100ns.
=> JSON: support nanoseconds when encosing/decoding DateTime

src/ua_types_encoding_json.c, tests/check_types_builtin_json.c
According to the OPC UA specification 1.04 part 6 paragraph 5.4.2.18:
"If a field has a null or default value it is omitted."
=> JSON: do not encode fileds of DataValue with default value

tools/travis/travis_linux_script.sh
This reenables the upload to codecov.io
=> CI: Use absolute path in PATH variable to remove warnings from gcov

CMakeLists.txt, examples/CMakeLists.txt, tools/cmake/CompilerFlags.cmake
Hey,
looked into #1680. Checked provided info ([1]), but also additional sources.
- Added functionality to check if flag is supported by compiler.
- Activated stack-protector-strong (should be default anyway) for the normal build. Not sure why Release was built without.
- Added additional run-time buffer overflow detection (which needs at least -O1).
- (Therefore) Activated -O2 as default Release optimization.
- Added Link-Time-Optimization (-flto)/Inter-Procedural-Optimization (IPO).
- Added two future compiler checks, which currently signalize their activity with a cmake warning.
- Added Release unit testing on Travis.
Any further ideas?
[1] https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc/
[2] https://blog.regehr.org/archives/1307
[3] …
=> CMake: enable IPO and additional hardening

.travis.yml, tools/travis/travis_linux_after_success.sh, tools/travis/travis_linux_before_install.sh, tools/travis/travis_linux_script.sh
Hey,
since #2559 focuses on a more convenient way by adding comment support,
this is a pre-stage and just breaks the CI if the code format does not align with
the specified clang-format style.
=> Run clang-format check for PR diff

.clang-format, .travis.yml, tools/travis/travis_linux_script.sh
This PR relaxates the requirement that all the PRs need to be formatted according to our clang-format style.
Travis is set to allow failure for this build, but still tests it to give feedback.
=> Relaxate the clang-format requirements for now and allow failure

CMakeLists.txt, plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c, plugins/securityPolicies/ua_securitypolicy_basic256.c, plugins/securityPolicies/ua_securitypolicy_basic256sha256.c, plugins/securityPolicies/ua_securitypolicy_mbedtls_common.c, plugins/securityPolicies/ua_securitypolicy_mbedtls_common.h
For users of the amalgamated distribution, it would be a nice feature to be able to enable and disable security support at build time.
=> Always include security policies in the amalgamated source file

include/ua_server_config.h, plugins/ua_config_default.c, src/server/ua_subscription.c
The Micro Embedded UA profile allow devices to not implement the
retransmission queue of DataChange Subscriptions. Previously there 
has been no possibility to disable this queue. Disabling the queue
can save some memory on a resource constrained device.
=> Added possibility to disable retransmission queue of sessions

src/server/ua_server_binary.c, tests/testing-plugins/testing_clock.c
- The server application should check the timestamp value in the
header according to CTT test cases in the version 1.03.341.385
- Timestamp is checked in the request headers of following APIs
Service_BrowseNext(), Service_TranslateBrowsePathsToNodeIds(),
Service_RegisterNodes(), Service_UnregisterNodes()
- This fix will resolve the following test cases
- ViewTranslateBrowsePath -> Err-024.js
- ViewRegisterNodes -> Err-009.js, Err-014.js
- View Minimum Continuation Point 01 -> Err-010.js
Signed-off-by: Jayanth Velusamy <jayanth.v@kalycito.com>
=> [FIX] Check timestamp values in request header

arch/posix/ua_architecture_functions.c, arch/ua_network_tcp.h, deps/ziptree.h, include/ua_client.h, include/ua_client_subscriptions.h, include/ua_server.h, include/ua_util.h, src/client/ua_client.c, src/client/ua_client_internal.h, src/client/ua_client_subscriptions.c, src/client/ua_client_worker.c, src/pubsub/ua_pubsub_ns0.c, src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_server_ns0.c, src/server/ua_services_discovery_multicast.c, src/server/ua_services_subscription.c, src/server/ua_services_view.c, src/server/ua_subscription.h, src/server/ua_subscription_datachange.c, src/server/ua_subscription_monitoreditem.c, src/ua_securechannel.c, src/ua_util.c
Running clang-format changes the files so that build is not possible anymore without those fixes.
This PR only includes some small reformatting. No change in functionality.
@bbara this is part of your #2558
=> Stack: Various small reformatting to fix build after running clang-format

plugins/ua_config_default.c, src/pubsub/ua_pubsub_networkmessage_json.c, src/ua_types_encoding_json.c
I found some malloc and free functions that should be UA_malloc and UA_free to keep the memory allocation functions unified throught the code
An issue though, is the pressence of malloc in deps/base64.c This I cannot change because, from what I understood, it works kind of as an independent file. I'm not sure the dependencies of other files and projects on this file.
This mismatch in base64.c might cause some problems when freeing the memory allocated there
=> Unify memory allocation calls

src/server/ua_nodes.c, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/nodes.py
See https://github.com/open62541/open62541/issues/2627
With this commit we support optional display name in the NodeSet2.xml.
If it is not given, we take the name part of the BrowseName.
This is part of #2630
=> Nodeset: Support empty display name and use BrowseName as default value

include/open62541/server_config.h, src/server/ua_server_internal.h, src/server/ua_services_subscription.c, src/server/ua_session.c, src/server/ua_session.h, src/server/ua_subscription.c, src/server/ua_subscription.h
By making the resource limitations for subscriptions and monitored
items global in the server, the sessions can share the resources
of the server instead of splitting the resources evenly over the
supported sessions and subscriptions.
This change allow servers to support profile requirements with less
resources. E.g. the Embedded UA server profile sets minimum
requirements on number of subscriptions for a session and number of
monitored items for a subscription. But the profile does not require
all sessions or all subscriptions to meet these requirements
concurrently.
=> [Review] Making the resource limitations of subscriptions global

tools/certs/create_self-signed.py, tools/certs/localhost.cnf
- Currently generated server certificate (server_cert.der) has
hostname set to localhost and IP Address set to 127.0.0.1
- In new CTT, using "localhost" as hostname in a certificate or
EndpointUrl is not allowed
- So modified Python script and the corresponding configuration
file (localhost.cnf) to dynamically identify the network
interfaces and the corresponding IP addresses
Signed-off-by: Asish Ganesh <asish.g@kalycito.com>
=> [CTT Fix] Remove localhost from hostname in server certificate

plugins/ua_config_default.c
- Currently security level value not initialized corresponding to
the message security mode
- In CTT, "Security Certificate Validation" test cases gets skipped
since security level value is zero for all security modes
- So modified the security level value corresponding to the message
security mode
Signed-off-by: Asish Ganesh <asish.g@kalycito.com>
=> [FIX] Add security level value for corresponding message security mode

arch/common/ua_lwip.h, arch/eCos/ua_architecture.h, arch/network_tcp.c, arch/posix/ua_architecture.h, arch/vxworks/ua_architecture.h, arch/wec7/ua_architecture.h, arch/win32/ua_architecture.h, examples/discovery/server_multicast.c, examples/discovery/server_register.c, include/open62541/architecture_functions.h
Fixes #2416
Adds the possibility to use port `0` in the config, which means the OS will assign a random port.
=> Stack: Add support for dynamic port assigning

CMakeLists.txt, doc/nodeset_compiler.rst, plugins/ua_config_default.c, src/server/ua_nodes.c, src/server/ua_services_nodemanagement.c, tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c, tools/cmake/macros_public.cmake, tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_datatypes.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/nodes.py, tools/nodeset_compiler/nodeset.py, tools/nodeset_compiler/nodeset_compiler.py, tools/schema/Opc.Ua.NodeSet2.PubSubMinimal.xml
This patch extends the nodeset compiler to support all possible attributes of the VariableType node class.
Using the DataType id from the xml description instead of BaseDataType causes an error when adding two nodes from Opc.Ua.NodeSet2.xml (i=17306 and i=17292 fail with "AddNodes: The value is incompatible with the datatype of the VariableType").
Both VariableType nodes use String as DataType attribute and are a subtype of i=16309. i=16309 has DataType i=862 which is a subtype of Struct.
Could there be something wrong with the type checking in ua_services_nodemanagement.c?
Page 30 of part 3 of the spec states "The VariableType NodeClass also defines a set of Attributes that describe the default or initial value of its instance Variables". Doesn't this imply that the DataType attribute …
=> Add all attributes of VariableType nodes in the nodeset compiler

src/server/ua_discovery_manager.c, tests/server/check_discovery.c
This (new) test case failed due to a null pointer access.
```
START_TEST(Server_new_delete) {
UA_Server *pServer = UA_Server_new();
configure_lds_server(pServer);
UA_Server_delete(pServer);
}
END_TEST
```
~~Fix will (hopefully) added later this day by me, when I found the exact reason.~~
Fix is added
=> Fix deleting a configured uninitialized  mdns server

include/ua_config.h.in, plugins/ua_log_socket_error.h
stdbool.h is only available in MSVC 2013 and later. A C++ build using MSVC 2012 is possible if the include is removed.
=> Fix issues with MSVC 2012

.gitignore, plugins/include/open62541/server_config_default.h, plugins/ua_config_default.c
This splits the monolithic `UA_ServerConfig_setXxx` methods into
- `UA_SeverConfig_setBasics` which sets up an initial configuration without any configured NetworkLayer, SecurityPolicy and Endpoint.
- `UA_ServerConfig_addNetworkLayerTCP`
- `UA_ServerConfig_addSecurityPolicyXxx`
- `UA_ServerConfig_addEndpoint`
This allows for a more fine grained configuration, if required.
This addresses #2692
=> Make server configuration more flexible

examples/server_ctt.c, plugins/ua_pki_default.c, src/ua_connection.c
This PR contains a implementation for passing trusted certificates and CRL files from command line argument.
**Usage:**
1. Create a directories `trustList` and `crl`
2. Copy the trusted certificates to `trustList` folder and revocation list to `crl` folder
3. Run server_ctt using the following command
`./server_ctt server_cert.der server_key.der -t trustList/ -c crl/`
4. Tested with certificates in CTT project (ver 1.03.341.389) `ctt_project_folder\PKI\copyToServer\ApplicationInstance_PKI`
**TODO:**
1. Make it robust
2. Cleanup hard-coded items
3. Windows build
@jpfr Shall we have a separate branch for this PR?
Regards
opcua-tsn-team-kalycito
=> Certificate fixes

include/open62541/plugin/securitypolicy.h
Missing UA_EXPORT that causes problems when building a shared library in windows.
=> Fix: Add UA_EXPORT to UA_SECURITY_POLICY_NONE_URI for shared builds

plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c, plugins/securityPolicies/ua_securitypolicy_basic256.c
- At present if trusted client certificate having key
encrypted with sha2-4096 is passed the response
received is BadCertificateUseNotAllowed
- According to CTT (Test case 052.js in Security
Certificate Validation) the expected result is Good
- Fixed the same by changing the max key length value
Signed-off-by: Asish Ganesh <asish.g@kalycito.com>
=> [CTT Fix] Connect using trusted client certificate

src/server/ua_server.c, src/server/ua_server_internal.h, src/server/ua_server_ns0.c
Fix namespace 1 initialisation problem that was introduced in commit fd08d012d95b5837c90b18ba3fd7230b2c4d8ef6.
Fixes #2692
=> Fix setup of namespace 1 URI

.travis.yml, tools/travis/travis_osx_script.sh
Travis support says:
the `hostname` command is actually a super ephemeral way to change it. There’s a different way:
`sudo scutil --set HostName <new host name>` which is more permanent and potentially more resilient
=> Travis: Different way to set custom hostname on OSX builds

include/ua_client_subscriptions.h, src/client/ua_client_subscriptions.c
A proposed fix for issue #2688
Setting the client handle from the monitored item id before sending the
modify request to the server solves that problem.
Note: The same issue should also exist on master.
=> Fix modification of monitored items

include/open62541/client_subscriptions.h, src/client/ua_client_subscriptions.c
If a client handle is modified after creation, the new value is used in
data change notifications from the server. If the new handle doesn't match
the initial handle, the client is unable to dispatch the data change
notification to the callback associated with the monitored item.
Client handles supplied by the API user during monitored item creation
are replaced internally by a counter value and there is no way to retrieve
the client handle for a monitored item after its creation.
Setting the client handle from the monitored item id before sending the
modify request to the server solves that problem.
=> [Cherry-Pick on master] Fix modification of monitored items

doc/CMakeLists.txt
Replaces #2552 
With this code, the copy command is replaced with a custom command which makes sure that the dependencies are correctly set.
=> CMake: Cleanup of cmake code for doc generation

src/server/ua_server_binary.c, src/server/ua_services_session.c
@cpipero uncovered the issue and proposed the fix in #2805.
=> Session: A NULL or empty UserIdentityToken should be treated as Anonymous

src/server/ua_server_binary.c, src/server/ua_server_internal.h, src/server/ua_server_utils.c, src/server/ua_services.h, src/server/ua_services_attribute.c, src/ua_securechannel.c, tests/server/check_server_readspeed.c
The savings in memory allocations are not worth the additional
complexity. The services now are uniformly defined.
=> Services: Remove the in-situ service special case

CMakeLists.txt, tools/cmake/open62541Config.cmake.in
I tried using the (cross-)compiled 0.3.0 in another CMake project, which failed as the config file was not found automatically. This fixes this and a few minor issues along the way.
=> CMake fixes for branch 0.3

tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c, tools/nodeset_compiler/backend_open62541_nodes.py
PR #1810 caused to loose the fix done in PR #1978...
I've re-introduced that fix and added a unit test to avoid this in the future.
In our case the problem showed in two OPC-UA Client (“Unified Automation UaExpert” and “Integration Objects OPC UA Explorer”):
when trying to do a Method Call, no Input / Output Arguments were shown (UA Explorer told they’re Opc.Ua.Matrix instead of array).
=> For 1 dimension arrays, initializing arrayDimensionsSize may confuse some OPC clients.

examples/pubsub/tutorial_pubsub_subscribe.c, src/pubsub/ua_pubsub.c
- Corrected datatype Int32 to Int64 inside fillTestDataSetMetaData function
- Resolve segmentation fault when removing ReaderGroup as suggested in #2849
=> Subscriber fix

src/server/ua_services_session.c
Tested in the CTT conformance unit "Security User Name Password"
=> Session: Check that encryption algorithm id matches policy

doc/CMakeLists.txt
With **cmake 3.0.2** the command **cmake -E copy ...** doesn't copy a list of files but only single files therefore the **add_custom_command** fails on i.e. debian8.
If the **DEPENDS in add_custom_command** is not important here and we want to be compatible with **cmake 3.0.2** the easiest cure would be to go back to the **file(COPY...** command.
=> Fix: compatibility with CMake version 3.0.2

src/pubsub/ua_pubsub.c, tests/CMakeLists.txt, tests/pubsub/check_pubsub_publish_uadp.c
Added a new UADP message generation testcase. This unit test publishes messages and register itself as subscriber. The received messages are decoded and some fields checked. This PR contains also an small bugfix, which affected the number of embedded DataSetMessages within one NetworkMessage.
=> PubSub UADP test and message generation fix

src/server/ua_server_ns0.c
This pull request contains a fix for _ServerDiagnostics_ test case in CTT
- Though it is disabled by default (_EnabledFlag_= False), client shall modify the value (based on access control) as the attribute _AccessLevel_ is set at _Current Read/Write_
- One of the test case in CTT (Subscription_Minimum_1/002.js) shall modify the value to _true_ check for diagnostics data
- Hence modified the _AccessLevel_ of _EnabledFlag_ to _Read_ only (Specification Part-5 - pg.no-11 (PDF pg.no-29))
=> [CTT] Set access level to read-only for ServerDiagnostics

tools/cmake/macros_public.cmake, tools/generate_datatypes.py
Fixes #2896
Exemplary call for GDS:
```
ua_generate_datatypes(
NAME "types_gds"
TARGET_SUFFIX "types-gds"
NAMESPACE_IDX 0
FILE_CSV "${FILE_NS_DIRPREFIX}/GDS/OpcUaGdsModel.csv"
FILES_BSD "${FILE_NS_DIRPREFIX}/GDS/Opc.Ua.Gds.Types.bsd"
IMPORT_BSD "UA_TYPES#${FILE_NS_DIRPREFIX}/Schema/Opc.Ua.Types.bsd"
)
```
=> DatatypeGenerator: Allow to import additional types as dependency

open62541.pc.in
With this fix GNUInstallDirs takes care of the multiarch-tuple (i.e. `x86_64-linux-gnu`) of the library path on debian.
=> debian: use GNUInstallDirs vars to set multiarch-tuple in pkg-config file

src/ua_types.c, tests/check_utils.c
Fix function UA_NodeId_order when compare UA_NodeId with identifierType equal UA_NODEIDTYPE_GUID
Fixes #2898
=> Core: More intuitive node id ordering

debian/open62541-dev.install, debian/open62541.install
=> Debian: Do not copy lib into open62541-dev to avoid overriding open62541 package

src/server/ua_services_monitoreditem.c
Sampling has to be activated again after a configuration change.
=> Subscriptions: Keep samplingCallback for the sampling MonitoringMode

examples/pubsub/tutorial_pubsub_subscribe.c, src/pubsub/ua_pubsub.c, tests/pubsub/check_pubsub_subscribe.c
- Remove the garbage value assignment for variables created using UA_Server_DataSetReader_addTargetVariables | Values will be assigned as NULL by default
- Unit test cases to verify the published and subscribed data for the following datatypes
- Int32
- Int64
- Boolean
=> Remove garbage value asssignment for target variables in Subscriber

examples/pubsub/tutorial_pubsub_subscribe.c
Currently the input parameter checks in addPubSubConnection are concatenated with boolean AND.  From the code that follows after the checks I take it that the checks should rather be concatenated with boolean OR so that any failed check will force a return.
=> Correct boolean check on input parameters

src/server/ua_services_nodemanagement.c
In CTT, Node Management Services / Node Management Add Node / Err-005 which is implementing the test case “AddNodes is called to add a Node of the NodeClass.Variable with the ‚HasSubtype‘ reference.” This reference is only allowed to be used for some specific NodeClasses.
=> server: CTT - Fix usage of incorrect Reference type

arch/network_tcp.c
memset(tcpClientConnection, 0, sizeof(TCPClientConnection)) added to initialize TCPClientConnection struct members. If TCPClientConnection members not initialized and UA_parseEndpointUrl return error ClientNetworkLayerTCP_free will raise exception.
=> Fix UA_ClientConnectionTCP_init

.travis.yml, CMakeLists.txt, appveyor.yml, debian/update_changelog.py, tools/cmake/SetGitBasedVersion.cmake, tools/travis/travis_linux_script.sh
This makes the creation of new releases more straight forward by automatically setting the `OPEN62541_VER_...` variables based on the output of `git describe`.
Creating a new tag will automatically take the version numbers from that tag.
This PR also adds support for automatically updating and setting the version of the debian changelog.
After merge, we do not have to manually set version numbers in the code anymore.
The current release for example has a wrong rc suffix: 
https://github.com/open62541/open62541/releases/tag/v1.0-rc4
=> Automatically set CMake version based on git tag

tools/nodeset_compiler/backend_open62541.py, tools/nodeset_compiler/backend_open62541_nodes.py, tools/nodeset_compiler/datatypes.py, tools/nodeset_compiler/nodes.py, tools/nodeset_compiler/nodeset.py, tools/nodeset_compiler/nodeset_compiler.py, tools/nodeset_compiler/nodeset_testing.py, tools/nodeset_compiler/opaque_type_mapping.py
There are some leftover antiquated licenses floating around in my python scripts. Some still contain revision information from my diplima thesis' svn repo... I think we should get rid of these and clearly mark the files as MPL-2.0 to comply /w the rest of the project. 
Reported by Rahul Mohan to me via mail.
=> [review] Unify license headers

appveyor.yml, azure-pipelines.yml, tools/appveyor/install.ps1, tools/azure-devops/build.ps1, tools/azure-devops/install.ps1
This moves most of the builds from Appveyor to the more efficient
and significantly faster Azure Pipelines system.
**We will get much faster Windows builds**
For now Azure Pipelines by default only supports VS2015 and VS2017,
therefore the builds for VS2013 and VS2008 still remain on Appveyor.
These can be transferred at a later stage.
=> ci: Migrate from Appveyor to Azure Pipelines

examples/pubsub/tutorial_pubsub_publish.c, examples/pubsub/tutorial_pubsub_subscribe.c, src/pubsub/ua_pubsub.c, src/pubsub/ua_pubsub.h, tests/pubsub/check_pubsub_subscribe.c
- Fix regist fail when adding multiple ReaderGroups under one connection
- Unit test to check multiple ReaderGroups addition
- Check for following Publisher configuration parameters in DataSetReader of Subscriber
- PublisherId
- WriterGroupId
- DataSetWriterId
- Modify WriterGroup message settings to enable configuration parameters in NetworkMessage
- Unit test to check if Subscriber checks the Publisher configuration parameters and then process the NetworkMessage
=> fix: Multiple ReaderGroups and Multiple DataSetReaders in Subscriber

arch/eCos/ua_architecture.h, arch/freertosLWIP/ua_architecture.h, arch/vxworks/ua_architecture.h, arch/wec7/ua_architecture.h
Fix for issue in PR #2993 
Multithreading is supported only for posix and win32.
Nevertheless, the defined macros for multithreading must be provided for other architectures as well.
=> fix(server): Add missing macro definitions for multithreading

src/server/ua_services_session.c, src/server/ua_session_manager.c
Function removeSession should call access control closeSession as the only one.
=> Fix multiple calls

src/server/ua_services_session.c, src/server/ua_session_manager.c
Function removeSession should call access control closeSession as the only one.
Should be merge into 1.0.
=> Fix call multiple times access controls closesession function

include/open62541/server.h, plugins/ua_config_default.c, src/server/ua_services_nodemanagement.c, tests/server/check_services_nodemanagement.c
1. generateChildNodeId: Used to define NodeIds for automatically generated nodes during recursive node instantiation
2. createOptionalChild: Used to define whether an optional child should be created during recursive node instantiation
=> Server: Two new callbacks to UA_GlobalNodeLifecycle

arch/eCos/ua_architecture.h, arch/freertosLWIP/ua_architecture.h, arch/posix/ua_architecture.h, arch/vxworks/ua_architecture.h, arch/wec7/ua_architecture.h, arch/win32/ua_architecture.h, include/open62541/server.h, plugins/ua_nodestore_default.c, src/server/ua_server.c, src/server/ua_server_binary.c, src/server/ua_server_internal.h, src/server/ua_services.h, src/server/ua_services_attribute.c, src/server/ua_services_discovery.c, src/server/ua_services_method.c, src/server/ua_services_monitoreditem.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_session.c, src/server/ua_services_subscription.c, src/server/ua_services_view.c, src/server/ua_subscription_datachange.c, src/server/ua_subscription_events.c, tests/server/check_server_historical_data.c, tests/server/check_server_readspeed.c, tests/server/check_services_subscriptions.c, tests/server/check_subscription_events.c
Continuation of PR #2993:
- Locks for the subscription and monitoredItem service sets
- Locks for the view service set 
- Fixes for unit tests
- Refactoring of the used multithreading macros
=> feat(server): Lock-based enhancement using mutexes (Part 2)

debian/control-template
Lintian complains that the dev package installs python scripts without stated dependency to python. Consequently there should be a dependency to python included for the dev package.
=> fix(debian): add python dependency to dev package

plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c, plugins/securityPolicies/ua_securitypolicy_basic256.c, plugins/securityPolicies/ua_securitypolicy_basic256sha256.c
This PR just improves logging but does not change any functionality.
In the old code the error would be more cryptic if private key is empty.
=> fix: Improve security policy logging if invalid private key is given

CONTRIBUTING.md
This PR updates the contributing guidelines to clarify the commit message structure.
It recommends to stick with https://www.conventionalcommits.org
This allows us to automatically generate the changelog and in the future use semantic releases more easily.
To check if at least the PR title or any commit inside the PR conforms with the guideline, I just enabled https://github.com/probot/semantic-pull-requests
This will add another CI status. Currently it is not required, but I suggest to set it as required after some time testing it.
=> docs: Update contributing guidelines for conventional commits

.dockerignore, CMakeLists.txt, Dockerfile, tools/nodeset_compiler/nodes.py, tools/travis/travis_linux_script.sh
The container can be built with:
`docker build -t open62541 . && docker run -p 4840:4840 open62541`
=> fix: Start ctt server as default application in docker container

src/pubsub/ua_pubsub.c, tests/pubsub/check_pubsub_subscribe.c
- Fix valgrind errors while running tutorial_pubsub_subscribe application by modifying UA_snprintf in UA_Server_DataSetReader_addTargetVariables 
- Unit test to verify that no segmentation fault occurs when adding ByteString variable in Subscriber metadata
=> fix: Resolve valgrind error in example Subscriber application

debian/libopen62541-dev.install-template
Braces should be removed here because _lintian_ states 
```
N:    This debhelper config file appears to use shell brace expansion (such as
N:    {foo,bar}) to specify files. This happens to work due to an accident of
N:    implementation but is not a supported feature. Only ?, *, and [...] are
N:    supported.
N:    
```
As long as this package produces only the shared lib the affected line should be reduced
to ```usr/lib/*/*.so```
=> fix(debian): remove braces in debhelper config file

debian/copyright
This removes the _lintian_ warning
```
W: open62541 source: syntax-error-in-dep5-copyright line 18: Continuation line outside a paragraph (maybe line 17 should be " .").
N: 
N:    The machine-readable copyright file didn't pass Debian control file
N:    syntax check.
N:    
N:    This issue may hide other issues as Lintian skips some checks on the
N:    file in this case.
N:    
N:    Refer to
N:    https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ for
N:    details.
N:    
N:    Severity: normal, Certainty: possible
N:    
N:    Check: source-copyright, Type: source
N:
```
Of course not really important but a bit more shiny in the debian sense
=> fix(debian): syntax errors in copyright file

doc/installing.rst
The Arch User Repository (AUR) is where the Arch community can submit packages and is supported across all Arch-based distributions.
In order to submit a package to the AUR, a [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) is added to the AUR and the files are compiled from source during installation. Analogue to the existing packages available for Debian, I have created a PKGBUILD for the current 1.0 branch (which would have to be updated to the 2.0 branch when this is released, this information will be added to the ["Creating a New Release" page in the Wiki](https://github.com/open62541/open62541/wiki/Creating-a-new-release)) as a stable "open62541" package and a PKGBUILD for the current master which is called "open62541-git" following conventions for AUR packages.
The …
=> docs: Add package to Arch User Repository

debian/rules-template
This patch fixes following _lintian_ output:
```
I: libopen62541-1: hardening-no-bindnow usr/lib/x86_64-linux-gnu/libopen62541.so.1.0.0
N: 
N:    This package provides an ELF binary that lacks the "bindnow" linker
N:    flag.
N:    
N:    This is needed (together with "relro") to make the "Global Offset Table"
N:    (GOT) fully read-only. The bindnow feature trades startup time for
N:    improved security. Please consider enabling this feature or consider
N:    overriding the tag (possibly with a comment about why).
N:    
N:    If you use dpkg-buildflags, you may have to add hardening=+bindnow or
N:    hardening=+all to DEB_BUILD_MAINT_OPTIONS.
N:    
N:    The relevant compiler flags are set in LDFLAGS.
N:    
N:    Refer to https://wiki.debian.org/Hardening for details.
N:
```
=> fix(debian): hardening no bindnow

debian/rules-template
Reverts open62541/open62541#3077
This leads to build errors. See e.g. #3080
=> Revert "fix(debian): hardening no bindnow"

include/open62541/server.h, src/server/ua_server.c, src/server/ua_server_binary.c, src/server/ua_server_discovery.c, src/server/ua_server_internal.h, src/server/ua_server_ns0.c, src/server/ua_services_attribute.c, src/server/ua_services_discovery.c, src/server/ua_services_discovery_multicast.c, src/server/ua_services_method.c, src/server/ua_services_monitoreditem.c, src/server/ua_services_nodemanagement.c, src/server/ua_services_session.c, src/server/ua_services_subscription.c, src/server/ua_services_view.c, src/server/ua_session.c, src/server/ua_session_manager.c, src/server/ua_subscription.c, src/server/ua_subscription_datachange.c, src/server/ua_subscription_monitoreditem.c, tests/multithreading/check_mt_addDeleteObject.c, tests/multithreading/check_mt_readWriteDeleteCallback.c, tests/multithreading/mt_testing.h, tests/server/check_services_subscriptions.c, tests/testing-plugins/thread_wrapper.h
Continuation of PR #2993 and #3043:
- Fixing issues with win32 plattform
- Locks for remaining server.h - functions
- Locks for Session, Subscription and MonitoredItem - handling
- Additional assertions
=> feat(server): Lock-based enhancement using mutexes (Part 3)

debian/rules-template
This enables hardening during debian package build and fixes the error due to #3077 described in #3080 and #3085 .
This fix disables the PIE flag explicitly.
=> fix(debian): hardening all but no PIE flag

debian/changelog, tools/prepare_packaging.py
**[PLEASE REVIEW]**
The main intention of this PR is to make the Debian version numbers more compatible to the Debian policy.
**Problem:**
When building pack/1.0 or pack/master `dpkg-source` complains
`dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision`
This is due to the fact that Debian uses dashes to mark revisions and revisions are not allowed with format `3.0(native)`.
The generated version numbers in  `debian/changelog` look like `1.0-rc1-53-g123456`, this has a second disadvantage. For example the version `1.0` will be identified by `dpkg` as smaller than the release candidate version `1.0-rc1` (could be checked with `dpkg --compare-versions`). As result one can only install `1.0` if version `1.0-rc1` has been purged …
=> feat(debian): more compatible version numbers

tools/cmake/FindMbedTLS.cmake
This prevents absolute paths for these libraries in open62541Targets.cmake
=> build: mark mbedTLS libraries as imported

tools/nodeset_compiler/nodes.py
Parsing of UAVariable xml element now also supports the Historizing attribute.
The Historizing attribute is documented in Annex F.8 of the document OPC Unified Architecture - Part 6 Mappings - Release 1.04 - OPC 10000-6 (https://opcfoundation.org/developer-tools/specifications-unified-architecture/part-6-mappings), and is also documented in the `UANodeSet.xsd` XML Schema file v1.04, at https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/Schema/UANodeSet.xsd#L358 .
Closes https://github.com/open62541/open62541/issues/2516
=> feat(nc): add support for reading Historizing attribute in UAVariable elements

tools/prepare_packaging.py
otherwise build will fail because there is no gpg key
See:
https://travis-ci.org/open62541/open62541/jobs/587034491#L11281
This is a temporary solution for the 1.0 release.
=> fix(debian): Do not set the distribution to unstable

debian/control-template, debian/rules-template, tools/prepare_packaging.py
This PR prevents some annoying lintian messages...
=> fix(debian): remove trailing white space and lines

src/server/ua_server_binary.c
The server modifies the send and recv buffer sizes for the connection but doesn't
include the changed values into the Acknowledge message.
According to OPC UA Part 6, 7.1.2.4, the buffer sizes shall not be larger than what
the client requested in in the HEL message.
Sending the server's default value causes clients with smaller buffer size limits
(for example Siemens S7-1500) to abort the connection attempt.
=> Fix buffer size negotiation

tests/fuzz/CMakeLists.txt, tests/fuzz/custom_memory_manager.c, tests/fuzz/oss-fuzz-copy.sh
mdns is not eligible for separate fuzzing, therefore we do it as part of open62541
See also:
https://github.com/google/oss-fuzz/pull/2928
=> ci: Add mdns to fuzzing

debian/rules-template
This PR fixes the lintian reported issue 
```
W: open62541 source: debian-rules-sets-DEB_BUILD_OPTIONS line 6
N: 
N:    The debian/rules file sets the DEB_BUILD_OPTIONS variable, which will
N:    override any user-specified build profile.
```
With the environment variable `DEB_BUILD_OPTIONS` the packager could influence the build process of a package as required (e.g. disable tests during build to get a faster build like `DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -rfakeroot ...`) but this will be overwritten by setting  `DEB_BUILD_OPTIONS` in `debian/rules` which is not the best idea.
This PR enables parallel build (using all available processor cores except 2) by injecting the appropriate option to `dh_auto_build`.
=> fix(debian): avoid overwriting env var DEB_BUILD_OPTIONS

tools/nodeset_compiler/backend_open62541_nodes.py
The generated code contains the array values, but not the size.
This breaks the array dimensions in UA_Argument.
=> Set {memberName}Size value for generated extension objects

src/server/ua_nodes.c
This PR proposes some fixes to the UA_Node_copy function.
To reproduce crashes compile the library (master [[last commit](https://github.com/open62541/open62541/commit/a2d07b3e54fdd6038a7f36eaa53e8ad2a537288e)]) with -DUA_ENABLE_IMMUTABLE_NODES=1 and run the unit tests.
=> [Review] (Bug) Fix crashes that occur when immutable nodes are enabled

src/server/ua_nodes.c
=> Backport from master: Fix reference target tree copying in UA_Node_copy

.gitmodules, tests/fuzz/CMakeLists.txt
It seems that for shallow submodules travis sometimes does not find
the referenced remote commit
=> ci: Disable shallow submodules since they lead to errors on travis.

Dockerfile
fix: adding missing submodule init command to Dockerfile
Without this line, `docker build` terminates with the following error message:
> CMake Error at CMakeLists.txt:830 (message):
>   File /opt/open62541/deps/ua-nodeset/Schema/Opc.Ua.NodeSet2.xml not found.
>   You probably need to initialize the git submodule for deps/ua-nodeset.
=> adding missing submodule init command to Dockerfile

src/pubsub/ua_pubsub_reader.c
- Changed status code of retval to UA_STATUSCODE_BADNOTFOUND
as the API functionality fails to invoke an error even a wrong
publisherID is subscribed
- TODO: Add Unit test case for PublisherId and DataSetWriterId checks
=> fix(pubsub): Resolve PublisherId and DataSetWriterId check issue

debian/control-template, debian/libopen62541-dev.install-template, debian/libopen62541-tools.install-template, tools/prepare_packaging.py
Building pack/1.0 produces the lintian message
```
I: libopen62541-1-dev: arch-dep-package-has-big-usr-share 104164kB 98%
N: 
N:    The package has a significant amount of architecture-independent data
N:    (over 4MB, or over 2MB and more than 50% of the package) in /usr/share
N:    but is an architecture-dependent package. This is wasteful of mirror
N:    space and bandwidth since it means distributing multiple copies of this
N:    data, one for each architecture.
N:
```
which is correct because the `libopen62541-<soname>-dev` package is architecture dependent and the tools are not. 
This PR splits the previous `libopen62541-<soname>-dev` into the architecture dependent `libopen62541-<soname>-dev` package and the architecture independent `libopen62541-<soname>-tools` package. The …
=> fix(debian): separate tools from dev

src/pubsub/ua_pubsub_reader.c
- Socket timeout should not be 300ms as it waits for a packet
for about 300ms and hogs the other resources
- Reduced the timeout to 1ms as subscribe callback timer
running at 5ms
=> fix(pubsub): Performance enhancement of subscriber server

CMakeLists.txt, debian/control-template, debian/open62541-doc.doc-base-template, debian/open62541-doc.install-template, debian/rules-template, doc/CMakeLists.txt, tools/prepare_packaging.py
This PR adds a Debian doc package and provides the PDF and HTML documentation for open62541, the installation place, as usual at Debian systems, will be `/usr/share/doc/open62541`.
In addition the package provides the open62541 example application sources at `/usr/share/open62541/examples`.
This PR is based on prototype work of @ralphlange (see https://github.com/ralphlange/open62541/tree/feature/debianization/debian)
=> feat(debian): add PDF and HTML docs including examples

CMakeLists.txt, debian/control-template, debian/libopen62541-dev.install-template
This PR adds the static library to the Debian dev package to enable the build of static linked apps. 
The dev package now provides the header files, the soft link to the shared lib AND the static lib. 
This PR is based on a cherry pick of the prototype work of @ralphlange (see https://github.com/ralphlange/open62541/tree/feature/debianization/debian)
=> feat(debian): add static library to dev package

debian/control-template
This PR addresses the problem reported by @Pro (launchpad builds failing [#3215](https://launchpadlibrarian.net/448601588/buildlog.txt.gz))
Since  Debian/bullseye or Ubuntu/Eoan the generation of the `open62541-doc` package fails because the Debian package `texlive-generic-extra` is not available anymore and should be replaced by `texlive-plain-generic`
@Pro could you please test it on launchpad?
=> fix(debian):use texlive-plain-generic since debian/bullseye or ubuntu/eoan

include/open62541/plugin/historydatabase.h, plugins/historydata/ua_history_database_default.c, src/server/ua_services_attribute.c
This PR adds interfaces for readModified, readProcessed, and readAtTime history requests so that users have ways to implement those requests in their custom history databases. 
No default implementations are provided.
=> [Review] Add readModified, readProcessed, readAtTime to UA_HistoryDatabase

tools/azure-devops/win/install.ps1
=> fix(ci): Pin msys2 to specific version otherwise install fails.

doc/building.rst
This PR adds documentation regarding Debian packaging and has two parts
- an example how one can locally build open62541 Debian packages inside a Docker container in a convenient way
- a small comment on how to deal with CMake build options in conjunction with Debian packaging
please feel free to slice and dice it - or to dump it :-)
=> feat(doc): example debian packaging inside docker container

src/pubsub/ua_pubsub.h, src/pubsub/ua_pubsub_manager.c, src/pubsub/ua_pubsub_ns0.c, src/pubsub/ua_pubsub_writer.c, tests/pubsub/check_pubsub_config_freeze.c
- The order of DSF should be the same while creating and publishing and
the existing implementation publishes reversely
- Used TAILQ structure for DSF instead of LIST structure
=> fix(PubSub): Publishing order of multiple DataSetFields

include/open62541/client_subscriptions.h, src/client/ua_client_highlevel.c, src/client/ua_client_internal.h, src/client/ua_client_subscriptions.c, tests/client/check_client_subscriptions.c
Implemented client async functions for subscriptions/monitored items.
I tried to reduce the number of modifications of the original code by splitting each synchronous function in separate parts.
Longer explanation what and why it is implemented that way:
Split synchronous function (SFN) into the following parts:
a) prepare the call
b) execute the call synchronously
c) handle the call result
The asynchronous function (AFN) implements the same schema as SFN; it replace
the synchronous call by an asynchronous one.  It appends the c) part as
ClientAsyncCallback to the asynchronous call.  It also receives a user-defined
callback, that has to be executed after part c) of the AFN has run.
The difficulty lays in the memory management of parts a) and c).  In the
synchronous application, the …
=> Async monitored items

include/open62541/server_pubsub.h, src/pubsub/ua_pubsub_manager.c, src/pubsub/ua_pubsub_writer.c, tests/pubsub/check_pubsub_config_freeze.c
This PR adds the automatic generation of DataSetMeta after  adding a PublishedDataSet and DataSetFields. The DataSetMetaData is  necessary for subscribers to decode the received packages.
The following new API method can be used to get a copy of the DataSetMetaData: 
UA_StatusCode UA_EXPORT UA_Server_getPublishedDataSetMetaData(UA_Server *server, const UA_NodeId pds, UA_DataSetMetaDataType *metaData);
=>  [PubSub] First Batch of DataSetMetaData implementation

examples/pubsub/tutorial_pubsub_connection.c
The `resuse` and `loopback` options are defined as type UA_TYPES_UINT32 in the example, but in UA_PubSubChannelUDPMC_open [plugins/ua_pubsub_udp.c] are expected to be of type
BOOLEAN. Using UINT32 for either of them will cause the options not to
be evaluated and hence not used.
=> Fix type of resuse and loopback options to UA_TYPES_BOOLEAN in tutorial_pubsub_connection.c example

src/client/ua_client.c
The log plugin provides a cleanup routine which is not called in UA_Client_delete(..). Since automatic cleanup can be enabled/disabled by setting UA_Logger.clear function pointer, UA_Client_delete(..) should automatically cleanup the log plugin.
=> Included plugin/log.h cleanup in UA_Client_delete(..).

src/server/ua_securechannel_manager.c, src/ua_securechannel.c, tests/client/check_client.c
* previousSecurityToken structure of UA_SecureChannel was not cleared
after generating the new remote symmetric key. This caused a server
to renew the remote key every time a message chunk was received. If
the client requested a renewal of the secure channel and new nonces
were exchanged, but the client continued to use the "old"
SecurityToken for some more message chunks the server generated a
remote key based on the new nonces when it should have used the key
of the current SecurityToken.
* UA_SecureChannelManager_cleanupTimedOut() changed currently used
SecurityToken to the next one if present. According to Part 4,
chapter 5.5.2 OpenSecureChannel the server shall use the existing
SecurityToken until it expires or the server receives a message
secured with the new SecurityToken. Hence, …
=> Solved issues related to SecurityToken renewal

include/open62541/types.h, tools/schema/datatypes_typedescription.txt
We observed generated binary encoding IDs that do not fit into an UA_UInt16, e.g. ns=2;i=543211 => Increasing UA_DataType.binaryEncodingId to UInt32.
In addition, added EnumDefinition and EnumField to decode datatype binary information (UA_ATTRIBUTEID_DATATYPEDEFINITION) from OPC UA servers.
=> Compability with generated types of UnifiedAutomation SDK

include/open62541/plugin/log.h
Hello,
while playing around with your cool project, we encountered a problem regarding the zero compiler warnings promise. When building the project as a library with a log-level other than 100 (set as part of the CMakeLists.txt line 129), the compiler creates warnings in the project using the open62541 library as the log-levels are realized by removing code via the use of macros. This possibly leaves empty functions that have a couple of unused arguments (source of this is the header file include.open62541.plugin/log.h). We solved this (quick&dirty) by adding an else case to the removal-macros that just 'touches' the variables. However, I did not check if the C++ optimizer is still able to remove the dead code section in production releases.
In addition, I would suggest to change the …
=> Compiler warnings while using Open62541 as library

src/pubsub/ua_pubsub_ns0.c
This PR solves the currently occurring build error if PubSub is enabled with the information model mapping. The issue was cased by the recent change from an size and pointer structure to the more flexible queue structures within the PubSub manager.
=> fix(pubsub) PubSub NS0 build error

plugins/ua_pubsub_ethernet.c
UA PubSub Ethernet.c includes some Linux header files and macros. In VxWorks, these macros and header files are different from Linux. In this PR, I used VxWorks macros to implement different codes in different systems.
=> Fix the build error  when enable pub/sub support over Ethernet in VxWorks7

include/open62541/plugin/historydatabase.h, src/server/ua_server_internal.h, src/server/ua_services_attribute.c, src/server/ua_subscription_events.c
This PR adds two new methods to UA_HistoryDatabase: setEvent and readEvent.
It also adds readObjectProperty function which is then used in historical events' implementation. (UA_Server_readObjectProperty/readObjectProperty are now analogous to UA_Server_writeObjectProperty/writeObjectProperty).
Some notes:
1. OPC UA Part 11, clause 5.3.2 says: "A HistoricalEventNode that has Event history available will provide the Property [HistoricalEventFilter]". When an event is triggered the server tries to read the HistoricalEventFilter property of an emitting node (not the origin node) and if the property is present it filters the event object and passes results to setEvent (happens for each emitter). On readEvent the client's filter should be mapped to a filter contained in the …
=> [Review] Historical events

plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c, plugins/securityPolicies/ua_securitypolicy_basic256.c, plugins/securityPolicies/ua_securitypolicy_basic256sha256.c, plugins/securityPolicies/ua_securitypolicy_none.c, src/ua_securechannel.c
Padding is now calculated with the local key size during decryption.
=> Fix: #3263

src/server/ua_subscription_alarms_conditions.c
As EnableState.Id is checked instead of the Retain when triggering a condition, I changed the error message.
https://github.com/open62541/open62541/blob/a2209072c72ed25918fbd00f19b14e491745a90b/src/server/ua_subscription_alarms_conditions.c#L2549-L2552
https://github.com/open62541/open62541/blob/a2209072c72ed25918fbd00f19b14e491745a90b/src/server/ua_subscription_alarms_conditions.c#L628
=> Fix: Error message in triggerConditionEvent

arch/network_ws.c
1. Fix memory access after free
2. Clean up message queue on connection free
3. Prepend the incomplete chunk in WebSocket layer
The last fix is necessary because the following code is actually broken (an issue will be created) https://github.com/open62541/open62541/blob/d02fc4f5a4b60bb30a3c9394643abdd93b1fd59c/src/ua_connection.c#L171-L174
=> Various fixes for WebSocket layer

src/client/ua_client.c, src/client/ua_client_connect.c, src/client/ua_client_connect_async.c, src/client/ua_client_internal.h, src/server/ua_server_binary.c, src/ua_connection.c, src/ua_securechannel.c, src/ua_securechannel.h, src/ua_securechannel_crypto.c, tests/client/check_client_async.c, tests/client/check_client_subscriptions.c
This clears up the control flow for OPN messages.
They are simply forwarded to the client/server layer.
This is preparatory work for more cleanup in the client.
=> Pull OPN decoding/encoding in the client/server layer

plugins/ua_config_default.c
The user may want to set his own logger even before any output is generated.
=> fix(server): Do not overwrite logger in default server config

src/server/ua_subscription_alarms_conditions.c
I was not able to add multiple (unexposed) conditions. One problem was an error in the handling/detection of condition branches.
The more difficult problem occurs when adding unexposed conditions with the same condition source. In this case, we have to make sure that a HASCONDITION reference is only added once from the condition source to the condition type. I did not found a way to check if this reference already exists. Therefore I just ignore this error.
=> support multiple conditions

src/server/ua_securechannel_manager.c, src/ua_securechannel.c, tests/client/check_client.c
* previousSecurityToken structure of UA_SecureChannel was not cleared
after generating the new remote symmetric key. This caused a server
to renew the remote key every time a message chunk was received. If
the client requested a renewal of the secure channel and new nonces
were exchanged, but the client continued to use the "old"
SecurityToken for some more message chunks the server generated a
remote key based on the new nonces when it should have used the key
of the current SecurityToken.
* UA_SecureChannelManager_cleanupTimedOut() changed currently used
SecurityToken to the next one if present. According to Part 4,
chapter 5.5.2 OpenSecureChannel the server shall use the existing
SecurityToken until it expires or the server receives a message
secured with the new SecurityToken. Hence, …
=> Backport #3277 to 1.0

src/client/ua_client_connect.c
There is currently an inconsistency. The client->endpointUrl variable is only used for the async connect. This is just a quick-fix.
Fixup for #3390 See:
https://github.com/open62541/open62541/commit/e93f8ebb698a1dd957952e68b15e09f0e4303ebe#diff-096258576a8c3ac7adc8daaf14b817e2L83
=> fix(client): Correctly set endpointUrl in HEL Message

examples/pubsub/tutorial_pubsub_mqtt_publish.c, src/pubsub/ua_pubsub_writer.c, tools/schema/datatypes_pubsub.txt
datatypes_pubsub.txt: add JsonWriterGroupMessageDataType
tutorial_pubsub_mqtt_publish.c: use correct datatype for WriterGroup json message settings
ua_pubsub_writer.c: UA_Server_addWriterGroup(): validate if correct type for json message settings is passed.
https://github.com/open62541/open62541/issues/3398
=> fix(ex): use correct data type for writer group json message settings

src/server/ua_services_attribute.c
According to the specification, a server that can't handle source
timestamps must reject a write request that include timestamps
according to the specification.
Part 4, chapter 5.10.4.2, value description:
"If the SourceTimestamp or the ServerTimestamp is specified, the
Server shall use these values. The Server returns a
Bad_WriteNotSupported error if it does not support writing of
timestamps."
An application that cannot handle source timestamps and maps its
parameters to OPC variable nodes using the data source callbacks
should reject requests that contain source timestamps. Right now such
implementations reject all write requests as the server
implementation adds the source timestamp if omitted by the client.
=> Server should only set source timestamp for valuesource data variables

arch/network_tcp.c, include/open62541/network_tcp.h, plugins/ua_config_default.c
In for example LWIP the number of TCP connection resources must be
configured at compile time. On a device with several protocols that
relies on TCP they must share this common pool of TCP resources. To
avoid one protocol allocating all TCP resources they must limit
themselfs in the number of TCP connections they allocate.
=> [REVIEW] Added possibility to configure max TCP connections limit

include/open62541/plugin/accesscontrol.h, plugins/ua_accesscontrol_default.c, src/server/ua_services_view.c
The PermissionType (Part 3) defines 17 permissions. Currently the
access control plugin can control all but 2 of them. Those are Browse
and ReceiveEvents. This change adds check for browse permission of
nodes.
=> Extended the access control plugin with check for browsing nodes

examples/custom_datatype/server_types_custom.c
Currently the datatype node for the 3D Type is not added to the address space, therefore a client has no information how to decode the extension object.
This PR adds the datatype node, UAExpert is able to decode the value.
=> [REVIEW]: add DataType node in example

doc/installing.rst
An official OpenBSD port of open62541 exists.  The binary package
is available as snapshot now and will be included in the upcoming
OpenBSD 6.7 release.  Put install instructions into the documention.
=> doc(openbsd): binary package available

tests/CMakeLists.txt
On OpenBSD there is not subunit package available.  Do not add it
to the library list to successfully build the tests.
The check package is installed in /usr/local/ so the include files
and libraries should be searched there.  Move this directory to the
end of the list so that other software lying there, like an old
version of open62531, is less likely to interfere with testing.
=> test(openbsd): compile options

.travis.yml, tools/travis/travis_osx_before_install.sh
The git repository for the HEAD version is unstable.
=> fix(ci): Use the regular valgrind from homebrew on MacOS X

src/server/ua_services_discovery_multicast.c
There was an issue if someone defined his own custom hostname as the IP Adress, which leads to an invalid dns name
=> fix(mdns): Replace dots in hostname with minus to ensure correct domain name

src/server/ua_services_session.c
I moved the debug log further down (after the null pointer check). 
And added an additional log, if the session pointer is invalid. 
I am not sure which log messages are needed.
But at least one can see that Service_ActivateSession has been called.
=> Fix crash: Avoid debug trace of nullpointer at Service_ActivateSession

tools/azure-devops/win/install.ps1
Hardcode Dr Memory Version to 2.2. Otherwise it fails with
"Failed to take over all threads after multiple attempts."
See for example: 
https://dev.azure.com/open62541/open62541/_build/results?buildId=1242&view=logs&j=0690d606-4da6-5fc6-313c-2fce474be087&t=6290dcff-a4f0-5630-9345-7cbc0279a890&l=1871
=> fix(ci): Pin DrMemory to v2.2 to avoid build failures

plugins/include/open62541/plugin/securitypolicy_openssl_common.h, plugins/securityPolicies/openssl/securitypolicy_openssl_common.c, plugins/securityPolicies/openssl/ua_openssl_basic128rsa15.c, plugins/securityPolicies/openssl/ua_openssl_basic256.c, plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c, plugins/securityPolicies/ua_securitypolicy_basic256.c, tests/CMakeLists.txt
The OPC UA  part 7 standard says:  Support at least Security Policy [A] and Security Policy [B]. Support of multiple Security Policies - even obsolete ones - is recommended. This will provide best interoperability and allows the end user to choose the required level of security.
This PR add the security policy Basic256 and Basic256Rsa15 support with OpenSSL.
All test cases of the OPC foundation CTT tool are passed.
=> [Review]add the security policy Basic256 and Basic256Rsa15 support with OpenSSL

tools/nodeset_compiler/backend_open62541_datatypes.py
This fixes QualifiedName Values in Nodeset files like this:
<UAVariable DataType="QualifiedName" ParentNodeId="ns=1;i=1012" NodeId="ns=1;i=6030" BrowseName="DefaultInstanceBrowseName">
<DisplayName>DefaultInstanceBrowseName</DisplayName>
<References>
<Reference ReferenceType="HasProperty" IsForward="false">ns=1;i=1012</Reference>
<Reference ReferenceType="HasTypeDefinition">i=68</Reference>
</References>
<Value>
<uax:QualifiedName>
<uax:NamespaceIndex>2</uax:NamespaceIndex>
<uax:Name>Identification</uax:Name>
</uax:QualifiedName>
</Value>
</UAVariable>
Previous leading to this:
```
INFO:__main__:Generating Code for Backend: open62541
Traceback (most recent call last):
File "<DevDir>/Open62541_Tests/install-debug/share/open62541/tools/nodeset_compiler/nodeset_compiler.py", line 189, in …
```
=> Fix: NodesetGenerator QualifiedName: 'NoneType' object has no attribute 'name'

include/open62541/server.h, src/server/ua_services_attribute.c
This pull request adds UA_Server_writeDataValue, analog to UA_Server_writeValue, but accepting a UA_DataValue, so you can control the StatusCodes and TimeStamps.
=> Add UA_Server_writeDataValue

include/open62541/server_config.h
Fix error C2143: syntax error : missing ';' before 'type' in MSVC
For MSVC, "UA_DEPRECATED" evaluates to "__declspec(deprecated)" which cannot be placed at the end of a deprecated statement, only in the front.
=> fix(server): misplaced UA_DEPRECATED macro

plugins/securityPolicies/openssl/ua_openssl_basic256sha256.c, plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c, plugins/securityPolicies/ua_securitypolicy_basic256.c, plugins/securityPolicies/ua_securitypolicy_basic256sha256.c
Root cause:
1. The function UA_ServerConfig_addAllSecurityPolicies() in
https://github.com/open62541/open62541/blob/master/plugins/ua_config_default.c will do like this:
`
UA_ServerConfig_addAllSecurityPolicies (...) {
...
UA_ServerConfig_addSecurityPolicyNone(config, &localCertificate);
UA_ServerConfig_addSecurityPolicyBasic128Rsa15(config, &localCertificate, &localPrivateKey);
UA_ServerConfig_addSecurityPolicyBasic256(config, &localCertificate, &localPrivateKey);
UA_ServerConfig_addSecurityPolicyBasic256Sha256(config, &localCertificate, &localPrivateKey);
...
}
`	
2. The function UA_ServerConfig_addSecurityPolicyBasic128Rsa15() will do like this:
`
UA_SecurityPolicy *tmp = (UA_SecurityPolicy *)
UA_realloc(config->securityPolicies,
sizeof(UA_SecurityPolicy) * (1 + …
=> fix(security policy) the  securityPolicy pointer in *_PolicyContext is invalidate

src/server/ua_services_session.c
While testing access rights we got UaExpert to perform a sequence
that we belive the open62541 server did not handle correctly:
1. OpenSecureChannel
2. CreateSession
3. ActivateSession
4. Some initial browsing/reading that eventually failed due to
limited access rights
5. CloseSecureCannel (session is now detached from the channel)
6. OpenSecureChannel
7. ActivateSession (same session id as activated in no. 3)
During the second ActivateSession the server failed the request
in UA_Session_generateNonce() as there was no channel attached to the
session. The session was detached from the secure channel when
UaExpert closed the channel in no. 5. This PR makes the session
attached to the new channel before generating the nonce.
=> [REVIEW] Attach session to channel when activating if no channel exists

src/server/ua_subscription.h, src/server/ua_subscription_alarms_conditions.c, src/server/ua_subscription_events.c
both BranchId and the passed ConditionId should be equal if we want to set the Event Field "ConditionId" with the main ConditionId.
Using "!UA_NodeId_equal" at this place allows the program to go each time inside the if-clause because BranchId is always equal Null NodeId. As a result, each Event ends up having a ConditionId Field within it.
This should fix the problem in https://github.com/open62541/open62541/pull/3415#issuecomment-582816205 and is related to https://github.com/open62541/open62541/issues/3451#issuecomment-591349071
=> Fix ConditionId Search (Alarms and Conditions)

arch/posix/CMakeLists.txt
Special compiler flags for OpenBSD are no longer necessary.  The
system compiler is now clang, and the default options used for other
operating systems work fine.  On OpenBSD everything is compiled
with PIC anyway to allow random address layout.  The current logic
was implemented in 4fbef714474d80ea9f9c443ec03890c408c11c32 with
the commit message "try building as rpm" which makes no sense.
=> build(openbsd): compile options

src/server/ua_server.c
If `UA_BUILD_FUZZING` authentication tokens and other variables are overridden internally. This causes subscriptions and other parts of the code to not work as expected.
Since `UA_BUILD_FUZZING` should not be used for debug or release builds in general, show a warning to avoid accidental usage of this build option.
=> fix(server): Add warning if fuzzing build is enabled

src/server/ua_subscription.c
Free resources in relation to retransmission queue is available or not.
=> Merge from 1.0: Fix memory leak if enableRetransmissionQueue is disabled

src/client/ua_client.c, src/server/ua_server_config.c
The client did check that logger context is not NULL before calling
the clear() callback.  This does not make sense as the default
config uses UA_Log_Stdout_clear() with a NULL context.  It does
make sense to reset the logger callbacks in the client and server
config clean() functions, so that they cannot be called after that.
Do that consistently for both client and server.
=> fix(log): Use logger clear callback consistenly

tests/testing-plugins/thread_wrapper.h
This fixes the mutex handling of the tests on windows.
I don't know the reason, why this is different to 
https://github.com/open62541/open62541/blob/578d521931777181d1a881c8335ca5fafcd66eb2/arch/win32/ua_architecture.h#L147-L156
It may be a good idea to unify this in the future. But some tricks are required to test without UA_MULTITHREADING set.
=> Fix: Mutex on win32

src/server/ua_subscription.h, src/server/ua_subscription_events.c, tests/server/check_subscription_events.c
This is a minimalistic implementation of the WhereClause for EventSubscriptions.
Fixes #3102
Limitations: Only UA_FILTEROPERATOR_OFTYPE is evaluted.
=> Evaluate whereClaus of event subscriptions for operator OfType

doc/installing.rst
Added missing "-1" in the package name
=> Fixed apt install for debian

src/client/ua_client_connect.c
If the client don't get the nonce from the remote server, the UA_SecureChannel_generateNewKeys() should not be called to generate the new key.
=> fix(client) don't generate new key if the client remote nonce is NULL

plugins/securityPolicies/openssl/securitypolicy_openssl_common.c, src/client/ua_client_connect.c, src/client/ua_client_highlevel.c
In all other async functions the request id is optional, but
__UA_Client_readAttribute_async crashes if it is NULL.  Pass local
storage to __UA_Client_AsyncService() and set the value of reqId
parameter only if the pointer is not NULL.
For that allocate the custem callback before the call to async
service.  This has the additional advantage that in case of memory
allocation error, the read attribute async has not done half the
work.  It would fail early instead.
=> fix(client): optional reqId in client read async

include/open62541/server.h
The attribute ContainsNoLoops is called with an s at the end.  The
function name UA_Server_readContainsNoLoop() contains a typo and
the s is missing.  Although this is an API break it shoud be corrected
to be consistent with the rest of the code and compliant to the
standard.
=> fix(server): ContainsNoLoop typo

arch/network_tcp.c
Quick fix for connection problems between client and server. It crashed with _DNS look up failed (WSAStartup was not called.)_
Pull request for [this Issue](https://github.com/open62541/open62541/issues/3609)
=> DNS lookup WSAStartup bug fix on Win 10 environment 

arch/network_ws.c
as stated in issue #3639 the websocket connections are not closed,
because libwebsockets does not get informed about the close event.
As stated in the lws documentation: to close a connection return -1 from within the lws callback
I stumbled uppon this problem, when running wsopcua client reconnect integration tests against the open62541
(usually working against UA-CPP server with websocket proxy) 
* fixes #3639
* allows connections with the officially registered websocket protocols opcua+uacp, opcua+json
=> fix: Really close the websocket connection

tests/check_chunking.c, tests/check_types_builtin.c, tests/check_types_custom.c, tests/check_types_memory.c, tests/check_types_parse.c, tests/check_types_range.c, tests/client/check_client_highlevel.c, tests/server/check_nodestore.c, tests/server/check_server.c, tests/server/check_server_callbacks.c, tests/server/check_server_userspace.c, tests/server/check_services_attributes.c, tests/server/check_services_call.c, tests/server/check_services_nodemanagement.c, tests/server/check_services_view.c
My clang 8.0.1 on OpenBSD could not compile the test programs due
to implicit conversion changes signedness errors.  Use the correct
unsigned ck_assert_uint_eq() function and change some data types.
=> test: fix signedness compile errors

examples/CMakeLists.txt, examples/server_loglevel.c, plugins/include/open62541/plugin/log_stdout.h, plugins/ua_log_stdout.c
Add UA_Log_Stdout_ErrorLevel which only prints Error level and above regardless of UA_LOGLEVEL being set lower.  
The logger can be enabled like this:
```
UA_ServerConfig *open62541_server_config = UA_Server_getConfig(open62541_server);
UA_ServerConfig_setDefault(open62541_server_config);
open62541_server_config->logger = UA_Log_Stdout_ErrorLevel_; 
```
This also allows log level being a command line parameter.
```
UA_Logger mylogger = {UA_Log_Stdout_loglevelcheck, (void*)mylevel, UA_Log_Stdout_clear};
```
The PR also makes it easier to clone UA_Log_Stdout, as some definitions is moved to `open62541/plugin/log_stdout.h`
The PR is based on 1.0.1, but should also be possible to cherry pick to master.
=> Levelled log

CMakeLists.txt
If OpenBSD CLang 8.0.1 is called with -mcet and -fcf-protection,
the resulting test binaries fail to execute.  Disable these options
on OpenBSD.
=> build: compile on OpenBSD

include/open62541/server_config.h, src/server/ua_server_binary.c
If no endpoint with SecurityPolicy None is available, it shall be
possible to open a secure channel with SecurityPolicy None to perform
the discovery services GetEndpoints, FindServers and
FindServersOnNetwork. See issue #1936 for details.
=> [Review] Added possibility to use SecurityPolicy None for discovery only

src/server/ua_subscription_events.c
Fixes recursive lock inside UA_Server_evaluateWhereClauseContentFilter
=> Small fix for evaluateWhereClauseContentFilter

include/open62541/server.h, src/server/ua_services_nodemanagement.c, tests/server/check_services_nodemanagement.c
In callbacks the userland needs its context.  The node lifecycle
callbacks often use the server's admin session.  Unfortunatey the
API does not provide a possiblility to set the handle of the admin
session, so the context in the lifecycle callbacks is always NULL.
As the admin session is not part of the config it cannot be set
like the callbacks.  Provide an additional server method
UA_Server_setGlobalNodeLifecycle() that sets both, the callbacks
and the context.
=> feat(server): set admin session context

debian/control-template, debian/rules-template
Currently the official debian packages (https://launchpad.net/~open62541-team/+archive/ubuntu/daily) do not include encryption. This PR adjust the dependecies to build these packages with encryption support. The missing encryption leads to errors like this:
`/usr/bin/c++  -O3 -DNDEBUG   CMakeFiles/testOPCUA.dir/simpleClient.C.o  -o testOPCUA -lopen62541 
CMakeFiles/testOPCUA.dir/simpleClient.C.o: In function `setupClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, …
=> fix(debian package) Enable encryption for the official debian packages

debian/control-template
There mustn't be a newline in the first block.
Otherwise the PPA build fails with:
```
dpkg-source: error: syntax error in recipe/debian/control at line 21: block lacks the 'Package' field
dpkg-buildpackage: error: dpkg-source -i -I --before-build recipe gave error exit status 25
```
/cc @andreasebner
=> fix(ci): Fix ppa build error. Regression from #3622

src/ua_types_encoding_binary.c
If the UInt16 namespaceIndex of a QualifiedName did not fit into a
chunk, it was omitted in the next chunk because the return code was not
checked and the string / array encoding would overwrite the last known
good position.
=> fix(core): fix QualifiedName encoding at chunk end

src/server/ua_services_session.c
Got this issue report from a contact.
```
memcpy(&tokenSecretLength, decryptedTokenSecret.data, sizeof(UA_UInt32));
```
data contains the length in little endian. On big endian systems simple memcpy doesn't work.
`UA_UInt32_decodeBinary` correctly handles endianess depending on the `UA_BINARY_OVERLAYABLE_INTEGER` value.
Will be ported to master in the next 1.1 to master merge
=> fix(core): Correct decrypt of security token on big endian

plugins/include/open62541/plugin/log_syslog.h, plugins/ua_log_syslog.c
A library should not call openlog(3).  It is the program's job to
do this once at startup.  There it can select its ident, logopts
and facility.  Remove the call and its parameter from UA_Log_Syslog()
and UA_Log_Syslog_withLevel().  Write in the documentation that
openlog(3) must be called before.
=> fix(plugin): Do not call openlog from syslog plugin

src/client/ua_client_connect.c
If the program did not set the client default config before calling
UA_Client_connect(), the program crashed due to a initConnectionFunc
NULL pointer.  This is a regression to the 1.0 behavior.  Better
log the problem in initConnect() and return internal error to give
the user a hint what went wrong.
=> fix(client): Check client config is set before connecting

CMakeLists.txt, plugins/include/open62541/plugin/securitypolicy_default.h, plugins/include/open62541/server_config_default.h, plugins/securityPolicies/openssl/ua_openssl_aes128sha256rsaoaep.c, plugins/securityPolicies/ua_securitypolicy_aes128sha256rsaoaep.c, plugins/ua_config_default.c, tests/CMakeLists.txt, tests/encryption/check_encryption_aes128sha256rsaoaep.c, tests/fuzz/CMakeLists.txt
- Aes128Sha256RsaOaep security policy tested against UaExpert, OPCF reference client and UA browser.
- Unit test added for the same
- Symmetric encryption algorithm Uri is corrected in 'Basic256Sha256' policy
=> Add 'Aes128Sha256RsaOaep' security policy

CMakeLists.txt, tools/cmake/FindMbedTLS.cmake, tools/cmake/open62541Config.cmake.in
If build with encrpytion and MbedTLS backend, search for MbedTLS when including the CMake package in a project.
"mbedtls::" forces cmake to look for the target and do not fall back to library. At the moment when building the library "mbedtls" is a target that resolves to the path of library. But when including open62541 in another project, cmake falls back to library seach, as no target "mbedtls" is defined. This causes problems (especially on windows) when mbedtls is not on the well known library path. (See #3364)
=> Search for MbedTLS when using CMake module #3364

tools/nodeset_compiler/nodes.py
The nodeset_compiler parsing code now correctly constructs the `__definition__`
Python attribute of a `DataTypeNode` if the input UANodeSetXML satisfies the following conditions:
1. The nodeset contains a datatype node in which another datatype node is nested.
2. The enclosing datatype node is located before the nested datatype in the UANodeSetXML.
Fixes #3716
=> fix(nc): correct nested datatype definition parsing

include/open62541/client.h, include/open62541/client_subscriptions.h
client section:
* mention connection management in relation to async events
* refer to client-async-services section
* don't mention deprecated call *_manuallySendPublishRequest()
client-async-services section:
* note about response order being determined by server
* mention possible handling in synchronous calls
* mention UA_Client_run_iterate() for explicit handling
* highlight need of calling UA_Client_run_iterate() for SecureToken renewal
client-subscriptions section:
* don't mention deprecated call *_runAsync()
* refer to client-async-services section
=> fix(doc): elaborate on asynchronous event handling

arch/network_tcp.c, tests/server/check_server_userspace.c
It should be possible to bind to a specific address instead of
always using a * socket for TCP listen.  Reuse the customHostname
of the server config.  That means that the hostname in the server
URL must be an IP address or resolveable by DNS.  The client also
puts the hostname of the URL into getaddrinfo(3) so this should not
be a problem.  Behavior changes if the customHostname was used to
create a discoveryUrl before.  Then it will be used to additionally
bind the address now.
I need this feature to build a proxy firewall that has several interface addresses. The OPC UA server should only listen on one of these.  Combining the bind address with the FQDN or IP addess in the URL seems reasonable to me.  If you disagree I could also try to extend the config and pass a second hostname down …
=> feat(server:) Use config customHostname to bind server address

src/pubsub/ua_pubsub_ns0.c
Life cycle is an English word, live cycle is a typo.
=> refactor(pubsub): rename liveCycle to lifeCycle

include/open62541/server.h
Resolves #3687, it feels like I missed many places, does this only occure twice?
=> Fix (documentation): Pass UA_NODEID_NUMERIC(X,0) for a unused NodeId in namespace X (#3687)

src/client/ua_client_connect.c
Some servers send a securityPolicyUri even with tokenType UA_USERTOKENTYPE_ANONYMOUS which doesn't make sense at all.
An open62541 based client should be able the connect to such servers anyway
Duplicate of #3788 for the 1.0 branch.
=> fix(client): don't check security policy for anonym token type

src/server/ua_services_nodemanagement.c
recursiveCallConstructors calls constructors for all unconstructed **child** nodes of a (parent) node recursively. Hence it determins the type of the child node in [line 1115](https://github.com/open62541/open62541/blob/master/src/server/ua_services_nodemanagement.c#L1115). So only typed children (variable and object node classes) have to be checked.
Before the fix the decission was based on the parent node class, which leads to errors, if a child is a method node for example.
This error occured while trying to load the PackML Companion Specification for the ExecuteState in PackMLMachineStateMachineType and should even be fixed in upcomming v1.1.2 updates.
=> Fix: BadTypeDefinitionInvalid for methods in instance declarations

CMakeLists.txt, examples/custom_datatype/custom_datatype.h, include/open62541/types.h, src/client/ua_client.c, src/server/ua_server_binary.c, src/server/ua_services_attribute.c, src/ua_securechannel.c, src/ua_timer.c, src/ua_types_encoding_binary.c, tests/check_securechannel.c, tests/check_types_custom.c, tests/fuzz/ua_debug_dump_pkgs_file.c, tools/nodeset_compiler/backend_open62541_typedefinitions.py, tools/nodeset_compiler/type_parser.py
This is a breaking change for those using custom datatypes.
The change is necessary for the use case of #3787.
=> [BREAKING] feat(core): Allow all types of NodeId for the binary encoding identifier

src/server/ua_server_internal.h, src/server/ua_server_utils.c, src/server/ua_services_nodemanagement.c, tests/server/check_node_inheritance.c
A HasInterface reference can be on an ObjectType (already supported) and on an Object (not yet supported).
This PR adds support for HasInterface on an Object.
See https://reference.opcfoundation.org/v104/Core/docs/Amendment7/4.9.2/
=> feat(server): Add support for HasInterface on Object
