open62541/open62541

tools/cmake/FindMbedTLS.cmake

If open62541 is included multiple times with find_package, the target may be created multiple times and cmake complains.

fix(cmake): Only add mbedtls targets if they do not exist yet.

---

plugins/securityPolicies/openssl/ua_pki_openssl.c

If the value is not set to NULL, a heap-use-after-free occurs in UA_CertificateVerification_clear().

Fix segfault in ua_pki_openssl.c

---

tools/valgrind_check_error.py

Do not use re.DOTALL so only one line will match and the rest of the content is kept
THis is the reason valgrind is not outputing the content when a failure occur. This can be seen in #3841 where the jobs now output the content after the same change was pushed there

Fix python regex removing all content

---

CMakeLists.txt

Currently, UA_ENABLE_ENCRYPTION_* must be activated to have the encryption plugins included into the amalgamation files.
These two options allow to include the encryption plugins without activating them. This allows the application including the amalgamation files to decide if encryption should be activated or not.

Add option to include encryption plugins into the amalgamated files

---

plugins/securityPolicies/securitypolicy_mbedtls_common.h

Missing mbedTLS headers would break the amalgamation build if UA_ENABLE_ENCRYPTION is used in combination with UA_ENABLE_ENCRYPTION_OPENSSL.

Fix amalgamation

---

arch/network_tcp.c
arch/network_ws.c
tests/testing-plugins/testing_networklayers.c

The initial value of a socket should be UA_INVALID_SOCKET and not 0 nor -1. Also, when checking that, the macro is used
I also removed some non-needed local variables.
This was triggered by #3777

[Review] fix(arch): Use UA_INVALID_SOCKET where needed

---

plugins/securityPolicies/openssl/securitypolicy_openssl_common.c
plugins/securityPolicies/openssl/securitypolicy_openssl_common.h
plugins/securityPolicies/openssl/ua_openssl_basic128rsa15.c
plugins/securityPolicies/openssl/ua_openssl_basic256.c
plugins/securityPolicies/openssl/ua_openssl_basic256sha256.c
plugins/securityPolicies/openssl/ua_pki_openssl.c

PEM currently does not work for the local certificate because the UA_ByteString holding the certificate file content is sent directly to the communication partner and part 6 states that a certificate must be DER encoded.
If necessary, this could be made possible by converting a loaded PEM encoded local certificate to DER.

OpenSSL PEM support

---

plugins/securityPolicies/openssl/securitypolicy_openssl_common.c
plugins/securityPolicies/openssl/securitypolicy_openssl_common.h
plugins/securityPolicies/openssl/ua_openssl_basic128rsa15.c
plugins/securityPolicies/openssl/ua_openssl_basic256.c
plugins/securityPolicies/openssl/ua_openssl_basic256sha256.c
plugins/securityPolicies/securitypolicy_mbedtls_common.c
plugins/securityPolicies/securitypolicy_mbedtls_common.h
plugins/securityPolicies/ua_securitypolicy_basic128rsa15.c
plugins/securityPolicies/ua_securitypolicy_basic256.c
plugins/securityPolicies/ua_securitypolicy_basic256sha256.c

The buffer containing the local certificate is directly added to OPC UA messages without further conversion.
According to Part 6 of the specification, the required encoding for certificates is DER, so a conversion is necessary for PEM encoded local certificates.

Add support for PEM encoded local certificates

---

src/server/ua_subscription_monitoreditem.c

This enable deleting new notifications, that have no values assigned, e.g. 
```cpp
UA_Notification *pNotification = UA_Notification_new();
// Do nothing with the notification
UA_Notification_delte(pServer, pNotification);
```
This was the case here:
https://github.com/open62541/open62541/blob/03a655667e91cd5ccb8221d919fa2ac6d5a00698/src/server/ua_subscription_events.c#L486-L496

Fix: Delete new notification

---

src/server/ua_subscription_events.c

The current event implementation uses UA_Server_readProperty which can lead to a double lock situation and therefore to a server crash. Since UA_Server_readProperty is used in an internal function we can switch to the internal readProperty which uses no locks.

fix(server) subscription events double lock in multithreading environments

---

tools/nodeset_compiler/backend_open62541_datatypes.py

E.g., EUInformation has struct members like `namespaceUri` which would become `namespaceuri` and therefore the generated code doesn't compile.

fix(nodeset_compiler): only set first char to lowercase of struct member

---

tools/certs/create_self-signed.py
tools/nodeset_compiler/backend_open62541.py
tools/nodeset_compiler/backend_open62541_nodes.py
tools/nodeset_compiler/datatypes.py
tools/nodeset_compiler/nodes.py
tools/nodeset_compiler/nodeset_compiler.py

I tried to build the RPM for Fedora Linux, but got the following error:
```
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
*** ERROR: ambiguous python shebang in /usr/share/open62541/tools/certs/create_self-signed.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
*** ERROR: ambiguous python shebang in /usr/share/open62541/tools/nodeset_compiler/nodeset_compiler.py: #!/usr/bin/env python. Change it to python3 (or python2) explicitly.
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.7d5fka (%install)
```
Therefore it makes sense to change the shebangs in the Python scripts explicitly to version 3.

Change the Python shebangs to Python version 3 explicitly.

---

include/open62541/server_pubsub.h
include/open62541/types.h
src/pubsub/ua_pubsub_reader.c
src/pubsub/ua_pubsub_writer.c
src/ua_types.c
tests/CMakeLists.txt
tests/check_types_builtin.c
tests/pubsub/check_pubsub_get_state.c

Added a getState method for following PubSub components:
ReaderGroup, DataSetReader, WriterGroup, DataSetWriter
Open questions:
- Naming convention of PubSub public functions
e.g.: UA_Server_removeWriterGroup vs. UA_Server_updateWriterGroupConfig
or UA_Server_getDataSetWriterConfig vs. UA_Server_DataSetWriter_getState
- UA_Server_setWriterGroupOperational and UA_Server_setReaderGroupOperational
These functions set the linked DataSetWriters and -Readers state as well
But in most tutorials the DataSetWriters- and Readers have been added after setting the group to operational, so their state is still disabled. Calling setOperational() function again does not change this at the moment, because nothing happens if the state is already operational
Shall we change the setOperational() methods to …

PubSub component getState

---

debian/control-template

`tools/certs/create_self-signed.py` depends on `python3` so the package `libopen62541-1-tools` must depend on `python3 `as well

fix(debian): a tools script depends on python3 so package must as well

---

CMakeLists.txt

Only check for (and potentially enable) IPO if the variable has
not been set yet. This allows to disable IPO on the commandline.
Reasoning: a consumer of the open62541 static library might decide
to not enable IPO. Currently open62541 is, via the requirement
that all objects files are IPO, forcing the consumer to also enable
IPO.

Allow to disable IPO on the commandline

---

tools/cmake/macros_public.cmake

Added IMPORT_BSD as multiValueArgs in CMake macro (ua_generate_nodeset_and_datatypes).

fix(datatype_generator): allow multiple imported bsd when generating dataTypes with NodeSet

---

CMakeLists.txt
include/open62541/plugin/pubsub.h
include/open62541/server.h
include/open62541/server_pubsub.h
plugins/ua_network_pubsub_mqtt.c
plugins/ua_pubsub_ethernet.c
plugins/ua_pubsub_ethernet_etf.c
plugins/ua_pubsub_ethernet_xdp.c
plugins/ua_pubsub_udp.c

The plugin header is freestanding. The server_pubsub.h adds definitions
on top of server.h.

refactor(pubsub): Sane include order for PubSub definitions

---

CMakeLists.txt
plugins/securityPolicies/openssl/securitypolicy_openssl_common.c
plugins/securityPolicies/securitypolicy_mbedtls_common.c
plugins/securityPolicies/ua_securitypolicy_none.c

If UA_ENABLE_ENCRYPTION_MBEDTLS is set, SecurityPolicy None will still just copy the certificate data.
If the input is PEM, the trailing null byte is not added and mbedTLS will fail to parse the data. This breaks the application URI check on server start.
In case of UA_ENABLE_ENCRYPTION_OPENSSL, there is a similar problem
if the PEM data is just copied into the local certificate byte string.

Fix PEM certificate handling for SecurityPolicy None

---

tools/cmake/open62541Config.cmake.in

The default cmake version on ubuntu 16.04 is version 3.5 which doesen't support the 'GREATER_EQUAL' comparison. Therefore find_package(open62541) fails on ubuntu 16.04.

Legacy support for older cmake versions

---

plugins/historydata/ua_history_data_backend_memory.c
plugins/historydata/ua_history_data_gathering_default.c

- The members of the context are freed, but the context itself is not.
- After extending memory with realloc, the new memory is not initialized

Fix memory issues in the historical data plugins

---

open62541.pc.in

The current generated pkg-config file seems to be incorrect and this breaks the library usage for systems that rely on pkg-config output for autoconfiguration.
The template now includes:
```
prefix=@CMAKE_INSTALL_PREFIX@
...
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
...
Cflags: -I${includedir}/open62541
```
So points to `include/open62541`. But then in some include files, for example `client.h` it is assumed to be one level under, for example:
```
#define UA_CLIENT_H_
#include <open62541/config.h>
#include <open62541/nodeids.h>
#include <open62541/types.h>
```
Or in similar way in example `client.c`:
```
#include <open62541/client_config_default.h>
#include <open62541/client_highlevel.h>
```
This PR fixes the pkg-config template file.
To reproduce one should do a build using …

Fix pkg-config include configuration directory

---

tools/nodeset_compiler/backend_open62541_typedefinitions.py

This fixes C2466 in Visual Studio, when compiling an bsd-File without types:
```xml
<opc:TypeDictionary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://opcfoundation.org/UA/Machinery/" DefaultByteOrder="LittleEndian" xmlns:opc="http://opcfoundation.org/BinarySchema/" xmlns:ua="http://opcfoundation.org/UA/" TargetNamespace="http://opcfoundation.org/UA/Machinery/">
<opc:Import Namespace="http://opcfoundation.org/UA/"/>
</opc:TypeDictionary>
```
>types_machinery_generated.h(22,79): error C2466: Zuordnung eines Arrays der konstanten Größe 0 nicht möglich.
```C
#ifndef TYPES_MACHINERY_GENERATED_H_
#define TYPES_MACHINERY_GENERATED_H_
#ifdef UA_ENABLE_AMALGAMATION
#include "open62541.h"
#else
#include <open62541/types.h>
#include <open62541/types_generated.h>
#endif …
```

Fix: Prevent array size 0, when no types are defined in a bsd file

---

src/ua_types_encoding_binary.c

DiagnosticInfo Encoding Mask description: ..., 0x20 InnerStatusCode, 0x40 InnerDiagnosticInfo
actual DiagnosticInfo Encoding: ..., 0x20 InnerDiagnosticInfo and InnerStatusCode is missing

Bugfix: setting up of encodingMask from DiagnosticInfo 

---

plugins/ua_pubsub_ethernet.c

UA_PubSubChannelEthernet_receive() returns an uninitialized value
(retval), if  there is more data available than fits into the
message buffer.
Control flow in case of the error:
Receive buffer size is 4096 - see UA_ReaderGroup_subscribeCallback.
timeout > 0
select resultsize > 0
recvmsg datalen > 0
remainingMessageLength >= 1496 -> false -> there is still more data

fix(plugin): use of uninitialized value

---

include/open62541/plugin/securitypolicy.h
plugins/crypto/openssl/ua_openssl_aes128sha256rsaoaep.c
plugins/crypto/openssl/ua_openssl_basic256.c
plugins/crypto/openssl/ua_openssl_basic256sha256.c

There is a small typo in include/open62541/plugin/securitypolicy.h, plugins/crypto/openssl/ua_openssl_aes128sha256rsaoaep.c, plugins/crypto/openssl/ua_openssl_basic256.c, plugins/crypto/openssl/ua_openssl_basic256sha256.c.
Should read `endpoint` rather than `endpoit`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, endpoit -> endpoint

---

include/open62541/architecture_functions.h

The "UA_" prefix was omitted in the declarations of 2 architecture wrapper functions, what results in failed build in case any of the affected functions are enabled. Added the prefix to match all other functions.

Bugfix for a typo that results in failed build of specific architectures

---

tools/nodeset_compiler/backend_open62541.py
tools/nodeset_compiler/backend_open62541_typedefinitions.py

This handles nodesets without datatypes (e.g. machinery, #4054). So this code does no longer causes errors:
```c
static UA_DataTypeArray customUA_TYPES_MACHINERY = {
NULL,
UA_TYPES_MACHINERY_COUNT,
UA_TYPES_MACHINERY
};
```
I've also noticed (but not modified), that the types are added multiple times, if nodesets depend on others, e.g. (Industrial Automation depends on DI):
- Calling namespace_di_generated add UA_TYPES_DI
- Calling namespace_ia_generated add UA_TYPES_IA and UA_TYPES_DI (again)
Is this intended? As `namespace_di_generated` must be called before `namespace_ia_generated` this seems to be redundant.
The `if(UA_TYPES_MACHINERY_COUNT)` is required, as the corresponding python-Variable is only available in `backend_open62541_typedefinitions.py` and not in `backend_open62541.py` …

Handle nodesets without datatypes (#4054)

---

src/server/ua_services_securechannel.c

(supersedes #4085)
With bad timing, a secure channel was "garbage collected" by the `UA_Server_cleanup `timer (runs every 10 seconds) while the channel was still being established.
This issue was detected by our stress tests that continuously connect and disconnect to the same server instance. It is easily reproducible by changing the `UA_Server_cleanup `interval to some small number, e.g. 
/* Add a regular callback for cleanup and maintenance. With a 10s interval. */
UA_Server_addRepeatedCallback(server, (UA_ServerCallback)UA_Server_cleanup, NULL,
0.001, NULL);

Fix sporadically failing connection attempt to server (1.2)

---

src/server/ua_services_attribute.c
src/server/ua_services_nodemanagement.c

Compiling open62541 with UA_ENABLE_AMALGAMATION=ON and  UA_LOGLEVEL=400 cause the error :
```
Scanning dependencies of target open62541-object
[ 65%] Building C object CMakeFiles/open62541-object.dir/open62541.c.o
/home/btc/open62541/b/open62541.c: In function ‘copyAttributeIntoNode’:
/home/btc/open62541/b/open62541.c:37890:56: error: suggest braces around empty body in an ‘if’ statement [-Werror=empty-body]
UA_StatusCode_name(retval));
^
/home/btc/open62541/b/open62541.c: In function ‘typeCheckVariableNode’:
/home/btc/open62541/b/open62541.c:40887:85: error: suggest braces around empty body in an ‘if’ statement [-Werror=empty-body]
nodeIdStr.data, UA_StatusCode_name(retval)));
^
/home/btc/open62541/b/open62541.c: At top level:
cc1: error: unrecognized command line option …
```

fix empty-body

---

plugins/crypto/openssl/ua_openssl_aes128sha256rsaoaep.c

Compiling open62541 with AMALGAMATION and OPENSSL cause :
```
../../src/libs/open62541.c: In function ‘UA_AsySig_Aes128Sha256RsaOaep_getLocalSignatureSize’:
../../src/libs/open62541.c:60261:12: error: ‘keyLen’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
return (size_t)keyLen;
^~~~~~~~~~~~~~
../../src/libs/open62541.c: In function ‘UA_AsymEn_Aes128Sha256RsaOaep_getLocalKeyLength’:
../../src/libs/open62541.c:60540:12: error: ‘keyLen’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
return (size_t)keyLen * 8;
^~~~~~~~~~~~~~
../../src/libs/open62541.c: In function ‘UA_AsymEn_Aes128Sha256RsaOaep_getRemoteBlockSize’:
../../src/libs/open62541.c:60287:12: error: ‘keyLen’ may be used uninitialized in this function [-Werror=maybe-uninitialized] …
```

Fix keyLen may be used uninitialized

---

include/open62541/client.h
src/client/ua_client.c

This pull request adds a new function `UA_Client_modifyAsyncCallback`, which can modify the callback of an ongoing async request. 
So a user can modify a callback, when the original callback/ userdata is no longer valid.
In my use case I have an instance, which issues a method call on construction. When the instance is destroyed, before the request is completed, the callback/userdata-Information is no longer valid (userdata is the this-pointer of the instance). With this method, I do set the async callback and userdata to NULL in the destructor, so the response is ignored.

Add UA_Client_modifyAsyncCallback

---

CMakeLists.txt
include/open62541/server.h
src/server/ua_services_attribute.c
src/server/ua_subscription.h
src/server/ua_subscription_alarms_conditions.c
src/server/ua_subscription_events.c
src/server/ua_subscription_monitoreditem.c
tests/server/check_server_alarmsconditions.c
tests/server/check_subscription_events.c

Fixes building shared library with multicast discovery.
Before this fix, `mdnsd_config.h` looks like this:
```c
/* We are building this library */
/* We are using this library */
```
Now it is the same as building mdns:
```c
/* We are building this library */
/* We are using this library */
```
So these lines have the desired effect:
https://github.com/open62541/open62541/blob/19c006a330b110d9df4e71f680d2ac90eeedaf95/CMakeLists.txt#L1284-L1287
Added/updated copyright for these past commits by me:
40cb2f0e46ccdb04ecfe4fcf5a133257aeed3ab1
0c10b3ea408741abcb339bf53e9975969ae09c01
a524accc338c9611a5ec60bf595c1a587243b457
1e29c3329a0e4ef649b859da31b0562849277c7f
3598c1677e301de0f48c83b3948a1955aa5c8492
PS: Is it intended that Python and CMake files have no license header?

Fix: Build shared library with discovery multicast

---

arch/vxworks/ua_architecture.h
arch/vxworks/ua_architecture_functions.c
examples/pubsub_realtime/pubsub_interrupt_publish.c
examples/pubsub_realtime/vxworks/pubsub_interrupt_publish_tsn.c
plugins/ua_pubsub_ethernet.c

VxWorks TSN publisher example was developed based on v1.1.2.
There are several refactors between v1.1.2 and v1.2, which have impact on VxWorks TSN publisher.
Some alignment work has to be done here.

[Review] Align VxWorks TSN publisher example with v1.2

---

src/server/ua_services_session.c

According to OPCUA spec 1.04 Part 4 page 162 the
EncryptionAlgorithm field in the UserIdentityToken shall be
"No encryption" if the SecurityPolicy is "None".
Currently the stack does not care about this field if the
SecurityPolicy is "None".
This triggers an error in OPC UA CTT Version 1.4.9.396
Security - Security User Name Password - Test Case 010.
In this test the EncryptionAlgorithm in the
UserIdentityToken is set to "abc123" and the test expects
the login attempt to fail.

Fix(Server): Check EncryptionAlgorithm is empty

---

CMakeLists.txt
examples/CMakeLists.txt

This will fix the following build failure:
```
CMake Error at CMakeLists.txt:2 (project):
The CMAKE_CXX_COMPILER:
/srv/storage/autobuild/run/instance-3/output-1/host/bin/arm-linux-g++
is not a full path to an existing compiler tool.
Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.
```
Fixes:
- http://autobuild.buildroot.org/results/86ca6a5a01ecfc7030c6be0da81924436b41d057
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

CMakeLists.txt: fix build without C++

---

arch/posix/CMakeLists.txt

Fix the following build failure without threads:
```
[100%] Linking C shared library bin/libopen62541.so
/home/buildroot/autobuild/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/arm-buildroot-linux-uclibcgnueabihf/8.3.0/../../../../arm-buildroot-linux-uclibcgnueabihf/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
CMakeFiles/open62541.dir/build.make:192: recipe for target 'bin/libopen62541.so.0.0.0' failed
make[3]: *** [bin/libopen62541.so.0.0.0] Error 1
```
Fixes:
- http://autobuild.buildroot.org/results/87ec3c987c991f790757276316d6caf81e635fa2
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

arch/posix/CMakeLists.txt: fix build without threads

---

include/open62541/server.h
src/server/ua_server_ns0.c
src/server/ua_subscription_monitoreditem.c
tests/server/check_subscription_events.c

Fix as discussed here: https://apps.opcfoundation.org/mantis/view.php?id=4206 (#4118)
Shall this be merged to master or 1.2? If the 1.2 should be used for the CTT-Tests of events it might be usefull there, as the issue (#4118)  was initially discovered in conjunction with CTT tests ("unknown event").
PS: I hope that I got the commit message format right this time.

fix(server): Replace SimpleOverflowEventType by EventQueueOverflowEventType #4118

---

debian/control-template
debian/rules-template

This PR extends the packaging configurations to enable the use of stable (1.1) debian packages togetehr with mbedtls based encryption support.

Backport support of encryption in debian packages

---

.github/workflows/build_linux.yml
tools/ci.sh

Update to ubuntu 20.04 for github actions (latest)
As python2-sphinx and clang++-10 is no longer available, I used python3 and clang-11
The exact version for ubuntu is set, as latest is sometimes ubuntu18.04 and sometimes ubuntu20.04 depending on the repository.
PS: Should the 1.2 branch stay on ubuntu18.04? If not, I can move this to 1.2.

Fix(ci) for ubuntu20.04

---

examples/custom_datatype/custom_datatype.h
src/ua_types.c
src/ua_types_encoding_binary.c
tests/check_types_custom.c
tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c
tests/nodeset-compiler/testnodeset.csv
tests/nodeset-compiler/testnodeset.xml
tests/nodeset-compiler/testtypes.bsd
tools/cmake/macros_public.cmake
tools/nodeset_compiler/backend_open62541_datatypes.py
tools/nodeset_compiler/backend_open62541_nodes.py
tools/nodeset_compiler/backend_open62541_typedefinitions.py
tools/nodeset_compiler/type_parser.py

This is my suggestion on how to handle the problem described in #3973.
There are two important things to observe with self containing structs:
- The field must be an array (which means that the member will become a pointer)
- A forward declaration must be added instead of doing definition and typedef in one step
The second commit in this PR is related to problems that occur if a struct has a field named "Double", "Int", "Float" or "Char".

Support self containing structs in the nodeset compiler

---

arch/network_tcp.c

no much to add.  There is a missing check for IPv6 when using a ipv6 type

Add missing #if UA_IPV6

---

arch/win32/ua_architecture.h
arch/win32/ua_clock.c
include/open62541/architecture_definitions.h

Embarcadero C++Builder 10.4 (clang 5.0 / win32) has a few incompatibilities in its standard library, which prevents building Open62541 on this compiler.
I would like to suggest two small additions to the architecture definition files to fix build on this compiler. The changes do not break existing behavior and are guarded by `#ifdef __CODEGEARC__` to only become active for this compiler.
I would also like to add a fix for a bug in the gmtime_s() call in the arch/win32/ua_clock.c file - the call uses the wrong parameter order.

fix(arch): Fix architecture definitions for Embarcadero C++Builder clang/win32

---

plugins/ua_pubsub_ethernet.c
plugins/ua_pubsub_ethernet_xdp.c
src/pubsub/ua_pubsub_reader.c

- Changed ethertype from LLC to ETHERTYPE_UADP(0xb62c) according to PubSub Specification
- Handled the padding bytes in the src file

[Review] Send ethernet packets with ethertype 0xb62c in PubSub

---

src/ua_types_encoding_binary.c

I had the following compiler warning when cross compiling from ubuntu to armv7l with clang
`implicit conversion from 'long long' to 'long double'`
The warning is fixed by explicitly casting the divisor.

explicit cast to avoid compiler warning

---

src/server/ua_services_nodemanagement.c

This PR extends the current implementation of the DeleteNode operation. Deleting nodes is done in two phases:
1. Calling the Destructors.
2. Delete the child nodes and the node itself.
Both steps are currently using their own loop and browse services calls to walk recursively over the information model. This PR introduces a new step which prepares the RefTree (containing all the child’s of the node) structure with an iterative walk over the information model. This RefTree is used in now used in both phases.
In addition, this PR solves a more substantial problem: If we delete a node, than all childs with only on incoming hierarchical reference can be deleted to. Let's assume the following information model:
A
-B
--C
-C
If we delete node "A" than node "C" can be also deleted because all …

feat(server) Use RefTree structure during node delete

---

src/server/ua_server_ns0.c

After bdb233e810a7c9f5187c2e53f0 several nodes are always removed, so the "FULL" Namespac 0 is no longer full and loading companion specifications complies about missing parent:
e.g. from here: https://github.com/umati/Sample-Server/pull/129/checks?check_run_id=2093072456#step:6:25
```c++
[2021-03-12 07:45:03.878 (UTC+0000)] info/session	SecureChannel 0 | Session g=00000001-0000-0000-0000-000000000000 | AddNode (ns=3;i=15001): Parent node not found
[2021-03-12 07:45:03.878 (UTC+0000)] info/session	SecureChannel 0 | Session g=00000001-0000-0000-0000-000000000000 | AddNode (ns=3;i=15001): The parent reference for is invalid
[2021-03-12 07:45:03.878 (UTC+0000)] info/session	SecureChannel 0 | Session g=00000001-0000-0000-0000-000000000000 | AddNode (ns=4;i=5008): Parent node not found …
```

fix(server): Keep Server Namespaces Object

---

include/open62541/server.h
plugins/ua_config_default.c
src/server/ua_services_nodemanagement.c

As the current version of the CCT does not like it, if there are HasModellingRule references on instances (it thinks the node is part of an instance declaration in a type definition), I added an option to suppress these references.
Only Nodes, which are not under the Types folder can omit this reference. In the default configuraiton, HasModellingRule are created in instances as before.

feat(server): Add modellingRulesOnInstances option, to omit HasModellingRule references in created instances

---

tools/certs/localhost.cnf

As per discussion in the OpenSSL issues [forum](https://github.com/openssl/openssl/issues/7754), it says that OpenSSL version 1.1.1 does not require RANDFILE configurations anymore.
- RANDFILE configuration causes error: 'Can't load /root/.rnd into RNG' (as shown below)
- After the fix the error get resolved (as shown below)

Update the localhost.cnf

---

arch/posix/ua_architecture_functions.c
arch/vxworks/ua_architecture_functions.c
arch/win32/ua_architecture_functions.c

Export malloc singleton function pointers, otherwise there are not
visible if we use shared object library build.

Export malloc singleton function pointers

---

plugins/ua_accesscontrol_default.c
src/server/ua_services_nodemanagement.c

AddressSanitizer detected two memory leaks when using open62451.
- The first one occurs when string IDs are used when creating child nodes. If this is the case, the NodeId must be cleaned up.
- The second case occurs when using Encryption, when calling UA_AccessControl_default, new memory is allocated, but before that it is not checked if memory has already been allocated elsewhere for the UA_AccessControl struct. Therefore, it must be ensured that the UA_AccessControl is clean at the beginning.

Fix: Fix memory leaks detected by AddressSanitizer.

---

src/client/ua_client_connect.c

Make the print more user friendly by explicitly mentioning the selected endpoint number

Print the selected endpoint number

---

plugins/ua_pubsub_ethernet.c

On frame reception, check if current PubSubConnection is for multicast or unicast and based on that apply correct filter condition.
Closes #4325

fix(pubsub): source vs destination address filtering on reception

---

arch/eCos/ua_architecture.h
arch/posix/ua_architecture.h
arch/vxworks/ua_architecture.h
arch/wec7/ua_architecture.h
arch/win32/ua_architecture.h
include/open62541/architecture_functions.h
plugins/ua_pubsub_ethernet.c
src/pubsub/ua_pubsub_reader.c

Two new wrappers UA_recvmsg and UA_ioctl are added and reflected to architecture specific files.
In pubsub_ethernet.c replace the direct system calls with wrappers in all places which caused troubles on our platform. Some more refactoring may be needed to support any other platforms in future.
By the way, in ua_pubsub_reader.c replace the platform dependent alloca with an already existing wrapper UA_STACKARRAY.
Closes #4324

fix(pubsub): remove platform dependencies

---

CMakeLists.txt
include/open62541/config.h.in
src/server/ua_server.c
src/ua_util_internal.h

Adding the possibility to use specific macros to check for error codes.
The following macros do error-code or error-state checks without logging anything and just evaluating an additional parameter.
- `UA_CHECK`
- `UA_CHECK_MEM`
`UA_CHECK_MEM` can be used in cases where an `malloc/calloc/realloc` call return-value is checked.
Here the return code is checked and returns the error code itself if the check encounters an error code.
```c
static UA_StatusCode
foo() {
UA_StatusCode rv = some_func();
UA_CHECK(rv, return rv);
return UA_STATUSCODE_GOOD;
}
```
If there is the need for a cleanup routine one can simply jump to an according label like in this example:
```c
static UA_StatusCode
foo() {
void *data;
UA_StatusCode rv = some_func_which_allocates_memory(data);
// check jumps into cleanup …
```

[REVIEW] Adding macros for checking error codes

---

src/pubsub/ua_pubsub_reader.c

buffer.data is pointing to memory in the data segment.
UA_ByteBuffer_clear on that buffer is thus an illegal operation.

fix(pubsub): remove invalid free for non-heap mem

---

CMakeLists.txt

Testing source-file testing_networklayers.c breaks
build when UA_DEBUG_DUMP_PKGS is enabled because
of missing dependencies (e.g. testing_clock) which are
only build for the testing-build.

build: remove testing source from build script

---

.github/workflows/dependent-issues.yml

Workflow that allows for adding dependencies into a pull request.
An example pullrequest message might look like this:
```
Depends on #4420 
This pull request depends on integrating the pullrequest #4420.
```
The dependent-issues-bot will add a "dependent" label to this pullrequest an block until the dependency is integrated.
This way developers can create multiple separate pullrequests that depend on one another.
An example image of such a pullrequest with the according bot-action:

ci: dependant issues (allows dependent PRs)

---

src/pubsub/ua_pubsub_reader.c

Fix a memory leak induced by pubsub decryption where it didn't free the security policy context memory.

[REVIEW] fix(pubsub): fix readergroup mem leak

---

tools/amalgamate.py

Do not try to redefine _CRT_SECURE_NO_WARNINGS if it is already
defined (for instance through the command line / build system).
This prevents warnings like
open62541.c(25): warning C4005: '_CRT_SECURE_NO_WARNINGS': macro redefinition
Alternative: Remove the define altogether, because the same checks already exists in open62541.h which is included in the lines below?

MSVC: Do not redefine _CRT_SECURE_NO_WARNINGS

---

examples/pubsub/tutorial_pubsub_mqtt_publish.c

Fix the usage info for example: tutorial_pubsub_mqtt_publish
Signed-off-by: Pingfang Liao <winndows@163.com>

fix(ex): fix the usage info for example: tutorial_pubsub_mqtt_publish

---

arch/posix/ua_architecture.h

When using errno in logging its nice to clean it afterwards (= 0) and also check if errno is set at all (== 0).

[REVIEW] fix(core): clean errno after using the error code

---

examples/pubsub_realtime/pubsub_interrupt_publish.c

Adjusting the PubSub TransportLayers configuration for example: pubsub_interrupt_publish

fix(ex): adjusting the PubSub TransportLayers configuration for example: pubsub_interrupt_publish

---

src/pubsub/ua_pubsub_writer.c
tests/pubsub/check_pubsub_subscribe_rt_levels.c

Enabling the build option UA_ENABLE_JSON_ENCODING causes a memory leak at UA_PubSubDataSetWriter_generateKeyFrameMessage() if the fieldNameAlias parameter of a PublishedDataSetfield config
has been set.
`valgrind --tool=memcheck --track-origins=yes --leak-check=full --leak-resolution=high --num-callers=40 ./bin/tests/check_pubsub_subscribe_rt_levels `
`
100%: Checks: 2, Failures: 0, Errors: 0
==21995== 
==21995== HEAP SUMMARY:
==21995==     in use at exit: 15 bytes in 1 blocks
==21995==   total heap usage: 7,807 allocs, 7,806 frees, 4,836,763 bytes allocated
==21995== 
==21995== 15 bytes in 1 blocks are definitely lost in loss record 1 of 1
==21995==    at 0x4C2DBC5: calloc (vg_replace_malloc.c:711)
==21995==    by 0x11B71C: UA_Array_copy (ua_types.c:1362)
==21995==    by 0x1184CD: …

fix mem leak at freezeWriterGroup with UA_ENABLE_JSON_ENCODING enabled

---

src/pubsub/ua_pubsub_reader.c

The function checkReaderIdentifier needs the
GroupHeader, WriterGroupId and DataSetWriterId in the received message
to find the correct reader.
The check at the beginning shall verify that all of these are available.
But the check was wrong.
There a segfault can happen if for example the payload header is
disabled.
Now the check should be correct and return BADNOTIMPLEMENTED
if one of the mandatory parameters is not available in the received
message.

fix(pubsub): checkReaderIdentifier msg content check

---

arch/network_tcp.c
examples/pubsub_realtime/vxworks/pubsub_interrupt_publish_tsn.c
include/open62541/client_subscriptions.h
include/open62541/server_pubsub.h
include/open62541/types.h
src/server/ua_server.c
src/server/ua_subscription.c
tests/pubsub/check_pubsub_subscribe_msgrcvtimeout.c
tools/nodeset_compiler/nodes.py
tools/nodeset_compiler/nodeset_compiler.py

In most places in the repository, "cannot" is used.
This patch replaces the few occurrences of "can't" with "cannot" to provide a consistent user experience.

style: Consistently use "cannot"

---

plugins/ua_pubsub_udp.c
src/ua_util.c
tests/check_utils.c
tests/pubsub/check_pubsub_connection_udp.c

Hi,
currently PubSub over IPv6 Multicast on Linux doesn't work. Enable it.
Tested on Linux v5.10 with the PubSub examples.
Thanks, Kurt

fix(pubsub): Fix IPv6 Multicast Support

---

src/server/ua_server_internal.h
src/server/ua_server_utils.c
src/server/ua_services.h
src/server/ua_services_nodemanagement.c

This commit adds support for interfaces that are not directly
attached to the object type being instantiated.
fix(core): HasInterface reference on base type (#4363)

Look for HasInterface references in the type hierarchy

---

src/pubsub/ua_pubsub.h
src/pubsub/ua_pubsub_reader.c
tests/pubsub/check_pubsub_decryption.c

This is a (maybe temporary) minimally invasive fix for multiple network messages from different writergroups that arrive at the same time. For this to work the fix enables iteration over all configured readergroups and their dataset readers for decoding (verify and decrypt) and processing each network message in a current buffer.

[REVIEW] fix(pubsub): mutiple readers same network message

---

examples/CMakeLists.txt
examples/custom_datatype/custom_datatype.h
examples/pubsub/tutorial_pubsub_publish_raw.c
examples/server_ctt.c
include/open62541/types.h
src/pubsub/ua_pubsub_writer.c
src/server/ua_services_attribute.c
src/ua_types.c
src/ua_types_encoding_binary.c
src/ua_types_encoding_json.c
src/ua_types_print.c
tests/check_types_builtin_json.c
tests/check_types_custom.c
tests/server/check_local_monitored_item.c
tests/server/check_services_attributes.c
tools/nodeset_compiler/backend_open62541_typedefinitions.py

This PR is based on #4408 and the major work is done by @Johnsik. This PR is intended to fix the mentioned problems in the original PR and cleans up the history.
Currently DataTypes con only contain members of a type, which is declared in ns0 or the same ns like the DataType. This restriction is based on the use of an index which refers to the right type entry in the types array. This PR replaces this index and use a pointer which can now also point to other type arrays.

[Review] Use Pointer within the DataTypeMember structure

---

CMakeLists.txt
plugins/crypto/openssl/securitypolicy_openssl_common.c
plugins/crypto/openssl/ua_openssl_version_abstraction.h
plugins/crypto/openssl/ua_pki_openssl.c

This cleans up the version specific openssl-Code to a separate file and fixes compatabilit with openssl 1.0 (tested on Ubuntu 16.04 Docker)
I've removes this version distinguish, as the first one works just fine with the new API:
https://github.com/open62541/open62541/blob/b82ad4df1b751e9a301102b32fea518394d00c19/plugins/crypto/openssl/ua_pki_openssl.c#L179-L185
There were some 1.0 bugs, which I tried to fix, but as I do not have CTT available, I was not able to test this.
This code does not work with 1.0, as `X509_get_key_usage` has been introduced in 1.1.
https://github.com/open62541/open62541/blob/b82ad4df1b751e9a301102b32fea518394d00c19/plugins/crypto/openssl/ua_pki_openssl.c#L509-L513
This is my replacement, which should do the same: …

[Review] Fix(plugin): Openssl versions less than 1.1

---

src/pubsub/ua_pubsub_reader.c

If there are multiple connections within a multicast group all connections receive all network messages, even if not all of networkmessages are meant for a specific connection.
Therefore it's not always an error if a DataSetReader could not be found.
We may not return an error or clear the received buffer in this case. But have to continue decoding the received data.
In the last commit 7c1b2b428314153a71d0027dcfc738828953ced7 I have searched for the cause and pushed a wrong fix, because I forgot to set the PR back to WIP.
Therefore the commit is reverted now and a new commit has been added.
In general the decodeNetworkMessage function (with encryption enabled) shall behave like UA_Server_processNetworkMessage, which only logs an information that the DataSetReader could not be found, but …

PubSub multicast configuration (encryption): process all network messages

---

tools/nodeset_compiler/datatypes.py

According to Section 5.33 of the OPC UA specification 10000-6, enumerations can be encoded as strings in the following format: `<symbol>_<value>`. This format is used by the UaModeler for enumerations that are nested in structures. As of yet, the XML Nodeset Compiler does not correctly interpret this encoding.
This pull request modifies the way the Nodeset Compiler parses Int32 values from XML elements to take into account the string encoding. The extension only concerns Int32 values since it's the datatype used for storing values of enumerations.
The following snippet of a nodeset XML exported by UaModeler serves to illustrate the issue. First, a custom enumeration Enum and structure StructEnum that holds an Enum are defined. Next, an instance of the new structure AStructEnum is created. …

fix(nc): add conformance to OPC 10000-6

---

src/pubsub/ua_pubsub_ns0.c

A minor fix here: published datasets should be connected via hasComponent reference

(fix) fixing pubsub dataset representation in information model

---

include/open62541/common.h
tools/nodeset_compiler/backend_open62541_nodes.py

Adding the various EventNotifier attributes in the code generation to indicate if the Node can be used to subscribe to Events or read/write historic Events.

fix(nodeset_compiler): Adding the various EventNotifier attributes in the code generation

---

tools/nodeset_compiler/backend_open62541_datatypes.py

Line breaks in value fields of type string are encoded with two backslashes.
This leads to the string "\n" being transmitted as actual value if the value is not overwritten by callbacks.
I assume this behaviour is not intentional, because a similar fix was already introduced for quotes and slashes in 2033d6a41326d472ddbfca7b0b93767d5cff41c9
See also the python reference https://docs.python.org/3/reference/lexical_analysis.html
> Both string and bytes literals may optionally be prefixed with a letter 'r' or 'R'; such strings are called raw strings and treat backslashes as literal characters. 
Example XML:
<UAVariable NodeId="ns=1;i=2013" BrowseName="1:TestNode" ParentNodeId="ns=1;i=1001" DataType="String">
<DisplayName>TestNode</DisplayName>
<Description>TestNode</Description>
<References> …

fix(nc): Remove additional backslash in line breaks inside string values

---

src/server/ua_server_ns0.c

The I4AAS companion specification depends on the Dictionaries object of the OPC UA Nodeset2 specification. Commit [bdb233e](https://github.com/open62541/open62541/commit/bdb233e810a7c9f5187c2e53f021c71abdefba80#diff-78df7143ea0c91caf7c6e0969cd003ad1265cbdb359a2fa529228c5263734dfe) removed this node and therefore breaks compatibility to the I4AAS specification.

fix(server): revert removal of Dictionaries object

---

.github/workflows/build_linux.yml
include/open62541/plugin/nodestore.h
plugins/ua_nodestore_hashmap.c
plugins/ua_nodestore_ziptree.c
src/server/ua_nodes.c
src/server/ua_server_internal.h
src/server/ua_server_utils.c
src/server/ua_services_method.c
src/server/ua_services_nodemanagement.c
src/server/ua_services_view.c
src/server/ua_subscription_alarms_conditions.c
tests/check_types_memory.c
tools/ci.sh
tools/nodeset_compiler/backend_open62541_typedefinitions.py

This saves about 20% of RAM because we don't need the tree pointer overhead.

Node references as an array when only few references

---

CMakeLists.txt

Allow the user to disable `-Werror` to avoid the following build failures:
```
/tmp/instance-0/output-1/build/open62541-v1.2.2/arch/network_tcp.c: In function 'connection_recv':
/tmp/instance-0/output-1/build/open62541-v1.2.2/arch/network_tcp.c:96:5: error: conversion to 'unsigned int' from 'int' may change the sign of the result [-Werror=sign-conversion]
96 |     UA_fd_set(connection->sockfd, &fdset);
|     ^~~~~~~~~
```
```
/tmp/instance-6/output-1/build/open62541-v1.2.2/plugins/ua_pubsub_udp.c: In function 'UA_PubSubChannelUDPMC_receive':
/tmp/instance-6/output-1/build/open62541-v1.2.2/plugins/ua_pubsub_udp.c:477:21: error: conversion to '__suseconds_t' {aka 'int'} from 'UA_UInt32' {aka 'unsigned int'} may change the sign of the result [-Werror=sign-conversion]
477 |     tmptv.tv_usec …
```

CMakeLists.txt: add UA_FORCE_WERROR

---

examples/pubsub/pubsub_subscribe_standalone.c
include/open62541/plugin/pubsub.h
plugins/ua_pubsub_ethernet.c
plugins/ua_pubsub_udp.c
src/pubsub/ua_pubsub.h
src/pubsub/ua_pubsub_reader.c
src/pubsub/ua_pubsub_security.c
tests/pubsub/check_pubsub_decryption.c
tests/pubsub/check_pubsub_multiple_subscribe_rt_levels.c
tests/pubsub/check_pubsub_publish_rt_levels.c
tests/pubsub/check_pubsub_publish_uadp.c
tests/pubsub/check_pubsub_subscribe_rt_levels.c

Depends on #4565 
Depends on #4579 
Receiving multiple messages in one pubsub callback was previously done like so:
1. create a buffer
2. call a recv wrapper on that buffer:
- fill the buffer with as much raw messages (opcua NetworkMessages) as it can carry and as are messages on the socket
3. process the buffer (decode and process all NetworkMessages)
This behavior led to the situation that the length of single messages in the buffer is unknown upon decoding. Decryption though needs this information for determining the position of the encrypted payload and signature.
This pull request implements the following behavior:
- call a recv wrapper on a functional closure
- receive each message separately and decode and process with the given closure
- make `check_pubsub_publish_uadp` …

[REVIEW] Fix receiving multiple messages in one pubsub callback

---

tools/nodeset_compiler/backend_open62541.py

`Node.references` is of type `set()` which is an unordered collection.
This results in a different order of elements on every run of nodeset compiler although the input did not change.
This change fixes this behaviour and produces identical (i.e. deterministic) output from the same input.

fix(nc): Sort references before adding to list of nodes

---

plugins/include/open62541/plugin/create_certificate.h

`_UA_BEGIN_DECLS` / `_UA_END_DECLS` where missing in `create_certificate.h` so using this in c++ was not possible.

fix(sec): Add 'extern "C"' to create_certificate.h

---

docker/Dockerfile

Docker build fails with :
```
---> Running in 78ec21179ee5
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
Call Stack (most recent call first):
/usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake/Modules/FindPython/Support.cmake:1177 (find_package_handle_standard_args)
/usr/share/cmake/Modules/FindPython3.cmake:181 (include)
CMakeLists.txt:15 …
```

Fix docker

---

include/open62541/types.h
src/ua_types_encoding_json.c
src/ua_types_encoding_json.h
tests/check_types_builtin_json.c
tools/ua-tool/ua.c
tools/ua2json/CMakeLists.txt
tools/ua2json/ua2json.c

It would be interesting to use the json decoding/encoding for example to decode a Variant from json description. Related to https://github.com/open62541/open62541/issues/4359

[Review] move the json encoding functions to public includes

---

tools/nodeset_compiler/backend_open62541_datatypes.py

Currently it's not possible to compile the IO-Link companion specification with our nodeset compiler. The problem exists because the IO-Link spec uses EnumStrings (Array of LocalizedText) and define values with a "null" text value. Our latest Nodeset-Compiler expect a value for the text attribute and crashes therefore.
Nodeset-XML example:
https://github.com/OPCFoundation/UA-Nodeset/blob/f0cd86388c7bb1fce87ef3c6b554e7a927f8613d/IOLink/Opc.Ua.IOLink.NodeSet2.xml#L4861-L5646
The problem is solved by setting an empty string within the nodeset compiler.

fix(nc) Allow EnumString with empty text field

---

docker/Dockerfile

using --no-cache-dir flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

chore : use --no-cache-dir flag to pip in dockerfiles to save space

---

src/server/ua_subscription_datachange.c

If the Node are become hidden during runtime the sampling callback did not report Bad_NodeIdKnown. Instead the callback evaluate a data change continuously.
I'm not sure what the line 90 really checks, but I must extend it.
The UA_ByteString_equal signale a datachange if mon->lastSampledValue is a NULL-ByteString all time.
```c
if(!value->value.type) {
*changed = UA_ByteString_equal(encoding, &mon->lastSampledValue);
return UA_STATUSCODE_GOOD;
}
```

[Review] MonitoredItem sampling callback handle Bad_StatusCodes improper

---

deps/mqtt-c/mqtt.c

instead of calling rv= __mqtt_ping(client), shouldn't it call mqtt_ping(client)?

fix(PubSub) : fix keep-alive call

---

include/open62541/util.h
src/client/ua_client.c
src/server/ua_session.h
src/server/ua_subscription.h

Wrong format specifiers cause a heap of compiler warnings with -Wformat enabled. I used the correct definitions from ``inttypes.h`` or cast to the correct type (to follow the scheme within the source code file).

Fixed compiler warnings (-Wformat) related to printf format specifiers

---

FEATURES.md
examples/access_control/server_access_control.c
plugins/crypto/openssl/ua_pki_openssl.c
plugins/include/open62541/plugin/accesscontrol_default.h
plugins/ua_accesscontrol_default.c
plugins/ua_config_default.c
src/server/ua_services_session.c

To support x509 certificates as user identity tokens, two things are needed:
1) Verify the user token signature (verify user is in possesion of private key).
2) Verify the user token (certificate) is trusted.
This PR implements step 1. Step 2 is left to the library user, to be implemented in the access control plugin.
See issue #3962 for discussion with @jpfr.
NOTE : the library user also needs to add the certificate token policy to the server configuration as follows:
```c
UA_ServerConfig * config = UA_Server_getConfig(server);
UA_AccessControl * ac = &config->accessControl;
// add support for certificate user token (not supported yet by open62541)
// delete old list of supported tokens
UA_Array_delete((void*)(uintptr_t)ac->userTokenPolicies,
ac->userTokenPoliciesSize, …
```

[Review] feat(server): Add user token signature check for x509 identity token

---

examples/events/client_eventfilter.c
examples/events/server_random_events.c
src/server/ua_subscription.h
src/server/ua_subscription_events.c
src/server/ua_subscription_monitoreditem.c
tests/server/check_subscription_events.c

This PR is the second batch of the event filter server logic. The changes are based on batch 1 #4608 
This Batch currently contains:
- Initial Content Filter skeleton (Where Clause evaluation)
- Use of the EventFilterResult structure
- Fix Issue with reduced server and A&C while using UaExpert
The PR is based on the work in #4225

Event-Filter Batch 2 (Using EventFilterResult, Content-Filter Skeleton)

---

src/server/ua_server_utils.c
src/server/ua_services_nodemanagement.c
tests/CMakeLists.txt
tests/server/check_interfaces.c
tests/server/interface-testmodel.xml

Sub nodes of ObjectType nodes and instances were missing the HasInterface reference.
With this patch, all necessary information should be there.
For verification purposes, I have used the XML file from https://github.com/open62541/open62541/pull/4479
What I would expect:
- TopLevelObjectType should have a child of type MyTestObjectType named ObjectWithInterfaces
- ObjectWithInterfaces in the ObjectType node should have two HasInterface references
- ObjectWithInterfaces in the ObjectType node should have three properties (one own property, one from each of the two interfaces. I assume this is correct according to https://reference.opcfoundation.org/v104/Core/docs/Amendment7/4.9.2/ Figure 7A)
- An instance of TopLevelObjectType should look the same

Fix HasInterface handling

---

debian/control-template

With branch 1.1 there is a dependency on libmbedtls introduced for open62541-dev, but this dependency is missing in the corresponding control file. As result the libmbedtls-dev package won't be automatically installed when installing open62541-dev, as pointed out in #4497. 
This patch adds the related dependency on libmbedtls-dev for open62541-dev and should solve #4497
This patch should be applied to branches 1.1 and master as well.

fix/debian): add libmbedtls-dev dependency to open62541-dev

---

src/server/ua_server.c

Currently the UA_Server_run_startup() function fails with the status
code UA_STATUSCODE_BADSECURITYCHECKSFAILED if the stack is built with
UA_ENABLE_ENCRYPTION=ON and the server config contains the
SecurityPolicyNone without an application certificate.
This is a problem if you build a product with encryption support but
supports to it run without any secured SecurityPolicies enabled and
no certificates installed.
This fix makes verifyServerApplicationURI() to not verify the
applicationURI of SecurityPolicyNone instances without an application
certificate.

[REVIEW] fix(server): Allow SecurityPolicyNone without an application certificate

---

src/client/ua_client.c
src/server/ua_server_binary.c

The binaryEncodingId variable of the UA_DataType structure has
over time changed from an 16 bit integer to an UA_NodeId type. This
has caused type missmatches between the format string and the
binaryEncodingId variable when it is used in in log messages.

[REVIEW] fix(server/client): Updated log message format strings to solve type missmatch build warnings

---

examples/pubsub/server_pubsub_subscriber_rt_level.c
include/open62541/server_pubsub.h
src/pubsub/ua_pubsub_reader.c
src/pubsub/ua_pubsub_readergroup.c
src/pubsub/ua_pubsub_writergroup.c
tests/pubsub/check_pubsub_subscribe_rt_levels.c

Provide an optional write callback for subscriber in fast-path
configuration:
If the callback is set, the application handles the write operation.
This can be useful when a special "write" function (e.g. with signaling)
is needed to write the variable in the underlying engineering system.
Without the write callback the sdk would first memcpy
the value to a buffer and afterwards the application needs to
retrieve the value and use special "write" function.
If the write callback is set, then the application can directly write
the variable value with it's preferred implementation.

feat(pubsub): subscriber before-write callback (fast-path)

---

src/server/ua_services_nodemanagement.c

`UA_Server_addVariableNode()` has potential memory leak if iParentId node is non-existent. In that case, `AddNode_addRefs()` will return UA_STATUSCODE_BADPARENTNODEIDINVALID, but the node will be released, not removed.

[REVIEW] fix(server): Delete node with non-existing parent

---

CMakeLists.txt

The `/WX` option (treat warning as errors) on MSVC was passed even if the option `UA_FORCE_WERROR` was set to `OFF` . Even if the name of the option is a bit gcc/clang specific, I think it make sense that if a user specifies `UA_FORCE_WERROR` set to `OFF`, probably the user wants to disable treating warning as errors on any platform.

Fix handling of UA_FORCE_WERROR CMake option on MSVC

---

CMakeLists.txt
deps/README.md
deps/mqtt-c/mqtt.c
deps/mqtt-c/mqtt.h
plugins/mqtt/ua_mqtt_adapter.c

Code is mixed with `UA_ENABLE_MQTT_TLS_OPENSSL` and NO TLS_OPENSSL.
This PR uses `#ifdef UA_ENABLE_MQTT_TLS_OPENSSL` to separate them.

[REVIEW] Fix Issue 4727 MQTT Build failed

---

tools/nodeset_compiler/type_parser.py

Running the generator under windows and linux produced a different types_generated.h (with a different ordering of the types).
Using and OrderedDict for snippets preserves the ordering and gives a more consistent result.

fix(nc): fix ordering of types parsed from xml

---

tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c
tools/nodeset_compiler/backend_open62541_nodes.py

Currently, the Powerlink nodeset example does not run. The problem is that the Value Rank does not match the ValueRank of the VariableType #3082. 
The PowerlinkVariableType is assigned a ValueRank of -1 (default). However, in the XML the node has a subtype BaseDataVariableType (ns=0;i=63), which has a ValueRank of -2.

fix(nc): Inherit the values rank even if the parents have < -1

---

arch/network_tcp.c

fix(arch): UA_fd_isset() evaluates to non-zero value
UA_fd_isset() evaluates to a non-zero value if the descriptor is part of the set.
See https://pubs.opengroup.org/onlinepubs/9699919799.2016edition/functions/select.html

[Review] fix(arch): UA_fd_isset() evaluates to non-zero value

---

tools/nodeset_compiler/backend_open62541_typedefinitions.py
tools/nodeset_compiler/type_parser.py

Don't allow any 8-bit result as this will give a warning during fuzzing.
Actually fix what was attempted in
e26cf59af81d1924f81eda32b332668600095243.

fix(core): Decoding Boolean must result in either 0 or 1.

---

appveyor.yml
tools/appveyor/build.ps1

Since AppVeyor builds currently need ~1:45h this PR reduces the number of tested features and enables the "fast_finish" strategy, which stops the build after the first failed run. E.g. if vs2008 fails than vs2013 is not executed.

feat(ci) Optimizations for faster AppVeyor builds

---

.github/workflows/coverage.yml
CMakeLists.txt
tests/CMakeLists.txt
tools/ci.sh
tools/cmake/FindGcov.cmake
tools/cmake/Findcodecov.cmake

After we stopped using travis, our CI-code coverage testing and uploading was no longer executed. In addition, the old mechanism used for uploading the coverage reports is deprecated. This PR introduces a GitHub action for uploading reports to codecov and change the cmake coverage integration.

feat(ci) re-enable code coverage testing based on github actions

---

src/server/ua_services_attribute.c
src/server/ua_services_method.c
tests/server/check_services_call.c

calling a method with empty variant causes a segfault:
```
#0  0x565a3f97 in typeEquivalence (t=0x0) at /workspaces/open62541_FEM/src/server/ua_services_attribute.c:756
#1  0x565a488c in adjustValueType (server=0x56703a40, value=0xffffd040, targetDataTypeId=0x566c15f8) at /workspaces/open62541_FEM/src/server/ua_services_attribute.c:1033
#2  0x5659eb90 in typeCheckArguments (server=0x56703a40, session=0x56703c74, argRequirements=0x566c14a8, argsSize=1, args=0xffffd040, inputArgumentResults=0x566d3a60)
at /workspaces/open62541_FEM/src/server/ua_services_method.c:81
#3  0x5659ece5 in validMethodArguments (server=0x56703a40, session=0x56703c74, method=0x566c10c8, request=0xffffd074, inputArgumentResults=0x566d3a60)
at /workspaces/open62541_FEM/src/server/ua_services_method.c:110
#4 …
```

[REVIEW]: Segfault with empty method arg

---

.dockerignore
docker/Dockerfile

Using the latest released Docker image open62541/open62541 in test environments could be cumbersome due to its size which is over 500MBs. Creating a multi-stage Dockerfile can solve this issue by moving only all the built binaries and runtime dependencies to the final image build stage. This way the final image size can be lowered to 30MBs.

Create multi-stage Dockerfile to minimize final Docker image size

---

examples/nodeset/CMakeLists.txt
tests/nodeset-compiler/CMakeLists.txt
tools/nodeset_compiler/backend_open62541_typedefinitions.py
tools/nodeset_compiler/nodes.py

Move ua-nodeset to f71b3f4 (Tag Glass=1.0.0-2022-01-01)
Fix nodeset compiler to handle new empty enumartion, contained in types-bsd.

server(deps) update and fix ua-nodeset (5fdc7d4 to f71b3f4)

---

src/server/ua_services_nodemanagement.c
tests/server/check_interfaces.c
tests/server/interface-testmodel.xml

If a BaseObjectType object with a HasInterface reference is instantiated from a model, the HasInterface reference is missing.

[REVIEW] Fix HasInterface reference on types without HasInterface reference

---

tools/cmake/FindCheck.cmake

This PR adjusts the FindCheck.cmake logic to avoid the current cmake warning (if unit tests are enabled).

fix(build) resolve cmake warning during find check library

---

arch/network_tcp.c

The issue was reported and fixed by @tboeckel in #4770

fix(arch): Use AF_INET in the socket hints if IPV6 is disabled

---

.github/workflows/build_linux.yml

* fixes [CB-K21-1240](https://www.cert-bund.de/advisoryshort/CB-K21-1240)

[Review] core(deps): Bumps LibreSSL to 3.4.2

---

.github/workflows/debian_packing.yml

Fix github action. Currently we build pack branches also for "-rc" tags.

fix(ci) build debian package branch only for standard releases 

---

src/server/ua_services_view.c
tests/server/check_services_view.c

If no matches are found a size of 0 is passed to UA_realloc(). The
behavior of realloc if the size is 0 is implementation defined and will
either return NULL or a valid pointer. Fix so bad out of memory is not
returned in case a NULL pointer shall be accepted.

[REVIEW] fix(server): fix no match for TranslateBrowsePathsToNodeIds

---

.github/workflows/cifuzz.yml

Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz, on which open62541 already runs.

feat(ci): Add CIFuzz integration

---

src/server/ua_subscription_events.c

An empty path should operate on the instance, not on the type node.

Fix SimpleAttributeOperand handling for empty path

---

src/server/ua_services_view.c

This a backport from #4724 to the 1.2 branch.

fix(server): browseReferences continuation point usage check

---

CMakeLists.txt

The path might contain regex-sensitive character (like '+').
See #4842.

fix(build): Don't use regex to get the install path for includes

---

arch/network_tcp.c
arch/posix/ua_architecture.h
arch/win32/ua_architecture.h

Hi,
If an output connection is not ready (buffer filled), it will return immediately
with EAGAIN, and connection_write retries to send data without checking if the
condition has changed. It results of an unwanted high CPU use. Polling with
POLLOUT event fixes this issue.
Only a posix implementation for now.
Please let me know if this work is worthwhile for open62541.

fix(core): check if output connection is ready before write

---

tools/amalgamate.py
tools/c2rst.py
tools/gdb-prettyprint.py
tools/generate_datatypes.py
tools/generate_nodeid_header.py
tools/generate_statuscode_descriptions.py
tools/nodeset_compiler/nodeset.py
tools/nodeset_compiler/nodeset_testing.py
tools/prepare_packaging.py
tools/update_copyright_header.py
tools/valgrind_check_error.py

The newer Ubuntu since 20.04 do not have the `python` binary.
There one explicitly needs to choose between `python2` or `python3`.
See also:
https://askubuntu.com/q/1296790/141958

fix: use `#!/usr/bin/env python3` instead of `#!/usr/bin/env python`

---

include/open62541/types.h
src/server/ua_services_monitoreditem.c
src/server/ua_subscription_events.c
src/ua_types.c
tests/CMakeLists.txt
tests/server/check_subscription_event_filter.c

This PR is the fourth batch of the event filter server logic.
This batch contains:
-> Dedicated Unit-Test for event filters
-> isNull Operator
-> Type conversion rules and compare operator
-> bitwise operator
-> between operator
-> inList operator
The PR is based on the work in #4225

Event-Filter Batch 4 - Extended Operators

---

src/server/ua_services_nodemanagement.c
tests/server/check_services_nodemanagement.c

If a node with Variable children is added, the variable children are never marked as dynamic.
This prevents the usage of the server and source timestamps in the DataValue.

[REVIEW] Fix the isDynamic flag for nested child variables

---

src/server/ua_services_nodemanagement.c
tests/server/check_node_inheritance.c
tests/server/check_services_attributes.c

This backports #4775 (fix for #4774) for v1.2. There was only a minor conflict.
As we use this branch in productive code for some time, having this official will be great.
CC: @jvoosten

backport #4774 for v1.2

---

tools/nodeset_compiler/nodeset_compiler.py

Hi,
I had a bug in the nodeset compiler importing different  Companion Specification nodeset and my new nodeset. The typesArray of the DataType was wrong, and the code was broken. 
The problem is in my opinion that the nodeset compiler skip existing nodeset but do not count them in the array index. So, the wrong types-array was used. I increased the index as well for skipped nodeset and that works fine. 
Here is the example input argument of the python script:
`
--bsd=D:/codelab/gms_sample_server/Sample-Server/model/GMS/opc.ua.gms.nodeset2.bsd --types-array=UA_TYPES --types-array=UA_TYPES_DI --types-array=UA_TYPES --types-array=UA_TYPES_DI --types-array=UA_TYPES_IA --types-array=UA_TYPES --types-array=UA_TYPES_DI --types-array=UA_TYPES_MACHINERY --types-array=UA_TYPES …

fix(nc): skipping nodeset issues wrong counter for TypesArray

---

include/open62541/types.h
src/server/ua_nodes.c
src/ua_types.c

Using {0} it not portable. 
I got this error in my build chain
```
open62541/src/server/ua_nodes.c:46:1: error: missing braces around initializer [-Werror=missing-braces]
const UA_ReferenceTypeSet UA_REFERENCETYPESET_NONE = {0};
^
open62541/src/server/ua_nodes.c:46:1: error: (near initialization for 'UA_REFERENCETYPESET_NONE.bits') [-Werror=missing-braces]
.cc1: error: unrecognized command line option "-Wno-static-in-inline" [-Werror]
.cc1: all warnings being treated as errors
```
Looks like a deja vu of https://github.com/open62541/open62541/issues/2134
Signed-off-by: Kjeld Flarup <kfa@deif.com>

Fix error: missing braces around initializer [-Werror=missing-braces]

---

src/server/ua_services_attribute.c

Enabling the History functionality but leaving it unconfigured leads to a null pointer dereference when calling Service_HistoryRead.

fix(services): Null pointer dereference in history service.

---

plugins/crypto/openssl/ua_openssl_create_certificate.c

While updating to latest master, I encountered passing of some const variables has changed.  
In the older tool chains I use, the functions in openssl does not have a const in the declaration, which causes a violation.
I'm actually in the process of migrating to openssl 1.1.1, so this will be less important for me soon.
Signed-off-by: Kjeld Flarup <kfa@deif.com>

Some const qualifiers which causes build with older openssl (pre 1.1) to fail.

---

CMakeLists.txt
src/server/ua_services_nodemanagement.c
tools/nodeset_compiler/backend_open62541_datatypes.py
tools/nodeset_compiler/backend_open62541_nodes.py
tools/nodeset_compiler/backend_open62541_typedefinitions.py
tools/nodeset_compiler/datatypes.py
tools/nodeset_compiler/nodeset_compiler.py

- Support of code generation for arrays. Currently, only the generation of "simple" arrays is possible. Arrays in structures or structures which are arrays themselves are not supported.
- Support of nodesets that have multiple Depends
- Fixed a bug with symmetric references when the target node is the same as the source node.

fix(nc): Support for multiple Depends inside a nodeset and improvement of the code generation of arrays

---

arch/network_tcp.c
include/open62541/server.h
plugins/ua_config_default.c
src/server/ua_server.c
src/server/ua_server_config.c
src/server/ua_services_securechannel.c
src/ua_connection.c
src/ua_connection_internal.h

Integrates the server iteration for the eventloop.
- code for server-networklayer-tcp removed from `arch/network_tcp.c`
- define and initialize connection-managersin server config (`include/open62541/server.h`, `plugins/ua_config_default.c`)
- `UA_Server_setupEventLoop` method which is called in `UA_Server_run_startup` (`server.c`)
- replace server specific code with eventloop-run in `UA_Server_run_iterate` (`server.c`)
- stop event-sources in `UA_Server_run_shutdown` (`server.c`)
- server-connection related logic and structure in `src/ua_connection.c` & `src/ua_connection_internal.h`
- networklayers (consistently integrate connection-managers/event-sources in networklayers - key-value-map ? )
- Get rid of complete arch/network_tcp server code and the corresponding logic of the callers?
- …

[REVIEW] Feature: Eventloop server integration

---

examples/events/client_eventfilter.c
examples/events/server_random_events.c
src/server/ua_subscription_events_filter.c

Extension and minor fixes for the client-event-filter example.
-> Literal Operands are used within the example.

fix(ex) extended client event-filter example 

---

tools/nodeset_compiler/nodeset_compiler.py

This reverts commit ca50a8d4fe8563932a761c3b1992d7017778097f.
Obsolete due to functionality introduce with commit a0c28b8bb51e797ab96c4f1af7fc952871a5fdc5

[Review]Revert "fix(nc): skipping nodeset issues wrong counter for TypesArray"

---

include/open62541/types.h
src/pubsub/ua_pubsub.h
src/pubsub/ua_pubsub_manager.c
src/pubsub/ua_pubsub_writer.c
src/ua_types.c
tests/pubsub/check_pubsub_pds.c
tests/pubsub/check_pubsub_publish.c
tests/pubsub/check_pubsub_subscribe_rt_levels.c

Part 14 requires that a PDS has a unique name within the Publisher. Make the corresponding check before creating a new PDS.
The new function `UA_PublishedDataSet_findPDSbyName` may be also used in future by new applications e.g. OPC UA FX.
By the way, added utility function `UA_String_isEmpty` to the core library. If such an addition is not appropriate, I can replace the check in ua_pubsub_manager.c with:
`UA_String_equal(&publishedDataSetConfig->name, &UA_STRING_NULL)`, or `(publishedDataSetConfig->name.length == 0)` like it's done elsewhere.

feat(pubsub): Recognize the PDS name

---

src/server/ua_server.c
src/server/ua_services_discovery.c

The endpoints contain an application description. If the user changes the server application description, the endpoints are currently not updated. This PR changes the default behavior and copy the latest application description to all the endpoints during the server start.

feat(server) automatic copy applicationdescription to the endpoints

---

src/server/ua_subscription_alarms_conditions.c

Do not log `"Entry not found in list!"` each time when a event is triggered:
As `isConditionOrBranch` is called for all events here:
https://github.com/open62541/open62541/blob/5f5214427b62e96e066270f4c2798f68b1375213/src/server/ua_subscription_events.c#L285-L295
There should be no UA_LOG_ERROR each time a event is triggered.

fix(server): Decrease logging severity in isConditionOrBranch

---

arch/eventloop_posix.c
arch/eventloop_posix_epoll.c
arch/eventloop_posix_udp.c
include/open62541/plugin/eventloop.h
tests/CMakeLists.txt
tests/check_eventloop_udp.c

Adds a UDP eventsource for the eventloop.
Generally the same as the TCP event source without some connection-based concepts of the TCP event source.

[REVIEW] Feature/eventsource udp

---

tools/nodeset_compiler/backend_open62541.py

Child nodes of methods nodes are not affected by the
UA_ENABLE_METHODCALLS in nodesets compiled by the
nodeset_compiler.py.
If UA_ENABLE_METHODCALLS is not set, the method nodes won't be
created but child nodes of the method nodes will. These child nodes
will fail during initialization as their parent node doesn't exist.
An example of this in Opc.Ua.NodeSet2.Reduced.xml is the
GetMonitoredItems node that has two child nodes; OutputArguments and
InputArguments.
This change makes child nodes of method nodes to only be initialized
if UA_ENABLE_METHODCALLS is defined.

[REVIEW] Fix(nc): Enable child nodes of method nodes with UA_ENABLE_METHODCALLS

---

src/ua_types_encoding_json.c

broken by c8fd22e37b8360eb6502bc1f5f12b0d3745acab4
Booleans in arrays of value "false" were incorrectly encoded as "null"
Previously: [true,null,true]
Currently: [true,false,true]

fix(core): do not encode false booleans as nulls

---

arch/network_tcp.c

This change adds code to handle a timeout of UA_select when the client tries to connect.
Previously, the return code for a timeout was unchecked, and instead handled as if successful. This caused issue #3221 .
Merging this change would also make pull request #4976 obsolete.

fix(client): handle timeout when connecting

---

.github/workflows/build_linux.yml

Relnotes: https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.4.3-relnotes.txt

[Review] core(deps): Bumps LibreSSL to 3.4.3

---

CMakeLists.txt
deps/mqtt-c/mqtt.c

Fix the errors that occur in the build process with the following CMake flags ([build.log](https://github.com/open62541/open62541/files/8419291/build.log)):
-DCMAKE_BUILD_TYPE=Debug
-DUA_BUILD_EXAMPLES=ON
-DUA_BUILD_UNIT_TESTS=ON
-DUA_ENABLE_PUBSUB=ON
-DUA_ENABLE_PUBSUB_MQTT=ON
-DUA_ENABLE_MQTT_TLS=ON
-DUA_ENABLE_MQTT_TLS_OPENSSL=ON
-DUA_NAMESPACE_ZERO=FULL
Fix missing conversions and zero-terminate the strTLS value to avoid the warning when the result is not expected to be NUL-terminated.
Fixed a bug in Cmake where the UA_ENABLE_MQTT_TLS_OPENSSL flag is overwritten again after it is set to ON in the UA_ENABLE_MQTT_TLS check.

fix(deps): Fix missing conversions and zero-terminate the strTLS value.

---

CMakeLists.txt

The open62541 can be compiled using the 1.05.01 nodeset. Due to missing specifications in the deps/ua-nodeset repository, a special flag must be set for the nodeset-option: LATEST_1_05. Due to a change between 1.05.00 and 1.05.01 a updated regex for the file version check is needed.

fix(server) adjust regex for latest nodeset flag

---

tools/nodeset_compiler/backend_open62541.py
tools/nodeset_compiler/nodes.py
tools/nodeset_compiler/nodeset.py

Currently, the nodeset compiler creates source file including the nodes of the information models
in a different order every time a rebuild is done. This is due to the use of sets which change the
order of there elements every time an element gets added. With this change the nodeset compiler
uses lists where order is relevant.

fix(nc): fix the determinism of the generated sources of the nodeset compiler

---

arch/eventloop_posix_tcp.c

resolves #4964 
This fix resolves 120 sek timeout for win32 shutdown of tcp connections.
1. calls shutdown "SD_SEND" for connections to be shut down
2. adds a delayed callback that closes a tcp connection after a peek to recv showed no data on the socket
3. if there is peeked data on the socket the delayed callback adds itself again and waits another cycle of the eventloop to process the data that arrived on the socket
As mentioned in the according issue by @ccvca, according to win32 documentation this is the correct way of shutting down a socket gracefully:
> 1. Call shutdown with how=SD_SEND.
> 2. Call [recv](https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-recv) or [WSARecv](https://docs.microsoft.com/en-us/windows/desktop/api/winsock2/nf-winsock2-wsarecv) until …

[REVIEW] fix(el): win32 shutdown takes 120 s

---

plugins/crypto/mbedtls/securitypolicy_mbedtls_common.c
plugins/crypto/mbedtls/securitypolicy_mbedtls_common.h
plugins/crypto/mbedtls/securitypolicy_pubsub_aes128ctr.c
plugins/crypto/mbedtls/securitypolicy_pubsub_aes256ctr.c
plugins/crypto/mbedtls/ua_pki_mbedtls.c
plugins/crypto/mbedtls/ua_securitypolicy_aes128sha256rsaoaep.c
plugins/crypto/mbedtls/ua_securitypolicy_basic128rsa15.c
plugins/crypto/mbedtls/ua_securitypolicy_basic256.c
plugins/crypto/mbedtls/ua_securitypolicy_basic256sha256.c
tests/pubsub/check_pubsub_decryption.c

Background: The mbedtls version from the pacman installer was updated to mbedtls 3.1.0. We used in our stack definitions from the entropy_poll.h, which is meant to be mbedtls internal only. Therefore, the header is not available anymore, see the mbedtls changelog:
* Move internal headers.
Header files that were only meant for the library's internal use and
were not meant to be used in application code have been moved out of
the include/ directory. The headers concerned are bn_mul.h, aesni.h,
padlock.h, entropy_poll.h and *_internal.h.
The entropy sources are now configured within the mbedtls_entropy_init only and custom configurations must be done directly in the mbedtls_config.

fix(sec) Remove use of mbedtls internal headers

---

plugins/crypto/openssl/ua_openssl_version_abstraction.h

The macro is only used in places where the variable is already (coincidentally) named correctly.

fix(plugin): correct typo for macro parameter

---

plugins/ua_network_pubsub_mqtt.h

fix: UA_PubSubTransportLayerMQTT symbol not available in shared library

---

arch/common/ua_lwip.h

Commit #4704 add polling to check if output connection is ready before write. This commit add missing defines for arch freertosLWIP and fix corresponding compiler errors.

fix(arch): add missing defines for poll on arch freertosLWIP

---

CMakeLists.txt

Since Nodeset Version 1.05.01 is now default for our master-branch and the deps are now referencing https://github.com/OPCFoundation/UA-Nodeset/tree/latest (1.05.01 + all companion specs) we do not need the LATEST_1_05 anymore.

feat(server) remove namespace LATEST_1_05 flag

---

CMakeLists.txt
tests/server/check_subscription_event_filter.c
tests/server/check_subscription_events.c

We recognized a massive runtime increase during the execution of the unit-tests. This PR fixes the reason behind:
The unit-tests for subscriptions are using threads and a mutex. Currently the thread function takes the mutex most of the time and other code paths are blocked therefore.

fix(tests) add realsleep in subscription-tests 

---

include/open62541/server.h
src/server/ua_server.c
src/server/ua_server_internal.h
tests/server/check_server.c

This PR introduces the counterpart function of the existing "getNamespaceByName" function. The Namespace String can be obtained by the namespace id.

feat(server) Add internal API function for Namespace Lookup

---

.idea/open625412.iml
plugins/ua_config_default.c
plugins/ua_pubsub_ethernet.c
plugins/ua_pubsub_udp.c
src/pubsub/ua_pubsub_manager.c
src/server/ua_subscription.c

Fix compilation for clang-15 which requires function signatures to match exactly. myfun() != myfun(void)

Fix: compilation bug due to missing void parameter

---

.github/workflows/doc_upload.yml

The new open62541-website is now online and we need to push the autogenerated documentation in the new location.

dix(doc) Update documentation push logic

---

src/pubsub/ua_pubsub.h
src/pubsub/ua_pubsub_ns0.c
src/pubsub/ua_pubsub_reader.c
src/pubsub/ua_pubsub_writergroup.c
tests/pubsub/check_pubsub_subscribe.c

Currently the check_pubsub_subscribe was not executed in our CI due to a cmake missconfiguration. In addition the test was broken over time and is fixed in this PR.

fix(test) Fix check_pubsub_subscribe + unit tests for heartbeat functionality

---

tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c
tests/server/check_interfaces.c

When compiling with UA_NAMESPACE_ZERO=FULL more -Wsign-conversion
errors show up.

test(core): fix more compiler errors

---

tools/open62541.pc.in

Paths in the pkg-config file are composed of `CMAKE_INSTALL_<dir>`
variables. However, it is allowed to specify them as absolute paths, see
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html#result-variables
> It should typically be a path relative to the installation prefix so
> that it can be converted to an absolute path in a relocatable way (see
> `CMAKE_INSTALL_FULL_<dir>`). However, an absolute path is also
> allowed.
If they are absolute, compositions like
`@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@` yield a wrong path.
Use the `CMAKE_INSTALL_FULL_<dir>` variables instead, as the CMake
documentation suggests.

build(pkgconfig): do not assume relative paths in open62541.pc

---

plugins/crypto/mbedtls/ua_securitypolicy_aes128sha256rsaoaep.c

Fixed a potential security issue because of remote signature size being used instead of local signature size

fix(securitypolicy): Use local key instead of remote key

---

plugins/ua_config_default.c
tests/check_securechannel.c

Based on a reported DoS vulnerability reported by Team82 (Claroty
Research).

fix(plugin): Add default limits for chunks and message size

---

examples/pubsub/tutorial_pubsub_mqtt_publish.c
examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_publisher.c
examples/pubsub_realtime/pubsub_TSN_loopback.c
examples/pubsub_realtime/pubsub_TSN_loopback_single_thread.c
examples/pubsub_realtime/pubsub_TSN_publisher.c
examples/pubsub_realtime/pubsub_TSN_publisher_multiple_thread.c
include/open62541/server_pubsub.h
src/pubsub/ua_pubsub.h
src/pubsub/ua_pubsub_config.c
src/pubsub/ua_pubsub_networkmessage.c
src/pubsub/ua_pubsub_networkmessage.h
src/pubsub/ua_pubsub_reader.c
src/pubsub/ua_pubsub_readergroup.c
src/pubsub/ua_pubsub_security.c
src/pubsub/ua_pubsub_writer.c
src/pubsub/ua_pubsub_writergroup.c

fix(pubsub): Free memory for sequence number
Memory for sequence number variables has been allocated in
ua_pubsub_networkmessage.c with UA_Variant_setScalarCopy, but not
freed.
fix(pubsub): Symmetric free of WG bufferedMessage
bufferedMessage is initialized in
UA_Server_freezeWriterGroupConfiguration, so it shall be cleared in
UA_Server_unfreezeWriterGroupConfiguration instead of
UA_WriterGroup_clear.
fix(pubsub): Free memory for dataSetPayloadHeader
dataSetWriterIds and dataSetPayload.sizes in payload header are set
irrespective of the variable payloadHeaderEnabled, thus the buffer
also has to be freed independently of this variable.

[Review] fix(pubsub): Memory fixes

---

examples/encryption/client_encryption.c

Example client_encryption: If one of the specified certificate files is in wrong format, the example ignored this and continued with policy #None
Unfortunately this does only write a short error message.  
The real error comes from `UA_CertificateVerification_Trustlist`, but even with full trace, it does not reveal which certifiate fails.  
Neither does it say anything about other parts of `UA_ClientConfig_setDefaultEncryption` failing which may lead to the same situation.
Signed-off-by: Kjeld Flarup <kfa@deif.com>

Example client_encryption ignored invalid certificates

---

.github/workflows/doc_upload.yml

The gh-pages branch is used in default mode. The PR forces to use the main branch in the github action.

fix(doc) set correct branch for documentation upload

---

README.md

We are using codecove in our project and coveralls is not supported anymore. To avoid confusion and 2 different coverage numbers, we should remove the badge.

fix(doc) remove unused coveralls badge

---

tests/testing-plugins/testing_clock.c

When compiled with clang on 32 bit platforms, -Wsign-conversion
prevents implicit conversion from UA_UInt32 to long.  Make sec and
ns UA_Int32 which is compatible with time_t and long in struct
timespec.

test(core): fix 32 bit sign-conversion compiler errors

---

include/open62541/types.h
src/server/ua_services_attribute.c
src/ua_types.c

Changed to first read the complete DataValue to get timestamps and
status. Then if a range is requested the requested range of
the variant is copied into the DataValue.
#5205

fix(server): Reading a range when using ValueBackend External failed

---

tools/nodeset_compiler/opaque_type_mapping.py

New types were added in OPC UA 1.05 which need to be added to the mapping table to be handled by the NodesetCompiler.
UriString is used now for example in OPC UA FX models.

feat(nc): support new subtypes of String

---

examples/pubsub/monitoring/server_pubsub_subscribe_custom_monitoring.c
include/open62541/server_pubsub.h
src/pubsub/ua_pubsub_reader.c
src/pubsub/ua_pubsub_readergroup.c
src/pubsub/ua_pubsub_writer.c
src/pubsub/ua_pubsub_writergroup.c
tests/pubsub/check_pubsub_subscribe_msgrcvtimeout.c

Allow applications to access the server data inside the callback. Since the server config can store also an application context, also the application data can be accessed from within the callback.

feat(pubsub): Pass the server pointer to the PubSub StateChangeCallback

---

src/ua_types.c
tests/check_types_range.c

The array dimensions of the destionation variant was set to the
dimensions of the source variant. Now the block size calculated
of the requested range is used.

fix(server): Fix array dimensions when copying range of variant

---

src/server/ua_server.c

Unit test check_pubsub_informationmodel_methods failed
sporadically because of a nullptr access (see issue #5239).

fix(server): check for valid channel before access

---

include/open62541/server.h
src/server/ua_subscription_alarms_conditions.c
tests/server/check_server_alarmsconditions.c

Hello,
this little proposal would enable the splitted creation of conditions just like other nodes.
Similiar to UA_Server_addNode_begin / _finish UA_Server_addCondition_begin / _finish would allow the modification of the condition node before finishing the instantiation, like adding children with specific NodeIds.
But still all additional functions of UA_Server_createCondition are preserved. The begin and finish functions:
- check if the passed condition type is a subtype of the OPC UA ConditionType
- checks whether the condition source has HasEventSource reference to its parent. If not, a HasEventSource reference will be created between condition source and server object
- exposes the condition in the address space if hierarchialReferenceType is not UA_NODEID_NULL by adding a reference …

[Review] feat(server): add a split version of UA_Server_createCondition

---

include/open62541/server.h
src/server/ua_server_internal.h
src/server/ua_services_attribute.c
src/server/ua_subscription_alarms_conditions.c
src/server/ua_subscription_events_filter.c

This fixes the refresh() and the refresh2() callback, in a (default) multithreaded build.
Tested using commit: 671a7f45
Subscribing to Conditions/Events cause several asserts. E.g.:
```
#0  0x767bb68b in msvcrt!abort () from C:\WINDOWS\System32\msvcrt.dll
#1  0x00e58ccc in _wassert ()
#2  0x00e58d69 in _assert ()
#3  0x00838bfa in UA_LOCK_ASSERT (lock=0x50ca044, num=1)
at <hidden>/Sample-Server/deps/open62541/arch/win32/ua_architecture.h:192
#4  0x008393c8 in UA_Server_getSessionById (server=0x50c9ba8, sessionId=0x77e7108)
at <hidden>/Sample-Server\deps\open62541\src\server\ua_services_session.c:156
#5  0x00d681c7 in refreshMethodCallback (server=0x50c9ba8, sessionId=0x77e7108, sessionContext=0x0,
methodId=0x5196fc8, methodContext=0x0, objectId=0x5195fc0, objectContext=0x0, inputSize=1, …
```

[Review] fix(server): Multithreading fixes in refresh and refresh2

---

tests/check_securechannel.c
tests/check_types_builtin.c
tests/client/check_client_encryption.c
tests/encryption/check_encryption_aes128sha256rsaoaep.c
tests/encryption/check_encryption_basic128rsa15.c
tests/encryption/check_encryption_basic256.c
tests/encryption/check_encryption_basic256sha256.c
tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c
tests/server/check_interfaces.c
tests/server/check_services_attributes.c
tests/server/check_services_nodemanagement.c
tests/testing-plugins/testing_clock.c

These fixes to compile with clang 13 are already in master branch.
Having them also in 1.3 branch also, make testing easier for me.
If you fear too much fallout when merging, just drop this pull request.

test(core): fix sign-conversion compiler errors

---

CHANGELOG
include/open62541/plugin/nodestore.h
include/open62541/server.h
include/open62541/util.h
src/server/ua_nodes.c
src/server/ua_server_internal.h
src/server/ua_services_attribute.c
src/server/ua_services_session.c
src/server/ua_services_view.c
src/server/ua_session.c
src/server/ua_session.h
src/server/ua_subscription_alarms_conditions.c
src/ua_util.c
tests/client/check_client.c
tests/server/check_server_alarmsconditions.c
tests/server/check_services_attributes.c
tests/server/check_services_view.c

This is a first start at supporting locale IDs
- The locale IDs from ActivateSession are stored in the UA_Session
- The server is extended with a getter for the locale IDs of a session
The client-side support has been cherry-picked from #4153.
This should be sufficient for the Value attribute of custom Variable nodes.
The BrowseName and Description attributes still need a different solution. I see the following options:
- The user can pass an array or map for both attributes instead of the scalar UA_LocalizedText and the server does the selection according to Part 4, 5.6.3.2
- Additional, optional callbacks for reading BrowseName and Description
I would prefer the second solution because this can be realized with less memory footprint (no need to duplicate values for nodes with the same …

[REVIEW] Locale ids support in the server

---

arch/eventloop_posix_udp.c

According to Linux /usr/include/bits/in.h IPV6_ADD_MEMBERSHIP is
obsolete.  It does not exist on OpenBSD.  Use IPV6_JOIN_GROUP
instead.

fix(arch): obsolete ipv6 define

---

src/pubsub/ua_pubsub_reader.c
src/pubsub/ua_pubsub_writer.c
src/pubsub/ua_pubsub_writergroup.c
tests/pubsub/check_pubsub_subscribe.c

Recently we wanted to use PubSub to publish messages to an Phoenix Contact PLCnext Starter Kit (AXC F 2152 2022.06), however it turns out the open62541 PubSub Implementation is not quite... there yet. We found some minor issues preventing any communication at-all.
It seems as if the PLC requires a very specific data format of the PubSub message (e.g. regarding what fields to include). Using wireshark we tried to get as close as possible to the PLC's own messages by configuring the open62541 PubSub publisher.
For successful communication, we needed to implement the following configs (adapted from PubSub Publisher example):
For the DataSetWriter:
````
UA_DataSetWriterConfig dataSetWriterConfig;
memset(&dataSetWriterConfig, 0, sizeof(UA_DataSetWriterConfig));
dataSetWriterConfig.name = …
```

Pubsub improvements

---

arch/network_tcp.c
tests/client/check_client_async_connect.c

Commit ef4394b1144e845df93760b951ef0f6bef63d053 may have fixed the
connect timeout, but it broke async connect without timeout.  That
made it impossible to continue processing during TCP handshake.
While the connect operation is in progress, the select system call
will return immediately if the timeout is 0.  Do not close the
connection in this case, but allow the application to call run_iterate()
again.  For the tests in the CI this makes no difference as connect
over Linux loopback interface succeeds immediately.

fix(client) connect iterate without timeout

---

src/pubsub/ua_pubsub_ns0.c

There is a deadlock when trying to cleanup a DataSetReader that is connected to a StandaloneSubscribedDataSet.
We don't need to delete the references ourself as this is already handled by the deleteNode()-methodcall.

fix(pubsub infomodel): remove deadlock datasetreader cleanup

---

include/open62541/architecture_definitions.h
include/open62541/util.h

C++20 deprecated compound volatile operations, so this code fails to
compile in C++20 mode due to -Werror.
Fix by separating loading and saving of the value, which, in the case
of architecture_definitions.h, even reduces the per-operation loads
from two to one.
Fixes: #5247

fix(core): use of compound volatile operations (deprecated in C++20)

---

README.md

fix the gcc linking argument in the examples-section of the README, see https://github.com/open62541/open62541/issues/3248#issuecomment-568370301

fix command in the examples-section of the README

---

examples/pubsub_realtime/pubsub_TSN_loopback_single_thread.c

In the usage() , the PCP should be 3 to meet the semantic.
program output show as follw:
```
-pubUri     [name]   Publisher Mac address (default opc.eth://01-00-5E-00-00-01:8.7 - where 8 is the VLAN ID and 3 is the PCP)
-subUri     [name]   Subscriber Mac address (default opc.eth://01-00-5E-7F-00-01:8.7 - where 8 is the VLAN ID and 3 is the PCP)
```

fix usage() mistake

---

tools/cmake/open62541Config.cmake.in

On some systems open62541Config.cmake finds python2 instead of python3. 
This leads to fails on re.fullmatch() in: https://github.com/open62541/open62541/blob/4d08612120eadea386af1e45a78a6d458b7f2331/tools/nodeset_compiler/nodeset.py#L431
Solution:
Force cmake to find python3

Find Python 3 in open62541Config.cmake.in

---

plugins/mqtt/ua_mqtt-c_adapter.c

(for UA_ENABLE_MQTT_TLS_OPENSSL=ON) client->socketfd is the same pointer as
channeldata->sockfd. client->sockfd is freed in disconnectMqtt() and again
afterwards in freeTLS(). Therefore set it to NULL in disconnectMqtt and free
it in freeTLS only.
Signed-off-by: Tobias Zimmermann <Tobias.Zimmermann@tq-group.com>

fix(pubsub): fix double free in openssl secured mqtt connection

---

examples/discovery/server_multicast.c
examples/discovery/server_register.c

Until 1.2 it was possible to set Port address dynamically but in version 1.3 it is not possible. Setting it to 0 will resolve to 4840, which will conflict with port assinged by default to LDS server in the example. Also the comment is misleading in the example. Therefore the comment is deleted and a fixed port 4841 is assinged to register and multicast server examples.
Signed-off-by: Muddasir Shakil <muddasir.shakil@linutronix.de>

fix (example): Correctly set port in register and multicast examples

---

plugins/crypto/mbedtls/ua_pki_mbedtls.c
tests/encryption/check_save_rejected_cert.c
tests/fuzz/ua_debug_dump_pkgs_file.c

fclose should only be called on valid FILE pointers, as fclose(0) is undefined.

fix: Check for successful file creation

---

include/open62541/common.h
include/open62541/server.h
src/server/ua_server.c
src/server/ua_server_internal.h

The indirection between network connections and SecureChannels no longer exists in the server.  The network statistics are made directly on the  SecureChannel level.

refactor(server): Remove refactored network statistics

---

examples/nodeset/CMakeLists.txt
examples/pubsub_realtime/nodeset/CMakeLists.txt

Currently building of the examples fails when open62541 is included inside another CMake project due to incorrect paths.

Build examples with open62541 not being a root of the CMake project.

---

CMakeLists.txt

Otherwise git-related directories in a submodule end up to be installed

fix(build): do not install git files

---

examples/pubsub/tutorial_pubsub_mqtt_subscribe.c

Bug fix in mqtt subscriber example. Set the messageReceiveTimout when pubsub monitoring is enabled. Also, change the port to allow the publisher and subscriber examples to run simultaneously.

fix(pubsub): Set the messageReceiveTimout when pubsub monitoring is enabled

---

src/client/ua_client.c

Cleanup of EventLoop and Logger was skipped if there are no SecurityPolicies specified.

fix(client): Possible memory leak when deleting client.

---

examples/pubsub_realtime/pubsub_interrupt_publish.c

This file was missed in commit fd76d7faaea38843eb74f578f6b82bf8252b98b7, which breaks build for a few examples.

fix(examples): Fix usage of publisherId in pubsub_interrupt_publish.c

---

arch/eventloop_posix_udp.c
include/open62541/plugin/eventloop.h
tests/check_eventloop_udp.c

Depends on #5355 
Adds the possibility to validate a UDP connection with its parameters without actually opening it.

[REVIEW] Feature/eventloop udp connection validation

---

src/server/ua_session.h

Fixes a GCC error about a format overflow when trying to print a NULL session
Fixes #5368

build(server): format overflow in UA_LOG_SESSION_INTERNAL

---

CMakeLists.txt
include/open62541/server_pubsub.h
src/pubsub/ua_pubsub.h
src/pubsub/ua_pubsub_manager.c
src/pubsub/ua_pubsub_manager.h
src/pubsub/ua_pubsub_ns0.c
src/pubsub/ua_pubsub_ns0.h
src/pubsub/ua_pubsub_securitygroup.c
tests/CMakeLists.txt
tests/pubsub/check_pubsub_sks_securitygroups.c

This PR is the second in series of SKS support. It adds the support for managing SecurityGroups on SKS server side. A securitygroup is an abstraction that represents the message security settings and security keys for a subset of NetworkMessages exchanged between Publishers and Subscribers. A SKS manages the SecurityGroups and maintains the mapping
between Roles and their access Permissions.
In the implementation two server API methods are added to create and remove the SecurityGroup in the server. With a securitygroup a keystorage with initial keys is also created in the server. The keystorage is updated periodically with new keys
by a callback function. The period of update cycle is set by KeyLifeTime parameter in SecurityGroup configuration. The conditional compilation with information …

[Review] feat (pubsub): SKS SecurityGroups

---

plugins/mqtt/ua_mqtt-c_adapter.c

This PR targets the support of mqtt openssl mutual authentication, which is required by many cloud platforms.

feat(pubsub): support mqtt openssl mutual authentication

---

src/client/ua_client_subscriptions.c

Fix wrong callback being invoked in UA_Client_Subscriptions_processPublishResponse, which led to client disconnect on PublishRequest expiration.
closes #4883

fix(client): wrong callback in UA_Client_Subscriptions_processPublishResponse

---

include/open62541/server_pubsub.h
src/pubsub/ua_pubsub_reader.c

SecurityParameters member of reader and readerGroup config was not used anywhere and was a single instance of UA_PubSubSecurityParameters type. ReaderGroupConfig already contains this info in other memebers.

refactor(pubsub): Removed unused field from DSR and RG config

---

plugins/crypto/mbedtls/securitypolicy_pubsub_aes128ctr.c
plugins/crypto/mbedtls/securitypolicy_pubsub_aes256ctr.c
tests/pubsub/check_pubsub_decryption.c

According to part 14 the initial value of AES128 encryption block counter should be set to 1, not 0.

fix(pubsub): Set correct block counter for aes128 encryption

---

src/pubsub/ua_pubsub_writer.c

don't clear dataSetMessage in UA_PubSubDataSetWriter_generateDeltaFrameMessage(), since some fields of dataSetMessage have been set in the UA_DataSetWriter_generateDataSetMessage().

fix(pubsub): fix generateDeltaFrameMessage issue

---

src/pubsub/ua_pubsub_manager.c
tools/schema/Opc.Ua.NodeSet2.PubSubMinimal.xml

Correct generation of the defaultDatagramPublisherId when starting the server. According to the specification (6.2.7.1), it is recommended to assign the MAC address of one of the network interfaces to the first 6 bytes and the OPC UA Server Port of the OPC UA application to the remaining two bytes.

[Review] fix(pubsub): Fix generation of the defaultDatagramPublisherId

---

CMakeLists.txt
include/open62541/types.h
src/ua_types_encoding_xml.c
src/ua_types_encoding_xml.h
tests/CMakeLists.txt
tests/check_types_builtin_xml.c

Initial PR for XML data encoding. Implemented encoding for the following data types:
- Boolean
- SByte
- Byte
- Int16
- UInt16
- Int32
- UInt32
- Int64
- UInt64
- Float
- Double
- String
- DateTime
- Guid
- NodeId
- ExpandedNodeId
Unsupported data types when trying to en-/decode shall throw an _UA_STATUSCODE_BADNOTIMPLEMENTED_ error. Also, included unit tests to validate functionality of both encoding and decoding of data values.
**NOTE**: Added TODO comments within decoding section, which note the restrictions of certain data types.

feature(core): XML data encoding for numeric + string built-in types

---

tests/nodeset-loader/CMakeLists.txt
tests/nodeset-loader/add_node_integration_test/CMakeLists.txt
tests/nodeset-loader/add_node_integration_test/client.c
tests/nodeset-loader/add_node_integration_test/run_test.sh
tests/nodeset-loader/add_node_integration_test/server.c

Add integration test consisting of an OPC UA Server with custom loaded nodesets. The test consists of an OPC UA Client that connects to the server and browses all of the nodes defined within the loaded nodeset XML files. The test validate if all of the nodes within the nodeset(s) can be successfully browsed.
For the companion standards which pass this test case, the nodesetLoader could be used for loading.
For the companion standards which do not pass this test base due to an error similar to the following:
>Error: cannot browse node: ns=3;i=1786
>
the nodesetLoader (even if it loads a part of the nodeset within the OPC UA server) has problems loading the issued nodes within the OPC UA address space.

feat(tests): Integration test for open62541 nodesetLoader

---

src/server/ua_server.c

Only fix up the loggers of the event loop and security policies if they pointed into the supplied config.  E.g. a shared external event loop may use a logger with a different context from that of the server instance.

fix(server) Refine fixup of logger pointers

---

examples/pubsub_realtime/vxworks/pubsub_interrupt_publish_tsn.c

For OPEN62541 upgraded, some variables and functions are removed or changed. So change the file,
pubsub_interrupt_publish_tsn.c to meet the upgradation.

Fix the build error in pubsub_interrupt_publish_tsn.c

---

src/pubsub/ua_pubsub_reader.c
tests/pubsub/check_pubsub_subscribe.c

The array dataSetPayloadHeader.dataSetWriterIds may only be evaluated if the payload header is enabled.

fix (pubsub): exception reading message without payload header

---

src/client/ua_client.c

Only copy event loop logger in UA_Client_newWithConfig if an event loop has been set in the config.

fix(client): Check existence of event loop in UA_Client_newWithConfig

---

tests/nodeset-loader/CMakeLists.txt
tests/nodeset-loader/add_node_integration_test/CMakeLists.txt
tests/nodeset-loader/add_node_integration_test/run_test_ordering.sh
tests/nodeset-loader/check_nodeset_loader_ordering_di.c

Within this PR, the ordering of the nodes within a nodeset XML file is tested for the [open62541-nodeset-loader](https://github.com/open62541/open62541-nodeset-loader). A modified version of the [DI](https://github.com/OPCFoundation/UA-Nodeset/blob/latest/DI/Opc.Ua.Di.NodeSet2.xml) companion specification is used as an example, where the parent node with id **ns=1;i=15001** is defined after its child nodes:
- ns=1;i=15002
- ns=1;i=15003
- ns=1;i=15004
- ns=1;i=15005
- ns=1;i=15006
- ns=1;i=15007
- ns=1;i=15008
- ns=1;i=15031
- ns=1;i=15032
- ns=1;i=15033
**NOTE**: Before this PR can be considered as completed, the dependency PR [#218](https://github.com/open62541/open62541-nodeset-loader/pull/218) must be merged.

feat(tests): Node ordering test case for open62541-nodeset-loader

---

.github/workflows/build_linux.yml
CMakeLists.txt
tests/check_types_builtin_xml.c
tests/nodeset-loader/CMakeLists.txt
tests/nodeset-loader/add_node_integration_test/run_test.sh
tests/nodeset-loader/add_node_integration_test/run_test_ordering.sh
tests/nodeset-loader/check_nodeset_loader_ua_nodeset.c
tools/ci.sh

Fixes #5501.
Also, included the following unit tests for the nodesetLoader in the CI:
- check_nodeset_loader_di
- check_nodeset_loader_autoid
- check_nodeset_loader_plc
- check_nodeset_loader_input
Included nodesetLoader (XML encoding) features within **unit_tests_alarms** CI pipeline, to test whole nodeset functionality, because of supported _UA_NAMESPACE_ZERO=FULL_ option:
- check_nodeset_loader_adi
- check_nodeset_loader_ua_nodeset
- check_nodeset_loader_compare_di
- check_nodeset_loader_testnodeset
- check_nodeset_loader_add_node_integration
Updated nodesetLoader UA-Nodeset tests with the latest version of the ua-nodeset dependency project [54e3513](https://github.com/OPCFoundation/UA-Nodeset/tree/54e35134bb6629789c017f82360e4fdc1577298b)
**NOTE**: For the CI to finish successfully, …

feat(ci): Enable nodesetLoader for CI builds

---

doc/building.rst

Ctest provides option to run individual tests. However, this information was not documented in the docs. This information is helpful for stack developers, so that they can run individual tests for the feature they are develoing.
Signed-off-by: Muddasir Shakil <muddasir.shakil@linutronix.de>
Reviewed-by: Kurt Kanzenbach <kurt@linutronix.de>

[REVIEW]fix(doc): add instructions to run individual tests

---

src/server/ua_server_internal.h
src/server/ua_subscription_alarms_conditions.c

Refresh event node ids were stored in a static variable; this failed if there were more than one server instance in the same address space. The node ids are now moved to UA_Server.

fix(server): Fix ConditionRefresh events with multiple server instances

---

doc/nodeset_compiler.rst
examples/nodeset/CMakeLists.txt
tests/nodeset-compiler/CMakeLists.txt
tests/nodeset-loader/CMakeLists.txt
tests/nodeset-loader/add_node_integration_test/run_test.sh
tests/nodeset-loader/check_nodeset_loader_ua_nodeset.c
tests/server/check_server_userspace.c

* replaces #5484 
* `DI/OpcUaDiModel.csv` was rename to `DI/Opc.Ua.Di.NodeIds.csv` here https://github.com/OPCFoundation/UA-Nodeset/commit/7cbf8f9877d8a38533d76e165e2974a536895de9

[Review] build(deps): bump deps/ua-nodeset from 54e3513 to 71774b4

---

plugins/ua_pubsub_udp.c

Freeing the memory with the previous commit
cfcf9753f284ce0ad49dc119b1f13a4c12460818 resulted in a memory access error.

fix(pubsub): Fix memory access at udp close

---

arch/eventloop_posix_tcp.c

Add REUSEPORT for linux so binding to multiple addresses for the same port is allowed, which we do with the default config. This will get rid of error "address already in use" upon binding.

[REVIEW] Patch/error binding socket

---

CMakeLists.txt

${OPENSSL_LIBRARIES} contains the absolute paths to the OpenSSL library. Instead, the imported targets are used. This is important when using exported targets e.g. while cross compiling. This is fixing #5421.

fix(build): replace absolute paths of OpenSSL with imported target

---

plugins/include/open62541/server_config_default.h
plugins/ua_config_default.c

In the version 1.3 the port was settable after calling UA_ServerConfig_setBasics
with the function UA_ServerConfig_addNetworkLayerTCP.
This function has been removed with commit
https://github.com/open62541/open62541/commit/86c20068e3ff92d9a1601bfbc5d9c5c4e530f517, so provide a new function
UA_ServerConfig_setBasics_withPort to set the port.
Also fix documentation and minor cleanup.

feat(server): Add init function for setting basic server configuration with port

---

examples/pubsub_realtime/pubsub_TSN_loopback.c
examples/pubsub_realtime/pubsub_TSN_loopback_single_thread.c
examples/pubsub_realtime/pubsub_TSN_publisher.c
examples/pubsub_realtime/pubsub_TSN_publisher_multiple_thread.c

For Arm processors sys/io.h does not exist, which
results in a build error. On x86 the header is not needed. Therefore it can be removed. This is also a fix for #4345

fix(examples): remove sys/io.h

---

tests/client/check_client_securechannel.c
tests/encryption/check_save_rejected_cert.c

The maximum server timeout has been increased from 50 to 200 with
commit 384a67276457223d505c2060c3224e567ce1930d.
fix(test): fix pointer parameter in check_save_rejected_cert

fix(test): use correct timeout in check_client_securechannel test

---

arch/network_tcp.c

With  VS2019 i had a NULL pointer assinment error in my client.c example delivered from yours.
I had subscribed 3 variables from an S7-1500 CPU with OPC-UA and it was working fine. 
I have droped the ethernet cable many times to watch reconnect, and than i got this error, and fixed it.
I cant find this in master and 1.3 branch.
The reconnect dose not work, in your example, but that's no proplem here.
Regards Jörg

prevent NULL pointer assinment error in UA_ClientConnectionTCP_poll()

---

examples/CMakeLists.txt
examples/pubsub/sks/CMakeLists.txt
examples/pubsub/sks/pubsub_publish_encrypted_sks.c
examples/pubsub/sks/pubsub_subscribe_encrypted_sks.c
examples/pubsub/sks/server_pubsub_central_sks.c
include/open62541/client.h
include/open62541/server_pubsub.h
src/client/ua_client.c
src/pubsub/ua_pubsub_keystorage.c
src/pubsub/ua_pubsub_keystorage.h
src/pubsub/ua_pubsub_readergroup.c
src/pubsub/ua_pubsub_securitygroup.c
src/pubsub/ua_pubsub_writergroup.c
tests/CMakeLists.txt
tests/client/check_client.c
tests/pubsub/check_pubsub_sks_client.c

An SKSClient is required by the Publisher and Subscriber applications to fetch the security Keys from the SKS server. The client is required to fetch the keys at regular interval. The next period to call the GetSecurityKeys Method is calculated from KeyLifeTime when the KeyStorage switches to the LastKey in the existing list. Then a timed callback is added to the server, which uses the sks client to call the GetSecurityKeys Method. The returned results are stored in the KeyStorage.
When the sks client has fetched the initial set of keys, in UA_Server_setSKSClient() function, The Reader/WriterGroup can be set to operational. The call to setOperational function will set the encrypting key from keystorage->currentItem to the channel context of the Writer/ReaderGroup and then set it into …

[Review] feat(pubsub): add SKS Client support and SKS examples

---

src/pubsub/ua_pubsub_connection.c
src/pubsub/ua_pubsub_readergroup.c
tests/pubsub/check_pubsub_udp_unicast.c

Removing and adding readergroups with pubsub lead to errors when the readergroups were set operational before. This fix opens and closes the communication channel for readergroups that are bound to a connection in the scope of the connection.
Thanks @MurzynJ for the discovery and possible fix of that error.

[REVIEW] fix(pubsub): enable remove and add readergroups

---

include/open62541/client.h
include/open62541/plugin/pki.h
include/open62541/server.h
plugins/crypto/mbedtls/ua_pki_mbedtls.c
plugins/crypto/openssl/ua_pki_openssl.c
plugins/crypto/ua_pki_none.c
plugins/ua_accesscontrol_default.c
plugins/ua_config_default.c
src/client/ua_client.c
src/client/ua_client_connect.c
src/pubsub/ua_pubsub_keystorage.c
src/server/ua_server.c
src/server/ua_server_config.c
src/server/ua_services_session.c
src/ua_securechannel.c

Also the logger in the callback context must be updated when the client or server configuration is moved.
Fixes commit b0da4178d23b4bbb882da49339879a8dc0fdbd9a.

refactor(plugin): Use pointer to pointer to logger for pki plugins

---

src/server/ua_subscription_alarms_conditions.c

This PR fixes a memory leak when acknowledging alarms.
The callback `afterWriteCallbackAckedStateChange()` was not clearing cloned `UA_NodeId`s on success resulting in memory leaks if condition node or condition source use node IDs with allocated identifiers, e.g. string.

Fix memory leak in afterWriteCallbackAckedStateChange()

---

include/open62541/types.h

If entire Nodeid variable was used, valgrind reported uninitialized memory.

fix(core): Initialize entire nodeid variable

---

src/pubsub/ua_pubsub_networkmessage.c

UDP subscriber crashed when it received the following message.
Without discussing if this is even a valid message, such crash shall not happen in any case. How can it be checked in the best way that stack is resistant to any malformed message?

fix(pubsub): prevent segfault on reception of a broken UADP message

---

src/pubsub/ua_pubsub_reader.c

TargetVariables structure was cleared twice unnecessarily. It's cleared for the first time in UA_DataSetReaderConfig_clear just above.

refactor(pubsub): don't clear TargetVariables twice

---

src/pubsub/ua_pubsub_dataset.c

By mistake the internal typeKind was set instead of a numeric identifier of the type's NodeId.
In future the special cases should be handled as specified:

fix(pubsub): set a correct builtInTypeId in FieldMetaData

---

src/client/ua_client.c
src/client/ua_client_subscriptions.c
tests/client/check_client_subscriptions.c

UA_Client_AsyncService_removeAll was called "reentrant" leading to an unauthorized memory access.

fix(client): Fix crash during Client_delete (#5649)

---

examples/CMakeLists.txt

UA_MULTITHREADING can be greater than 100, in which case these examples won't be built.

examples: CMakeLists.txt: fix multithreading check

---

src/pubsub/ua_pubsub_ns0.c

Copy nodeId when reading UA_NS0ID_PUBLISHEDDATAITEMSTYPE_PUBLISHEDDATA.

fix(pubsub): fix memory issue after reading publishedData property

---

src/server/ua_services_attribute.c
tools/schema/datatypes_minimal.txt

During the write of a value, we check if the node datatype and the incoming value are compatible. In some cases a automatic adjustment can be done. With changes in the master, the adjust behavior for enums was not triggered anymore. This PR changes the compatible type check and therefore enables the enum-type transformation (from int32 to dedicated enum type).

fix(core) remove special case for enum handling in type compatible check

---

src/server/ua_services_attribute.c

The automatic adjust type logic does currently not check custom datatypes. E.g. the automatic UInt32 <--> ENUM conversion is not possible if the ENUM is defined in a custom namespace.

fix(server) include custom-datatypes in automatic type adjust logic

---

tools/generate_statuscode_descriptions.py

I would like to request an explicit switch to UTF-8 when reading the file.
The rest of the files (a few lines below) are already opened as UTF-8.
(If the patch gets accepted, it would be great to have it end up both in 1.3 and master branch.)

Explicitly set encoding to UTF-8 when reading file

---

examples/pubsub/pubsub_subscribe_standalone.c
src/pubsub/ua_pubsub_networkmessage.c
src/pubsub/ua_pubsub_networkmessage.h
src/pubsub/ua_pubsub_reader.c
tests/CMakeLists.txt
tests/pubsub/check_pubsub_encoding.c
tests/pubsub/check_pubsub_encoding_custom.c
tests/pubsub/check_pubsub_multiple_subscribe_rt_levels.c
tests/pubsub/check_pubsub_publish_rt_levels.c
tests/pubsub/check_pubsub_publish_uadp.c
tools/ua2json/ua2json.c

The decoding of custom data types did not work because the helper functions for decoding the payload of a network message set the `UA_DataTypeArray` argument to NULL. 
I fixed this problem by not using the helper functions and instead use `UA_decodeBinaryInternal(...)` directly with the given data type and the `UA_DataTypeArray`. 
To not break existing code, I added a wrapper function. (See comments)
I also added a new test that covers all the custom data types. I used the definitions from` check_types_custom.c` and `check_pubsub_encoding.c`

[Review] Fix PubSub decoding of custom datatypes. 

---

tools/packaging/debian/control-template

For information about package see https://packages.debian.org/search?keywords=libmbedtls14

Allow dependency to libmbedtls14 for debian bookworm

---

plugins/crypto/openssl/ua_openssl_aes128sha256rsaoaep.c
plugins/crypto/openssl/ua_openssl_basic128rsa15.c
plugins/crypto/openssl/ua_openssl_basic256.c
plugins/crypto/openssl/ua_openssl_basic256sha256.c

[Update the Server Certificate at Runtime](https://www.open62541.org/doc/master/server.html#update-the-server-certificate-at-runtime) only works for the mbedTLS implementation. For openssl the updateCertificateAndPrivateKey function pointers are missing. This leads to an segmentation fault at runtime. So I added those functions for all 4 secure endpoints.

Openssl runtime server cert update

---

arch/eventloop_posix_tcp.c

FIX: socket descriptor leak when UA_connect failed

---

src/pubsub/ua_pubsub_networkmessage.c
src/pubsub/ua_pubsub_networkmessage.h
src/pubsub/ua_pubsub_writer.c
tests/pubsub/check_pubsub_subscribe.c

Accoding to the spec ([7.2.2.5.6](https://reference.opcfoundation.org/Core/Part14/v105/docs/7.2.2.5.6#Table144)):
"A [DataSetMessage](https://reference.opcfoundation.org/search/307?t=DataSetMessage) should be padded with 0 if the size is smaller than the [ConfiguredSize](https://reference.opcfoundation.org/Core/Part14/v105/docs/6.3.1.3.3). If the  [ConfiguredSize](https://reference.opcfoundation.org/Core/Part14/v105/docs/6.3.1.3.3) is 0 the message can have dynamic length. If the [DataSetMessage](https://reference.opcfoundation.org/search/307?t=DataSetMessage) size is bigger than the [ConfiguredSize](https://reference.opcfoundation.org/Core/Part14/v105/docs/6.3.1.3.3), the bit 0 of the [DataSetFlags1](https://reference.opcfoundation.org/search/307?t=DataSetFlags1) should be set to false …

[Review] PubSub v1.05 add optional Padding for DataSetMessages

---

CMakeLists.txt
plugins/ua_pubsub_udp_multicast.c

Included fixes for:
• Incorrect way of creation an empty library for macOS. 
• Incorrect macros for macOS.

fix(plugin,cmake): Failure when build in MacOSX

---

examples/pubsub/server_pubsub_file_configuration.c
tools/ci.sh

This enables the `server_pubsub_file_configuration` example and fixes an include error.

fix(CI): Enable file config example

---

examples/nodeset/server_testnodeset.c
tools/ci.sh

This enables the `tutorial_server_alarms_conditions` example in the CI.
This also fixes a small memory leak in the `server_testnodeset` example that is also enabled by the full ns0. 
PR #5650 and #5747 will also fix the memory leak in the `server_testnodeset` example.

fix(CI): Enable alarm conditions example in CI

---

examples/encryption/server_encryption.c
plugins/crypto/openssl/ua_openssl_create_certificate.c
plugins/include/open62541/plugin/create_certificate.h
tests/encryption/check_cert_generation.c

The expiration time for certificates generated by the UA_CreateCertificate function where hard coded to 1 year. For more flexability I added the ExpirationInDays as a function argument. This is a public API breaking change.

Make the Certificate expiration configurable

---

arch/network_tcp.c
arch/wec7/ua_architecture.h
deps/aa_tree.c

Windows CE does not support socket status determination via WSAPoll, so that CPU-saving measure needs to be disabled.
This is an attempt to solve issue #5388.
Please note that I am actually working on Windows Embedded Compact 2013 (aka wec8) and not wec7. I got it running there but I have no way to test this on wec7, so it would be great if @fraxh22 could test if this solves the problem.
I am also totally open for input since the changes feel hacky.
If this becomes an agreeable fix eventually, I am also provide the changes to get it running on wec2013, i.e., as a new architecture if the maintainers agree.
Cheers!

Disable polling for Windows CE

---

plugins/crypto/openssl/ua_openssl_aes128sha256rsaoaep.c
plugins/crypto/openssl/ua_openssl_basic128rsa15.c
plugins/crypto/openssl/ua_openssl_basic256.c
plugins/crypto/openssl/ua_openssl_basic256sha256.c

Recently I added the update server cert at runtime function for the openssl builds with this PR https://github.com/open62541/open62541/pull/5712 .
I forgot to clear the thumbprint befor creating the new one so there is a memory leak. This PR should fix that.

fix(plugin): free old thumbprint befor creating the new one

---

examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_publisher.c
examples/pubsub_realtime/nodeset/pubsub_nodeset_rt_subscriber.c
examples/pubsub_realtime/pubsub_TSN_loopback.c
examples/pubsub_realtime/pubsub_TSN_publisher.c
examples/pubsub_realtime/pubsub_interrupt_publish.c
tools/ci.sh

This enables the realtime examples. 
NOTE: Since the CI just runs the examples without any arguments, I just fixed memory leaks that occur when those examples are just called without any arguments. I also returned 0 instead of -1 since this would break the CI.
How should this be done? Should we provide a way to run the examples with arguments?

fix(CI): Enabled pubsub realtime examples

---

src/client/ua_client_highlevel.c

Fetching HDA did not work while UAExpert did. Used Wireshark to analyze the difference.

fix(HDA): Replace HDA dataEncoding with empty string

---

include/open62541/architecture_definitions.h

Written by @anzeskerjancDS.
This fixes a segfault in our application (we did a few more changes which we might make into a PR later, but this is a direct bug fix, others are less straightforward). A separate bug fix is needed for master where this code was heavily refactored, but we would greatly appreciate a fix in the 1.3 branch as well.
The function `_InterlockedCompareExchangePointer`/`InterlockedCompareExchangePointer` expects the parameters in a different order.
* https://learn.microsoft.com/en-us/cpp/intrinsics/interlockedcompareexchangepointer-intrinsic-functions?view=msvc-170
* https://learn.microsoft.com/en-us/windows/win32/api/winnt/nf-winnt-interlockedcompareexchangepointer
```c
void * _InterlockedCompareExchangePointer (
void * volatile * Destination,
void * Exchange,
void * …
```

fix(core): Fix the order of parameters for MSVC

---

examples/CMakeLists.txt
examples/access_control_encrypt/client_access_control_encrypt.c
examples/ci_server.c
examples/client.c
examples/client_async.c
examples/client_historical.c
examples/discovery/client_find_servers.c
examples/encryption/client_encryption.c
examples/pubsub/sks/pubsub_publish_encrypted_sks.c
examples/pubsub/tutorial_pubsub_mqtt_publish.c
examples/pubsub/tutorial_pubsub_mqtt_subscribe.c
tools/ci.sh
tools/examples_with_valgrind.py

This allows to set arguments for the examples in the CI script.
The execution of the examples is outsourced to a python script since the associative arrays in bash didn't work as expected in the CI environment. 
You can set a client or server that needs to be running for each examples. Servers are started before the example, clients are started 10 seconds afterwards. 
You can also set arguments for the examples like a server address or certificates and keys that will be generated as well.
Some examples just run the client examples as well and might need a better client but this provides an environment where things can be adjusted easily. 
I added another example `ci_server.c` that is used for a lot of examples. 
There is also a blacklist for examples that dont work right now. Its mostly …

[REVIEW] CI: Added support for arguments in the examples workflow

---

CHANGELOG
src/ua_types_encoding_binary.c
src/ua_types_encoding_json.c
tests/check_types_builtin.c
tests/check_types_builtin_json.c
tests/check_types_custom.c
tests/pubsub/check_pubsub_encoding_custom.c

The decoding does not unwrap the extension objects that the
structures are wrapped into when encoded if the variant contains an
array of structures.
The implemented unit tests of this PR reveals the issue. Also the
test parseCustomArray is updated to what we belive is the correct
behavior.
This change will however break any existing implementation that relies on the extension object is not unwrapped. But the current behavior where a single structure (scalar value) is unwrapped but an array of structures are not must be seen as a bug in the implementation.

[REVIEW] fix(core): Decoding variant with array of structure fails

---

tools/nodeset_compiler/backend_open62541.py
tools/nodeset_injector/CMakeLists.txt
tools/nodeset_injector/empty.bsd.template

The type array of the respective nodeset is not adjusted if an empty bsd file is specified. If no bsd is specified or the xml file does not contain a base64 block, an empty bsd file is automatically generated.
PADIM specification included in the nodesetinjector.
Fix for #5814

fix(nodesetinjector):  Bug fixing when adjusting the type array.

---

tools/prepare_packaging.py

Fix parsing of version_minor and version_patch from git description.
For version v1.3.5-... the version_minor was set to 5 and version_patch
was empty with the old regex.
Error was introduced in PR #4854.

fix(ci): Fix git version matching

---

CMakeLists.txt
plugins/crypto/mbedtls/securitypolicy_mbedtls_common.c
plugins/crypto/mbedtls/securitypolicy_mbedtls_common.h
plugins/crypto/mbedtls/ua_securitypolicy_aes256sha256rsapss.c
plugins/crypto/mbedtls/ua_securitypolicy_basic256.c
plugins/crypto/mbedtls/ua_securitypolicy_basic256sha256.c
plugins/crypto/openssl/securitypolicy_openssl_common.c
plugins/crypto/openssl/securitypolicy_openssl_common.h
plugins/crypto/openssl/ua_openssl_aes256sha256rsapss.c
plugins/include/open62541/plugin/securitypolicy_default.h
plugins/include/open62541/server_config_default.h
plugins/ua_config_default.c
src/client/ua_client_connect.c
src/server/ua_services_session.c
tests/CMakeLists.txt
tests/encryption/check_encryption_aes256sha256rsapss.c
tests/fuzz/CMakeLists.txt

Adding the new security policy Aes256-Sha256-RsaPss.

[REVIEW]feat(server): Add Aes256-Sha256-RsaPss security policy

---

include/open62541/architecture_definitions.h

This PR removes compiler warnings (that are being treated as errors in release builds), demonstrated by #5898.
@ja4nm

fix(core): Avoid VS compiler warnings

---

arch/eventloop_posix.c

The log "Process delayed callbacks" is called as often as the log "Iterate the EventLoop", so the log level should also be UA_LOGLEVEL_TRACE, not UA_LOGLEVEL_DEBUG.

fix(arch): Decrease log level for processing delayed callbacks

---

include/open62541/client.h
tools/nodeset_compiler/backend_open62541_typedefinitions.py

Some  "static inline" functions need to be moved to UA_INLINABLE so that the library can be comfortably used as a dynamically linked library. 
**The following needs to be done :** 
**Unsure about moving these :**
- Node store 
- Event loop
- Architechture
Maybe I missed something, but I am busy writing dart/flutter bindings , and the automated tooling that I am using complains about "static inline" functions, so I these will come to the surface later on.

[WIP] Move all relevant public "static inline"  API functions to UA_INLINABLE 

---

plugins/ua_log_stdout.c

The constant string arrays logLevelNames and logCategoryNames are not exported neither in header include nor in dynamic library.  But they appear in static libopen62541.a library and my create conflicts. Declare these symbols static to keep them local in ua_log_stdout.c .

fix(plugin): Declare log constants static

---

src/pubsub/ua_pubsub_eventloop.c

If the old type UA_TYPES_DATAGRAMWRITERGROUPTRANSPORTDATATYPE is used for transportSettings, no address can be used for unicast configuration. Yet a multicast configuration with this type must be possible.

fix(pubsub): No WriterGroup address with old transportSettings type

---

src/pubsub/ua_pubsub_eventloop.c

If a socket is closed without data transfered, the sendChannel has not been set yet and the writer group is freed with the connection.

fix(pubsub): Fix double free of writer group for unicast connection

---

src/server/ua_server_ns0.c

StartTime is set for all data models in ua_server.c, but the node is missing in the minimal NS0.

fix(server): StartTime is missing in minimal NS0

---

src/pubsub/ua_pubsub_reader.c
tests/pubsub/check_pubsub_subscribe_msgrcvtimeout.c

If the function UA_PubSubConnection_setPubSubState is used with UA_PUBSUBSTATE_OPERATIONAL in state UA_PUBSUBSTATE_PREOPERATIONAL, The state is reset to UA_PUBSUBSTATE_PREOPERATIONAL internally. Thus the state has to be set manually (like in ua_pubsub_eventloop.c) and the user callback has to be called.
fix(tests): Unlock mutex in state callbacks before throwing assert
fix(tests): Reset expected cb counter in check_pubsub_subscribe_msgrcvtimeoout

fix(pubsub): Set reader group to operational

---

src/pubsub/ua_pubsub_networkmessage.c
src/pubsub/ua_pubsub_networkmessage.h
src/pubsub/ua_pubsub_reader.c

If a received message is not intended for a DataSetReader, the saved
NetworkMessage must not be used.

fix(PubSub): Check DataSetReader before using saved NetworkMessage

---

tests/pubsub/check_pubsub_sks_client.c
tests/pubsub/check_pubsub_sks_pull.c

- Check for nullptr before access in check_pubsub_sks_pull
- Abort while loop after 1000 retries in check_pubsub_sks_client
SKS Tests still fail, but do not run forever

fix(tests): Remove endless loop in sks tests

---

src/server/ua_services_monitoreditem.c
tests/server/check_services_subscriptions.c

cherry-picked from 1.4 but kept the check that verifies that the publishing interval is a valid sampling interval.
Without this fix several CTT test cases in "Monitored Item Services" failed.

fix(server): Return publishing interval if sampling interval == -1.0

---

plugins/include/open62541/plugin/accesscontrol_default.h
plugins/ua_accesscontrol_default.c
tests/CMakeLists.txt
tests/server/check_server_password.c

Username password validation in access control plugin allows only passwords stored in plaintext.  Add a callback to implement custom validation.  This allows salted password hashes and timing safe comparison in the server.  Furthermore remote validation could be implemented.  The new function UA_AccessControl_setCallback() is used to install a UA_UsernamePasswordLoginCallback with context.
The function to set the callback is added to the server config.  This reduces the API change.  Adding a parameter to UA_AccessControl_default() would also work, but this would require users to change the callers.  If this change is accepted, I can write some tests.  It looks like there are not any tests for username password login.

feat(plugin): Allow custom password validation

---

CMakeLists.txt
plugins/ua_config_json.c
tools/azure-devops/win/build.ps1
tools/ci.sh

If the macro UA_LOCK_ASSERT() is not generating code, the variable UA_EventLoopPOSIX *el is not used.  OpenBSD 7.4 clang version 13.0.0 generates a warning in this case which aborts the build due to -Werror.  Compile with -Wno-unused-variable instead.

build(arch): disable compiler error unused variable

---

include/open62541/common.h
include/open62541/server.h
src/server/ua_services_attribute.c
tests/server/check_services_attributes.c

For servers implemented according to specification 1.04, this attribute is required for variables. The attribute is an extension of the AccessLevel attribute and must therefore have at least the same bits set as the AccessLevel attribute.
The server returns BadNotSupported for some attributes like RolePermissions or AccessRestrictions. Unsupported/not allowed attributes must be answered with BadAttributeIdInvalid.

[REVIEW]feat(server): Added support for the AccessLevelEx attribute.

---

examples/pubsub/pubsub_publish_encrypted.c
examples/pubsub/pubsub_subscribe_encrypted.c
examples/pubsub/pubsub_subscribe_standalone_dataset.c
examples/pubsub/server_pubsub_publisher_iop.c
examples/pubsub/server_pubsub_publisher_on_demand.c
examples/pubsub/server_pubsub_subscribe_custom_monitoring.c
examples/pubsub/server_pubsub_subscriber_rt_level.c
examples/pubsub/tutorial_pubsub_publish.c
examples/pubsub/tutorial_pubsub_subscribe.c

Without defined key value for interface only the default interface will join the multicast group due to INADDR_ANY address in setsockopt. The additional argument makes it easier to use other interfaces.

[Review] feat(ex): add interface argument usage for udp pubsub

---

plugins/ua_config_default.c
src/server/ua_server_ns0.c

The SecurityLevel in the EndpointsDescriptions is an indicator for the security of this endpoint. The value 0 represents a special feature and should be used for endpoints that are not recommended and, for example, are now only supported for backwards compatibility.
The ServerProfileArray still contains the values of the last certification. The URL of the Micro Embedded Device Profile must be adapted to that of the standard 2017 UA Server Profile.

[REVIEW] Fix SecurityLevel in the EndpointDescription

---

examples/server_ctt.c
plugins/include/open62541/server_config_default.h
plugins/ua_config_default.c

Added start parameters for disabling Aes policies in the server_ctt.
Added start parameters for enabling None and deprecated policies in the server_ctt.
Added new function that configures the server with secure security policies only.

[REVIEW] Added ability to configure server with secure policies only

---

arch/eventloop_posix_epoll.c
arch/eventloop_posix_select.c

If UA_Server_addPubSubConnection was called in a (real-time) linux system from a task with lower priority than the task that called UA_Server_run, a deadlock occured.

[REVIEW] fix(el): Unlock EventLoop mutex before wait condition

---

tools/cmake/macros_public.cmake

fix(core): Do not reset tools directory when installed

---

CMakeLists.txt
arch/win32/ua_architecture.h

As a recent mingw version is required for the build, the libressl hack will cause problems and is no longer required for recent libressl and mingw version. (MinGW with gcc 8 was not able to build open62541 anymore, upgrade to recent mingw with gcc 13 requires these fixes)

fix(core): LibreSSL build on win32

---

plugins/crypto/openssl/ua_pki_openssl.c

Compiling on `alpine-3.18` fails if this is not included explicitly.
Thanks @ccvca for preparation.
```
#11 279.1 [ 73%] Building C object CMakeFiles/open62541-plugins.dir/plugins/crypto/openssl/ua_pki_openssl.c.o
#11 279.3 /src/Sample-Server/deps/open62541/plugins/crypto/openssl/ua_pki_openssl.c: In function 'UA_ReloadCertFromFolder':
#11 279.3 /src/Sample-Server/deps/open62541/plugins/crypto/openssl/ua_pki_openssl.c:288:31: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'UA_MAX'?
#11 279.3   288 |     char             certFile[PATH_MAX];
#11 279.3       |                               ^~~~~~~~
#11 279.3       |                               UA_MAX
#11 279.3 /src/Sample-Server/deps/open62541/plugins/crypto/openssl/ua_pki_openssl.c:288:31: note: each undeclared …
```

[Review] fix(core): Include limits.h for PATH_MAX

---

CMakeLists.txt
tools/open62541.pc.in

While a UA_ENABLE_AMALGAMATION macro is defined in the amalgamated open62541.h file and undefined in the non-amalgamated open62541/config.h file, it is not usable in downstream projects as they would need a priori knowledge which of the header files to include. They may try a test compilation in their build system's configure phase with one of the headers and set UA_ENABLE_AMALGAMATION if amalgamation is detected. However, this causes some code duplication in each downstream project.
Exporting the flag in the pkg-config file enables downstream projects to check for the open62541 dependency as usual and automatically get the necessary flag.
This is slightly related to #3178, although just concerning an import of open62541 via pkg-config.
In case of cmake, it would probably (I'm not very …

build(pkgconfig): export amalgamation flag

---

include/open62541/config.h.in

Allows to compile the library as a amalgamated, and then change the UA_LOGLEVEL in the CMakefile of the project that's using the amalgamated files.

Support defining UA_LOGLEVEL in an external CMakefile

---

plugins/ua_accesscontrol_default.c
src/server/ua_services_subscription.c
src/server/ua_subscription.c

fix(server): Bug fixes in the subscription transfer service.

---

doc/CMakeLists.txt

The header include files plugin/network.h and plugin/pubsub.h have been deleted.  They must also be removed from the dependencies of the documentation build.

docs(plugins): build docs without obsolete headers

---

tools/ua2json/ua2json.c

The initializer for UA_DecodeJsonOptions does not contain all fields and emits warning: missing field 'namespacesSize' initializer [-Wmissing-field-initializers].  As variable opt is constant, it can also be declared static.  Then it is allocated in BSS and zero initialized if there is no initializer.

fix(tools): ua2json initialize options struct

---

doc/nodeset_compiler.rst

The nodeset compiler has been migrated from opcua.rocks to medium.com. The old link does not work anymore.

[REVIEW] docs(nc): update link to tutorials

---

include/open62541/client_highlevel_async.h

The function UA_Client_sendAsyncBrowseNextRequest() was missing in the API.  In older open62541 versions the user of the library could implement it using UA_Client_sendAsyncRequest().  But as this function is gone in version 1.4 the client highlevel async API should be complete.

feat(client): add UA_Client_sendAsyncBrowseNextRequest

---

CMakeLists.txt
arch/eventloop_posix_eth.c

- Don't set an architecture define in config.h.in when amalgamating
- Disable eventloop_posix_eth if __linux__ is not defined

Fix architecture independent amalgamation (#6110)

---

examples/pubsub/tutorial_pubsub_mqtt_publish.c
examples/pubsub/tutorial_pubsub_mqtt_subscribe.c

Resolves #5990 with additional TRANSPORT_PROFILE_URI and updated json enabling.
transportProfiles in ua_pubsub_eventloop do not have the used pubsub-mqtt profile. Additional supported pubsub-mqtt-uadp and pubsub-mqtt-json definitions will fix the examples.
Also json encoding is activated indirectly in the example with UA_ENABLE_JSON_ENCODING, but at the same time the --json argument is also offered for publish example while subscriber example doesn't have such argument. This is inconsistent and confusing.
Now the same argument should activate the json encoding when the example applications are called while uadp as still default/fallback.

[REVIEW] fix(ex): fix json encoding in pubsub mqtt tutorial

---

src/pubsub/ua_pubsub_connection.c

Resolve #6130 with a correct pubsub reader group status when the pubsub connection is disabled.
Using the current connection state leads to multiple calls of UA_ReaderGroup_disconnect which also adds multiple deleteTopicConnection (eventloop_mqtt.c) as delayed callbacks. After a longer callstack this ends with the second call of UA_free(tc).
This is actually a double free error which is now displayed as invalid read on later memory access by valgrind test. Changing state to readerGroup->state _(in this case UA_PUBSUBSTATE_PREOPERATIONAL -> UA_PUBSUBSTATE_PREOPERATIONAL)_ avoids the earlier call of UA_ReaderGroup_disconnect and deleteTopicConnection is called only once.
The new pattern is similar with writerGroup->state for publisher a few lines later.
To be honest, I still don't …

[Review] fix(pubsub): Fix mqtt reader group shutdown

---

include/open62541/server.h
src/server/ua_services_discovery.c
src/server/ua_services_session.c
tests/CMakeLists.txt
tests/encryption/check_username_connect_none.c

If the server is built with security support, plain text passwords are currently rejected and no corresponding token is offered in the None policy endpoint.
A client without encryption support is unable to authenticate using username and password, even if a None policy endpoint is offered.
This commit adds the "allowNonePolicyPassword" option to the server config to enable access for clients with no encryption support.

[REVIEW] Add server option to allow password with None policy

---

examples/server_ctt.c
include/open62541/server.h
plugins/server_config.json5
src/server/ua_services_discovery.c

* Server returns the status BadServiceUnsupported for Service RegisterServer.
* Server will continuously register with the LDS (every 10 minutes).

[REVIEW] Fix register server ctt

---

src/pubsub/ua_pubsub_writergroup.c

Evaluate status code of addCustomCallback callback and UA_WriterGroup_addPublishCallback
With commit f462b9f80788b748a499f321e72a029a20fb15ac the custom cyclic callbacks have been called again, but not evaluated.

fix(pubsub): Evaluate status code of addCustomCallback callback

---

src/ua_types.c

Users might have manually created an inconsistent array. Defensive programming is good practice.

feat(core): Add a consistency check to UA_Array_copy

---

src/server/ua_services_nodemanagement.c

This PR proposes a solution to #6134.
Data source variables can now be added even if they return a non-good status code while adding (e.g., during system startup).

Allow to add data source variable with non-good status

---

tests/pubsub/check_pubsub_sks_client.c

This was forgotten in 5c979cd8c5d2624d5837a71da463db7d0b34919f:
```
/open62541/tests/pubsub/check_pubsub_sks_client.c:583:90: error: use of undeclared identifier 'sksPullRequestCallback'; did you mean 'sksPullRequestCallback_pubsub'?
583 |     UA_Server_setSksClient(publisherApp, securityGroupId, config, testingSKSEndpointUrl, sksPullRequestCallback, NULL);
|                                                                                          ^~~~~~~~~~~~~~~~~~~~~~
|                                                                                          sksPullRequestCallback_pubsub
```

fix(test): use correct name for sks callback

---

src/server/ua_discovery_mdns.c

Fix memcpy issue (maybe "copy&paste" error from fix in 1.3 ->  47239db132de3db30b975d65853a5a2ee295124c).

fix(server): memory handling in the server mdns implementation.

---

include/open62541/config.h.in

Use an uppercase T to match the #cmakedefine's above.
Fixes: 7547a8a9dc0b64eaf7a568305d82a78da6a6a6a1

fix(build): lowercase typo in UA_ARCHITECTURE_*

---

src/server/ua_subscription_datachange.c

Same fix that's already on master
Previous PR: #6198
Fixes: #6191

UA_MonitoredItem_processSampledValue(): fix passing subscription pointer to UA_LOG_DEBUG_SUBSCRIPTION

---

tests/nodeset-compiler/CMakeLists.txt

Add dependencies for the nodeset compiler tests to ensure that the generator targets are built beforehand.

[REVIEW]Add dependencies for the nodeset compiler tests

---

examples/tutorial_server_method_async.c
tests/server/check_discovery.c
tests/testing-plugins/thread_wrapper.h

Checking for `WIN32` only works by virtue of CMake defining `WIN32`, by itself. The `_WIN32` define actually comes from the compiler, so use that instead.
Since these are examples and tests, don't use `UA_ARCHITECTURE_WIN32`.

fix(examples,tests): correct Windows define

---

tests/nodeset-loader/check_memory.sh
tests/nodeset-loader/check_nodeset_loader_ua_nodeset.c
tests/nodeset-loader/run_test.sh

Removes IEC 61850 tests, as NodeSet was removed from `deps/UA-NodeSet`
Disables MDIS tests, as v1.3 NodeSet contains unreferenced nodes. Issue with OPCF raised.
Superseeds #6035

[REVIEW] build(deps): bump deps/ua-nodeset from `d1bb6a2` to `19d7d52`

---

src/pubsub/ua_pubsub_reader.c

We can't use the size of UA_String structure for field length calculation in dataSetMessages in form of rawData. It contains pointer to allocated memory, so the size is the same for all strings. Also the size of UA_String varies between platforms, since sizeof(size_t) and sizeof(byte*) are 4 bytes on 32-bit systems and 8 bytes on 64-bit systems. Length of binary encoded string = 4 (string length encoded as uint32) + N bytes (actual string data). For fixed message layout N equals maxStringlength.

fix(pubsub): fixed string field length calculations for RawData DatasetMessages

---

src/pubsub/ua_pubsub_eventloop.c
src/pubsub/ua_pubsub_reader.c

Changed log level of messages logged on every message send/receive from info to debug:  
* Reader: info message was logged whenever received message didn't match one of dataset readers, so with every message when 2+ readers were present.  
* Connection: info message was logged every time message was sent via UDP connection with localhost address

fix(pubsub): Changed level of messages littering log

---

plugins/crypto/mbedtls/ua_pki_mbedtls.c
plugins/crypto/openssl/ua_pki_openssl.c

If an error occurs in the UA_CertContext_Init function, the allocated memory is not released because the context and clear function in the UA_CertificateVerification structure are not set before the function returns.

[REVIEW] Fix a memory leak for the PKI CertContext

---

examples/pubsub_realtime/vxworks/pubsub_interrupt_publish_tsn.c

The function prototype of changeApplicationCallbackIntervali() and addApplicationCallback() can't meet the function pointer type. Change the function prototype of changeApplicationCallbackInterval() and addApplicationCallback().

Fix build warning in examples/pubsub_realtime/vxworks/pubsub_interrupt_publish_tsn.c.

---

src/ua_types_encoding_binary.c

It is often forgotten to include -DNDEBUG in the compiler flags when using the single-file release.

NDEBUG to UA_DEBUG in ua_types_encoding_binary.c

---

src/server/ua_services_discovery.c
src/server/ua_subscription.c
src/server/ua_subscription_monitoreditem.c
src/ua_types_encoding_json.c

Compiling with "gcc -Wshadow" shows a few shadow vars, this patch is fixing them.
I am very new to open62541, so please forgive if something is not fully complient with
how patch requests should be sent in.
open62541 compile flags are already very strict, but it seems that "-Wshadow" is still missing
and might be a good addition to the default flags. Also I have just done a standard compile,
but not looked at tests or all possible compile targets.
Comments?
best regards and thanks for open62541,
Florian La Roche

[Review] style: fix shadow var found from "gcc -Wshadow"

---

CMakeLists.txt
arch/eventloop_posix.c
arch/eventloop_posix_tcp.c
include/open62541/config.h.in
include/open62541/server.h
plugins/ua_config_default.c
src/server/ua_server.c
src/server/ua_server_binary.c
src/server/ua_services_discovery.c
src/ua_securechannel.c
src/ua_securechannel.h
tools/azure-devops/win/build.ps1
tools/ci.sh

The reuseaddr socket option is now disabled by default.
Server does not start if Binary Protocol Manager fails to start.

[REVIEW] Disable the reuseaddr socket option by default

---

tools/ua2json/ua2json.c

With this addition the UA_BUILD_TOOLS option in CMake can be enabled

fix (tools): Make ua2json compile under Windows

---

src/pubsub/ua_pubsub_reader.c

The retval variable is used in two different conditional compile parts of the function and declared in the first.
If UA_ENABLE_PUBSUB_INFORMATIONMODEL is not defined but UA_ENABLE_PUBSUB_MONITORING is defined, this results in a compilation error.

fix(pubsub): Move variable declaration into its own conditional define

---

tools/ua2json/ua2json.c

Rather than including a Microsoft specific header io.h for the read() function under Windows, use the more portable fread() function instead, which is defined in stdio.h on Windows too.

fix(tools): use the more portable fread() function instead of read()

---

src/server/ua_server_binary.c

%.*s must be used if a length of an unlimited buffer is provided and only the first 'n' bytes should be printed.

fix(server): Fix string output with %*s

---

arch/eventloop_posix_udp.c
arch/posix/ua_architecture.h
include/open62541/plugin/eventloop.h

In case of multicast configuration only an IP address was allowed
for the network interface. Now also network interface names can be
used.

fix(pubsub): Allow interface name for multicast

---

arch/posix/ua_architecture.h
include/open62541/config.h.in

Please refer to the commit message and the referenced issue for details.
As a minor note: Defining `_XOPEN_SOURCE` to 600 should lock down the compilation environment to a strict POSIX compliant environment.
This means that BSD socket features are unavailable. Presumably this is fine on glibc Linux systems however a lot of other Unix Systems won't allow this (and so does FreeBSD).
Probably a better solution to this problem is to check whether it is safe to define `_XOPEN_SOURCE` during the configure stage.

(#6414) Fix compilation failures on FreeBSD

---

.github/workflows/build_linux.yml
examples/pubsub/sks/server_pubsub_central_sks.c
include/open62541/server.h
include/open62541/types.h
plugins/ua_config_default.c
src/client/ua_client.c
src/client/ua_client_connect.c
src/client/ua_client_internal.h
src/client/ua_client_subscriptions.c
src/server/ua_server.c
src/server/ua_server_config.c

- Fix comment to explain that the UA_clear() function also initializes the content after deallocating any contained dynamic memory.
- Rename two functions postfixes from _clean() to _clear() to match the naming conventions used for the datatype delete functions.

fix(types): correct comment and make function names more consistent

---

doc/index.rst

The documentation page https://www.open62541.org/doc/master/ contains a dead link in the introduction:
> [...] See https://open62541.org/certified-sdk for more details.
Opening the link https://open62541.org/certified-sdk returns 404 Page not found.
I assume the proper link is https://open62541.org/certification which returns a page with the title "Certified SDK", which matches the dead link path name.

Fix dead link to certified SDK page

---

tools/packaging/debian/control-template

Due to commit 6091b1865f87acf3285b45b06c38d740cab40cd5 the tools package now contains architecture-specific
content (usr/lib/*/cmake/open62541/*).
Thus the package must be declared with Architecture 'any' instead of
'all'.

fix(build): Declare tools package architecture-specific

---

CMakeLists.txt
tools/cmake/open62541Config.cmake.in

The directory ua-nodeset does not exist any more, the schema files can be found below the schema directory.

fix(build): Fix path to schema files in CMakeLists

---

CMakeLists.txt
tools/cmake/open62541Config.cmake.in

Currently the transitive reference to the crypto plugin could not be resolved in environments with an installed open62541 stack.

fix(server) find crypto plugin in cmake install

---

arch/eventloop_posix_tcp.c

This removes an assertion that is based on an assumption that does not hold true in certain concurrent uses of the async client on Posix platforms. See #6455 for a more detailed description.
Fixes #6455

fix(arch): Remove assertion with invalid assumption

---

CMakeLists.txt

If CMake is not executed in the source code directory, there is an error because Git cannot find the repository. It is therefore necessary to specify the working directory for Git.

Fix CMake git working directory

---

CMakeLists.txt
tools/cmake/open62541Config.cmake.in
tools/cmake/open62541Macros.cmake

Use UA_SCHEMA_DIR for path to schema file to be independent from the different case of the 'schema' and 'Schema' folder.
Resolves #6508

[REVIEW] fix(build): Correct path for schema files of external build

---

tools/generate_bsd.py
tools/nodeset_compiler/backend_open62541.py

When generating the namespace code, the namespaceIndex may not be set correctly if the nodeset is based on multiple nodesets.
The code for extracting the bsd file from the nodeset has been adjusted. The check that the variable node is the node containing the bsd as a base64-encoded byte string has been extended.

[REVIEW] Correct setting of the namespaceIndex

---

CMakeLists.txt

Fixed CMake imported targets `OpenSSL::Crypto` and `OpenSSL::SSL` being written literally (without being expanded) to output files `open62541Targets.cmake` and `open62541.pc`.

[Review] fix(build): fix OpenSSL link flags in build output files

---

src/client/ua_client_connect.c
tests/client/check_client.c

Thanks to @Alexk12 for the analysis and suggested fix (see issue #5783).
If the connection is denied by the OPC UA server with e.g. `BadSecurityChecksFailed` the subsequent call to `UA_Client_delete` / `UA_Client_disconnect` hangs, because the exit condition for the while loop in `disconnectSecureChannel` is never reached: 
https://github.com/open62541/open62541/blob/3888af3410b53be0c5fa15b9d762dbab5b84902e/src/client/ua_client_connect.c#L2212
It was probably caused by the added "recursion check" in closeSecureChannel (commit 4bd6f4023ab59fa8ba1f17f5d82dd89636fc9995) that was added in v1.4.0-rc1
`UA_SecureChannel_shutdown` (correctly) sets `UA_SECURECHANNELSTATE_CLOSING` when actually closing the TCP connection, but is never called when the state is already set to …

fix(client): channel state set to CLOSING without closing underlying connection

---

src/ua_types_encoding_json.c

If src/ua_types_encoding_json.c is compiled with "gcc -Wshadow", a warning is output for an already defined var. This change fixes this.

fix(core): ret is already defined, so reuse var

---

plugins/ua_config_json.c

In plugins/ua_config_json.c mdnsIpAddressList can only be set if UA_HAS_GETIFADDR is undefined.

fix(plugins): mdnsIpAddressList only if UA_HAS_GETIFADDR is undefined

---

plugins/crypto/mbedtls/ua_pki_mbedtls.c
plugins/ua_config_default.c

Some items use 2<<y instead of 1<<y==2^y.
I've kept the buffer size in ua_pki_mbedtls.c the same, though this could also get reduced.

fix(core): fix default network values in UA_ConnectionConfig_default

---

plugins/crypto/openssl/ua_openssl_aes256sha256rsapss.c

Add the missing function 'updateCertificateAndPrivateKey' in the rsapss security policy for the openssl implementation.

[REVIEW] Add missing function in the rsapss security policy for openssl

---

src/server/ua_services_attribute.c

The default HistoryBackend does not support Event-History. Currently the server misses a check if event subscruption is tried to use.

fix(server) additional check for history backend configuraiton

---

plugins/server_config.json5

specs say that server capability "NA" should be listed as first capability and be the only one.

remove server capability "NA" from config file

---

src/server/ua_discovery.c

Added static check for enabled encryption.
The discovery example fails (server_register can't register with the LDS) if encryption is disabled and this check is missing. It corresponds to UA_Server_register, line 475.

Don't force UA_MESSAGESECURITYMODE_SIGNANDENCRYPT if encryption is disabled.

---

examples/discovery/server_multicast.c

server_multicast.c: remove "NA" from server capabilities and only keep "LDS" as server capability.

refactor(examples): server_multicast.c: remove "NA" from server capabilities

---

src/server/ua_discovery_mdns.c

In src/server/ua_discovery_mdns.c if no local hostname is given and thus INADDR_ANY/0.0.0.0 should be used, use gethostname() as local hostname.
Until now an error is returned from UA_Discovery_addRecord().

refactor(server): add local hostname if none given for LDS-ME.

---

examples/discovery/server_multicast.c
examples/discovery/server_register.c
tests/fuzz/corpus_generator.c
tests/fuzz/fuzz_tcp_message.cc

Avoid spaces in mdnsServerName as this is used for mDNS records.

refactor(examples,tests): avoid spaces for mDNS records

---

include/open62541/config.h.in

For building on UNIX, always define UA_HAS_GETIFADDR.

refactor(build): CMakeLists.txt: define UA_HAS_GETIFADDR on UNIX

---

src/server/ua_discovery_mdns.c

initialize newUrl
do not add path to discoveryUrl if empty, otherwise (null) will be added to the discoveryUrl

Fix discoveryUrl initialisation

---

examples/discovery/server_multicast.c

Currently an IP 42.42.42.42 is set and the comment suggests that the network stack resets this to 0.0.0.0 in server_multicast.c. Just set 0.0.0.0 directly.

refactor(examples): do not set an invalid IP in server_multicast.c

---

CMakeLists.txt

Fix for issue #6609 (build fails if open62541 is not the top level folder in a project hierarchy).

Make UA_SCHEMA_DIR an internal cache variable.

---

include/open62541/client.h

It seems that UA_Client_connectSecureChannel_async should connect asynchronously as the name suggests.
Problem introduced in: https://github.com/open62541/open62541/pull/5789

fix(client) UA_Client_connectSecureChannel_async not async.

---

plugins/crypto/mbedtls/certificategroup.c

The verifyCertificate function of the mbedTLS plugin has a bug (at least I assume so) in that when it finds the issuer of the remote certificate in the "list of **issuer** certificates", it will look for the appropriate CRL in the "list of **trusted** CRLs".

fix(plugin): search CRL in correct list in verifyCertificate (mbedTLS)

---

tests/nodeset-compiler/check_nodeset_compiler_autoid.c
tests/nodeset-compiler/check_nodeset_compiler_plc.c
tests/nodeset-compiler/check_nodeset_compiler_testnodeset.c

unistd.h does not seem to be used in these tests, but breaks compilation on Windows.

refactor(tests): fix compilation on windows by removing unused include unistd.h

---

src/pubsub/ua_pubsub.h

Changes the include syntax for the 'ua_pubsub_keystorage.h' file from
<> to "". This resolves a compile error that occurred because the
compiler was unable to find the file when it was included with <>
signs, which are typically used for system libraries. Now, with the ""
signs, the compiler should be able to locate the file in the local
directory.

fix(pubsub): Change include syntax

---

CMakeLists.txt

[REVIEW] Make UA_FILE_NS0 visible in other CMake files.

---

deps/base64.c
src/server/ua_services_attribute.c
src/ua_types_encoding_binary.c

The order of the `locale` and `localizedText` fields is different between the encoding mask and the encoded values in the body: https://reference.opcfoundation.org/Core/Part6/v105/docs/5.2.2.12
The two fields have been in the wrong order since v0.1 of open62541.

Fix binary encoding and decoding for DiagnosticInfo

---

CMakeLists.txt

In case CMAKE_BUILD_TYPE is not set, it defaults to "Debug", but BUILD_TYPE_LOWER_CASE was left unset.

fix(build): CMakeLists.txt: set BUILD_TYPE_LOWER_CASE after CMAKE_BUILD_TYPE is final

---

azure-pipelines.yml

Looks like some remnants of Debian build, now doing nothing except producing fake test ".deb" files for artifact and wasting ~2-3min of azure servers time.
I know almost nothing about this project and its history to attempt to modify this toward functional Azure Debian build (I don't even know if that would be desired), but jpfr agreed about removing it - I can do *that*.

ci: comment out azure-pipeline-dist.yml

---

CMakeLists.txt
plugins/crypto/ua_securitypolicy_filestore.c

- `make` can't find `pthread` and `rt` libraries while building `open62541` with `android.toolchain.cmake` and they cause errors. 
But NDK already has them. So, we don't need to look them for Android.
- We need to set `Android platform` to at least `24` because `epoll_create1` came with level `21` and `ifaddrs.h` came with `24`.
- `#include <bits/stdio_lim.h>` already included in `stdio`. We don't need to add it and android can't find it.
https://github.com/open62541/open62541/issues/6663

Android Compatibility Improvements

---

src/ua_types.c

When building under Linux, the function `UA_DataType_getStructMember` is a global (external) symbol when building statically and a local symbol when building a shared library.
This fix makes it a global (external) symbol for both build types.

fix(core): add UA_EXPORT for UA_DataType_getStructMember

---

src/server/ua_services_method.c

Calling memcpy() with a null pointer is undefined behavior even if the length is zero. The source pointer may be null if there are no arguments so check the argument count before calling memcpy().

fix(server): Eliminate memcpy() undefined behavior

---

plugins/crypto/openssl/ua_pki_openssl.c

Check for null pointer befor passing then into a openssl function.

fix(sec): avoid memmory read access errors

---

include/open62541/types.h
plugins/crypto/openssl/ua_pki_openssl.c
src/ua_types.c

If a chain of Certificate Authorities (CAs) longer than one is present, all CRL checks on the additional CAs were bypassed. This resulted in the potential acceptance of certificates that have been revoked or have expired CRLs.

fix(plugin): Proper error handling when checking all CRLs

---

src/pubsub/ua_pubsub_reader.c

If a beforeWrite callback is used without an externalDataValue pointer, an exception occurred.

fix(pubsub): Fix exception at PubSub update

---

plugins/crypto/openssl/certificategroup.c

Check for null pointer befor passing then into a openssl function.
See https://github.com/open62541/open62541/pull/6688 for 1.3 branch.

fix(sec): avoid memmory  read access errors

---

arch/eventloop_posix/eventloop_posix.h
arch/eventloop_posix/eventloop_posix_tcp.c

If accept() fails, some of the error codes indicate failure with the incoming connection, not the server socket. Do not kill the server socket if one of those error codes are detected.

fix(el): Treat some accept() errors as temporary

---

src/ua_securechannel.c

[REVIEW] fix: improve reported error when the client tries to use a security policy that is not available

---

src/pubsub/ua_pubsub_ns0.c

The data type of the mandatory entry GroupVersion in the PubSub info model was uninitialized because of a missing read callback.

fix(pubsub): Fix GroupVersion data type in info model

---

examples/tutorial_server_firststeps.c

Noticed this when going through the tutorial for the first time

docs: Fix typo in tutorial_server_firststeps

---

plugins/crypto/openssl/certificategroup.c
plugins/crypto/openssl/securitypolicy_common.c

Replace the detection of DER encoding using magic numbers by OpenSSL functions trying to decode the input as DER first and if not successful as PEM afterwards. This approach is less error prone and more flexible, as it supports Elliptic Curve keys and certificates as well.

[Review]refactor(plugin): avoid magic numbers in detection of DER encoding

---

doc/building.rst

This was missing from the build options list.

fix(docs): Add entry for UA_ENABLE_JSON_ENCODING

---

doc/building.rst

The list didn't render correctly in Sphinx, nor Github because it was missing a newline. Now it should look correct!

fix(docs): Fix rendering of the UA_ENABLE_ENCRYPTION options

---

doc/building.rst

This was missing from the build options list.

fix(docs): Add entry for UA_ENABLE_DIAGNOSTICS

---

doc/building.rst

In 4ec3bd92f5761020ce546ddeec2f1de610d02acb these build options were switched on by default, but this was not reflected in the docs yet.

fix(docs): PubSub build options are now enabled by default

---

tools/ci/ci.sh

* `sudo echo 1 >  /proc/sys/net/ipv4/tcp_tw_reuse` not allowed in CI (permission denied)

fix(ci): fix allow reuse of TIME-WAIT sockets

---

tests/CMakeLists.txt

This PR fixes Unit Test compilation under Visual Studio 2022.
Notes:
- Firewall pop-up at every test the first time, may be an issue for the CI server
- One test for the branch v1.4 is failing
```
----------------------------------------------------------
1/66 Testing: check_types_builtin
1/66 Test: check_types_builtin
Command: "D:/open62541/build/bin/tests/Release/check_types_builtin.exe"
Directory: D:/open62541/build/tests
"check_types_builtin" start time: Nov 11 14:23 W. Europe Standard Time
Output:
----------------------------------------------------------
Running suite(s): Built-in Data Types 62541-6 Table 1
98%: Checks: 68, Failures: 1, Errors: 0
D:\open62541\tests\check_types_builtin.c:894:F:encode:UA_Float_encodeShallWorkOnExample:0: Assertion 'dst.data[3] == result[i][3]' failed: …
```

fix(build): unit test compilation under MSVC

---

plugins/ua_config_default.c
src/server/ua_server.c
src/server/ua_server_ns0_gds.c
tests/CMakeLists.txt
tests/encryption/check_gds_informationmodel.c
tools/ci/ci.sh

Currently, after a write, the data is decoded directly into a TrustListDataType and applied to the transaction. However, this means that it is not possible to write larger data using multiple write calls.
This will be fixed in this PR. The data to be written is first cached. After a CloseAndUpdate the data is decoded into a TrustListDataType and applied to the transaction.

[REVIEW] Allow stream-based writing of the trust list

---

include/open62541/client_subscriptions.h
src/client/ua_client_subscriptions.c
src/pubsub/ua_pubsub_dataset.c

I need this when trying to integrate open62541 into an environment (LabVIEW from National Instruments) that is considerably different than most programming environments. It offers a possibility to interface to shared libraries but requires event resources that must be allocated and deallocated in the LabVIEW environment itself and from the shared library side can't be managed, only used. So I store that resource in the subscription user context.
While there is a delete callback to manage that user context, I can not call any C function from that callback to deallocate the event resource when the subscription is deleted. Instead I have to retrieve that event resource and pass it back into the environment to close it there.
Without this function I would have to somehow post the event …

feat(client): Add new function to retrieve the user supplied subscription and monitored item contexts

---

src/server/ua_server_binary.c

Now they are correctly purged when too many connections are open. This fixes the problem reported in #6863.

fix(server): Immediately set new SecureChannels to CONNECTED

---

include/open62541/plugin/eventloop.h
plugins/ua_config_default.c

This function is only generated for Linux and should not be attempted to call for other Posix platforms. As this connection manager uses raw ethernet frames it can't be implemented easily on other platforms without using entirely different APIs such as pcap/Npcap. This fixes Issue #6883

fix(eventloop): only attempt to call the UA_ConnectionManager_new_POSIX_Ethernet() when compiling for Linux

---

CMakeLists.txt

ua_securitypolicy_none.c requires UA_*_LoadCertificate() if encryption is enabled.

Fix amalgamation order

---

src/ua_util.c
tests/check_utils.c

This fixes #6905. The branch on the return value of `UA_Array_resize()` is necessary:
- On success, we must not decrement the internal map size again—`UA_Array_resize()` already did that for us.
- On failure, the underlying array storage is left as-is, leaving a null element in the last position. We must decrement the map size anyway to avoid accessing this null element in the other operations.

Fix double decrement in UA_KeyValueMap_remove()

---

src/pubsub/ua_pubsub_reader.c

UA_TYPES_* are indexes of the types in the type array (they are starting from 0).
We need to compare the builtInType to the well-known numeric identifier of the type (they are starting from 1).

fix(pubsub): Fix invalid DataType comparison on creation of DSR

---

.github/workflows/doc_upload.yml

This was apparently missed when moving the file in https://github.com/open62541/open62541/pull/6766 and the workflow has been broken on master since.
Note: The contributing guidelines list `ci` as a semantic commit type not a scope, but the actual commits over the last three years use it as a scope, so I followed that.

fix(ci): use correct path to ci.sh for doc_upload workflow

---

include/open62541/server_pubsub.h
src/pubsub/ua_pubsub_dataset.c
tests/pubsub/check_pubsub_publish.c

In some use cases it's necessary to configure them. There is no reason why they should not be part of the configuration.

feat(pubsub): Make DataSetFieldId and field Description configurable.

---

plugins/crypto/mbedtls/securitypolicy_common.c

Private key associated with a security policy is used for multipule purposes:
- asymmetric encryption/decryption
- asymmetric signing/verification
- certificate/CSR signing
The schemes used for each of the above operations differ in various policies. However, for certificate/CSR signing, for all RSA-based policies, the used scheme is always RSASSA-PKCS1-v1_5 (MBEDTLS_RSA_PKCS_V15).
Before generating a CSR, enforce using the RSASSA-PKCS1-v1_5 by setting the corresponding private key context.
This fixes a bug that in some edge cases, the private key context left after the previous usage of RSA module (e.g. if the last usage was to decrypt the user password) had the scheme set to RSAES-OAEP (MBEDTLS_RSA_PKCS_V21). This resulted in an invalid signature over the CSR.

fix(core): Fix issue with invalid signature on the generated CSR

---

plugins/crypto/mbedtls/ua_mbedtls_create_certificate.c

Fixes #6936. The fix itself is simply the swapping of two constants in f840415d9620670fbde8ea6e7d69d079368b1a74. 077695f233d8cc5c952042fff7821a79a8c86a73 makes use of `sizeof()` to avoid duplication and potential mistakes in the future regarding the buffer size (which I noticed while fixing the bug).
The remaining two commits clean up the code to match the surrounding code style.
Technically, this is a breaking change.

Respect certificate format in `UA_CreateCertificate()` with Mbed TLS

---

plugins/server_config.json5
plugins/ua_config_json.c

Add the Aes256_Sha256_RsaPss security policy to
the json configuration plugin. The server_config.json5
example configuration file is updated as well.

fix(plugin): add SecurityPolicy#Aes256_Sha256_RsaPss to json configuration plugin

---

src/client/ua_client_connect.c

Wrong data were passed to logger, which resulted in segmentation fault.

fix(client): Fixed log message crashing application

---

include/open62541/types.h

so that ua-cli can use it when open62541 is compiled as shared library

fix(types): make UA_String_append an exported function, 

---

.github/workflows/doc_upload.yml

GitHub is rolling out the [update of ubuntu-latest runners to ubuntu 24.04](https://github.com/actions/runner-images/issues/10636). This version of ubuntu has removed the un-versioned package `python-six`, only providing `python3-six`, which has made the doc_upload [workflow](https://github.com/open62541/open62541/actions/runs/12297577071/job/34319033378) [fail](https://github.com/open62541/open62541/actions/runs/12297600427/job/34319108388).
(Note that the `python-six` package in ubuntu 22.04 only contains the python2 interface while this workflow uses python3)
This PR fixes the workflow by removing the package completely as it appears to be unused and it seems to work.

[Review] fix(ci): remove python-six dependency from doc_upload workflow

---

.github/dependabot.yml

With this dependabot now actually opens PRs like https://github.com/marwinglaser/open62541/pull/6 for outdated actions. Explicitly passing a directory for `github-actions` is [unnecessary](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory) according to the documentation and if specified it likely needs to be the full `.github/workflows`.

[Review] fix(deps): fix dependabot github-actions config

---

src/server/ua_session.c
src/util/ua_util.c
tests/check_kvm_utils.c
tests/server/check_session.c

Fixed issues related to:
- Initializing a session's attribute key value map
- Removing values from a key value map (mapSize was reduced twice)
Also added test cases that check against the fixed issues.
Related to:
- https://github.com/open62541/open62541/issues/6724
- https://github.com/open62541pp/open62541pp/issues/362

fix(server): Missing session attribute init and KVM removal

---

examples/client_subscription_loop.c

Async functions have to be used in callbacks else the error message "Cannot run EventLoop from the run method itself" occurs under Windows 10 with Microsoft Visual Studio 17 2022.

fix(client example) client_subscription_loop.c: Async functions used in callbacks

---

src/pubsub/ua_pubsub_networkmessage_binary.c

Trying to send too long string would result in program crashing:  when the string length exceeded maxStringLength, lengthDifference would underflow and we would try to zero out gigabytes of memory. Added check to avoid that.
Would that be the correct approach? to just return with error and try sending the message later?
Is this the correct statuscode to return in such case?

fix(pubsub): fixed program crashing when sending too long strings

---

deps/ziptree.c

Warning appears (at least) with GCC 11.5.0 and 14.2.1 when using -O2, so reproduce for example with both -O2 and -Werror=maybe-uninitialized and get:
```
‘prev_order’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
```
Could fix also #6738

fix(deps): Remove maybe-uninitialized warning from ziptree

---

CMakeLists.txt

According to the CMake [documentation](https://cmake.org/cmake/help/latest/command/unset.html): "unsetting a normal variable can expose a cache variable that was previously hidden".
This can lead to wrong build results if UA_NAMESPACE_ZERO is changed to FULL after configuring the project with default REDUCED value. This happens e.g. if ccmake is used like shown in the documentation.
Set UA_FILE_NS0_PRIVATE to "" like proposed in the CMake documentation to prevent this behavior.
This fixes https://github.com/open62541/open62541/issues/6937

[Review] Fix UA_FILE_NS0_PRIVATE variable unset

---

CMakeLists.txt

When open62541 gets included into another CMake project using CPM, it still tries to read the version info from a git tag. This leads to wrong version numbers within the config.h header. This PR fix fixes the problem and only changes the version number from git when open62541 is the main CMake project.

[Review] fix(build): only try to read open62541 version number from git when it is the main CMake project

---

arch/common/ua_timer.c
arch/eventloop_posix.c
arch/eventloop_posix_eth.c
arch/eventloop_posix_tcp.c
arch/eventloop_posix_udp.c
include/open62541/config.h.in
src/client/ua_client.c
src/client/ua_client_connect.c
src/client/ua_client_subscriptions.c
src/pubsub/ua_pubsub_eventloop.c
src/pubsub/ua_pubsub_keystorage.c
src/pubsub/ua_pubsub_ns0.c
src/pubsub/ua_pubsub_writergroup.c
src/server/ua_server.c
src/server/ua_server_ns0_diagnostics.c
src/server/ua_services_attribute.c
src/server/ua_services_discovery.c
src/server/ua_services_method.c
src/server/ua_services_nodemanagement.c
src/server/ua_services_session.c
src/server/ua_services_subscription.c
src/server/ua_services_view.c
src/server/ua_subscription_datachange.c
src/server/ua_subscription_monitoreditem.c

By using recursive locking we do not have to release the locks before entering into user-supplied callbacks.
This solves #7010.

Recursive locking

---

src/server/ua_discovery_mdns.c

If we publish mDNS records in src/server/ua_discovery_mdns.c, always add a ".local." suffix for all entries.

refactor(server): use ".local" for mDNS published records

---

.github/workflows/coverage.yml

Targeting this to 1.4 makes it conflict with some changes from #6979 (my bad for targeting that against master). Maybe that one should be backported first?

fix(ci): make codecov run for release branches

---

plugins/crypto/openssl/ua_openssl_aes128sha256rsaoaep.c
plugins/crypto/openssl/ua_openssl_aes256sha256rsapss.c

At the moment, the PEM to DER conversion in openssl is only done for
http://opcfoundation.org/UA/SecurityPolicy#None
http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
This fix will also automatically convert PEM certificates to DER for:
http://opcfoundation.org/UA/SecurityPolicy#Aes256_Sha256_RsaPss
http://opcfoundation.org/UA/SecurityPolicy#Aes128_Sha256_RsaOaep
Reported here:
https://github.com/umati/Sample-Server/issues/1348
Code taken from Basic256Sha256:
https://github.com/open62541/open62541/blob/42b58674bcf6afc3a3465e81bf95523379c45ade/plugins/crypto/openssl/ua_openssl_basic256sha256.c#L558-L561

Fix EndpointDescription consistent certificate conversion for openssl

---

.github/ISSUE_TEMPLATE/bug_report.md

GitHub broke the old ISSUE_TEMPLATE.md format in the top-level directory with the "New Issue Experience" feature preview, so it's probably time to update to the new format.
This is the bare minimum to make the issue template show up again. In the future, this should probably be cleaned up a bit and updated to adopt new features GitHub provides (e.g., having multiple templates for different types of issues).
You can compare the UI by trying to open an issue in [this repository](https://github.com/open62541/open62541/issues) vs. [my fork](https://github.com/marwinglaser/open62541/issues), which has this commit applied on the HEAD branch.

refactor: convert issue template to new format

---

.github/workflows/build_linux.yml

GitHub Actions [support objects as matrix values](https://github.com/github/docs/issues/26469#issuecomment-1760332235) (see below), so lets use this instead of `include:` to simplify the build_linux matrix. The remaining commits are some minor cleanup in the same file.
Note that the linter in the GitHub web editor complains about this, but in this case [it appears like the linter is wrong](https://github.com/github/docs/issues/26469#issuecomment-1892388775)
---
From https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-using-a-multi-dimension-matrix:
> A variable configuration in a matrix can be an array of objects.
>
> ```yaml
> matrix:
>   os:
>     - ubuntu-latest
>     - macos-latest
>   node:
>     - version: 14
>     - version: 20
> …
```

refactor build_linux workflow

---

.github/workflows/coverage.yml

I *think* this works and the docs/examples indicate it should, but I don't know how to properly test it.
Also, this requires a GitHub actions secret called `CODECOV_TOKEN` that contains the repository upload token found [here](https://app.codecov.io/gh/open62541/open62541/config/general) (requires authentication). I don't have the permission to modify GitHub secrets, so someone else will have to create that.
The same is the case for the 1.4 release branch. What is the policy for changes that should go into multiple branches? I see there is a [PR to merge 1.4 back into master](https://github.com/open62541/open62541/pull/6946), but that is relatively old and Codecov is broken on both now. 
Context: https://github.com/open62541/open62541/pull/7033#issuecomment-2604607901

fix(ci): pass CODECOV_TOKEN to codecov-action

---

include/open62541/config.h.in

* refactor(core): Use recursive locks [93838cd37c166464b324d648ea52d916429c478d] introduced recursive locking.
* PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP is not defined in musl libc
* use PTHREAD_MUTEX_INITIALIZER on musl libc systems
Fixes #7039

fix(core): allow recursive locking with musl libc

---

examples/access_control/server_access_control.c

Allow connections with a username and password without encryption, ensuring compatibility between the Access Control Client and Server examples.

Fix access control server example

---

codecov.yml

coverage tree on master: https://app.codecov.io/github/open62541/open62541/commit/7c500a124244911d1f06695d59ac6d96965a564f/tree
coverage tree with this patch: https://app.codecov.io/github/open62541/open62541/pull/7055/tree

refactor(ci): exclude tests and examples from code coverage

---

CMakeLists.txt

It's reasonable to assume that users that set `UA_ENABLE_AMALGAMATION=ON` expect that to build with a simple `make` (or equivalent for other build systems).

fix(build): build amalgamation target by default if enabled

---

include/open62541/config.h.in
plugins/ua_log_stdout.c

There is no cross-plattform way to statically initialize a recursive lock.

refactor(core): Remove UA_LOCK_STATIC_INIT and its only user

---

src/server/ua_services_discovery.c

UA_DiscoveryManager_getNextServerOnNetworkRecord returns NULL if there is no entry.
Add a break to the entry loop to avoid dereferencing a NULL pointer.

[Review] Fix null pointer dereference in ua_services_discovery.c

---

.github/workflows/build_linux.yml
tools/ci/ci.sh
tools/ci/examples_with_valgrind.py

There are no tests for the multicast examples in CI. This can lead to unintended regressions.
Add both variants of the multicast example to already existent valgrind build tests.

[REVIEW] test: add multicast examples to valgrind build tests

---

.github/workflows/doc_upload.yml

Backport https://github.com/open62541/open62541/pull/6978 to 1.4 to fix doc upload worflow.

fix(ci): remove python-six dependency from doc_upload workflow

---

.github/workflows/release.yml
tools/ci/ci.sh

These are the small required changes mentioned in https://github.com/open62541/open62541/pull/6956, which [broke the release workflow on master](https://github.com/open62541/open62541/actions/workflows/release.yml?query=branch%3Amaster) after https://github.com/open62541/open62541/pull/6946

fix(ci): fix release workflow after bad merge

---

.github/workflows/build_linux.yml

Targeting master as that's where all the resources are used. This should likely be backported to 1.4 as well, but that needs to be done manually, as there are a bunch of conflicts because https://github.com/open62541/open62541/pull/7033 happened on master only (my bad). Maybe I should backport that as well?

feat(ci): run valgrind checks on ubuntu-24.04 (current latest) only

---

CHANGELOG
include/open62541/server_pubsub.h

Remove a misleading comment about the content of the variable
externalDataValue in the PubSub beforeWrite callback.
The beforeWrite callback is called with the data pointer containing the
data before the update. It may be used for a double buffer
implementation.
The original code change that changed the usage of the beforeWrite
callback was done with commit
06da5d07bd9a653d32e7a6ed06deae994d29953c.

fix(pubsub): Correct documentation of beforeWrite callback

---

arch/posix/eventloop_posix.h

Use <limits.h> and <sys/params.h> instead of <linux/limits.h> as this is not available on all Linux distributions.
Also remove redundant headers.

Use a standard header for system limits to improve portability

---

src/server/ua_server_async.c

The interval for checking for timeout of asynchronous operations is 1 second, not 100 seconds.

fix(server): Fix comment about timeout interval

---

plugins/crypto/ua_certificategroup_filestore.c
plugins/crypto/ua_filestore_common.c
plugins/crypto/ua_filestore_common.h

Removed inclusion of unguarded architecture-specific headers from the filestore backend plugin

Removing architecture dependency from the filestore backend plugin

---

include/open62541/server.h
src/server/ua_server.c
src/server/ua_server_binary.c
tests/fuzz/fuzz_binary_message.cc

This is necessary to prevent concurrent processes updating the data while we copy it out into `UA_ServerStatistics`.
Fixes #7189

fix(server): lock server state while copying out statistics

---

.github/workflows/build_linux.yml
.github/workflows/build_ubuntu2204.yml
tests/pubsub/check_pubsub_connection_mqtt.c
tools/ci.sh
tools/valgrind_check_error.py
tools/valgrind_suppressions.supp

This reverts the changes from #7133 and instead uses an ubuntu 20.04 container. This allows us to keep using this older Ubuntu version as long as we need to. A similar PR for the rewritten CI on the master branch that works with the version matrix is also in the works, where it can also be expanded to build on even older ubuntu versions or even different distributions.
This depends on a minimally modified custom docker image, which is currently built in a new repository (https://github.com/marwinglaser/images) and stored in GitHub's container registry. Before this PR is merged these images should be migrated to the open62541 organization. Interestingly enough we already have a similar repository that currently seems unused (https://github.com/open62541/open62541-ci), which would be a nice …

Run linux CI in an ubuntu container

---

src/client/ua_client_connect.c

Currently in connectSync we first get the current timestamp and calculate the maxDate based on the configured timeout. Then we call the initConnect function. Within this function we start the event loop, if this has not already been done, which in the end leads to a call to the start function of the event loop. This can cause the following problem: 
The start function sets the CLOCK_MONOTONIC_RAW which affects the UA_DateTime_nowMonotonic. As the now and maxDate timestamps are collected beforehand, the timebase is not the same. 
The error occurs for example when using POSIX and trying to connect to an offline server. The maxDate timestamp is due to the wrong timersource and is significantly smaller than the now, which means that the condition if(maxDate < now) will never be true and the …

Fix potential infinite loop in client connect

---

src/ua_types_encoding_json_105.c

issue link: https://issues.oss-fuzz.com/issues/387317444
In this PR a high-severity vulnerability in `removeFieldFromEncoding `where an invalid memory range (negative size) could be passed to `memmove`(), triggering an ASAN crash (Negative-size-param). The fix adds bounds checks to ensure that start and end are within the valid range of the UA_ByteString and that end >= start. This prevents undefined behavior when removing fields during JSON decoding in ExtensionObjects.

Fix ASAN crash in removeFieldFromEncoding by validating memory bounds

---

include/open62541/config.h.in

Adds support for C++ compilation when using C11 atomics. It achieves this by including the `atomic` header in C++ and defining aliases for the C-style atomic types and functions to their C++ counterparts.
Closes #7076.

[Review] fix(build): adds C++ support for C11 atomics

---

src/server/ua_services_discovery.c

Fix issue where the same URL is in the discovery URLs list multiple times:

[Review] fix(server): fix duplicate entries in discoveryUrls list

---

src/ua_securechannel.c

In case UA_ENABLE_ENCRYPTION is not set and a client tries to connect with a certificate, channel->certificateVerification is set, but certificateVerification->verityCertificate callback is (most likely) not set, causing null pointer dereference.

[Review] fix(core): use of null pointer in certificate verification

---

src/server/ua_subscription_events_filter.c

Fix compiler warning for local value not referenced in case some compile flags are not set.

[Review] fix(server): local variable not referenced

---

src/client/ua_client.c
src/client/ua_client_internal.h

Commit de9d691906547c9fc99e0a77198a80fe5bba54b1 fixed a use after free in UA_Client_AsyncService_cancel().  Move all elements to a local list before iterating over the callbacks.  Commit 713cdb419f0f844517afc549c7c1ef48d8498cfb fixed the same bug in in asyncServiceTimeoutCheck().  After timeout, remove the async service calls from the global list and store them in a local one.  Call UA_Client_AsyncService_cancel() and UA_free() while traversing this local list.  Otherwise the callback could free a global list element that asyncServiceTimeoutCheck() is referencing.
Backport these fixes from 1.4 to 1.3.  I have been carrying them in my local patch set for too long.

fix(client): use after free in client asyncServiceCalls

---

plugins/crypto/mbedtls/ua_mbedtls_create_certificate.c

In createcertificate, strlen() was used on a not null terminated string. This could result in using uninitialized memory for SAN attributes or even segfaults.

mbedtls createcertificate: fix length calculation

---

.github/workflows/build_linux.yml

Currently, some of our Linux build tests succeed after a few seconds without executing anything. This issue has arisen due to the change in docker integration in the builds. The tests with the short execution time do not match the configured OS, e.g.
matrix-build, which is defined for Ubuntu 20.04, but the current run is based on Ubuntu 22.04. Therefore, these tests should not be executed, and the non-execution is intended in general. However, these tests should certainly not appear in the list of executed tests, so I have overhauled the YAML definitions.
Additionally, we are currently pointing to a non-open62541 organisation container registry for our runners. We should move this dependency to our repository and build our own 'images' repository.

refactor(ci): reorganize build configurations for linux builds

---

tools/ua-cli/ua.c

Fix possible NULL-pointer dereference in ua-cli as reported by clang scan-build.

refactor(tools): fix possible NULL-pointer dereference in ua-cli

---

tools/cmake/FindCheck.cmake

The variable in the build system later on is with S at the end

fix(tools): Fix variable name CHECK_INCLUDE_DIRS mismatch

---

tests/testing-plugins/testing_networklayers_pcap.c

Remove these unused vars (reported from clang scan-build).

refactor(tests): remove unused vars

---

CMakeLists.txt

A few small changes to CMakeLists.txt:
- Compiling open62541 you can see it mentioning a target of "liblibmdnsd". Seems "add_library()" in cmake should be changed from libmdnsd to only mdnsd.
- Remove trailing whitespace.
- Change tabs into spaces.

refactor(build): change libmdns target name

---

plugins/historydata/ua_history_data_gathering_default.c
plugins/include/open62541/plugin/historydata/history_data_gathering_default.h

Stopping a node from in memory historizing removes both recording and the ability to read historical data. There is no way to stop recording new values while keeping the existing historical data available for clients.
I propose adding a paused flag to the backend's context. When paused is true, new values are not recorded, but historical reads still work. This is implemented by checking the flag in setValue_gathering_default and providing a function to set the flag.

feat: Add pause to historical data gathering

---

tools/cmake/open62541Macros.cmake

This resolves the CMake warnings that occur when amalgamation is enabled. In this configuration, there is no parent scope available, which leads to warnings during the configuration process.
To address this issue, the variables are not set for the parent scope. Instead, they are defined as internal cache variables. This prevents warnings and ensures that the variables remain available in CMake projects that include the stack via add_subdirectory.

Resolve missing parent scope warning in CMake with amalgamation enabled

---

src/server/ua_server_internal.h
src/server/ua_services_monitoreditem.c

Fixed (#7326). Issue seemed to be that struct callback would attempt to include UA_Server_EventNotificationCallback in a union when it was not defined. Additionally, headers for both UA_Server_createEventMonitoredItem and UA_Server_createEventMonitoredItemEx had correct preprocessor dirrectives, buyt function implementation did not, causing another compilation error.

fix(server): Fixed issue building with UA_ENABLE_SUBSCRIPTIONS_EVENTS=OFF (#7326)

---

arch/posix/eventloop_posix.h
arch/posix/eventloop_posix_eth.c
arch/zephyr/eventloop_zephyr.h
examples/client_connect_loop.c
examples/client_subscription_loop.c
include/open62541/server.h
plugins/ua_config_json.c
plugins/ua_log_stdout.c
src/server/ua_session.h
src/server/ua_subscription.h
src/ua_securechannel.h
src/util/ua_eventfilter_grammar.c
tests/check_types_builtin_xml.c
tests/client/check_client_subscriptions.c
tests/server/check_session.c
tools/ua-cli/ua.c

Fix some clang compiler warnings about:
- not-needed semicolons
- unused macros
- sign conversion in ua-cli

refactor(examples,tools,server,plugins): clang compiler warnings

---

tools/certs/create_self-signed.py

Hello @jpfr and maintainers,
This PR fixes and enhances the certificate generation script create_self-signed.py:
Replaces os.system() with subprocess.run() for better error control
Adds run_command() wrapper to capture output and detect failures
Improves structure and reliability on OpenSSL 3.x environments
This is a clean version of https://github.com/open62541/open62541/pull/7338 without any merge conflicts or CLA issues.
Tested on Ubuntu 24.04, OpenSSL 3.x.
Best regards,
Jianbin

fix(tools): improve structure and compatibility in create_self-signed.py

---

examples/discovery/server_lds.c

Hi @jpfr,
- Add a custom `applicationName` to the LDS example.
- Use `UA_LOCALIZEDTEXT_ALLOC` to ensure correct memory ownership so `UA_Server_delete()` frees it safely (avoid invalid free on shutdown).
- Add NULL-check for `serverCapabilities` allocation.
Thanks, 
Jianbin

refactor(examples): set allocated ApplicationName in server_lds example

---

arch/posix/clock_posix.c

This is intended to only trigger on OSX, but since Hurd uses Mach as well it overmatches when it should be checking for both `__APPLE__` and `__MACH__`.
https://www.gnu.org/software/hurd/hurd/porting/guidelines.html
```
#ifdef __MACH__
Some applications put Apple Darwin-specific code inside #ifdef __MACH__ guards. Such guard is clearly not enough, since not only Apple uses Mach as a kernel. This should be replaced by #if defined(__MACH__) && defined(__APPLE__)
```

Fix APPLE || MACH ifdef to only trigger on APPLE && MACH

---

tools/cmake/open62541Macros.cmake

The PR fixes the problem described in the issue https://github.com/open62541/open62541/issues/7390 .

Avoid caching open62541_* cmake variables

---

arch/posix/eventloop_posix.h
arch/posix/eventloop_posix_tcp.c
include/open62541/common.h
include/open62541/plugin/eventloop.h
tests/check_eventloop_tcp.c

Currently, there is no way to limit the number of open sockets. This PR introduces a new server configuration flag that limits the maximum number of open sockets.
Once a connection has been accepted, the server verifies whether the maximum limit has been reached. If so, the listening sockets are deregistered from the socket list.

Add socket limit configuration flag

---

CMakeLists.txt
src/pubsub/ua_pubsub_config.c
src/pubsub/ua_pubsub_connection.c
src/pubsub/ua_pubsub_internal.h
src/pubsub/ua_pubsub_manager.c
src/pubsub/ua_pubsub_ns0.c
src/pubsub/ua_pubsub_ns0_sks.c
src/pubsub/ua_pubsub_reader.c
src/pubsub/ua_pubsub_readergroup.c
src/pubsub/ua_pubsub_writer.c
src/pubsub/ua_pubsub_writergroup.c
tests/pubsub/check_pubsub_informationmodel_methods.c

This PR introduces the following changes:
- Representation of the State Object for all PubSub entities in the NS0.
- Implementation of the enable/disable functions in NS0.
- Mapping the internal PubSubManager state to the state of the PublishSubscribe object.
- Overhauling file-based PubSub loading with respect to state machine interaction. Ensuring the entire configuration is loaded until the state machines of the components are triggered.
- Add a state flag to the PubSubManager to indicate a 'configuration phase', influencing state changes to enable all components when a complete configuration is applied.

Implement PubSub NS0 states including enable/disable + update in the PubSub file configuration
